CREATE TABLE IF NOT EXISTS `form_physical_examination` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,

pname varchar(255),
pbdate varchar(255),
pe_id varchar(255),
pe_date varchar(255),
height varchar(255),
weight varchar(255),
bmi varchar(255),
blood_pressure varchar(255),
temperature varchar(255),
pulse varchar(255),
respiration varchar(255),
general_well_developed tinyint(1) default NULL,
general_no_deformities tinyint(1) default NULL,
general_well_nourished tinyint(1) default NULL,
general_well_groomed tinyint(1) default NULL,
general_normal_habitus tinyint(1) default NULL,
neck_neck tinyint(1) default NULL,
neck_neck_data varchar(255),
neck_thyroid tinyint(1) default NULL,
neck_thyroid_data varchar(255),
respiratory_effort tinyint(1) default NULL,
respiratory_effort_data varchar(255),
auscultated_lungs tinyint(1) default NULL,
auscultated_lungs_data varchar(255),
auscultated_heart_sounds tinyint(1) default NULL,
auscultated_heart_sounds_data varchar(255),
auscultated_heart_murmurs tinyint(1) default NULL,
auscultated_heart_murmurs_data varchar(255),
peripheral_vascular tinyint(1) default NULL,
peripheral_vascular_data varchar(255),
gastr_abdomen tinyint(1) default NULL,
gastr_abdomen_data varchar(255),
gastr_hernia tinyint(1) default NULL,
gastr_hernia_data varchar(255),
gastr_liver tinyint(1) default NULL,
gastr_liver_data varchar(255),
gastr_spleen tinyint(1) default NULL,
gastr_spleen_data varchar(255),
gastr_stool_guaiac tinyint(1) default NULL,
gastr_stool_guaiac_data varchar(255),
lymph_neck tinyint(1) default NULL,
lymph_neck_data varchar(255),
lymph_axilla tinyint(1) default NULL,
lymph_axilla_data varchar(255),
lymph_groin tinyint(1) default NULL,
lymph_groin_data varchar(255),
lymph_other tinyint(1) default NULL,
lymph_other_data varchar(255),
skin_inspected tinyint(1) default NULL,
skin_inspected_data varchar(255),
neur_orient_time tinyint(1) default NULL,
neur_orient_place tinyint(1) default NULL,
neur_orient_person tinyint(1) default NULL,
neur_orient_comments tinyint(1) default NULL,
neur_mood_normal tinyint(1) default NULL,
neur_mood_depressed tinyint(1) default NULL,
neur_mood_anxious tinyint(1) default NULL,
neur_mood_agitated tinyint(1) default NULL,
neur_mood_other tinyint(1) default NULL,
gynec_breasts tinyint(1) default NULL,
gynec_breasts_data varchar(255),
gynec_ext_genitalia tinyint(1) default NULL,
gynec_ext_genitalia_data varchar(255),
gynec_urethral_meatus tinyint(1) default NULL,
gynec_urethral_meatus_data varchar(255),
gynec_urethra tinyint(1) default NULL,
gynec_urethra_data varchar(255),
gynec_bladder tinyint(1) default NULL,
gynec_bladder_data varchar(255),
gynec_vagina_support tinyint(1) default NULL,
gynec_vagina_support_data varchar(255),
gynec_cervix tinyint(1) default NULL,
gynec_cervix_data varchar(255),
gynec_uterus tinyint(1) default NULL,
gynec_uterus_data varchar(255),
gynec_adnexa tinyint(1) default NULL,
gynec_adnexa_data varchar(255),
gynec_anus tinyint(1) default NULL,
gynec_anus_data varchar(255),
gynec_rectal tinyint(1) default NULL,
gynec_rectal_data varchar(255),
tot_num_examined varchar(255),

PRIMARY KEY (id)
) TYPE=MyISAM;
