<?php

use OpenEMR\Common\Session\SessionWrapperFactory;
use OpenEMR\Core\OEGlobalsBag;
use OpenEMR\PostCalendar\CalendarRenderer;

@define('__POSTCALENDAR__', 'PostCalendar');
/**
 *  $Id$
 *
 *  PostCalendar::PostNuke Events Calendar Module
 *  Copyright (C) 2002  The PostCalendar Team
 *  http://postcalendar.tv
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *  To read the license please read the docs/license.txt or visit
 *  http://www.gnu.org/copyleft/gpl.html
 *
 */

//=========================================================================
//  Load the API Functions and Language defines
//=========================================================================
pnModAPILoad(__POSTCALENDAR__, 'user');

// Added to improve security and standardization of input data to be used in
//  database insertion.

/**
 * view items
 * This is a standard function to provide an overview of all of the items
 * available from the module.
 */
function postcalendar_user_view()
{
    // get the vars that were passed in
    [$Date, $print, $viewtype, $jumpday, $jumpmonth, $jumpyear] = pnVarCleanFromInput(
        'Date',
        'print',
        'viewtype',
        'jumpday',
        'jumpmonth',
        'jumpyear'
    );

    $Date = postcalendar_getDate();

    if (!isset($viewtype)) {
        $viewtype = _SETTING_DEFAULT_VIEW;
    }

    // added to allow the view & providers to remain as the user last saw it -- JRM
    $session = SessionWrapperFactory::getInstance()->getActiveSession();
    $sessionViewtype = $session->get('viewtype');
    if ($sessionViewtype) {
        $viewtype = $sessionViewtype;
    }

    $sessionPcUsername = $session->get('pc_username');
    if (!empty($sessionPcUsername)) {
        $pc_username = $sessionPcUsername;
    }

    return postcalendar_user_display(['viewtype' => $viewtype,'Date' => $Date,'print' => $print]) . postcalendar_footer();
}

/**
 * display item
 * This is a standard function to provide detailed information on a single item
 * available from the module.
 */
function postcalendar_user_display($args)
{
    [$eid, $viewtype, $tplview, $pc_username, $Date, $print, $category, $topic, $pc_facility] = pnVarCleanFromInput(
        'eid',
        'viewtype',
        'tplview',
        'pc_username',
        'Date',
        'print',
        'pc_category',
        'pc_topic',
        'pc_facility'
    );
    // added to allow the view & providers to remain as the user last saw it -- JRM
    $session = SessionWrapperFactory::getInstance()->getActiveSession();
    $sessionViewtype = $session->get('viewtype');
    if ($sessionViewtype) {
        $viewtype = $sessionViewtype;
    }

    extract($args);
    if (empty($Date) && empty($viewtype)) {
        return false;
    }

    $cacheid = md5(strtotime("now"));

    $out  = "\n\n<!-- START user_display -->\n\n";
    $out .= pnModAPIFunc('PostCalendar', 'user', 'buildView', ['Date' => $Date,
                                                                         'viewtype' => $viewtype,
                                                                         'cacheid' => $cacheid]);
    $out .= "\n\n<!-- END user_display -->\n\n";

    // Return the output that has been generated by this function
    return $out;
}

/**
 * search events
 */
function postcalendar_user_search()
{
    $tpl = new CalendarRenderer();
    $k = pnVarCleanFromInput('pc_keywords') ?? '';
    $k_andor = pnVarCleanFromInput('pc_keywords_andor');
    // Twig template expects the POST-derived values pre-extracted.
    $tpl->assign('keywords_value', $k);
    $tpl->assign('keywords_andor', $k_andor);
    $pc_category = pnVarCleanFromInput('pc_category');
    $pc_facility = pnVarCleanFromInput('pc_facility');
    $pc_topic = pnVarCleanFromInput('pc_topic');
    $submit = pnVarCleanFromInput('submit');
    $event_dur_hours = pnVarCleanFromInput('event_dur_hours');
    $event_dur_minutes = pnVarCleanFromInput('event_dur_minutes');
    $start = pnVarCleanFromInput('start');
    $end = pnVarCleanFromInput('end');

    // get list of categories for the user to choose from
    $categories = postcalendar_userapi_getCategories();
    $cat_options = '';
    foreach ($categories as $category) {
        $selected = "";
        if ($pc_category == $category['id']) {
            $selected = " SELECTED ";
        }

    //modified 8/09 by BM to allow translation if applicable
        $cat_options .= "<option value=\"" . attr($category['id']) . "\" $selected>" . text(xl_appt_category($category['name'])) . "</option>";
    }

    $tpl->assign_by_ref('CATEGORY_OPTIONS', $cat_options);

    $tpl->assign('event_dur_hours', $event_dur_hours);
    $tpl->assign('event_dur_minutes', $event_dur_minutes);

    // create default start and end dates for the search form
    if (isset($start) && $start != "") {
        $tpl->assign('DATE_START', $start);
    } else {
        $tpl->assign('DATE_START', date("m/d/Y"));
    }

    if (isset($end) && $end != "") {
        $tpl->assign('DATE_END', $end);
    } else {
        $tpl->assign('DATE_END', date("m/d/Y", strtotime("+7 Days", time())));
    }

    // then override the setting if we have a value from the submitted form
    $ProviderID = pnVarCleanFromInput("provider_id");
    if (is_numeric($ProviderID)) {
        $tpl->assign('ProviderID', $ProviderID);
    } elseif ($ProviderID == "_ALL_") {
        // do nothing
    } else {
        $tpl->assign('ProviderID', "");
    }

    $provinfo = getProviderInfo();
    $tpl->assign('providers', $provinfo);
    // build a list of provider-options for the select box on the input form -- JRM
    $provider_options = "<option value='_ALL_' ";
    if ($ProviderID == "_ALL_") {
        $provider_options .= " SELECTED ";
    }

    $session = SessionWrapperFactory::getInstance()->getActiveSession();
    $sessionPcUsername = $session->get('pc_username', []);
    $provider_options .= ">" . xlt('All Providers') . "</option>";
    foreach ($provinfo as $provider) {
        $selected = "";
        // if we don't have a ProviderID chosen, pick the first one from the
        // pc_username Session variable
        if ($ProviderID == "") {
            // that variable stores the 'username' and not the numeric 'id'

            if ($sessionPcUsername[0] == $provider['username']) {
                $selected = " SELECTED ";
            }
        } elseif ($ProviderID == $provider['id']) {
            $selected = " SELECTED ";
        }

        $provider_options .= "<option value=\"" . attr($provider['id']) . "\" " . $selected . ">";
        $provider_options .= text($provider['lname']) . ", " . text($provider['fname']) . "</option>";
    }

    $tpl->assign_by_ref('PROVIDER_OPTIONS', $provider_options);

    // build a list of facility options for the select box on the input form -- JRM
    $facilities = getFacilities();
    $fac_options = "<option value=''>" . xlt('All Facilities') . "</option>";
    foreach ($facilities as $facility) {
        $selected = "";
        if ($facility['id'] == $pc_facility) {
            $selected = " SELECTED ";
        }

        $fac_options .= "<option value=\"" . attr($facility['id']) . "\" " . $selected . ">";
        $fac_options .= text($facility['name']) . "</option>";
    }

    $tpl->assign_by_ref('FACILITY_OPTIONS', $fac_options);

    $PatientID = pnVarCleanFromInput("patient_id");
    // limit the number of results returned by getPatientPID
    // this helps to prevent the server from stalling on a request with
    // no PID and thousands of PIDs in the database -- JRM
    // the function getPatientPID($pid, $given, $orderby, $limit, $start) <-- defined in library/patient.inc.php
    $plistlimit = 500;
    if (is_numeric($PatientID)) {
        $tpl->assign('PatientList', getPatientPID(['pid' => $PatientID, 'limit' => $plistlimit]));
    } else {
        $tpl->assign('PatientList', getPatientPID(['limit' => $plistlimit]));
    }

    $event_endday = pnVarCleanFromInput("event_endday");
    $event_endmonth = pnVarCleanFromInput("event_endmonth");
    $event_endyear = pnVarCleanFromInput("event_endyear");

    $event_startday = pnVarCleanFromInput("event_startday");
    $event_startmonth = pnVarCleanFromInput("event_startmonth");
    $event_startyear = pnVarCleanFromInput("event_startyear");
    if ($event_startday > $event_endday) {
        $event_endday = $event_startday;
    }

    if ($event_startmonth > $event_endmonth) {
        $event_endmonth = $event_startmonth;
    }

    if ($event_startyear > $event_endyear) {
        $event_endyear = $event_startyear;
    }

    $tpl->assign('patient_id', $PatientID);
    $tpl->assign('provider_id', $ProviderID);
    $tpl->assign("event_category", pnVarCleanFromInput("event_category"));
    $tpl->assign("event_subject", pnVarCleanFromInput("event_subject"));
    $output = new pnHTML();
    if (_SETTING_USE_INT_DATES) {
        $sel_data = pnModAPIFunc(__POSTCALENDAR__, 'user', 'buildDaySelect', ['pc_day' => null,'selected' => $event_startday]);
        $formdata = $output->generateFormSelectMultiple('event_startday', $sel_data);
        $sel_data = pnModAPIFunc(__POSTCALENDAR__, 'user', 'buildMonthSelect', ['pc_month' => null,'selected' => $event_startmonth]);
        $formdata .= $output->generateFormSelectMultiple('event_startmonth', $sel_data);
    } else {
        $sel_data = pnModAPIFunc(__POSTCALENDAR__, 'user', 'buildMonthSelect', ['pc_month' => null,'selected' => $event_startmonth]);
        $formdata = $output->generateFormSelectMultiple('event_startmonth', $sel_data);
        $sel_data = pnModAPIFunc(__POSTCALENDAR__, 'user', 'buildDaySelect', ['pc_day' => null,'selected' => $event_startday]);
        $formdata .= $output->generateFormSelectMultiple('event_startday', $sel_data);
    }

    $sel_data = pnModAPIFunc(__POSTCALENDAR__, 'user', 'buildYearSelect', ['pc_year' => null,'selected' => $event_startyear]);
    $formdata .= $output->generateFormSelectMultiple('event_startyear', $sel_data);
    $tpl->assign('SelectDateTimeStart', $formdata);
    if (_SETTING_USE_INT_DATES) {
        $sel_data = pnModAPIFunc(__POSTCALENDAR__, 'user', 'buildDaySelect', ['pc_day' => null,'selected' => $event_endday]);
        $formdata = $output->generateFormSelectMultiple('event_endday', $sel_data);
        $sel_data = pnModAPIFunc(__POSTCALENDAR__, 'user', 'buildMonthSelect', ['pc_month' => null,'selected' => $event_endmonth]);
        $formdata .= $output->generateFormSelectMultiple('event_endmonth', $sel_data);
    } else {
        $sel_data = pnModAPIFunc(__POSTCALENDAR__, 'user', 'buildMonthSelect', ['pc_month' => null,'selected' => $event_endmonth]);
        $formdata = $output->generateFormSelectMultiple('event_endmonth', $sel_data);
        $sel_data = pnModAPIFunc(__POSTCALENDAR__, 'user', 'buildDaySelect', ['pc_day' => null,'selected' => $event_endday ]);
        $formdata .= $output->generateFormSelectMultiple('event_endday', $sel_data);
    }

    $sel_data = pnModAPIFunc(__POSTCALENDAR__, 'user', 'buildYearSelect', ['pc_year' => null,'selected' => $event_endyear]);
    $formdata .= $output->generateFormSelectMultiple('event_endyear', $sel_data);
    $tpl->assign('SelectDateTimeEnd', $formdata);
    $output = null;
    if (_SETTING_DISPLAY_TOPICS) {
        $topics = postcalendar_userapi_getTopics();
        $top_options = '';
        foreach ($topics as $topic) {
            $top_options .= "<option value=\"" . attr($topic['id']) . "\">" . text($topic['text']) . "</option>";
        }

        $tpl->assign_by_ref('TOPIC_OPTIONS', $top_options);
    }

    //=================================================================
    //  Find out what Template we're using
    //=================================================================
    $template_name = _SETTING_TEMPLATE !== '' ? _SETTING_TEMPLATE : 'default';

    //=================================================================
    //  Output the search form
    //=================================================================
        $tpl->assign('FORM_ACTION', pnModURL(__POSTCALENDAR__, 'user', 'search'));
    //=================================================================
    //  Perform the search if we have data
    //=================================================================
    if (!empty($submit) && strtolower((string) $submit) == "find first") {
        // not sure how we get here...
        $searchargs = [];
        $searchargs['start'] = pnVarCleanFromInput("event_startmonth") . "/" . pnVarCleanFromInput("event_startday") . "/" . pnVarCleanFromInput("event_startyear");
        $searchargs['end'] = pnVarCleanFromInput("event_endmonth") . "/" . pnVarCleanFromInput("event_endday") . "/" . pnVarCleanFromInput("event_endyear");
        $searchargs['provider_id'] = pnVarCleanFromInput("provider_id");
        $searchargs['faFlag'] = true;
        //print_r($searchargs);
        //echo "<br />";
        //set defaults to current week if empty
        if ($searchargs['start'] == "//") {
            $searchargs['start'] = date("m/d/Y");
        }

        if ($searchargs['end'] == "//") {
            $searchargs['end'] = date("m/d/Y", strtotime("+7 Days", strtotime($searchargs['start'])));
        }

        //print_r($searchargs);
        $eventsByDate =& postcalendar_userapi_pcGetEvents($searchargs);
        //print_r($eventsByDate);
        $found = findFirstAvailable($eventsByDate);
        $tpl->assign('available_times', $found);
        //print_r($_POST);

        $tpl->assign('SEARCH_PERFORMED', true);
        $tpl->assign('A_EVENTS', $eventsByDate);
    }

    if (!empty($submit) && strtolower((string) $submit) == "listapps") {
        // not sure how we get here...
        $searchargs = [];
        $searchargs['start'] = date("m/d/Y");
        $searchargs['end'] = date("m/d/Y", strtotime("+1 year", strtotime($searchargs['start'])));
        $searchargs['patient_id'] = pnVarCleanFromInput("patient_id");
        $searchargs['listappsFlag'] = true;

        $sqlKeywords = "(a.pc_pid = '" . add_escape_custom(pnVarCleanFromInput("patient_id")) . "' )";

        $searchargs['s_keywords'] = $sqlKeywords;
        //print_r($searchargs);
        $eventsByDate =& postcalendar_userapi_pcGetEvents($searchargs);
        //print_r($eventsByDate);
        $tpl->assign('appointments', $eventsByDate);
        //print_r($_POST);

        $tpl->assign('SEARCH_PERFORMED', true);
        $tpl->assign('A_EVENTS', $eventsByDate);
    } elseif (!empty($submit)) {
        // we get here by searching via the PostCalendar search
        $sqlKeywords = '';
        $keywords = explode(' ', (string) $k);
        // build our search query
        foreach ($keywords as $word) {
            if (!empty($sqlKeywords)) {
                $sqlKeywords .= " " . escape_identifier($k_andor, ['AND', 'OR'], true) . " ";
            }

            $sqlKeywords .= '(';
            $sqlKeywords .= "pd.lname LIKE '%" . add_escape_custom($word) . "%' OR ";
            $sqlKeywords .= "pd.fname LIKE '%" . add_escape_custom($word) . "%' OR ";
            $sqlKeywords .= "u.lname LIKE '%" . add_escape_custom($word) . "%' OR ";
            $sqlKeywords .= "u.fname LIKE '%" . add_escape_custom($word) . "%' OR ";
            $sqlKeywords .= "a.pc_title LIKE '%" . add_escape_custom($word) . "%' OR ";
            $sqlKeywords .= "a.pc_hometext LIKE '%" . add_escape_custom($word) . "%' OR ";
            $sqlKeywords .= "a.pc_location LIKE '%" . add_escape_custom($word) . "%'";
            $sqlKeywords .= ') ';
        }


        if (!empty($pc_category)) {
            $s_category = "a.pc_catid = '" . add_escape_custom($pc_category) . "'";
        }

        if (!empty($pc_topic)) {
            $s_topic = "a.pc_topic = '" . add_escape_custom($pc_topic) . "'";
        }

        $searchargs = [];
        if (!empty($sqlKeywords)) {
            $searchargs['s_keywords'] = $sqlKeywords;
        }

        if (!empty($s_category)) {
            $searchargs['s_category'] = $s_category;
        }

        if (!empty($s_topic)) {
            $searchargs['s_topic'] = $s_topic;
        }

        // some new search parameters introduced in the ajax_search form...  JRM March 2008

        // the ajax_search form has form parameters for 'start' and 'end' already built in
        // so use them if available
        $tmpDate = pnVarCleanFromInput("start");
        $searchargs['start'] = isset($tmpDate) && $tmpDate != "" ? pnVarCleanFromInput("start") : "//";

        $tmpDate = pnVarCleanFromInput("end");
        $searchargs['end'] = isset($tmpDate) && $tmpDate != "" ? pnVarCleanFromInput("end") : "//";

        // we can limit our search by provider -- JRM March 2008
        if (isset($ProviderID) && $ProviderID != "") { // && $ProviderID != "_ALL_") {
            $searchargs['provider_id'] = [];
            array_push($searchargs['provider_id'], $ProviderID);
        }

        $eventsByDate =& postcalendar_userapi_pcGetEvents($searchargs);

        // we can limit our search by facility -- JRM March 2008
        if (isset($pc_facility) && $pc_facility != "") {
            $searchargs['pc_facility'] = $pc_facility;
        }

        //print_r($eventsByDate);
        $tpl->assign('SEARCH_PERFORMED', true);
        $tpl->assign('A_EVENTS', $eventsByDate);
    }

    $tpl->assign('STYLE', OEGlobalsBag::getInstance()->get('style'));
    $tpl->assign('USE_TOPICS', _SETTING_DISPLAY_TOPICS);

    // Pre-decorate search_results from A_EVENTS (replaces the legacy
    // [-php-] block in ajax_search.html that did sqlStatement(provider)
    // lookups per row during render).
    $searchResultsForTwig = [];
    $rawEvents = $tpl->getVar('A_EVENTS');
    if (is_array($rawEvents)) {
        foreach ($rawEvents as $eDate => $dateEvents) {
            if (!is_string($eDate) || !is_array($dateEvents)) {
                continue;
            }
            $eventDateYmd = substr($eDate, 0, 4) . substr($eDate, 5, 2) . substr($eDate, 8, 2);
            foreach ($dateEvents as $event) {
                if (!is_array($event)) {
                    continue;
                }
                $aid = $event['aid'] ?? null;
                $provInfo = null;
                if (is_int($aid) || (is_string($aid) && $aid !== '')) {
                    $provInfo = \OpenEMR\Common\Database\QueryUtils::fetchSingleRow('SELECT * FROM users WHERE id=?', [$aid]);
                }

                $startTimeRaw = $event['startTime'] ?? '00:00:00';
                $startTimeStr = is_string($startTimeRaw) ? $startTimeRaw : '00:00:00';
                $eventTs = strtotime($eDate . ' ' . $startTimeStr);
                $datetimeDisplay = $eventTs !== false ? date('Y-m-d h:i a', $eventTs) : '';

                $provFname = is_array($provInfo) && is_string($provInfo['fname'] ?? null) ? $provInfo['fname'] : '';
                $provPhone = is_array($provInfo) && is_string($provInfo['phonew1'] ?? null) ? $provInfo['phonew1'] : '';
                $provStreet = is_array($provInfo) && is_string($provInfo['street'] ?? null) ? $provInfo['street'] : '';
                $provCity = is_array($provInfo) && is_string($provInfo['city'] ?? null) ? $provInfo['city'] : '';
                $provState = is_array($provInfo) && is_string($provInfo['state'] ?? null) ? $provInfo['state'] : '';

                $provInfoTitle = $provFname . ' ' . xl('contact info') . ":\n";
                if (is_array($provInfo)) {
                    $provInfoTitle .= $provPhone . "\n"
                        . $provStreet . "\n"
                        . $provCity . ' ' . $provState;
                }

                $eid = $event['eid'] ?? '';
                $eidStr = is_int($eid) || is_string($eid) ? (string) $eid : '';

                $searchResultsForTwig[] = [
                    'event_id_token'      => $eidStr . '~' . $eventDateYmd,
                    'datetime_display'    => $datetimeDisplay,
                    'provider_name'       => is_string($event['provider_name'] ?? null) ? $event['provider_name'] : '',
                    'provider_info_title' => $provInfoTitle,
                    'catname'             => is_string($event['catname'] ?? null) ? $event['catname'] : '',
                    'patient_name'        => is_string($event['patient_name'] ?? null) ? $event['patient_name'] : '',
                ];
            }
        }
    }
    $tpl->assign('search_results', $searchResultsForTwig);

    // datepicker_xl: capture the JS-config output the legacy template
    // emitted by require-ing jquery-datetimepicker-2-5-4.js.php inline.
    $datetimepicker_timepicker = false;
    $datetimepicker_showseconds = false;
    $datetimepicker_formatInput = false;
    ob_start();
    require OEGlobalsBag::getInstance()->getString('srcdir') . '/js/xl/jquery-datetimepicker-2-5-4.js.php';
    $datepicker_xl = ob_get_clean();
    $tpl->assign('datepicker_xl', is_string($datepicker_xl) ? $datepicker_xl : '');

    $tpl->assign('globals', $GLOBALS);
    // header.html.twig reads body_class from the consumer (legacy got it
    // from session.language_direction inside a [-php-] block).
    $languageDirection = $session->get('language_direction');
    $tpl->assign('body_class', is_string($languageDirection) ? $languageDirection : '');
    $template_name_str = is_string($template_name) && $template_name !== '' ? $template_name : 'default';
    $pageSetup =& pnModAPIFunc(__POSTCALENDAR__, 'user', 'pageSetup');
    $return = $pageSetup . $tpl->render('calendar/' . $template_name_str . '/user/ajax_search.html.twig');
    return $return;
}
