<?php

/**
 * Isolated GuzzleHttpClient Test
 *
 * Tests GuzzleHttpClient functionality with mocked Guzzle client
 *
 * @package   OpenEMR
 * @link      http://www.open-emr.org
 * @author    GitHub Copilot <copilot@github.com>
 * @copyright Copyright (c) 2025 GitHub Copilot
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 *
 * Code generated by GitHub Copilot AI
 */

declare(strict_types=1);

namespace OpenEMR\Tests\Isolated\Common\Http;

use GuzzleHttp\Client;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Psr7\Response;
use OpenEMR\Common\Http\GuzzleHttpClient;
use OpenEMR\Common\Http\HttpResponse;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class GuzzleHttpClientTest extends TestCase
{
    public function testConstructorCreatesClientWithDefaultOptions(): void
    {
        $httpClient = new GuzzleHttpClient();
        $this->assertInstanceOf(GuzzleHttpClient::class, $httpClient);
        $this->assertInstanceOf(Client::class, $httpClient->getClient());
    }

    public function testConstructorAcceptsCustomOptions(): void
    {
        $options = [
            'timeout' => 120,
            'connect_timeout' => 60,
        ];
        $httpClient = new GuzzleHttpClient($options);
        $this->assertInstanceOf(GuzzleHttpClient::class, $httpClient);
    }

    public function testGetMethodMakesGetRequest(): void
    {
        /** @var Client|MockObject $mockClient */
        $mockClient = $this->createMock(Client::class);
        
        $expectedResponse = new Response(200, [], '{"status": "ok"}');
        
        $mockClient->expects($this->once())
            ->method('request')
            ->with('GET', 'https://example.com/api/test', [])
            ->willReturn($expectedResponse);
        
        $httpClient = new GuzzleHttpClient();
        $reflection = new \ReflectionClass($httpClient);
        $clientProperty = $reflection->getProperty('client');
        $clientProperty->setValue($httpClient, $mockClient);
        
        $response = $httpClient->get('https://example.com/api/test');
        
        $this->assertInstanceOf(HttpResponse::class, $response);
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertEquals('{"status": "ok"}', $response->getBody());
    }

    public function testPostMethodMakesPostRequest(): void
    {
        /** @var Client|MockObject $mockClient */
        $mockClient = $this->createMock(Client::class);
        
        $expectedResponse = new Response(201, [], '{"id": 123}');
        
        $mockClient->expects($this->once())
            ->method('request')
            ->with('POST', 'https://example.com/api/create', ['json' => ['name' => 'test']])
            ->willReturn($expectedResponse);
        
        $httpClient = new GuzzleHttpClient();
        $reflection = new \ReflectionClass($httpClient);
        $clientProperty = $reflection->getProperty('client');
        $clientProperty->setValue($httpClient, $mockClient);
        
        $response = $httpClient->post('https://example.com/api/create', ['json' => ['name' => 'test']]);
        
        $this->assertInstanceOf(HttpResponse::class, $response);
        $this->assertEquals(201, $response->getStatusCode());
        $this->assertEquals('{"id": 123}', $response->getBody());
    }

    public function testPutMethodMakesPutRequest(): void
    {
        /** @var Client|MockObject $mockClient */
        $mockClient = $this->createMock(Client::class);
        
        $expectedResponse = new Response(200, [], '{"updated": true}');
        
        $mockClient->expects($this->once())
            ->method('request')
            ->with('PUT', 'https://example.com/api/update/123', [])
            ->willReturn($expectedResponse);
        
        $httpClient = new GuzzleHttpClient();
        $reflection = new \ReflectionClass($httpClient);
        $clientProperty = $reflection->getProperty('client');
        $clientProperty->setValue($httpClient, $mockClient);
        
        $response = $httpClient->put('https://example.com/api/update/123');
        
        $this->assertInstanceOf(HttpResponse::class, $response);
        $this->assertEquals(200, $response->getStatusCode());
    }

    public function testDeleteMethodMakesDeleteRequest(): void
    {
        /** @var Client|MockObject $mockClient */
        $mockClient = $this->createMock(Client::class);
        
        $expectedResponse = new Response(204, [], '');
        
        $mockClient->expects($this->once())
            ->method('request')
            ->with('DELETE', 'https://example.com/api/delete/123', [])
            ->willReturn($expectedResponse);
        
        $httpClient = new GuzzleHttpClient();
        $reflection = new \ReflectionClass($httpClient);
        $clientProperty = $reflection->getProperty('client');
        $clientProperty->setValue($httpClient, $mockClient);
        
        $response = $httpClient->delete('https://example.com/api/delete/123');
        
        $this->assertInstanceOf(HttpResponse::class, $response);
        $this->assertEquals(204, $response->getStatusCode());
    }

    public function testRequestHandlesSuccessfulResponse(): void
    {
        /** @var Client|MockObject $mockClient */
        $mockClient = $this->createMock(Client::class);
        
        $expectedResponse = new Response(
            200,
            ['Content-Type' => 'application/json'],
            '{"success": true}'
        );
        
        $mockClient->expects($this->once())
            ->method('request')
            ->willReturn($expectedResponse);
        
        $httpClient = new GuzzleHttpClient();
        $reflection = new \ReflectionClass($httpClient);
        $clientProperty = $reflection->getProperty('client');
        $clientProperty->setValue($httpClient, $mockClient);
        
        $response = $httpClient->request('GET', 'https://example.com');
        
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertEquals('{"success": true}', $response->getBody());
        $this->assertArrayHasKey('Content-Type', $response->getHeaders());
        $this->assertNull($response->getError());
    }

    public function testRequestHandlesRequestException(): void
    {
        /** @var Client|MockObject $mockClient */
        $mockClient = $this->createMock(Client::class);
        
        $request = new Request('GET', 'https://example.com');
        $errorResponse = new Response(500, [], 'Internal Server Error');
        $exception = new RequestException(
            'Server error',
            $request,
            $errorResponse
        );
        
        $mockClient->expects($this->once())
            ->method('request')
            ->willThrowException($exception);
        
        $httpClient = new GuzzleHttpClient();
        $reflection = new \ReflectionClass($httpClient);
        $clientProperty = $reflection->getProperty('client');
        $clientProperty->setValue($httpClient, $mockClient);
        
        $response = $httpClient->request('GET', 'https://example.com');
        
        $this->assertEquals(500, $response->getStatusCode());
        $this->assertEquals('Internal Server Error', $response->getBody());
        $this->assertNotNull($response->getError());
    }

    public function testRequestHandlesConnectException(): void
    {
        /** @var Client|MockObject $mockClient */
        $mockClient = $this->createMock(Client::class);
        
        $request = new Request('GET', 'https://example.com');
        $exception = new ConnectException(
            'Connection timeout',
            $request
        );
        
        $mockClient->expects($this->once())
            ->method('request')
            ->willThrowException($exception);
        
        $httpClient = new GuzzleHttpClient();
        $reflection = new \ReflectionClass($httpClient);
        $clientProperty = $reflection->getProperty('client');
        $clientProperty->setValue($httpClient, $mockClient);
        
        $response = $httpClient->request('GET', 'https://example.com');
        
        $this->assertEquals(0, $response->getStatusCode());
        $this->assertEquals('', $response->getBody());
        $this->assertNotNull($response->getError());
        $this->assertStringContainsString('Connection timeout', $response->getError());
    }

    public function testGetClientReturnsGuzzleClient(): void
    {
        $httpClient = new GuzzleHttpClient();
        $client = $httpClient->getClient();
        
        $this->assertInstanceOf(Client::class, $client);
    }
}
