DELETE FROM `list_options` WHERE list_id='dashboard' OR option_id='dashboard';


INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`, `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`, `activity`, `subtype`, `edit_options`, `timestamp`) VALUES
('dashboard', 'appointments', 'Appointments', 5, 0, 0, '', '{ \"id\": \"right\", \"element_component\": \"Container\", \"element\": \"Container\", \"element_title\": \"Appointments\", \"children\": [ { \"element_active\": true, \"element_component\": \"Appointments\", \"element\": \"appointments\", \"element_title\": \"Appointments1\" }, { \"element_active\": true, \"element_component\": \"Appointments\", \"element\": \"appointments\", \"element_title\": \"Appointments2\" }, { \"element_active\": true, \"element_component\": \"Appointments\", \"element\": \"appointments\", \"element_title\": \"Appointments3\" } ]}', '', 0, 0, 1, '', 1, '2019-04-21 03:33:30'),
('dashboard', 'medical_problems', 'Medical Problems', 4, 0, 0, '', '{\n \"id\": \"right\",\n \"element_component\": \"Container\",\n \"element\": \"Container\",\n \"element_title\": \"Medical Highlights\",\n \"children\": [\n {\n \"element_active\": true,\n \"element_component\": \"MedicalHighlight\",\n \"element\": \"MedicalProblems\",\n \"element_title\": \"Medical Problems\"\n },\n {\n \"element_active\": true,\n \"element_component\": \"MedicalHighlight\",\n \"element\": \"Allergies\",\n \"element_title\": \"Allergies\"\n },\n {\n \"element_active\": true,\n \"element_component\": \"MedicalHighlight\",\n \"element\": \"Medications\",\n \"element_title\": \"Medications\"\n }\n ]\n} ', '', 0, 0, 1, '', 1, '2019-04-21 03:33:30'),
('dashboard', 'menu_dashboard', 'Menu', 1, 0, 0, '', '{\"id\":\"header\",\"element_component\":\"MenuDashboard\",\"element\":\"MenuDashboard\"}', '', 0, 0, 1, '', 1, '2019-04-21 03:33:30'),
('dashboard', 'patient_details', 'Patient Details', 2, 0, 0, '', '{\"id\":\"left\",\"element_component\":\"PatientData\",\"element\":\"PatientData\"}', '', 0, 0, 1, '', 1, '2019-04-21 03:33:30'),
('dashboard', 'patient_messages', 'Patient Messages', 3, 0, 0, '', '{\"id\":\"left\",\"element_component\":\"PatientMessages\",\"element\":\"PatientMessages\"}', '', 0, 0, 1, '', 1, '2019-04-21 03:33:30'),
('dashboard', 'billing', 'Billing', 8, 0, 0, '', '{"id":"left","element_component":"PatientBilling","element":"PatientBilling"}', '', 0, 0, 1, '', 1, '2019-04-21 06:33:30'),
('lists', 'dashboard', 'dashboard', 306, 1, 0, '', NULL, '', 0, 0, 1, '', 1, '2019-04-21 03:30:49');


UPDATE `list_options` SET `notes` = '{ \"id\": \"right\", \"element_component\": \"Container\", \"element\": \"Container\", \"element_title\": \"Appointments\", \"children\": [ { \"type\":\"past\" ,\"element_active\": true, \"element_component\": \"Appointments\", \"element\": \"appointments\", \"element_title\": \"Past appointments\" }, {\"type\":\"appointment_recurrences\", \"element_active\": true, \"element_component\": \"Appointments\", \"element\": \"appointments\", \"element_title\": \"Recurrenced appointments\" }, { \"element_active\": true, \"element_component\": \"Appointments\", \"element\": \"appointments\",\"type\":\"future\", \"element_title\": \"Future appointments\" } ]}' WHERE `list_options`.`list_id` = 'dashboard' AND `list_options`.`option_id` = 'appointments';
UPDATE `list_options` SET `notes` = '{\"id\":\"left\",\"element_component\":\"PatientData\",\"element\":\"PatientData\",\"settings\":{\"defaultGroupId\":1}}' WHERE `list_options`.`list_id` = 'dashboard' AND `list_options`.`option_id` = 'patient_details';
