CREATE TABLE IF NOT EXISTS `form_progressnotes` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
prog_p longtext,
prog_r longtext,
prog_bp longtext,
prog_ht longtext,
prog_wt longtext,
prog_temp longtext,
prog_lmp longtext,
prog_last_pap_smear longtext,
prog_last_td_booster longtext,
prog_allergies longtext,
prog_last_mammogram longtext,
prog_present_complaint longtext,
prog_skin_abn varchar(255),
prog_skin_ne varchar(255),
prog_head_abn varchar(255),
prog_head_ne varchar(255),
prog_eyes_abn varchar(255),
prog_eyes_ne varchar(255),
prog_ears_abn varchar(255),
prog_ears_ne varchar(255),
prog_nose_abn varchar(255),
prog_nose_ne varchar(255),
prog_throat_abn varchar(255),
prog_throat_ne varchar(255),
prog_teeth_abn varchar(255),
prog_teeth_ne varchar(255),
prog_neck_abn varchar(255),
prog_neck_ne varchar(255),
prog_chest_abn varchar(255),
prog_chest_ne varchar(255),
prog_breast_abn varchar(255),
prog_breast_ne varchar(255),
prog_lungs_abn varchar(255),
prog_lungs_ne varchar(255),
prog_heart_abn varchar(255),
prog_heart_ne varchar(255),
prog_abdomen_abn varchar(255),
prog_abdomen_ne varchar(255),
prog_spine_abn varchar(255),
prog_spine_ne varchar(255),
prog_extremeities_abn varchar(255),
prog_extremeities_ne varchar(255),
prog_lowback_abn varchar(255),
prog_lowback_ne varchar(255),
prog_neuro_abn varchar(255),
prog_neuro_ne varchar(255),
prog_rectal_abn varchar(255),
prog_rectal_ne varchar(255),
prog_pelvic_abn varchar(255),
prog_pelvic_ne varchar(255),
prog_assessment longtext,
prog_plan longtext,
prog_breast_se longtext,
prog_dental_h longtext,
prog_diagnosis longtext,
prog_injur_p longtext,
prog_new_treat longtext,
prog_nutrition_e longtext,
prog_sexual_p longtext,
prog_substance_a longtext,
PRIMARY KEY (id)
) TYPE=MyISAM;
