<?php
/**
 * interface/modules/zend_modules/module/Immunization/view/layout/layout.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Bindia Nandakumar <bindia@zhservices.com>
 * @copyright Copyright (c) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
use OpenEMR\Core\Header;

echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate()->xl('Immunization'))->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php Header::setupHeader(); ?>

        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/carecoordination_style.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/sendTo.css')
        ->prependStylesheet($this->basePath() . '/css/immunization.css')
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/application/sendTo.js')
        ->prependFile($this->basePath() . '/js/scripts/immunization.js')
        ->prependFile($this->basePath() . '/js/application/common.js')
        ->prependFile($this->basePath() . '/js/lib/modernizr.min.js')
        ?>

    </head>
    <body class="body_top">
        <div class="container-fluid">
            <?php echo $this->javascriptGlobals(); ?>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
