<?php
/**
 * interface/modules/zend_modules/module/Immunization/view/layout/layout.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Bindia Nandakumar <bindia@zhservices.com>
 * @copyright Copyright (c) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
use OpenEMR\Core\Header;

echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle($this->translate()->xl('Immunization'))->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php Header::setupHeader(['datetime-picker', 'modernizr']); ?>

        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/carecoordination_style.css" />
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/style.css" />
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/sendTo.css" />
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/immunization.css" />
        <script src="<?php echo $this->basePath(); ?>/js/application/sendTo.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/scripts/immunization.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/application/common.js"></script>
        <script>
        $(function() {
          $(".date_field").datetimepicker({
            <?php $datetimepicker_timepicker = false;
            $datetimepicker_showseconds = false;
            $datetimepicker_formatInput = false;
            require($GLOBALS['srcdir'] . '/js/xl/jquery-datetimepicker-2-5-4.js.php'); ?>
          });
        });
        </script>
    </head>
    <body class="body_top">
        <div class="container-fluid">
            <?php echo $this->javascriptGlobals(); ?>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
