# Modified from the original XMLForm Generated table
# do not regenerate
CREATE TABLE IF NOT EXISTS `form_gyn_ros` (
    date datetime default NULL comment 'last modified date',
    id bigint(20) NOT NULL auto_increment,
    pid bigint(20) NOT NULL default 0,
    user varchar(255) default NULL,
    groupname varchar(255) default NULL,
    authorized tinyint(4) default NULL,
    activity tinyint(4) default NULL,
    cardio_reviewed varchar(255),
    cardio_note TEXT,
    gastro_reviewed varchar(255),
    gastro_note TEXT,
    Urinary_reviewed varchar(255),
    Urinary_note TEXT,
    cns_reviewed varchar(255),
    cns_note TEXT,
    other_reviewed varchar(255),
    other_note TEXT,
    complications_reviewed varchar(255),
    complications_note TEXT,
    lmpdate datetime default NULL,
    cycle_int varchar(30),
    cycle_int_note TEXT,
    flowfhcount tinyint(2),
    flowhrs tinyint(2),
    pmb varchar(255),
    vag_discharge varchar(255),
    vag_discharge_note TEXT,
    vag_itching varchar(255),
    vag_itching_note TEXT,
    vag_odor varchar(255),
    vag_odor_note TEXT,
    vag_irratation varchar(255),
    vag_irratation_note TEXT,
    vag_spotting varchar(255),
    vag_spotting_note TEXT,
    priortreatment varchar(255),
    priortreatment_note TEXT,
    pain_menses varchar(25),
    pain_level varchar(2),
    pain_location varchar(30),
    pain_lenth varchar(30),
    pain_drug_resp varchar(30),
    pain_intercourse varchar(255),
    pain_intercourse_time TEXT,
    PRIMARY KEY (id)
) ENGINE=MyISAM;

