rto_date VARCHAR(16) DEFAULT NULL,
rto_target_date VARCHAR(16) DEFAULT NULL,
rto_ordered_by VARCHAR(255) DEFAULT NULL,
rto_type VARCHAR(16) DEFAULT NULL,
rto_msg_trail TEXT DEFAULT NULL,
rto_action_trail TEXT DEFAULT NULL,
rto_repeat TINYINT(1) DEFAULT 0,
rto_stop_date VARCHAR(32) DEFAULT NULL,
