x-includes:
  selenium-template: "compose-shared-selenium.yml"
  webserver-template: "compose-shared-apache.yml"
  database-template: "compose-shared-mariadb.yml"

services:
  mysql:
    image: mariadb:10.11
  openemr:
    image: openemr/openemr:flex-3.22-php-8.4
