ignore:
- tests/PHPStan/         # Static analysis rules — not exercised by PHPUnit
- tests/Rector/          # Rector rules — run outside PHPUnit coverage
- tests/eventdispatcher/ # Example modules for documentation

# Strip environment-specific path prefixes from coverage reports so Codecov
# can match them to repository files. See https://docs.codecov.com/docs/fixing-paths
fixes:
- '/var/www/localhost/htdocs/openemr/::'     # Apache Docker container
- '/usr/share/nginx/html/openemr/::'         # nginx Docker container
- '/home/runner/work/openemr/openemr/::'     # GitHub Actions runner (isolated tests)

coverage:
  status:
    project:
      default:
        target: 4%        # Require at least 4% overall project coverage
        threshold: 0      # No tolerance below the 4% target
    patch:
      default:
        target: 0%        # New code doesn't need any coverage
        threshold: 0
