ignore:
- tests/PHPStan/         # Static analysis rules — not exercised by PHPUnit
- tests/Rector/          # Rector rules — run outside PHPUnit coverage
- tests/eventdispatcher/ # Example modules for documentation

# Strip environment-specific path prefixes from coverage reports so Codecov
# can match them to repository files. See https://docs.codecov.com/docs/fixing-paths
fixes:
- '/var/www/localhost/htdocs/openemr/::'     # Apache Docker container
- '/usr/share/nginx/html/openemr/::'         # nginx Docker container
- '/home/runner/work/openemr/openemr/::'     # GitHub Actions runner (isolated tests)

coverage:
  status:
    project:
      default:
        target: 27%       # Lock in current ~27% coverage as floor (was 4%)
        threshold: 1%     # Allow 1% fluctuation for test-unrelated changes
    patch:
      default:
        target: 50%       # New code must have at least 50% coverage (was 0%)
        threshold: 5%     # Flexibility for config/migration/generated files
