CREATE TABLE IF NOT EXISTS `form_medical_decision` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,

pname varchar(255),
pbdate varchar(255),
md_pid varchar(255),
md_date varchar(64),
test_lab tinyint(1),
test_lab_cervical tinyint(1),
test_lab_hpv tinyint(1),
test_lab_wet_mount tinyint(1),
test_lab_chlamydia tinyint(1),
test_lab_gonorrhea tinyint(1),
test_lab_other tinyint(1),
test_lab_other_data varchar(255),
test_rad tinyint(1),
test_rad_mammogram tinyint(1),
test_rad_other tinyint(1),
test_rad_other_data varchar(255),
previous_test_results tinyint(1),
previous_test_results_data varchar(255),
test_results_discussion tinyint(1),
test_results_discussion_data varchar(255),
old_records_reviewed tinyint(1),
old_records_reviewed_data varchar(255),
history_other_source tinyint(1),
history_other_source_data varchar(255),
independent_review tinyint(1),
independent_review_data varchar(255),
established_problem tinyint(1),
assessment_and_plan longtext,
md_risk varchar(16),
pc_smoking tinyint(1),
pc_contraception tinyint(1),
pc_weight tinyint(1),
pc_safe_sex tinyint(1),
pc_exercise tinyint(1),
pc_other tinyint(1),
patient_education tinyint(1),
minutes_counseled varchar(255),
total_encounter_time varchar(255),

PRIMARY KEY (id)
) ENGINE=MyISAM;
