CREATE TABLE IF NOT EXISTS `form_bronchitis` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
bronchitis_date_of_illness datetime default NULL,
bronchitis_hpi longtext,
bronchitis_ops_fever varchar(255),
bronchitis_ops_cough varchar(255),
bronchitis_ops_dizziness varchar(255),
bronchitis_ops_chest_pain varchar(255),
bronchitis_ops_dyspnea varchar(255),
bronchitis_ops_sweating varchar(255),
bronchitis_ops_wheezing varchar(255),
bronchitis_ops_malaise varchar(255),
bronchitis_ops_sputum varchar(255),
bronchitis_ops_appearance longtext,
bronchitis_ops_all_reviewed varchar(255),
bronchitis_review_of_pmh varchar(255),
bronchitis_review_of_medications varchar(255),
bronchitis_review_of_allergies varchar(255),
bronchitis_review_of_sh varchar(255),
bronchitis_review_of_fh varchar(255),
bronchitis_tms_normal_right varchar(255),
bronchitis_tms_normal_left varchar(255),
bronchitis_nares_normal_right varchar(255),
bronchitis_nares_normal_left varchar(255),
bronchitis_tms_thickened_right varchar(255),
bronchitis_tms_thickened_left varchar(255),
bronchitis_tms_af_level_right varchar(255),
bronchitis_tms_af_level_left varchar(255),
bronchitis_nares_swelling_right varchar(255),
bronchitis_nares_swelling_left varchar(255),
bronchitis_tms_retracted_right varchar(255),
bronchitis_tms_retracted_left varchar(255),
bronchitis_nares_discharge_right varchar(255),
bronchitis_nares_discharge_left varchar(255),
bronchitis_tms_bulging_right varchar(255),
bronchitis_tms_bulging_left varchar(255),
bronchitis_tms_perforated_right varchar(255),
bronchitis_tms_perforated_left varchar(255),
bronchitis_tms_nares_not_examined varchar(255),
bronchitis_no_sinus_tenderness varchar(255),
bronchitis_oropharynx_normal varchar(255),
bronchitis_sinus_tenderness_frontal_right varchar(255),
bronchitis_sinus_tenderness_frontal_left varchar(255),
bronchitis_oropharynx_erythema varchar(255),
bronchitis_oropharynx_exudate varchar(255),
bronchitis_oropharynx_abcess varchar(255),
bronchitis_oropharynx_ulcers varchar(255),
bronchitis_sinus_tenderness_maxillary_right varchar(255),
bronchitis_sinus_tenderness_maxillary_left varchar(255),
bronchitis_oropharynx_appearance longtext,
bronchitis_sinus_tenderness_not_examined varchar(255),
bronchitis_oropharynx_not_examined varchar(255),
bronchitis_heart_pmi varchar(255),
bronchitis_heart_s3 varchar(255),
bronchitis_heart_s4 varchar(255),
bronchitis_heart_click varchar(255),
bronchitis_heart_rub varchar(255),
bronchitis_heart_murmur longtext,
bronchitis_heart_grade longtext,
bronchitis_heart_location longtext,
bronchitis_heart_normal varchar(255),
bronchitis_heart_not_examined varchar(255),
bronchitis_lungs_bs_normal varchar(255),
bronchitis_lungs_bs_reduced varchar(255),
bronchitis_lungs_bs_increased varchar(255),
bronchitis_lungs_crackles_lll varchar(255),
bronchitis_lungs_crackles_rll varchar(255),
bronchitis_lungs_crackles_bll varchar(255),
bronchitis_lungs_rubs_lll varchar(255),
bronchitis_lungs_rubs_rll varchar(255),
bronchitis_lungs_rubs_bll varchar(255),
bronchitis_lungs_wheezes_lll varchar(255),
bronchitis_lungs_wheezes_rll varchar(255),
bronchitis_lungs_wheezes_bll varchar(255),
bronchitis_lungs_wheezes_dll varchar(255),
bronchitis_lungs_normal_exam varchar(255),
bronchitis_lungs_not_examined varchar(255),
bronchitis_diagnostic_tests longtext,
diagnosis1_bronchitis_form varchar(255),
diagnosis2_bronchitis_form varchar(255),
diagnosis3_bronchitis_form varchar(255),
diagnosis4_bronchitis_form varchar(255),
bronchitis_additional_diagnosis longtext,
bronchitis_treatment longtext,
PRIMARY KEY (id)
) ENGINE=InnoDB;
