CREATE TABLE IF NOT EXISTS `form_bronchitis` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user text(255) default NULL,
groupname text(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
bronchitis_date_of_illness datetime default NULL,
bronchitis_hpi longtext,
bronchitis_ops_fever text(255),
bronchitis_ops_cough text(255),
bronchitis_ops_dizziness text(255),
bronchitis_ops_chest_pain text(255),
bronchitis_ops_dyspnea text(255),
bronchitis_ops_sweating text(255),
bronchitis_ops_wheezing text(255),
bronchitis_ops_malaise text(255),
bronchitis_ops_sputum text(255),
bronchitis_ops_appearance longtext,
bronchitis_ops_all_reviewed text(255),
bronchitis_review_of_pmh text(255),
bronchitis_review_of_medications text(255),
bronchitis_review_of_allergies text(255),
bronchitis_review_of_sh text(255),
bronchitis_review_of_fh text(255),
bronchitis_tms_normal_right text(255),
bronchitis_tms_normal_left text(255),
bronchitis_nares_normal_right text(255),
bronchitis_nares_normal_left text(255),
bronchitis_tms_thickened_right text(255),
bronchitis_tms_thickened_left text(255),
bronchitis_tms_af_level_right text(255),
bronchitis_tms_af_level_left text(255),
bronchitis_nares_swelling_right text(255),
bronchitis_nares_swelling_left text(255),
bronchitis_tms_retracted_right text(255),
bronchitis_tms_retracted_left text(255),
bronchitis_nares_discharge_right text(255),
bronchitis_nares_discharge_left text(255),
bronchitis_tms_bulging_right text(255),
bronchitis_tms_bulging_left text(255),
bronchitis_tms_perforated_right text(255),
bronchitis_tms_perforated_left text(255),
bronchitis_tms_nares_not_examined text(255),
bronchitis_no_sinus_tenderness text(255),
bronchitis_oropharynx_normal text(255),
bronchitis_sinus_tenderness_frontal_right text(255),
bronchitis_sinus_tenderness_frontal_left text(255),
bronchitis_oropharynx_erythema text(255),
bronchitis_oropharynx_exudate text(255),
bronchitis_oropharynx_abcess text(255),
bronchitis_oropharynx_ulcers text(255),
bronchitis_sinus_tenderness_maxillary_right text(255),
bronchitis_sinus_tenderness_maxillary_left text(255),
bronchitis_oropharynx_appearance longtext,
bronchitis_sinus_tenderness_not_examined text(255),
bronchitis_oropharynx_not_examined text(255),
bronchitis_heart_pmi text(255),
bronchitis_heart_s3 text(255),
bronchitis_heart_s4 text(255),
bronchitis_heart_click text(255),
bronchitis_heart_rub text(255),
bronchitis_heart_murmur longtext,
bronchitis_heart_grade longtext,
bronchitis_heart_location longtext,
bronchitis_heart_normal text(255),
bronchitis_heart_not_examined text(255),
bronchitis_lungs_bs_normal text(255),
bronchitis_lungs_bs_reduced text(255),
bronchitis_lungs_bs_increased text(255),
bronchitis_lungs_crackles_lll text(255),
bronchitis_lungs_crackles_rll text(255),
bronchitis_lungs_crackles_bll text(255),
bronchitis_lungs_rubs_lll text(255),
bronchitis_lungs_rubs_rll text(255),
bronchitis_lungs_rubs_bll text(255),
bronchitis_lungs_wheezes_lll text(255),
bronchitis_lungs_wheezes_rll text(255),
bronchitis_lungs_wheezes_bll text(255),
bronchitis_lungs_wheezes_dll text(255),
bronchitis_lungs_normal_exam text(255),
bronchitis_lungs_not_examined text(255),
bronchitis_diagnostic_tests longtext,
diagnosis1_bronchitis_form text(255),
diagnosis2_bronchitis_form text(255),
diagnosis3_bronchitis_form text(255),
diagnosis4_bronchitis_form text(255),
bronchitis_additional_diagnosis longtext,
bronchitis_treatment longtext,
PRIMARY KEY (id)
) ENGINE=InnoDB;
