# docker-compose.yml for travis ci testing
services:
  mysql:
    restart: always
    image: mariadb:11.6
    command: ['mariadbd','--character-set-server=utf8mb4']
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    image: openemr/openemr:flex-3.20
    ports:
    - 80:80
    - 443:443
    volumes:
    - ../../:/var/www/localhost/htdocs/openemr
    environment:
      FORCE_NO_BUILD_MODE: "yes"
      EMPTY: "yes"
    depends_on:
    - mysql
