CREATE TABLE IF NOT EXISTS `form_hearingtest` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
right_ear_250 longtext,
right_ear_500 longtext,
right_ear_1000 longtext,
right_ear_2000 longtext,
right_ear_3000 longtext,
right_ear_4000 longtext,
right_ear_5000 longtext,
right_ear_6000 longtext,
left_ear_250 longtext,
left_ear_500 longtext,
left_ear_1000 longtext,
left_ear_2000 longtext,
left_ear_3000 longtext,
left_ear_4000 longtext,
left_ear_5000 longtext,
left_ear_6000 longtext,
with_hearing_aid varchar(255),
additional_notes longtext,
PRIMARY KEY (id)
) ENGINE=InnoDB;
