# Helpers for BATS tests of .github/scripts/sync-byte-identical.sh.
#
# Loaded by sync.bats via `load 'helpers'`. Provides synthetic-git-repo
# fixture setup + helpers for asserting against the script's outputs.
#
# Pattern follows tests/bats/docker/helpers.bash -- standalone bash
# helpers; no bats-support / bats-assert dependency (kept simple with
# plain [[ ]] in the .bats files).

# Resolve the script-under-test's absolute path AT LOAD TIME. BATS sets
# BASH_SOURCE while sourcing the helpers, before any @test does `cd`
# into its temp working dir.
__HELPERS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNC_BYTE_IDENTICAL_SCRIPT="$(cd "${__HELPERS_DIR}/../../../.." && pwd)/.github/scripts/sync-byte-identical.sh"

# Create a fresh temp git repo with master + the target rel branch (default
# rel-810), both rooted at an empty seed commit. cd's into the repo.
#
# Sets: REPO, OUTPUT_DIR (in the calling shell -- BATS's setup() runs in
# the same shell as the @test that follows).
setup_test_repo() {
    local rel_branch="${1:-rel-810}"
    REPO=$(mktemp -d -t sync-byte-identical-test-XXXX)
    OUTPUT_DIR="${REPO}/output"
    mkdir -p "$OUTPUT_DIR"

    cd "$REPO"
    git init -q -b master
    git config user.email "test@example.com"
    git config user.name "Test"
    git commit -q --allow-empty -m "seed"
    git branch "$rel_branch"
}

teardown_test_repo() {
    cd /
    rm -rf "$REPO"
}

# Add or update a file on a specific branch with the given content.
write_on_branch() {
    local branch="$1" path="$2" content="$3"
    git checkout -q "$branch"
    mkdir -p "$(dirname "$path")"
    echo "$content" > "$path"
    git add "$path"
    git commit -q -m "write $path on $branch"
}

# Delete a file on a specific branch.
delete_on_branch() {
    local branch="$1" path="$2"
    git checkout -q "$branch"
    git rm -q "$path"
    git commit -q -m "delete $path on $branch"
}

# Write the FILES_ALL config on master with the given file list (one per
# arg). Skipping arguments yields an empty `files:` list (useful for the
# "empty config" test).
write_files_all_config() {
    git checkout -q master
    mkdir -p .github
    {
        echo "# Auto-generated by helpers.bash for testing."
        echo "files:"
        for f in "$@"; do
            echo "  - $f"
        done
    } > .github/docker-byte-identical.yml
    git add .github/docker-byte-identical.yml
    git commit -q -m "FILES_ALL config: $*"
}

# Write the FILES_ALL config raw -- caller provides the entire YAML.
# Useful for malformed-list / duplicate-entry tests.
write_files_all_raw() {
    local content="$1"
    git checkout -q master
    mkdir -p .github
    echo "$content" > .github/docker-byte-identical.yml
    git add .github/docker-byte-identical.yml
    git commit -q -m "FILES_ALL config (raw)"
}
