services:
  mysql:
    extends:
      file: ../compose-shared.yml
      service: mysql
    image: mariadb:11.4
  openemr:
    extends:
      file: ../compose-shared.yml
      service: openemr
    image: openemr/openemr:flex-3.18
