/*
Most of this monitoring code was generated by Codex 5.3
*/

locals {
  alarm_actions  = var.alarm_sns_topic_arn != "" ? [var.alarm_sns_topic_arn] : []
  alb_arn_suffix = local.alb_arn_effective != "" ? try(element(split("loadbalancer/", local.alb_arn_effective), 1), "") : ""
  tg_arn_suffix  = local.openemr_target_group_arn_effective != "" ? "targetgroup/${try(element(split("targetgroup/", local.openemr_target_group_arn_effective), 1), "")}" : ""
}

resource "aws_cloudwatch_metric_alarm" "alb_5xx" {
  count               = local.create_monitoring_effective ? 1 : 0
  alarm_name          = "${local.app_name}-alb-5xx"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "HTTPCode_Target_5XX_Count"
  namespace           = "AWS/ApplicationELB"
  period              = 60
  statistic           = "Sum"
  threshold           = 5
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions

  dimensions = {
    LoadBalancer = local.alb_arn_suffix
    TargetGroup  = local.tg_arn_suffix
  }
}

resource "aws_cloudwatch_metric_alarm" "alb_unhealthy_hosts" {
  count               = local.create_monitoring_effective ? 1 : 0
  alarm_name          = "${local.app_name}-alb-unhealthy-hosts"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "UnHealthyHostCount"
  namespace           = "AWS/ApplicationELB"
  period              = 60
  statistic           = "Maximum"
  threshold           = 0
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions

  dimensions = {
    LoadBalancer = local.alb_arn_suffix
    TargetGroup  = local.tg_arn_suffix
  }
}

resource "aws_cloudwatch_metric_alarm" "alb_latency_high" {
  count               = local.create_monitoring_effective ? 1 : 0
  alarm_name          = "${local.app_name}-alb-latency-high"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 3
  metric_name         = "TargetResponseTime"
  namespace           = "AWS/ApplicationELB"
  period              = 60
  statistic           = "Average"
  threshold           = 2
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions

  dimensions = {
    LoadBalancer = local.alb_arn_suffix
    TargetGroup  = local.tg_arn_suffix
  }
}

resource "aws_cloudwatch_metric_alarm" "ecs_cpu_high" {
  count               = local.create_monitoring_effective ? 1 : 0
  alarm_name          = "${local.app_name}-ecs-openemr-cpu-high"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 3
  metric_name         = "CPUUtilization"
  namespace           = "AWS/ECS"
  period              = 60
  statistic           = "Average"
  threshold           = 80
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions

  dimensions = {
    ClusterName = aws_ecs_cluster.app.name
    ServiceName = aws_ecs_service.openemr.name
  }
}

resource "aws_cloudwatch_metric_alarm" "ecs_memory_high" {
  count               = local.create_monitoring_effective ? 1 : 0
  alarm_name          = "${local.app_name}-ecs-openemr-memory-high"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 3
  metric_name         = "MemoryUtilization"
  namespace           = "AWS/ECS"
  period              = 60
  statistic           = "Average"
  threshold           = 85
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions

  dimensions = {
    ClusterName = aws_ecs_cluster.app.name
    ServiceName = aws_ecs_service.openemr.name
  }
}

resource "aws_cloudwatch_metric_alarm" "rds_cpu_high" {
  count               = local.create_monitoring_effective && local.create_db_effective ? 1 : 0
  alarm_name          = "${local.app_name}-rds-cpu-high"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 3
  metric_name         = "CPUUtilization"
  namespace           = "AWS/RDS"
  period              = 60
  statistic           = "Average"
  threshold           = 80
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.mysql[0].id
  }
}

resource "aws_cloudwatch_metric_alarm" "rds_free_storage_low" {
  count               = local.create_monitoring_effective && local.create_db_effective ? 1 : 0
  alarm_name          = "${local.app_name}-rds-free-storage-low"
  comparison_operator = "LessThanThreshold"
  evaluation_periods  = 3
  metric_name         = "FreeStorageSpace"
  namespace           = "AWS/RDS"
  period              = 300
  statistic           = "Average"
  threshold           = 5000000000
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.mysql[0].id
  }
}

resource "aws_cloudwatch_dashboard" "openemr" {
  count          = local.create_monitoring_effective ? 1 : 0
  dashboard_name = "${local.app_name}-openemr-overview"

  dashboard_body = jsonencode({
    widgets = [
      {
        type   = "metric"
        x      = 0
        y      = 0
        width  = 12
        height = 6
        properties = {
          title   = "ALB Traffic and Errors"
          view    = "timeSeries"
          stacked = false
          region  = var.aws_region
          metrics = [
            ["AWS/ApplicationELB", "RequestCount", "LoadBalancer", local.alb_arn_suffix, "TargetGroup", local.tg_arn_suffix],
            ["AWS/ApplicationELB", "HTTPCode_Target_4XX_Count", "LoadBalancer", local.alb_arn_suffix, "TargetGroup", local.tg_arn_suffix],
            ["AWS/ApplicationELB", "HTTPCode_Target_5XX_Count", "LoadBalancer", local.alb_arn_suffix, "TargetGroup", local.tg_arn_suffix]
          ]
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 0
        width  = 12
        height = 6
        properties = {
          title   = "ALB Target Health and Latency"
          view    = "timeSeries"
          stacked = false
          region  = var.aws_region
          metrics = [
            ["AWS/ApplicationELB", "HealthyHostCount", "LoadBalancer", local.alb_arn_suffix, "TargetGroup", local.tg_arn_suffix],
            ["AWS/ApplicationELB", "UnHealthyHostCount", "LoadBalancer", local.alb_arn_suffix, "TargetGroup", local.tg_arn_suffix],
            ["AWS/ApplicationELB", "TargetResponseTime", "LoadBalancer", local.alb_arn_suffix, "TargetGroup", local.tg_arn_suffix]
          ]
        }
      },
      {
        type   = "metric"
        x      = 0
        y      = 6
        width  = 12
        height = 6
        properties = {
          title   = "ECS OpenEMR CPU and Memory"
          view    = "timeSeries"
          stacked = false
          region  = var.aws_region
          metrics = [
            ["AWS/ECS", "CPUUtilization", "ClusterName", aws_ecs_cluster.app.name, "ServiceName", aws_ecs_service.openemr.name],
            ["AWS/ECS", "MemoryUtilization", "ClusterName", aws_ecs_cluster.app.name, "ServiceName", aws_ecs_service.openemr.name]
          ]
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 6
        width  = 12
        height = 6
        properties = {
          title   = "EFS Throughput and Connections"
          view    = "timeSeries"
          stacked = false
          region  = var.aws_region
          metrics = [
            ["AWS/EFS", "TotalIOBytes", "FileSystemId", aws_efs_file_system.openemr_sites.id],
            ["AWS/EFS", "ClientConnections", "FileSystemId", aws_efs_file_system.openemr_sites.id],
            ["AWS/EFS", "BurstCreditBalance", "FileSystemId", aws_efs_file_system.openemr_sites.id]
          ]
        }
      },
      {
        type   = "metric"
        x      = 0
        y      = 12
        width  = 24
        height = 6
        properties = {
          title   = "RDS Database Health (if created)"
          view    = "timeSeries"
          stacked = false
          region  = var.aws_region
          metrics = local.create_db_effective ? [
            ["AWS/RDS", "CPUUtilization", "DBInstanceIdentifier", aws_db_instance.mysql[0].id],
            ["AWS/RDS", "DatabaseConnections", "DBInstanceIdentifier", aws_db_instance.mysql[0].id],
            ["AWS/RDS", "FreeStorageSpace", "DBInstanceIdentifier", aws_db_instance.mysql[0].id],
            ["AWS/RDS", "FreeableMemory", "DBInstanceIdentifier", aws_db_instance.mysql[0].id],
            ["AWS/RDS", "ReadLatency", "DBInstanceIdentifier", aws_db_instance.mysql[0].id],
            ["AWS/RDS", "WriteLatency", "DBInstanceIdentifier", aws_db_instance.mysql[0].id]
          ] : []
        }
      },
      {
        type   = "log"
        x      = 0
        y      = 18
        width  = 24
        height = 6
        properties = {
          title  = "OpenEMR Recent Errors"
          region = var.aws_region
          query  = "SOURCE '/ecs/${var.openemr_task_family}' | fields @timestamp, @message | filter @message like /ERROR|Exception|fatal/i | sort @timestamp desc | limit 100"
          view   = "table"
        }
      }
    ]
  })
}

/*
Most of this monitoring code was generated by Codex 5.3
*/
