<script>
    /* +-----------------------------------------------------------------------------+
     * Copyright 2016 matrix israel
     * LICENSE: This program is free software; you can redistribute it and/or
     * modify it under the terms of the GNU General Public License
     * as published by the Free Software Foundation; either version 3
     * of the License, or (at your option) any later version.
     * This program is distributed in the hope that it will be useful,
     * but WITHOUT ANY WARRANTY; without even the implied warranty of
     * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
     * GNU General Public License for more details.
     * You should have received a copy of the GNU General Public License
     * along with this program. If not, see
     * http://www.gnu.org/licenses/licenses.html#GPL
     *    @author  Oshri Rozmarin <oshri.rozmarin@gmail.com>
     * +------------------------------------------------------------------------------+
     *
     */
    <?php
    if ($closeBeforeOpening):
    ?>
    opener.document.forms[0].submit();
    window.close();

    <?php
    endif;
    ?>
</script>


<div class="safekey">
            <label class="yoursafekey"><?php echo $translate->z_xlt('Your safe key is')?>:</label>

            <div class="box">
                <h1><?php echo $this->escapeHtml($randomSafeKey)?></h1>
            </div>
            <p><?php echo $translate->z_xlt('Store your safe key at settings globals in security tab')?></p>

            <input type="button" name="back" value="<?php echo $translate->z_xlt('Back')?>" onclick="back()" />
            <input type="button" name="back" value="<?php echo $translate->z_xlt('Generate new key')?>" onclick="newkey()" />

</div>


<script>
    function back(){
        window.location.href = window.history.back(1);
    }

    function newkey(){
        location.reload();
    }
</script>