<?php
/* +-----------------------------------------------------------------------------+
*    OpenEMR - Open Source Electronic Medical Record
*    Copyright (C) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
*
*    This program is free software: you can redistribute it and/or modify
*    it under the terms of the GNU Affero General Public License as
*    published by the Free Software Foundation, either version 3 of the
*    License, or (at your option) any later version.
*
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU Affero General Public License for more details.
*
*    You should have received a copy of the GNU Affero General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*    @author  Bindia Nandakumar  <bindia@zhservices.com>
* +------------------------------------------------------------------------------+
*/

$listener	    = $this->listenerObject;
$res            = $this->view;
$title1 	    = $listener->z_xlt('Report');
$title2 	    = $listener->z_xlt('Immunization Registry');
$codes          = $listener->z_xlt('Codes'); 
$from           = $listener->z_xlt('From'); 
$to             = $listener->z_xlt('To');
$isFormRefresh  = $this->isFormRefresh;
$form           = $this->form;
$form->setAttribute('action', $this->url('immunization', array('action' => 'index')).'/index');
$form->prepare();

?>
    <script type="text/javascript">
        $(document).ready(function(){
            height_value = $('.responsive tr').length * 25 + 220;
            if(height_value < 245){ height_value = 245 };
            parent.iframeLoaded(height_value, 'immunization_iframe');
        });
    </script>
    <body>
        <div id="report_parameters_daterange">
            <?php echo date("d F Y", strtotime($this->form_data['form_from_date'])) ." &nbsp; to &nbsp; ". date("d F Y", strtotime($this->form_data['form_to_date'])); ?>
        </div>
        <?php echo $this->form()->openTag($form);?>
        <div id="printtable">
        <div class="se_in_15 se_in_16">
            <table>
                <tr>
                    <td class="se_in_16_label"><label><?php echo $listener->z_xlt('Date'); ?></label></td>
                    <td nowrap>
                            <?php echo  $this->formRow($form->get('from_date'));?>
                            <?php echo  $this->formRow($form->get('to_date'));?>
                            <script type="text/javascript">
                                $(document).ready(function(){
                                        $( "#from_date" ).datepicker("setDate", '<?php echo $this->commonplugin->date_format($this->form_data['form_from_date'], $GLOBALS['date_display_format'], 'yyyy-mm-dd');?>' );
                                        $( "#to_date" ).datepicker("setDate", '<?php echo $this->commonplugin->date_format($this->form_data['form_to_date'], $GLOBALS['date_display_format'], 'yyyy-mm-dd');?>');
                                });
                            </script>
                    </td>
                </tr>
                <tr>
                    <td><label><?php echo $codes; ?></label></td>
                    <td>
                        <?php echo  $this->formRow($form->get('codes'));?>
                    </td>
                </tr>
                <tr>
                    <td><label><?php echo $listener->z_xlt('Patient Name/ID'); ?></label></td>
                    <td><input  style="width: 46% !important;" type="text" name="patient_id" value="<?php echo $this->escapeHtml($this->form_data['patient_id']);?>" /><br/></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formRow($form->get('search')); ?>
                    </td>
                </tr>
             </table>
        </div>
        </div>
        <div class="clear"></div>
        <div class="body_inner_wrapper">
            <div class="header_wrap">
                <div class="header_wrap_left">
                    <div class="search_button" id="searchbutton" title="<?php echo $listener->z_xla('Search');?>"><?php echo $listener->z_xlt('SEARCH'); ?></div>&nbsp;&nbsp;
                    <?php if(count($res) > 0){?>
                    <?php echo $this->formRow($form->get('hl7button')); ?>&nbsp;&nbsp;
                    <?php
                        $arr = $this->getVariables('Application\Controller\SendtoController','sendAction');
                        $arr['required_butons'] = array('download');
                        $arr['send_via']        = 'download';
                        $arr['download_format'] = array('hl7_format');
                        $this->layout('immunization/layout/layout');
                        echo $this->partial("application/sendto/send",$arr);
                    ?>
                    <div class="se_in_3" title="<?php echo $listener->z_xla('Reload');?>" onclick="reloadPage();"></div>
                    <?php }?>
                </div>
                <div class="header_wrap_right" style="<?php if(count($res) == 0){ ?>display: none;<?php } ?>">
                    <div class="se_in_4">
                        <label style="font-size:12px;"><?php echo $listener->z_xlt('Show');?>&nbsp;</label>&nbsp;<input maxlength="3" type="text" onkeypress="return isNumber(event)" id="form_results" name="form_results" value="<?php echo $this->escapeHtml($this->form_data['results']);?>" />&nbsp;<label style="font-size:12px;">&nbsp;<?php echo $listener->z_xlt('Immunizations'); ?></label>
                    </div>
                    <div class="se_in_6">
                        <div class="se_in_5">
                            <div class="se_in_5-1" onclick="pagination('first');"></div>
                            <div class="se_in_5-2" onclick="<?php if($this->form_data['current_page'] > 1) { ?> pagination('previous'); <?php } ?>"></div>
                            <div class="se_in_5-3" onclick="<?php if($this->form_data['current_page'] < $this->form_data['total_pages']) { ?> pagination('next'); <?php }?>"></div>
                            <div class="se_in_5-4" onclick="pagination('last');"></div>
                        </div>
                        <div class="clear"></div>
                        <div class="se_in_7">
                            <label><?php echo $listener->z_xlt('Page');?> <?php echo $this->escapeHtml($this->form_data['current_page']);?> - <?php echo $listener->z_xlt('of');?> <?php echo $this->escapeHtml($this->form_data['total_pages']);?></label>
                        </div><!-- se_in_7 -->
                    </div><!-- se_in_6 -->
                </div>
               </div>
        </div>

        <?php if($isFormRefresh == 'true'){ ?>
        <div class="clear"></div>
        <div class="se_in_8">
           <?php if(count($res) > 0){ ?>
           <table class="responsive"> 
                <tr class="se_in_9">
                        <th width="2%">#</th>
                        <th width="10%" ><?php echo $listener->z_xlt('Patient Id'); ?></th>
                        <th width="15%"><?php echo $listener->z_xlt('Patient Name'); ?></th>
                        <th width="18%"><?php echo $listener->z_xlt('Immunization Code'); ?></th>
                        <th><?php echo $listener->z_xlt('Immunization Title'); ?></th>
                        <th><?php echo $listener->z_xlt('Immunization Date'); ?></th>	
                </tr>
                <?php 
                $slno       = ($this->escapeHtml($this->form_data['current_page']) - 1) * $this->escapeHtml($this->form_data['results']); 
                foreach ($res as $value):
                  $slno++;
                ?>
                <tr>
                        <td style="height: 17px;"><label><?php echo $slno;?>)</label></td>
                        <td width="10%"><?php echo $this->escapeHtml($value['patientid']); ?></td>
                        <td><?php echo $this->escapeHtml($value['patientname']); ?></td>
                        <td><?php echo $this->escapeHtml($value['cvx_code']); ?></td>
                        <td><?php echo $this->escapeHtml($listener->z_xlt($value['immunizationtitle'])); ?></td>
                        <td><?php echo $this->commonplugin->date_format($value['immunizationdate'], $GLOBALS['date_display_format'], 'yyyy-mm-dd'); ?></td>	
                </tr>
                 <?php endforeach; ?>
                <tr>
                    <th colspan="6">
                    <?php echo $listener->z_xlt('Total Number of Immunizations').':'; ?>
                    <?php echo $this->escapeHtml(sizeof($res));?>
                    </th>
                </tr>
           </table> 
           <?php } else {?>
                <div style="width: 60%; margin-left: auto; margin-right: auto; border: 1px solid #CCCCCC; text-align:center; padding: 30px; font-size: 15px; font-weight: bold; background: #f7f7f7;<?php if(count($this->details) > 0){ ?>display: none; <?php } ?>">
                    <?php echo $listener->z_xlt('Nothing to display');?>
                </div>
           <?php }?>
        </div>
        <?php } ?>
        <input type="hidden" name="form_current_page" id="form_current_page" value="<?php echo trim($this->escapeHtml($this->form_data['current_page']));?>" />
        <input type="hidden" name="form_total_pages" id="form_total_pages" value="<?php echo $this->escapeHtml($this->form_data['total_pages']);?>" />
        <input type="hidden" name="form_count" id="form_count" value="<?php echo $this->escapeHtml($this->form_data['res_count']);?>" />
        <input type="hidden" name="form_new_search" id="form_new_search" value="" />
    </body>

<?php echo $this->form()->closeTag(); ?>