; vim: ft=dosini
[global]
error_log = /proc/self/fd/2
log_limit = 32768

[www]
access.log = ${PHP_FPM_ACCESS_LOG}
; Allow env vars to reach workers
clear_env = no
; Capture stdout/stderr for loggers
catch_workers_output = yes
decorate_workers_output = no

listen = ${PHP_FPM_LISTEN}
