; Default PHP settings
display_errors = Off
error_reporting = E_ALL
expose_php = Off
log_errors = On

; https://www.php.net/manual/en/function.assert.php
assert.exception = 1
zend.assertions = ${PHP_ZEND_ASSERTIONS}
