<?php
/**
 * interface/modules/zend_modules/module/Documents/view/documents/documents/retrieve.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Basil PT <basil@zhservices.com>
 * @copyright Copyright (c) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
?>
<div>
	<center>
		<div class="doc-doc-ls-23"></div>
		<div class="doc-doc-ls-24"><?php echo $this->listenerObject->z_xlt('Preview not available for this document type');?></div>
	</center>
</div>