x-includes:
  node-version: "24"
  selenium-template: "compose-shared-selenium/docker-compose.yml"
  webserver-template: "compose-shared-nginx/compose.yml"
  database-template: "compose-shared-mariadb.yml"
  mailpit-template: "compose-shared-mailpit/compose.yml"

services:
  mysql:
    image: mariadb:12.2@sha256:b3af559fc38e013c50dd5b5993bfbbb21125c1a62d976b3b0a14d9c4acaae578
  openemr:
    image: openemr/dev-php-fpm:8.3@sha256:b7304018c9504bb0c9a2b28e358c66a4ec15a9ff8f914dc1f6d11c0e8dedb8f5
