CREATE TABLE IF NOT EXISTS `form_ext_exam2` (
	`id` BIGINT(20) NOT NULL auto_increment,
	`date` DATETIME DEFAULT NULL,
	`pid` BIGINT(20),
	`user` VARCHAR(255) DEFAULT NULL,
	`groupname` VARCHAR(255) DEFAULT NULL,
	`authorized` TINYINT(4),
	`activity` TINYINT(4),
	`form_complete` VARCHAR(16) DEFAULT NULL,
	`form_priority` VARCHAR(16) DEFAULT NULL,
	`approved_by` VARCHAR(255) DEFAULT NULL,
	`approved_dt` DATETIME DEFAULT NULL,

	`form_dt` date DEFAULT NULL,
	`cc` TEXT DEFAULT NULL,
	`hpi` TEXT DEFAULT NULL,
	`rec_review` TINYINT(1),
	`diagnostics_nt` MEDIUMTEXT DEFAULT NULL,
	`form_type` VARCHAR(32) DEFAULT 'exam',

/* General Examination */
	`vid` BIGINT(20) DEFAULT 0,
	`ge_dictate` MEDIUMTEXT DEFAULT '',
	`ge_gen_norm` TINYINT(1),
	`ge_gen_norm_nt` TEXT DEFAULT NULL,
	`ge_gen_dev` TINYINT(1),
	`ge_gen_dev_nt` TEXT DEFAULT NULL,
	`ge_gen_groom` TINYINT(1),
	`ge_gen_groom_nt` TEXT DEFAULT NULL,
	`ge_gen_dis` TINYINT(1),
	`ge_gen_dis_nt` TEXT DEFAULT NULL,
	`ge_gen_jaun` VARCHAR(1) DEFAULT NULL,
	`ge_gen_jaun_nt` TEXT DEFAULT NULL,
	`ge_gen_waste` VARCHAR(1) DEFAULT NULL,
	`ge_gen_waste_nt` TEXT DEFAULT NULL,
	`ge_gen_sleep` VARCHAR(1) DEFAULT NULL,
	`ge_gen_sleep_nt` TEXT DEFAULT NULL,
	`ge_gen_nt` TEXT DEFAULT NULL,
/* Head */
	`ge_hd_atra` TINYINT(1),
	`ge_hd_atra_nt` TEXT DEFAULT NULL,
	`ge_hd_norm` TINYINT(1),
	`ge_hd_norm_nt` TEXT DEFAULT NULL,
	`ge_hd_feat` VARCHAR(2) DEFAULT NULL,
	`ge_hd_feat_nt` TEXT DEFAULT NULL,
	`ge_hd_ant` VARCHAR(2) DEFAULT NULL,
	`ge_hd_ant_nt` TEXT DEFAULT NULL,
	`ge_hd_chks` TEXT DEFAULT NULL,
	`ge_hd_nt` TEXT DEFAULT NULL,
/* Eyes */
	`ge_eyer_norm` VARCHAR(1) DEFAULT NULL,
	`ge_eyer_norm_nt` TEXT DEFAULT NULL,
	`ge_eye_pupil` VARCHAR(1) DEFAULT NULL,
	`ge_eye_pupil_nt` TEXT DEFAULT NULL,
	`ge_eye_hem` VARCHAR(1) DEFAULT NULL,
	`ge_eye_hem_nt` TEXT DEFAULT NULL,
	`ge_eye_exu` VARCHAR(1) DEFAULT NULL,
	`ge_eye_exu_nt` TEXT DEFAULT NULL,
	`ge_eye_av` VARCHAR(1) DEFAULT NULL,
	`ge_eye_av_nt` TEXT DEFAULT NULL,
	`ge_eye_pap` VARCHAR(1) DEFAULT NULL,
	`ge_eye_pap_nt` TEXT DEFAULT NULL,
	`ge_eyer_exo` VARCHAR(1) DEFAULT NULL,
	`ge_eyer_exo_nt` TEXT DEFAULT NULL,
	`ge_eyer_stare` VARCHAR(1) DEFAULT NULL,
	`ge_eyer_stare_nt` TEXT DEFAULT NULL,
	`ge_eyer_lag` VARCHAR(1) DEFAULT NULL,
	`ge_eyer_lag_nt` TEXT DEFAULT NULL,
	`ge_eyer_scleral` TINYINT(1),
	`ge_eyer_scleral_nt` TEXT DEFAULT NULL,
	`ge_eyer_eomi` VARCHAR(1) DEFAULT NULL,
	`ge_eyer_eomi_nt` TEXT DEFAULT NULL,
	`ge_eyer_perrl` VARCHAR(1) DEFAULT NULL,
	`ge_eyer_perrl_nt` TEXT DEFAULT NULL,
	`ge_eyel_norm` VARCHAR(1) DEFAULT NULL,
	`ge_eyel_norm_nt` TEXT DEFAULT NULL,
	`ge_eyel_exo` VARCHAR(1) DEFAULT NULL,
	`ge_eyel_exo_nt` TEXT DEFAULT NULL,
	`ge_eyel_stare` VARCHAR(1) DEFAULT NULL,
	`ge_eyel_stare_nt` TEXT DEFAULT NULL,
	`ge_eyel_lag` VARCHAR(1) DEFAULT NULL,
	`ge_eyel_lag_nt` TEXT DEFAULT NULL,
	`ge_eyel_scleral` TINYINT(1),
	`ge_eyel_scleral_nt` TEXT DEFAULT NULL,
	`ge_eyel_eomi` VARCHAR(1) DEFAULT NULL,
	`ge_eyel_eomi_nt` TEXT DEFAULT NULL,
	`ge_eyel_perrl` VARCHAR(1) DEFAULT NULL,
	`ge_eyel_perrl_nt` TEXT DEFAULT NULL,
	`ge_eye_nt` TEXT DEFAULT NULL,
/* Ears */
	`ge_earr_tym_nt` TEXT DEFAULT NULL,
	`ge_earr_clear` VARCHAR(1) DEFAULT NULL,
	`ge_earr_clear_nt` TEXT DEFAULT NULL,
	`ge_earr_perf` VARCHAR(1) DEFAULT NULL,
	`ge_earr_perf_nt` TEXT DEFAULT NULL,
	`ge_earr_ret` VARCHAR(1) DEFAULT NULL,
	`ge_earr_ret_nt` TEXT DEFAULT NULL,
	`ge_earr_pus` VARCHAR(1) DEFAULT NULL,
	`ge_earr_pus_nt` TEXT DEFAULT NULL,
	`ge_earr_ceru` VARCHAR(1) DEFAULT NULL,
	`ge_earr_ceru_nt` TEXT DEFAULT NULL,
	`ge_earr_bulge` VARCHAR(1) DEFAULT NULL,
	`ge_earr_bulge_nt` TEXT DEFAULT NULL,
	`ge_earl_tym_nt` TEXT DEFAULT NULL,
	`ge_earl_clear` VARCHAR(1) DEFAULT NULL,
	`ge_earl_clear_nt` TEXT DEFAULT NULL,
	`ge_earl_perf` VARCHAR(1) DEFAULT NULL,
	`ge_earl_perf_nt` TEXT DEFAULT NULL,
	`ge_earl_ret` VARCHAR(1) DEFAULT NULL,
	`ge_earl_ret_nt` TEXT DEFAULT NULL,
	`ge_earl_pus` VARCHAR(1) DEFAULT NULL,
	`ge_earl_pus_nt` TEXT DEFAULT NULL,
	`ge_earl_ceru` VARCHAR(1) DEFAULT NULL,
	`ge_earl_ceru_nt` TEXT DEFAULT NULL,
	`ge_earl_bulge` VARCHAR(1) DEFAULT NULL,
	`ge_earl_bulge_nt` TEXT DEFAULT NULL,
	`ge_ear_nt` TEXT DEFAULT NULL,
/* Nose */
	`ge_nose_ery` VARCHAR(1) DEFAULT NULL,
	`ge_nose_ery_nt` TEXT DEFAULT NULL,
	`ge_nose_swell` VARCHAR(1) DEFAULT NULL,
	`ge_nose_swell_nt` TEXT DEFAULT NULL,
	`ge_nose_pall` VARCHAR(1) DEFAULT NULL,
	`ge_nose_pall_nt` TEXT DEFAULT NULL,
	`ge_nose_polps` VARCHAR(1) DEFAULT NULL,
	`ge_nose_polps_nt` TEXT DEFAULT NULL,
	`ge_nose_sept` VARCHAR(1) DEFAULT NULL,
	`ge_nose_sept_nt` TEXT DEFAULT NULL,
	`ge_nose_nt` TEXT DEFAULT NULL,
/* Mouth */
	`ge_mouth_moist` TINYINT(1),
	`ge_mouth_moist_nt` TEXT DEFAULT NULL,
	`ge_mouth_les` TINYINT(1),
	`ge_mouth_les_nt` TEXT DEFAULT NULL,
	`ge_mouth_dent` VARCHAR(1) DEFAULT NULL,
	`ge_mouth_dent_nt` TEXT DEFAULT NULL,
	`ge_mouth_gm_red` VARCHAR(1) DEFAULT NULL,
	`ge_mouth_gm_red_nt` TEXT DEFAULT NULL,
	`ge_mouth_gm_swell` VARCHAR(1) DEFAULT NULL,
	`ge_mouth_gm_swell_nt` TEXT DEFAULT NULL,
	`ge_mouth_gm_bld` VARCHAR(1) DEFAULT NULL,
	`ge_mouth_gm_bld_nt` TEXT DEFAULT NULL,
	`ge_mouth_th_car` VARCHAR(1) DEFAULT NULL,
	`ge_mouth_th_car_nt` TEXT DEFAULT NULL,
	`ge_mouth_th_pd` VARCHAR(1) DEFAULT NULL,
	`ge_mouth_th_pd_nt` TEXT DEFAULT NULL,
	`ge_mouth_th_er` VARCHAR(1) DEFAULT NULL,
	`ge_mouth_th_er_nt` TEXT DEFAULT NULL,
	`ge_mouth_chks` TEXT DEFAULT NULL,
	`ge_mouth_nt` TEXT DEFAULT NULL,
/* Throat */
	`ge_thrt_ery` TINYINT(1),
	`ge_thrt_ery_nt` TEXT DEFAULT NULL,
	`ge_thrt_exu` TINYINT(1),
	`ge_thrt_exu_nt` TEXT DEFAULT NULL,
	`ge_thrt_ton_exu` VARCHAR(1) DEFAULT NULL,
	`ge_thrt_ton_exu_nt` TEXT DEFAULT NULL,
	`ge_thrt_ton_en` VARCHAR(2) DEFAULT NULL,
	`ge_thrt_ton_en_nt` TEXT DEFAULT NULL,
	`ge_thrt_uvu_mid` VARCHAR(1) DEFAULT NULL,
	`ge_thrt_uvu_mid_nt` TEXT DEFAULT NULL,
	`ge_thrt_uvu_swell` VARCHAR(1) DEFAULT NULL,
	`ge_thrt_uvu_swell_nt` TEXT DEFAULT NULL,
	`ge_thrt_uvu_dev` VARCHAR(1) DEFAULT NULL,
	`ge_thrt_uvu_dev_nt` TEXT DEFAULT NULL,
	`ge_thrt_pal_swell` VARCHAR(1) DEFAULT NULL,
	`ge_thrt_pal_swell_nt` TEXT DEFAULT NULL,
	`ge_thrt_pal_pet` VARCHAR(1) DEFAULT NULL,
	`ge_thrt_pal_pet_nt` TEXT DEFAULT NULL,
	`ge_thrt_chks` TEXT DEFAULT NULL,
	`ge_thrt_nt` TEXT DEFAULT NULL,
/* Neck */
	`ge_nk_sup` TINYINT(1),
	`ge_nk_brit` VARCHAR(1) DEFAULT NULL,
	`ge_nk_jvp` VARCHAR(1) DEFAULT NULL,
	`ge_nk_lymph` VARCHAR(1) DEFAULT NULL,
	`ge_nk_trach` TINYINT(1),
	`ge_nk_brit_nt` TEXT DEFAULT NULL,
	`ge_nk_nt` TEXT DEFAULT NULL,
/* Thyroid */
	`ge_thy_norm` TINYINT(1),
	`ge_thy_norm_nt` TEXT DEFAULT NULL,
	`ge_thy_nod` VARCHAR(1) DEFAULT NULL,
	`ge_thy_nod_nt` TEXT DEFAULT NULL,
	`ge_thy_brit` VARCHAR(1) DEFAULT NULL,
	`ge_thy_brit_nt` TEXT DEFAULT NULL,
	`ge_thy_tnd` VARCHAR(1) DEFAULT NULL,
	`ge_thy_tnd_nt` TEXT DEFAULT NULL,
	`ge_thy_nt` TEXT DEFAULT NULL,
/* Lymph */
	`ge_lym_cerv` VARCHAR(1) DEFAULT NULL,
	`ge_lym_cerv_nt` TEXT DEFAULT NULL,
	`ge_lym_sup` VARCHAR(1) DEFAULT NULL,
	`ge_lym_sup_nt` TEXT DEFAULT NULL,
	`ge_lym_ax` VARCHAR(1) DEFAULT NULL,
	`ge_lym_ax_nt` TEXT DEFAULT NULL,
	`ge_lym_in` VARCHAR(1) DEFAULT NULL,
	`ge_lym_in_nt` TEXT DEFAULT NULL,
	`ge_lym_nt` TEXT DEFAULT NULL,
/* Breasts */
	`ge_br_sym` VARCHAR(1) DEFAULT NULL,
	`ge_br_sym_nt` TEXT DEFAULT NULL,
	`ge_brr_axil` VARCHAR(1) DEFAULT NULL,
	`ge_brr_axil_nt` TEXT DEFAULT NULL,
	`ge_brr_mass` VARCHAR(1) DEFAULT NULL,
	`ge_brr_mass_nt` TEXT DEFAULT NULL,
	`ge_brr_tan` VARCHAR(1) DEFAULT NULL,
	`ge_brr_tan_nt` TEXT DEFAULT NULL,
	`ge_brr_chng` VARCHAR(1) DEFAULT NULL,
	`ge_brr_chng_nt` TEXT DEFAULT NULL,

	`ge_brr_nt` TEXT DEFAULT NULL,
	`ge_brl_axil` VARCHAR(1) DEFAULT NULL,
	`ge_brl_axil_nt` TEXT DEFAULT NULL,
	`ge_brl_mass` VARCHAR(1) DEFAULT NULL,
	`ge_brl_mass_nt` TEXT DEFAULT NULL,
	`ge_brl_tan` VARCHAR(1) DEFAULT NULL,
	`ge_brl_tan_nt` TEXT DEFAULT NULL,
	`ge_brl_chng` VARCHAR(1) DEFAULT NULL,
	`ge_brl_chng_nt` TEXT DEFAULT NULL,
	`ge_brl_nt` TEXT DEFAULT NULL,
	`ge_nipr_ev` VARCHAR(1) DEFAULT NULL,
	`ge_nipr_ev_nt` TEXT DEFAULT NULL,
	`ge_nipr_in` VARCHAR(1) DEFAULT NULL,
	`ge_nipr_in_nt` TEXT DEFAULT NULL,
	`ge_nipr_mass` VARCHAR(1) DEFAULT NULL,
	`ge_nipr_mass_nt` TEXT DEFAULT NULL,
	`ge_nipr_dis` VARCHAR(1) DEFAULT NULL,
	`ge_nipr_dis_nt` TEXT DEFAULT NULL,
	`ge_nipr_ret` VARCHAR(1) DEFAULT NULL,
	`ge_nipr_ret_nt` TEXT DEFAULT NULL,
	`ge_nipr_nt` TEXT DEFAULT NULL,
	`ge_nipl_ev` VARCHAR(1) DEFAULT NULL,
	`ge_nipl_ev_nt` TEXT DEFAULT NULL,
	`ge_nipl_in` VARCHAR(1) DEFAULT NULL,
	`ge_nipl_in_nt` TEXT DEFAULT NULL,
	`ge_nipl_mass` VARCHAR(1) DEFAULT NULL,
	`ge_nipl_mass_nt` TEXT DEFAULT NULL,
	`ge_nipl_dis` VARCHAR(1) DEFAULT NULL,
	`ge_nipl_dis_nt` TEXT DEFAULT NULL,
	`ge_nipl_ret` VARCHAR(1) DEFAULT NULL,
	`ge_nipl_ret_nt` TEXT DEFAULT NULL,
	`ge_nipl_nt` TEXT DEFAULT NULL,
/* Cardiovascular */
	`ge_cr_norm` VARCHAR(1) DEFAULT NULL,
	`ge_cr_norm_nt` TEXT DEFAULT NULL,
	`ge_cr_mur` VARCHAR(1) DEFAULT NULL,
	`ge_cr_mur_nt` TEXT DEFAULT NULL,
	`ge_cr_gall` VARCHAR(1) DEFAULT NULL,
	`ge_cr_gall_nt` TEXT DEFAULT NULL,
	`ge_cr_click` VARCHAR(1) DEFAULT NULL,
	`ge_cr_click_nt` TEXT DEFAULT NULL,
	`ge_cr_rubs` VARCHAR(1) DEFAULT NULL,
	`ge_cr_rubs_nt` TEXT DEFAULT NULL,
	`ge_cr_extra` VARCHAR(1) DEFAULT NULL,
	`ge_cr_extra_nt` TEXT DEFAULT NULL,
	`ge_cr_mur_dtl` VARCHAR(1) DEFAULT NULL,
	`ge_cr_mur_dtl_nt` TEXT DEFAULT NULL,
	`ge_cr_pmi` VARCHAR(1) DEFAULT NULL,
	`ge_cr_pmi_nt` TEXT DEFAULT NULL,
	`ge_cr_nt` TEXT DEFAULT NULL,
/* Pulmonary */
	`ge_pul_clear` VARCHAR(1) DEFAULT NULL,
	`ge_pul_rales` VARCHAR(1) DEFAULT NULL,
	`ge_pul_whz` VARCHAR(1) DEFAULT NULL,
	`ge_pul_ron` VARCHAR(1) DEFAULT NULL,
	`ge_pul_dec` VARCHAR(1) DEFAULT NULL,
	`ge_pul_crack` VARCHAR(1) DEFAULT NULL,
	`ge_pul_rales_nt` TEXT DEFAULT NULL,
/* Gastrointestinal */
	`ge_gi_soft` VARCHAR(1) DEFAULT NULL,
	`ge_gi_soft_nt` TEXT DEFAULT NULL,
	`ge_gi_tend` VARCHAR(2) DEFAULT NULL,
	`ge_gi_tend_loc` VARCHAR(3) DEFAULT NULL,
	`ge_gi_tend_nt` TEXT DEFAULT NULL,
	`ge_gi_dis` VARCHAR(2) DEFAULT NULL,
	`ge_gi_dis_nt` TEXT DEFAULT NULL,
	`ge_gi_scar` VARCHAR(1) DEFAULT NULL,
	`ge_gi_scar_nt` TEXT DEFAULT NULL,
	`ge_gi_hern` VARCHAR(1) DEFAULT NULL,
	`ge_gi_hern_nt` TEXT DEFAULT NULL,
	`ge_gi_bowel` VARCHAR(1) DEFAULT NULL,
	`ge_gi_bowel_nt` TEXT DEFAULT NULL,
	`ge_gi_hepa` VARCHAR(1) DEFAULT NULL,
	`ge_gi_hepa_nt` TEXT DEFAULT NULL,
	`ge_gi_spleno` VARCHAR(1) DEFAULT NULL,
	`ge_gi_spleno_nt` TEXT DEFAULT NULL,
	`ge_gi_asc` VARCHAR(1) DEFAULT NULL,
	`ge_gi_asc_nt` TEXT DEFAULT NULL,
	`ge_gi_pnt` VARCHAR(1) DEFAULT NULL,
	`ge_gi_pnt_nt` TEXT DEFAULT NULL,
	`ge_gi_grd` VARCHAR(1) DEFAULT NULL,
	`ge_gi_grd_nt` TEXT DEFAULT NULL,
	`ge_gi_reb` VARCHAR(1) DEFAULT NULL,
	`ge_gi_reb_nt` TEXT DEFAULT NULL,
	`ge_gi_mass` VARCHAR(1) DEFAULT NULL,
	`ge_gi_mass_nt` TEXT DEFAULT NULL,
	`ge_gi_bwl_dtl` VARCHAR(1) DEFAULT NULL,
	`ge_gi_her_dtl` TEXT DEFAULT NULL,
	`ge_gi_nt` TEXT DEFAULT NULL,
/* Neuro */
	`ge_neu_ao` VARCHAR(1) DEFAULT NULL,
	`ge_neu_ao_nt` TEXT DEFAULT NULL,
	`ge_neu_cn` VARCHAR(1) DEFAULT NULL,
	`ge_neu_cn_nt` TEXT DEFAULT NULL,
	`ge_neu_bicr` VARCHAR(1),
	`ge_neu_bicr_nt` TEXT DEFAULT NULL,
	`ge_neu_bicl` VARCHAR(1),
	`ge_neu_bicl_nt` TEXT DEFAULT NULL,
	`ge_neu_trir` VARCHAR(1),
	`ge_neu_trir_nt` TEXT DEFAULT NULL,
	`ge_neu_tril` VARCHAR(1),
	`ge_neu_tril_nt` TEXT DEFAULT NULL,
	`ge_neu_brar` VARCHAR(1),
	`ge_neu_brar_nt` TEXT DEFAULT NULL,
	`ge_neu_bral` VARCHAR(1),
	`ge_neu_bral_nt` TEXT DEFAULT NULL,
	`ge_neu_patr` VARCHAR(1),
	`ge_neu_patr_nt` TEXT DEFAULT NULL,
	`ge_neu_patl` VARCHAR(1),
	`ge_neu_patl_nt` TEXT DEFAULT NULL,
	`ge_neu_achr` VARCHAR(1),
	`ge_neu_achr_nt` TEXT DEFAULT NULL,
	`ge_neu_achl` VARCHAR(1),
	`ge_neu_achl_nt` TEXT DEFAULT NULL,
	`ge_neu_pup` VARCHAR(1) DEFAULT NULL,
	`ge_neu_pup_nt` TEXT DEFAULT NULL,
	`ge_neu_plow` VARCHAR(1) DEFAULT NULL,
	`ge_neu_plow_nt` TEXT DEFAULT NULL,
	`ge_neu_dup` VARCHAR(1) DEFAULT NULL,
	`ge_neu_dup_nt` TEXT DEFAULT NULL,
	`ge_neu_dlow` VARCHAR(1) DEFAULT NULL,
	`ge_neu_dlow_nt` TEXT DEFAULT NULL,
	`ge_neu_str_nt` TEXT DEFAULT NULL,
	`ge_neu_tn` VARCHAR(1) DEFAULT NULL,
	`ge_neu_tn_nt` TEXT DEFAULT NULL,
	`ge_neu_sns_chc` VARCHAR(1) DEFAULT NULL,
	`ge_neu_sns_chc_nt` TEXT DEFAULT NULL,
	`ge_neu_cc_norm` TINYINT(1),
	`ge_neu_cc_fn` VARCHAR(1) DEFAULT NULL,
	`ge_neu_cc_fn_nt` TEXT DEFAULT NULL,
	`ge_neu_cc_hs` VARCHAR(1) DEFAULT NULL,
	`ge_neu_cc_hs_nt` TEXT DEFAULT NULL,
	`ge_neu_cc_ra` VARCHAR(1) DEFAULT NULL,
	`ge_neu_cc_ra_nt` TEXT DEFAULT NULL,
	`ge_neu_cc_rm` VARCHAR(1) DEFAULT NULL,
	`ge_neu_cc_rm_nt` TEXT DEFAULT NULL,
	`ge_neu_cc_pd` VARCHAR(1) DEFAULT NULL,
	`ge_neu_cc_pd_nt` TEXT DEFAULT NULL,
	`ge_neu_cc_nt` TEXT DEFAULT NULL,
	`ge_neu_sense` TEXT DEFAULT NULL,
/* Musculoskeletal */
	`ge_ms_intact` TINYINT(1),
	`ge_ms_intact_nt` TEXT DEFAULT NULL,
	`ge_ms_mass` VARCHAR(1) DEFAULT NULL,
	`ge_ms_mass_nt` TEXT DEFAULT NULL,
	`ge_ms_tnd` VARCHAR(1) DEFAULT NULL,
	`ge_ms_tnd_nt` TEXT DEFAULT NULL,
	`ge_ms_scl` VARCHAR(1) DEFAULT NULL,
	`ge_ms_scl_nt` TEXT DEFAULT NULL,
	`ge_ms_cval` VARCHAR(1) DEFAULT NULL,
	`ge_ms_cval_nt` TEXT DEFAULT NULL,
	`ge_ms_cvar` VARCHAR(1) DEFAULT NULL,
	`ge_ms_cvar_nt` TEXT DEFAULT NULL,
	`ge_ms_lim` VARCHAR(1) DEFAULT NULL,
	`ge_ms_lim_nt` TEXT DEFAULT NULL,
	`ge_ms_def` VARCHAR(1) DEFAULT NULL,
	`ge_ms_def_nt` TEXT DEFAULT NULL,
	`ge_ms_full` VARCHAR(1) DEFAULT NULL,
	`ge_ms_full_nt` TEXT DEFAULT NULL,
	`ge_ms_gait` VARCHAR(1) DEFAULT NULL,
	`ge_ms_gait_nt` TEXT DEFAULT NULL,
	`ge_ms_chks` TEXT DEFAULT NULL,
	`ge_ms_norm` TINYINT(1),
	`ge_ms_nt` TEXT DEFAULT NULL,
/* Extremeties */
	`ge_ext_edema` VARCHAR(1) DEFAULT NULL,
	`ge_ext_edema_chc` VARCHAR(1) DEFAULT NULL,
	`ge_ext_edema_nt` TEXT DEFAULT NULL,
	`ge_ext_pls_rad` VARCHAR(1) DEFAULT NULL,
	`ge_ext_pls_dors` VARCHAR(1) DEFAULT NULL,
	`ge_ext_pls_post` VARCHAR(1) DEFAULT NULL,
	`ge_ext_pls_pop` VARCHAR(1) DEFAULT NULL,
	`ge_ext_pls_fem` VARCHAR(1) DEFAULT NULL,
	`ge_ext_refill` VARCHAR(1) DEFAULT NULL,
	`ge_ext_club` VARCHAR(1) DEFAULT NULL,
	`ge_ext_club_nt` TEXT DEFAULT NULL,
	`ge_ext_cyan` VARCHAR(1) DEFAULT NULL,
	`ge_ext_cyan_nt` TEXT DEFAULT NULL,
	`ge_ext_nt` TEXT DEFAULT NULL,
/* Diabetic Foot */
	`ge_db_prop` VARCHAR(1) DEFAULT NULL,
	`ge_db_prop_nt` TEXT DEFAULT NULL,
	`ge_db_vib` VARCHAR(1) DEFAULT NULL,
	`ge_db_vib_nt` TEXT DEFAULT NULL,
	`ge_db_sens` VARCHAR(1) DEFAULT NULL,
	`ge_db_sens_nt` TEXT DEFAULT NULL,
	`ge_db_nt` TEXT DEFAULT NULL,
/* Testicular */
	`ge_te_cir` VARCHAR(1) DEFAULT NULL,
	`ge_te_cir_nt` TEXT DEFAULT NULL,
	`ge_te_les` VARCHAR(1) DEFAULT NULL,
	`ge_te_les_nt` TEXT DEFAULT NULL,
	`ge_te_dis` VARCHAR(1) DEFAULT NULL,
	`ge_te_dis_nt` TEXT DEFAULT NULL,
	`ge_te_size` VARCHAR(1) DEFAULT NULL,
	`ge_te_size_nt` TEXT DEFAULT NULL,
	`ge_te_palp` VARCHAR(1) DEFAULT NULL,
	`ge_te_palp_nt` TEXT DEFAULT NULL,
	`ge_te_mass` VARCHAR(1) DEFAULT NULL,
	`ge_te_mass_nt` TEXT DEFAULT NULL,
	`ge_te_tend` VARCHAR(1) DEFAULT NULL,
	`ge_te_tend_nt` TEXT DEFAULT NULL,
	`ge_te_ery` VARCHAR(1) DEFAULT NULL,
	`ge_te_ery_nt` TEXT DEFAULT NULL,
	`ge_te_nt` TEXT DEFAULT NULL,
/* Genital */
	`ge_te_lmaj` VARCHAR(1) DEFAULT NULL,
	`ge_te_lmaj_nt` TEXT DEFAULT NULL,
	`ge_te_lmin` VARCHAR(1) DEFAULT NULL,
	`ge_te_lmin_nt` TEXT DEFAULT NULL,
	`ge_te_intro` VARCHAR(1) DEFAULT NULL,
	`ge_te_intro_nt` TEXT DEFAULT NULL,
	`ge_te_urethra` VARCHAR(1) DEFAULT NULL,
	`ge_te_urethra_nt` TEXT DEFAULT NULL,
	`ge_te_clit` VARCHAR(1) DEFAULT NULL,
	`ge_te_clit_nt` TEXT DEFAULT NULL,
/* Rectal */
	`ge_rc_tone` VARCHAR(1) DEFAULT NULL,
	`ge_rc_tone_nt` TEXT DEFAULT NULL,
	`ge_rc_ext` VARCHAR(1) DEFAULT NULL,
	`ge_rc_ext_nt` TEXT DEFAULT NULL,
	`ge_rc_pro` VARCHAR(1) DEFAULT NULL,
	`ge_rc_pro_nt` TEXT DEFAULT NULL,
	`ge_rc_pro2` VARCHAR(1) DEFAULT NULL,
	`ge_rc_pro2_nt` TEXT DEFAULT NULL,
	`ge_rc_bog` VARCHAR(1) DEFAULT NULL,
	`ge_rc_bog_nt` TEXT DEFAULT NULL,
	`ge_rc_hard` VARCHAR(1) DEFAULT NULL,
	`ge_rc_hard_nt` TEXT DEFAULT NULL,
	`ge_rc_mass` VARCHAR(1) DEFAULT NULL,
	`ge_rc_mass_nt` TEXT DEFAULT NULL,
	`ge_rc_tend` VARCHAR(1) DEFAULT NULL,
	`ge_rc_tend_nt` TEXT DEFAULT NULL,
	`ge_rc_color` VARCHAR(2),
	`ge_rc_color_nt` TEXT DEFAULT NULL,
	`ge_rc_nt` TEXT DEFAULT NULL,
/* Skin */
	`ge_skin_app` TINYINT(1),
	`ge_skin_app_nt` TEXT DEFAULT NULL,
	`ge_skin_les` TINYINT(1),
	`ge_skin_les_nt` TEXT DEFAULT NULL,
	`ge_skin_ver` VARCHAR(1) DEFAULT NULL,
	`ge_skin_ver_nt` TEXT DEFAULT NULL,
	`ge_skin_jau` VARCHAR(1) DEFAULT NULL,
	`ge_skin_jau_nt` TEXT DEFAULT NULL,
	`ge_skin_con` VARCHAR(1) DEFAULT NULL,
	`ge_skin_con_nt` TEXT DEFAULT NULL,
	`ge_skin_ecc` VARCHAR(1) DEFAULT NULL,
	`ge_skin_ecc_nt` TEXT DEFAULT NULL,
	`ge_skin_rash` VARCHAR(1) DEFAULT NULL,
	`ge_skin_rash_nt` TEXT DEFAULT NULL,
	`ge_skin_abs` VARCHAR(1) DEFAULT NULL,
	`ge_skin_abs_nt` TEXT DEFAULT NULL,
	`ge_skin_lac` VARCHAR(1) DEFAULT NULL,
	`ge_skin_lac_nt` TEXT DEFAULT NULL,
	`ge_skin_nt` TEXT DEFAULT NULL,
/* Psych */
	`ge_psych_judge` TINYINT(1),
	`ge_psych_judge_nt` TEXT DEFAULT NULL,
	`ge_psych_orient` TINYINT(1),
	`ge_psych_orient_nt` TEXT DEFAULT NULL,
	`ge_psych_memory` TINYINT(1),
	`ge_psych_memory_nt` TEXT DEFAULT NULL,
	`ge_psych_mood` TINYINT(1),
	`ge_psych_mood_nt` TEXT DEFAULT NULL,
	`ge_psych_nt` TEXT DEFAULT NULL,
/* Normal Exam By Section */
	`ge_gen_norm_exam` TINYINT(1),
	`ge_hd_norm_exam` TINYINT(1),
	`ge_eye_norm_exam` TINYINT(1),
	`ge_ear_norm_exam` TINYINT(1),
	`ge_nose_norm_exam` TINYINT(1),
	`ge_mouth_norm_exam` TINYINT(1),
	`ge_thrt_norm_exam` TINYINT(1),
	`ge_nk_norm_exam` TINYINT(1),
	`ge_thy_norm_exam` TINYINT(1),
	`ge_lym_norm_exam` TINYINT(1),
	`ge_br_norm_exam` TINYINT(1),
	`ge_cr_norm_exam` TINYINT(1),
	`ge_pul_norm_exam` TINYINT(1),
	`ge_gi_norm_exam` TINYINT(1),
	`ge_neu_norm_exam` TINYINT(1),
	`ge_ms_norm_exam` TINYINT(1),
	`ge_ext_norm_exam` TINYINT(1),
	`ge_db_norm_exam` TINYINT(1),
	`ge_te_norm_exam` TINYINT(1),
	`ge_rc_norm_exam` TINYINT(1),
	`ge_skin_norm_exam` TINYINT(1),
	`ge_psych_norm_exam` TINYINT(1),

	`proc_choices` TEXT DEFAULT NULL,
	`proc_nt`	MEDIUMTEXT DEFAULT NULL,

/* Diagnosis Section */
	`assess` TEXT DEFAULT NULL,
	`plan` TEXT DEFAULT NULL,
	`review_nt` TEXT DEFAULT NULL,
	`admit` TINYINT(1),
	`admit_nt` TEXT DEFAULT NULL,
	`return_chk` TINYINT(1),
	`reviewed` TINYINT(1),
	`rto_num` TINYINT(2),
	`rto_frame` VARCHAR(1) DEFAULT NULL,
	`rto_soon` TINYINT(1),
	`rto_nt` TEXT DEFAULT NULL,
	`instruct` TEXT DEFAULT NULL,
	`lab_pend` TINYINT(1),
	`referral_printed` TINYINT(1) DEFAULT 0,
	`referral_docid` BIGINT(20) DEFAULT 0,
	`printed` TINYINT(1) DEFAULT 0,

PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `form_wmt_ros` (
	`id` BIGINT(20) NOT NULL auto_increment,
	`date` DATETIME DEFAULT NULL,
	`pid` BIGINT(20),
	`user` VARCHAR(255) DEFAULT NULL,
	`groupname` VARCHAR(255) DEFAULT NULL,
	`authorized` TINYINT(4),
	`activity` TINYINT(4),

	`link_id` BIGINT(20),
	`link_name` VARCHAR(255) DEFAULT NULL,
	`ros_yes` LONGTEXT DEFAULT NULL,
	`ros_no` LONGTEXT DEFAULT NULL,
	`ros_constitutional_hpi` TINYINT(1),
	`ros_constitutional_none` TINYINT(1),
	`ros_cardio_hpi` TINYINT(1),
	`ros_cardio_none` TINYINT(1),
	`ros_muscle_hpi` TINYINT(1),
	`ros_muscle_none` TINYINT(1),
	`ros_allergic_hpi` TINYINT(1),
	`ros_allergic_none` TINYINT(1),
	`ros_skin_hpi` TINYINT(1),
	`ros_skin_none` TINYINT(1),
	`ros_respiratory_hpi` TINYINT(1),
	`ros_respiratory_none` TINYINT(1),
	`ros_breast_hpi` TINYINT(1),
	`ros_breast_none` TINYINT(1),
	`ros_neurologic_hpi` TINYINT(1),
	`ros_neurologic_none` TINYINT(1),
	`ros_eyes_hpi` TINYINT(1),
	`ros_eyes_none` TINYINT(1),
	`ros_endocrine_hpi` TINYINT(1),
	`ros_endocrine_none` TINYINT(1),
	`ros_ent_hpi` TINYINT(1),
	`ros_ent_none` TINYINT(1),
	`ros_lymphatic_hpi` TINYINT(1),
	`ros_lymphatic_none` TINYINT(1),
	`ros_gastro_hpi` TINYINT(1),
	`ros_gastro_none` TINYINT(1),
	`ros_psychiatric_hpi` TINYINT(1),
	`ros_psychiatric_none` TINYINT(1),
	`ros_genito_hpi` TINYINT(1),
	`ros_genito_none` TINYINT(1),
	`ros_ears_hpi` TINYINT(1),
	`ros_ears_none` TINYINT(1),
	`ros_hear_hpi` TINYINT(1),
	`ros_hear_none` TINYINT(1),
	`ros_nose_hpi` TINYINT(1),
	`ros_nose_none` TINYINT(1),
	`ros_sinus_hpi` TINYINT(1),
	`ros_sinus_none` TINYINT(1),
	`ros_throat_hpi` TINYINT(1),
	`ros_throat_none` TINYINT(1),
	`ros_neck_hpi` TINYINT(1),
	`ros_neck_none` TINYINT(1),
	`ros_sleep_hpi` TINYINT(1),
	`ros_sleep_none` TINYINT(1),
	`ros_nt` MEDIUMTEXT DEFAULT NULL,
	`input_source` TINYINT(1),

PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `form_wmt_ros_comments` (
	`id` BIGINT(20) NOT NULL auto_increment,
	`date` DATETIME DEFAULT NULL,
	`pid` BIGINT(20),
	`user` VARCHAR(255) DEFAULT NULL,
	`groupname` VARCHAR(255) DEFAULT NULL,
	`authorized` TINYINT(4),
	`activity` TINYINT(4),

	`link_id` BIGINT(20),
	`link_name` VARCHAR(255) DEFAULT NULL,
	`link_field` VARCHAR(64) DEFAULT NULL,
	`note` MEDIUMTEXT DEFAULT NULL,
	`input_source` TINYINT(1),

PRIMARY KEY (`id`),
UNIQUE `form_key` (`link_id`, `link_name`, `link_field`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `wmt_keyed_text` (
	`id` BIGINT(20) NOT NULL auto_increment,
	`date` DATETIME DEFAULT NULL,
	`user` VARCHAR(255) DEFAULT NULL,

	`key_val` VARCHAR(255),
	`note` MEDIUMTEXT DEFAULT NULL,

PRIMARY KEY (`id`),
UNIQUE `form_key` (`key_val`)
) ENGINE=InnoDB;

INSERT INTO `wmt_pop_forms` (`form_name`, `pop_form`, `archive_form`, `referral_form`) VALUES ("ext_exam2", "1", "1", "1") ON DUPLICATE KEY UPDATE `pop_form`= VALUES(`pop_form`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_AO", "EE1 AO", "0", "1", "Extended Exam List"), ("EE1_AO", "1", "X 1", "10", "0", ""),("EE1_AO", "2", "X 2", "20", "0", ""), ("EE1_AO", "3", "X 3", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_Distended", "EE1 Distended", "0", "1", "Extended Exam List"), ("EE1_Distended", "d", "Distended", "10", "0", ""),("EE1_Distended", "n", "Nondistended", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_DTR", "EE1 DTR", "0", "1", "Extended Exam List"), ("EE1_DTR", "1", "0 - None", "10", "0", ""),("EE1_DTR", "2", "1+ Slight", "20", "0", ""),("EE1_DTR", "3", "2+ Brisk", "30", "0", ""),("EE1_DTR", "4", "3+ Very Brisk", "40", "0", ""), ("EE1_DTR", "5", "4+ Clonus", "50", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_GI_Location", "EE1 GI Location", "0", "1", "Extended Exam List"), ("EE1_GI_Location", "ru", "RUQ", "10", "0", ""),("EE1_GI_Location", "lu", "LUQ", "20", "0", ""), ("EE1_GI_Location", "rl", "RLQ", "30", "0", ""), ("EE1_GI_Location", "ll", "LLQ", "40", "0", ""), ("EE1_GI_Location", "ep", "Epigastric", "50", "0", ""), ("EE1_GI_Location", "pe", "Periumbilical", "60", "0", ""), ("EE1_GI_Location", "su", "Suprapubic", "70", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_Prostate", "EE1 Prostate", "0", "1", "Extended Exam List"), ("EE1_Prostate", "n", "Normal", "10", "0", ""),("EE1_Prostate", "e", "Enlarged", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_Pupil", "EE1 Pupil", "0", "1", "Extended Exam List"), ("EE1_Pupil", "2", "2 mm", "10", "0", ""),("EE1_Pupil", "3", "3 mm", "20", "0", ""),("EE1_Pupil", "4", "4 mm", "30", "0", ""),("EE1_Pupil", "5", "5 mm", "40", "0", ""), ("EE1_Pupil", "6", "6 mm", "50", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_RTO_Frame", "EE1 RTO Frame", "0", "1", "Extended Exam List"), ("EE1_RTO_Frame", "d", "Day(s)", "10", "0", ""),("EE1_RTO_Frame", "w", "Week(s)", "20", "0", ""), ("EE1_RTO_Frame", "m", "Month(s)", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_RTO_Number", "EE1 RTO Number", "0", "1", "Extended Exam List"), ("EE1_RTO_Number", "1", "1", "10", "0", ""),("EE1_RTO_Number", "2", "2", "20", "0", ""),("EE1_RTO_Number", "3", "3", "30", "0", ""),("EE1_RTO_Number", "4", "4", "40", "0", ""), ("EE1_RTO_Number", "5", "5", "50", "0", ""), ("EE1_RTO_Number", "6", "6", "60", "0", ""), ("EE1_RTO_Number", "7", "7", "70", "0", ""), ("EE1_RTO_number", "10", "10", "100", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_Septum", "EE1 Septum", "0", "1", "Extended Exam List"), ("EE1_Septum", "d", "Deviated", "10", "0", ""),("EE1_Septum", "m", "Midline", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_Stool_Color", "EE1 Stool Color", "0", "1", "Extended Exam List"), ("EE1_Stool_Color", "br", "Brown", "10", "0", ""),("EE1_Stool_Color", "bl", "Black", "20", "0", ""), ("EE1_Stool_Color", "re", "Red", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_Tender", "EE1 Tender", "0", "1", "Extended Exam List"), ("EE1_Tender", "t", "Tender", "10", "0", ""),("EE1_Tender", "n", "Nontender", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_Testes_Size", "EE1 Testes Size", "0", "1", "Extended Exam List"), ("EE1_Testes_Size", "n", "Normal", "10", "0", ""),("EE1_Testes_Size", "s", "Small", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_Tone", "EE1 Tone", "0", "1", "Extended Exam List"), ("EE1_Tone", "n", "Normal Sphincter Tone", "10", "0", ""),("EE1_Tone", "l", "Lax Sphincter Tone", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_Denture", "EE1 Denture Options", "0", "1", "Extended Exam List"), ("EE1_Denture", "n", "Normal", "10", "0", ""),("EE1_Denture", "c", "Dental Caries", "20", "0", ""), ("EE1_Denture", "d", "Dentures", "30", "0", "")  ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "EE1_YesNo", "EE1 YesNo", "0", "1", "Extended Exam Form List"), ("EE1_YesNo", "y", "Yes", "10", "0", ""),("EE1_YesNo", "n", "No", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Erythema", "Erythema", "0", "1", "Multi-Use List"), ("Erythema", "e", "Erythema", "10", "0", ""),("Erythema", "n", "No Erythema", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "NormAbnorm", "NormAbnorm", "0", "1", "Multi-Use List"), ("NormAbnorm", "n", "Normal", "10", "0", ""),("NormAbnorm", "a", "Abnormal", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Edema", "Edema", "0", "1", "Multi-Use List"), ("Edema", "1", "1 +", "10", "0", ""),("Edema", "2", "2 +", "20", "0", ""), ("Edema", "3", "3 +", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "HardSoft", "HardSoft", "0", "1", "Multi-Use List"), ("HardSoft", "h", "Hard", "10", "0", ""),("HardSoft", "s", "Soft", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "MassNone", "MassNone", "0", "1", "Multi-Use List"), ("MassNone", "m", "Mass", "10", "0", ""),("MassNone", "n", "No Masses", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Zero_to_4", "Zero to 4", "0", "1", "Multi-Use List"), ("Zero_to_4", "0", "0", "10", "0", ""),("Zero_to_4", "2", "2", "20", "0", ""),("Zero_to_4", "3", "3", "30", "0", ""),("Zero_to_4", "4", "4", "40", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Zero_to_5", "Zero to 5", "0", "1", "Multi-Use List"), ("Zero_to_5", "0", "0", "10", "0", ""),("Zero_to_5", "2", "2", "20", "0", ""),("Zero_to_5", "3", "3", "30", "0", ""),("Zero_to_5", "4", "4", "40", "0", ""), ("Zero_to_5", "5", "5", "50", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Yes_No", "Yes_No", "0", "1", "Multi-Use List"), ("Yes_No", "y", "Yes", "10", "0", ""),("Yes_No", "n", "No", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Blood_Types", "Blood Types", "0", "1", "Multi-Use List"), ("Blood_Types", "A", "A", "10", "0", ""),("Blood_Types", "B", "B", "20", "0", ""),("Blood_Types", "AB", "AB", "30", "0", ""),("Blood_Types", "O", "O", "40", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "RH_Factor", "RH Factor", "0", "1", "Multi-Use List"), ("RH_Factor", "+", "Positive", "10", "0", ""),("RH_Factor", "-", "Negative", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Family_History_Problems", "Family History Problems", "0", "1", "Multi-Use List"), ("Family_History_Problems", "DIA", "Diabetes", "10", "0", "Sample Entry"),("Family_History_Problems", "HD", "Heart Disease", "20", "0", "Sample Entry") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Family_Relationships", "Family Relationships", "0", "1", "Multi-Use List"), ("Family_Relationships", "f", "Father", "10", "0", ""),("Family_Relationships", "m", "Mother", "20", "0", ""),("Family_Relationships", "mf", "Maternal Grandfather", "30", "0", ""),("Family_Relationships", "mm", "Maternal Grandmother", "40", "0", ""),("Family_Relationships", "pf", "Paternal Grandfather", "50", "0", ""),("Family_Relationships", "pm", "Paternal Grandmother", "50", "0", ""),("Family_Relationships", "b", "Brother", "50", "0", ""),("Family_Relationships", "s", "Sister", "50", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES 
("lists", "Family_History_Choices", "Family History Choices", "0", "1", "Multi-Use List"), 
("Family_History_Choices", "diabetes", "Diabetes", "10", "0", "Set Seq Negative to Disable"),
("Family_History_Choices", "coronary", "Coronary Artery Disease", "20", "0", "Set Seq Negative to Disable"), 
("Family_History_Choices", "htn", "HTN", "30", "0", "Set Seq Negative to Disable"), 
("Family_History_Choices", "hyper", "Hyperlipidemia", "40", "0", "Set Seq Negative to Disable"), 
("Family_History_Choices", "thyroid", "Thyroid Cancer", "50", "0", "Set Seq Negative to Disable"), 
("Family_History_Choices", "colon", "Colon Cancer", "60", "0", "Set Seq Negative to Disable"), 
("Family_History_Choices", "lung", "Lung Cancer", "70", "0", "Set Seq Negative to Disable") 
ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Medical_History_Problems", "Medical History Problems", "0", "1", "Multi-Use List"), ("Medical_History_Problems", "DIA", "Diabetes", "10", "0", "Sample Entry"),("Medical_History_Problems", "HD", "Heart Disease", "20", "0", "Sample Entry") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Image_Types", "Image Types", "0", "1", "Multi-Use List"), ("Image_Types", "X", "X-Ray", "10", "0", "Sample Entry"),("Image_Types", "ct", "CT Scan", "20", "0", "Sample Entry"),("Image_Types", "mri", "MRI", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Vital_Arm", "Vital Arm", "0", "1", "Multi-Use List"), ("Vital_Arm", "left", "Left", "10", "0", "System Use - DO NOT DELETE"),("Vital_Arm", "right", "Right", "20", "0", "System Use - DO NOT DELETE") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Form_Priority", "Form Priority", "0", "1", "Multi-Use List"), ("Form_Priority", "l", "Low", "10", "0", ""),("Form_Priority", "n", "Normal", "20", "0", ""), ("Form_Priority", "u", "Urgent", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Form_Status", "Form Status", "0", "1", "Multi-Use List"), ("Form_Status", "i", "Incomplete", "10", "0", "Required - Do Not Delete"),("Form_Status", "c", "Complete", "20", "0", "Required - Do Not Delete"), ("Form_Status", "a", "Approved", "30", "0", "Required - Do Not Delete") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `user_settings` (`setting_user`, `setting_label`, `setting_value`) VALUES ("0", "wmt::med_hist::ext_exam2", "1"), 
("0", "wmt::fh_options::ext_exam2", "dia|coronary|htn|hyper|thy|colon|lung|hd|cardiac|vhd|arr"), 
("0", "wmt::fyi_img_nt::ext_exam2", "1"), 
("0", "wmt::fyi_allergy_nt::ext_exam2", "1"), 
("0", "wmt::fyi_med_nt::ext_exam2", "1"), 
("0", "wmt::fyi_medhist_nt::ext_exam2", "1"), 
("0", "wmt::fyi_surg_nt::ext_exam2", "1"), 
("0", "wmt::fyi_imm_nt::ext_exam2", "1"), 
("0", "wmt::fyi_admissions_nt::ext_exam2", "1"), 
("0", "wmt::fyi_pmh_nt::ext_exam2", "1"), 
("0", "wmt::fyi_fh_nt::ext_exam2", "1"), 
("0", "wmt::fyi_sh_nt::ext_exam2", "1"), 
("0", "wmt::cc_rows::ext_exam2", "5"), 
("0", "wmt::hpi_rows::ext_exam2", "10"), 
("0", "wmt::use_tasks::ext_exam2", "0"), 
("0", "wmt::tmp_hpi_disp_mode::ext_exam2", "block"), 
("0", "wmt::tmp_diag_disp_mode::ext_exam2", "block"), 
("0", "wmt::tmp_cc_disp_mode::ext_exam2", "block"), 
("0", "wmt::tmp_med_disp_mode::ext_exam2", "block"), 
("0", "wmt::tmp_all_disp_mode::ext_exam2", "block"), 
("0", "wmt::hpi_clear_ros::ext_exam2", "1"), 
("0", "wmt::float_menu_lab_link::ext_exam2", "1"), 
("0", "wmt::float_menu_relink::ext_exam2", "1"), 
("0", "wmt::link_prev_diags::ext_exam2", "1"), 
("0", "wmt::wellness_vitals::ext_exam2", "1"), 
("0", "wmt::wellness_blood::ext_exam2", "1"), 
("0", "wmt::wellness_cardio::ext_exam2", "1"), 
("0", "wmt::wellness_colon::ext_exam2", "1"), 
("0", "wmt::wellness_hearing::ext_exam2", "1"), 
("0", "wmt::wellness_dental::ext_exam2", "1"), 
("0", "wmt::wellness_diabetes::ext_exam2", "1"), 
("0", "wmt::wellness_gyn::ext_exam2", "1"), 
("0", "wmt::use_mce_edit::ext_exam2", "0") 
ON DUPLICATE KEY UPDATE `setting_label`= VALUES(`setting_label`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`, `codes`, `mapping`) VALUES 
("lists", "Ext_ROS_Keys", "Extended Form ROS Keys", "0", "1", "System List", "", ""), 
("Ext_ROS_Keys", "rs_con_fever", "Fever/Chills", "10", "0", "Required - Do Not Delete", "Constitutional", ""),
("Ext_ROS_Keys", "rs_con_weight_loss", "Weight Loss", "20", "0", "Required - Do Not Delete", "Constitutional", ""),
("Ext_ROS_Keys", "rs_con_weight_gain", "Weight Gain", "30", "0", "Required - Do Not Delete", "Constitutional", ""),
("Ext_ROS_Keys", "rs_con_sleep", "Sleep Problems", "40", "0", "Required - Do Not Delete", "Constitutional", ""),
("Ext_ROS_Keys", "rs_con_fatigue", "Fatigue/Malaise", "50", "0", "Required - Do Not Delete", "Constitutional", ""),
("Ext_ROS_Keys", "rs_con_expose", "Exposures", "60", "0", "Required - Do Not Delete", "Constitutional", ""),
("Ext_ROS_Keys", "rs_con_travel", "Recent Travel", "70", "0", "Required - Do Not Delete", "Constitutional", ""),
("Ext_ROS_Keys", "rs_con_other", "Other", "80", "0", "Required - Do Not Delete", "Constitutional", ""),
("Ext_ROS_Keys", "rs_ent_sore_throat", "Sore Throat", "10", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_sinus_problem", "Sinus Problems", "20", "0", "Required - Do Not Delete : DO NOT USE", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_hearing_problem", "Hearing Problems", "30", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_tinnitus", "Tinnitus", "40", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_hot_flash", "Hot Flashes", "50", "0", "Required - Do Not Delete : DO NOT USE", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_swollen_lymph", "Swollen Lymph Nodes", "60", "0", "Required - Do Not Delete : DO NOT USE", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_mass", "Mass", "70", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_left_ear_pain", "Left Ear Pain", "80", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_right_ear_pain", "Right Ear Pain", "90", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_hayfever", "Hayfever", "100", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_frequent_colds", "Frequent Colds", "110", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_congestion", "Nasal Congestion", "120", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_runny_nose", "Runny Nose", "130", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_nose_bleed", "Nose Bleeds", "140", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_mouth_sores", "Mouth Sores", "150", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_bleeding_gums", "Bleeding Gums", "160", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_dental_pain", "Dental Pain", "170", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_hoarse", "Hoarseness", "180", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_sneezing", "Sneezing", "190", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_ear_drainage", "Ear Drainage", "200", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_nasal_drip", "Post Nasal Drip", "210", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_ent_other", "Other", "220", "0", "Required - Do Not Delete", "Ear/Nose/Throat/Mouth", ""),
("Ext_ROS_Keys", "rs_rsp_wheezing", "Wheezing", "10", "0", "Required - Do Not Delete", "Respiratory", ""),
("Ext_ROS_Keys", "rs_rsp_short_of_breath", "Shortness of Breath", "20", "0", "Required - Do Not Delete", "Respiratory", ""),
("Ext_ROS_Keys", "rs_rsp_cough", "Cough", "30", "0", "Required - Do Not Delete", "Respiratory", ""),
("Ext_ROS_Keys", "rs_rsp_sleep_apnea", "Sleep Apnea", "40", "0", "Required - Do Not Delete : DO NOT USE", "Respiratory", ""),
("Ext_ROS_Keys", "rs_rsp_sputum", "Sputum", "50", "0", "Required - Do Not Delete", "Respiratory", ""),
("Ext_ROS_Keys", "rs_rsp_dyspnea", "Dyspnea on Exertion", "60", "0", "Required - Do Not Delete", "Respiratory", ""),
("Ext_ROS_Keys", "rs_rsp_hemoptysis", "Hemoptysis", "70", "0", "Required - Do Not Delete", "Respiratory", ""),
("Ext_ROS_Keys", "rs_rsp_snoring", "Snoring", "80", "0", "Required - Do Not Delete", "Respiratory", ""),
("Ext_ROS_Keys", "rs_rsp_breath_pain", "Pain with Breathing", "90", "0", "Required - Do Not Delete", "Respiratory", ""),
("Ext_ROS_Keys", "rs_rsp_breath_difficulty", "Difficulty Breathing", "100", "0", "Required - Do Not Delete", "Respiratory", ""),
("Ext_ROS_Keys", "rs_rsp_other", "Other", "110", "0", "Required - Do Not Delete", "Respiratory", ""),
("Ext_ROS_Keys", "rs_geni_incontinence", "Incontinence", "10", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_urine_burn", "Burning w/Urination", "20", "0", "Required - Do Not Delete : DO NOT USE", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_urine_retain", "Urine Retention", "40", "0", "Required - Do Not Delete : DO NOT USE", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_vaginal_discharge", "Vaginal Discharge", "50", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_painful_period", "Painful Periods", "70", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_painful_sex", "Painful Intercourse", "80", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_fibroids", "Fibroids", "90", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_infertile", "Infertile", "100", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_urgency", "Urgency", "110", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_hematuria", "Hematuria", "120", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_nocturia", "Nocturia", "130", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_desire_change", "Change in Sexual Desire", "140", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_weak_stream", "Weak Stream", "150", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_dribbling", "Dribbling", "160", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_frequent_uti", "Frequent UTI", "170", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_abnormal_bleeding", "Abnormal Bleeding", "180", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_changed_color", "Altered Color/Odor of Urine", "190", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_urine_frequent", "Frequency", "200", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_genital_sores", "Genital Sores", "210", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_swelling", "Swelling", "220", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_undescended_testicle", "Undescended Testicles", "230", "0", "Required - Do Not Delete", "Genitourinary", "male"),
("Ext_ROS_Keys", "rs_geni_penile_discharge", "Penile Discharge", "240", "0", "Required - Do Not Delete", "Genitourinary", "male"),
("Ext_ROS_Keys", "rs_geni_hernia", "Hernia", "250", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_vaginal_itch", "Vaginal Itching", "260", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_rash", "Rash", "270", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_irregular", "Menstrual Irregularity", "280", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_pms", "Premenstrual Symptoms", "290", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_ed", "Erectile Dysfunction", "300", "0", "Required - Do Not Delete", "Genitourinary", "male"),
("Ext_ROS_Keys", "rs_geni_age_menarche", "Age of Menarche", "310", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_menopause", "Menopausal Symptoms", "320", "0", "Required - Do Not Delete", "Genitourinary", "female"),
("Ext_ROS_Keys", "rs_geni_std", "STD Exposure/Unprotected Intercourse", "330", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_low_desire", "Low Sexual Desire", "340", "0", "Required - Do Not Delete : DO NOT USE", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_decreased_libido", "Decreased Libido", "340", "0", "Required - Do Not Delete : DO NOT USE", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_sexuality", "Sexuality", "340", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_geni_other", "Other", "370", "0", "Required - Do Not Delete", "Genitourinary", ""),
("Ext_ROS_Keys", "rs_neu_dizziness", "Dizziness", "10", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_seizures", "Seizures/Involuntary Movement", "20", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_numb", "Numbness/Tingling", "30", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_muscle_strength", "Muscle Strength", "40", "0", "Required - Do Not Delete : DO NOT USE", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_headaches", "Headaches", "50", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_tremors", "Tremors", "60", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_dysarthria", "Dysarthria", "70", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_faint", "Fainting/Blackouts", "80", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_disorient", "Disorientation", "90", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_paralysis", "Paralysis", "100", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_vertigo", "Vertigo", "110", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_mem_loss", "Memory Loss", "120", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_dementia", "Dementia", "130", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_neu_other", "Other", "140", "0", "Required - Do Not Delete", "Neurologic", ""),
("Ext_ROS_Keys", "rs_end_hbg", "High Blood Glucose", "10", "0", "Required - Do Not Delete", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_hotcold_int", "Hot/Cold Intolerance", "15", "0", "Required - Do Not Delete", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_hair_loss", "Hair Loss", "20", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_diabetes", "Diabetes", "30", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_thyroid", "Thyroid Problems", "40", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_tired", "Fatigue", "50", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_dysphagia", "Dysphagia", "60", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_odynophagia", "Odynophagia", "70", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_voice_change", "Change in Voice", "80", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_polyuria", "Polyuria", "90", "0", "Required - Do Not Delete", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_polydipsia", "Polydipsia", "100", "0", "Required - Do Not Delete", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_nightmares", "Nightmares", "110", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_night_sweat", "Night Sweats", "120", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_brittle_nails", "Brittle Nails", "130", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_excess_sweat", "Excessive Sweating", "140", "0", "Required - Do Not Delete", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_neck_change", "Change in Nexk Size", "150", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_acne", "Acne", "160", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_hirsutism", "Hirsutism", "170", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_excess_thirst", "Excessive Thirst", "180", "0", "Required - Do Not Delete : DO NOT USE", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_growth", "Growth Issues", "190", "0", "Required - Do Not Delete", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_polyphagia", "Polyphagia", "200", "0", "Required - Do Not Delete", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_hot_flashes", "Hot Flashes", "200", "0", "Required - Do Not Delete", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_steroid", "Steroid Use", "200", "0", "Required - Do Not Delete", "Endocrine", ""),
("Ext_ROS_Keys", "rs_end_other", "Other", "200", "0", "Required - Do Not Delete", "Endocrine", ""),
("Ext_ROS_Keys", "rs_lym_swollen", "Swollen Glands", "10", "0", "Required - Do Not Delete", "Lymphatic", ""),
("Ext_ROS_Keys", "rs_lym_bruise", "Easy Bruising", "20", "0", "Required - Do Not Delete", "Lymphatic", ""),
("Ext_ROS_Keys", "rs_lym_nose_bleed", "Chronic Nose Bleeds", "30", "0", "Required - Do Not Delete", "Lymphatic", ""),
("Ext_ROS_Keys", "rs_lym_sickle_cell", "Sickle Cell Trait", "40", "0", "Required - Do Not Delete : DO NOT USE", "Lymphatic", ""),
("Ext_ROS_Keys", "rs_lym_anemia", "Anemia", "50", "0", "Required - Do Not Delete", "Lymphatic", ""),
("Ext_ROS_Keys", "rs_lym_blood_transfuse", "Multiple Blood Transfusions", "60", "0", "Required - Do Not Delete", "Lymphatic", ""),
("Ext_ROS_Keys", "rs_lym_other", "Other", "70", "0", "Required - Do Not Delete", "Lymphatic", ""),
("Ext_ROS_Keys", "rs_eye_blurred", "Blurred Vision", "10", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_double", "Double Vision", "20", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_vision_change", "Vision Changes", "30", "0", "Required - Do Not Delete : DO NOT USE", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_vision_loss", "Vision Loss", "40", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_macular", "Macular Degeneration", "50", "0", "Required - Do Not Delete : DO NOT USE", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_blindness", "Blindness", "60", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_pain", "Pain", "70", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_dry", "Dryness", "80", "0", "Required - Do Not Delete : DO NOT USE", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_glasses", "Wears Glasses", "90", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_contacts", "Wears Contacts", "100", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_red", "Redness", "110", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_itch", "Itchy Eyes", "120", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_swelling", "Swelling", "130", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_photophobia", "Photophobia", "140", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_discharge", "Discharge", "150", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_eye_other", "Other", "160", "0", "Required - Do Not Delete", "Eyes", ""),
("Ext_ROS_Keys", "rs_car_pain", "Chest Pain", "10", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_breathe_difficult", "Difficulty Breathing", "20", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_swelling", "Swelling", "30", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_palpitations", "Palpitations", "40", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_fainting", "Fainting", "50", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_murmur", "Murmur", "60", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_hbp", "High Blood Pressure", "70", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_leg_cramp", "Leg Cramps", "80", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_orthopnea", "Orthopnea", "90", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_edema", "Peripheral Edema", "100", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_jaw_pain", "Jaw Pain", "110", "0", "Required - Do Not Delete : DO NOT USE", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_arm_pain", "Arm Pain", "120", "0", "Required - Do Not Delete : DO NOT USE", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_back_pain", "Back Pain", "130", "0", "Required - Do Not Delete : DO NOT USE", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_acute_nitro", "Acute Nitroglycerin Use", "140", "0", "Required - Do Not Delete : DO NOT USE", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_car_other", "Other", "150", "0", "Required - Do Not Delete", "Cardiovascular", ""),
("Ext_ROS_Keys", "rs_gas_nausea", "Nausea", "10", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_vomit", "Vomiting", "20", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_reflux", "Reflux", "30", "0", "Required - Do Not Delete : DO NOT USE", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_abdominal_pain", "Abdominal Pain", "40", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_jaundice", "Jaundice", "50", "0", "Required - Do Not Delete : DO NOT USE", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_bowel_change", "Change in Bowel Habits", "60", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_diarrhea", "Diarrhea", "70", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_constipation", "Constipation", "80", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_melena", "Melena", "90", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_hematemesis", "Hematemesis", "100", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_hematochezia", "Hematochezia", "110", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_anal_pain", "Anal Pain", "120", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_excess_gas", "Excessive Flatulence", "130", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_heartburn", "Heartburn/Indigestion", "140", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_no_appetite", "Loss of Appetite", "150", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_difficult_swallow", "Difficulty Swallowing", "160", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_bloating", "Bloating/Fullness", "170", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_gas_other", "Other", "180", "0", "Required - Do Not Delete", "Gastrointestinal", ""),
("Ext_ROS_Keys", "rs_msc_joint_pain", "Joint Pain", "10", "0", "Required - Do Not Delete", "Musculoskeletal", ""),
("Ext_ROS_Keys", "rs_msc_joint_stiff", "Joint Stiffness", "20", "0", "Required - Do Not Delete", "Musculoskeletal", ""),
("Ext_ROS_Keys", "rs_msc_weak", "Muscle Weakness", "30", "0", "Required - Do Not Delete", "Musculoskeletal", ""),
("Ext_ROS_Keys", "rs_msc_muscle_pain", "Muscle Pain", "40", "0", "Required - Do Not Delete", "Musculoskeletal", ""),
("Ext_ROS_Keys", "rs_msc_poly_up", "Polymyalgia Above the Waist", "50", "0", "Required - Do Not Delete : DO NOT USE", "Musculoskeletal", ""),
("Ext_ROS_Keys", "rs_msc_poly_down", "Polymyalgia Below the Waist", "60", "0", "Required - Do Not Delete : DO NOT USE", "Musculoskeletal", ""),
("Ext_ROS_Keys", "rs_msc_limit", "Limitation of Movement", "70", "0", "Required - Do Not Delete", "Musculoskeletal", ""),
("Ext_ROS_Keys", "rs_msc_edema", "Edema", "80", "0", "Required - Do Not Delete", "Musculoskeletal", ""),
("Ext_ROS_Keys", "rs_msc_deformity", "Deformity", "90", "0", "Required - Do Not Delete", "Musculoskeletal", ""),
("Ext_ROS_Keys", "rs_msc_other", "Other", "100", "0", "Required - Do Not Delete", "Musculoskeletal", ""),
("Ext_ROS_Keys", "rs_skin_rash", "Rash", "10", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_mole_change", "Mole Changes", "20", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_color_change", "Pigmentation/Color Change", "30", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_sores", "Lesions/Sores", "40", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_hirsutism", "Hirsutism", "50", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_hair_loss", "Hair Loss", "60", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_hair_change", "Change in Hair Texture", "70", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_bites", "Insect Bites", "80", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_nail_change", "Change in Nails", "90", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_nail_injury", "Injury to Nails", "100", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_scalp_rash", "Scalp Lesions/Rash", "110", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_burn", "Burn", "120", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_acne", "Acne", "130", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_hives", "Hives", "140", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_skin_other", "Other", "150", "0", "Required - Do Not Delete", "Skin/Hair/Nails", ""),
("Ext_ROS_Keys", "rs_psy_depress", "Depressed Mood/Crying", "10", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_anxious", "Anxiety/Worry", "20", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_suicide", "Thoughts of Suicide", "30", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_homicide", "Thoughts of Homicide", "40", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_impaired", "Cognitive Impairment", "50", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_mood_swing", "Mood Swings", "60", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_outbursts", "Outbursts", "70", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_stress", "Stress", "80", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_behavior_change", "Change in Behavior", "90", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_school_problem", "Problems in School", "100", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_hallucinate", "Hallucinations", "110", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_voices", "Hearing Voices", "120", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_psy_other", "Other", "130", "0", "Required - Do Not Delete", "Psychiatric", ""),
("Ext_ROS_Keys", "rs_breast_nipple_discharge", "Nipple Discharge", "10", "0", "Required - Do Not Delete - DO NOT USE", "Breasts", ""),
("Ext_ROS_Keys", "rs_breast_lump", "Lumps", "20", "0", "Required - Do Not Delete - DO NOT USE", "Breasts", ""),
("Ext_ROS_Keys", "rs_breast_change", "Skin Changes", "30", "0", "Required - Do Not Delete - DO NOT USE", "Breasts", ""),
("Ext_ROS_Keys", "rs_breast_other", "Other", "30", "0", "Required - Do Not Delete - DO NOT USE", "Breasts", ""),
("Ext_ROS_Keys", "rs_imm_hayfever", "Hayfever", "10", "0", "Required - Do Not Delete - DO NOT USE", "Immunologic", ""),
("Ext_ROS_Keys", "rs_imm_medications", "Medications", "20", "0", "Required - Do Not Delete - DO NOT USE", "Immunologic", ""),
("Ext_ROS_Keys", "rs_imm_other", "Other", "30", "0", "Required - Do Not Delete", "Immunologic", "")
ON DUPLICATE KEY UPDATE `codes`= VALUES(`codes`), `mapping`=VALUES(`mapping`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Facial_Features", "Facial Features", "0", "1", "Multi-Use List"), ("Facial_Features", "s", "Symmetric", "10", "0", ""),("Facial_Features", "d", "Dysmorphic", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "ant_font", "Anterior Fontanel", "0", "1", "Multi-Use List"), ("ant_font", "o", "Open, Soft & Flat", "10", "0", ""),("ant_font", "s", "Sunken", "20", "0", ""), ("ant_front", "b", "Bulging", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "ear_drain", "Ear Drainage", "0", "1", "Multi-Use List"), ("ear_drain", "c", "Clear", "10", "0", ""),("ear_drain", "b", "Bloody", "20", "0", ""), ("ear_drain", "p", "Purulent", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "tonsil_size", "Tonsil Size", "0", "1", "Multi-Use List"), ("tonsil_size", "1", "1+", "10", "0", ""),("tonsil_size", "2", "2+", "20", "0", ""), ("tonsil_size", "3", "3+", "30", "0", ""), ("tonsil_size", "4", "4+", "40", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "one_to_five", "One To Five", "0", "1", "Multi-Use List"), ("one_to_five", "1", "1", "10", "0", ""),("one_to_five", "2", "2", "20", "0", ""), ("one_to_five", "3", "3", "30", "0", ""), ("one_to_five", "4", "4", "40", "0", ""), ("one_to_five", "5", "5", "50", "0","") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "one_to_six", "One To Six", "0", "1", "Multi-Use List"), ("one_to_six", "1", "1", "10", "0", ""),("one_to_six", "2", "2", "20", "0", ""), ("one_to_six", "3", "3", "30", "0", ""), ("one_to_six", "4", "4", "40", "0", ""), ("one_to_six", "5", "5", "50", "0",""), ("one_to_six", "6", "6", "60", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "bowel_detail", "Bowel Sound Detail", "0", "1", "Multi-Use List"), ("bowel_detail", "e", "Hyperactive", "10", "0", ""),("bowel_detail", "n", "Normoactive", "20", "0", ""), ("bowel_detail", "o", "Hypoactive", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "neuro_tone", "Neuro Strength Tone", "0", "1", "Multi-Use List"), ("neuro_tone", "n", "Normal", "10", "0", ""),("neuro_tone", "e", "Hypertonia", "20", "0", ""), ("neuro_tone", "o", "Hypotonia", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "left_right", "Left Right", "0", "1", "Multi-Use List"), ("left_right", "l", "Left", "10", "0", ""),("left_right", "r", "Right", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`, `codes`) VALUES 
("lists", "ext_exam2_modules", "Ext Exam Modules/Order", "0", "1", "Required for Ext Exam", ""), 
("ext_exam2_modules", "cc", "Chief Complaint", "10", "0", "Negative Seq to Hide", "specified_text_box|||view_documents"), 
("ext_exam2_modules", "hpi", "History of Present Illness", "20", "0", "Negative Seq to Hide", "specified_text_box|||hpi_lookup"), 
("ext_exam2_modules", "img", "Images", "30", "0", "Negative Seq to Hide", "image_summary"), 
("ext_exam2_modules", "sh", "Social History", "40", "0", "Negative Seq to Hide", "|db_"), 
("ext_exam2_modules", "all", "Allergies", "50", "0", "Negative Seq to Hide", "allergies"), 
("ext_exam2_modules", "ps", "Surgeries", "60", "0", "Negative Seq to Hide", "previous_surgeries"), 
("ext_exam2_modules", "meds", "Current Medications", "70", "0", "Negative Seq to Hide", "medications_erx"), 
("ext_exam2_modules", "med_hist", "Medication History", "80", "0", "Negative Seq to Hide", "medications_history_erx"), 
("ext_exam2_modules", "imm", "Immunizations", "90", "0", "Negative Seq to Hide", "immunizations"), 
("ext_exam2_modules", "well_full", "Wellness", "100", "0", "Negative Seq to Hide", "|db_"), 
("ext_exam2_modules", "hosp", "Admissions", "110", "0", "Negative Seq to Hide", "hospitalizations"), 
("ext_exam2_modules", "pmh", "Medical History", "120", "0", "Negative Seq to Hide", "past_med_history"), 
("ext_exam2_modules", "fh", "Family History", "130", "0", "Negative Seq to Hide", "family_history"), 
("ext_exam2_modules", "ros", "Review of Systems", "-40", "0", "Negative Seq to Hide", ""), 
("ext_exam2_modules", "ros2", "Review of Systems", "140", "0", "Negative Seq to Hide", ""), 
("ext_exam2_modules", "review_nt", "Documents/Records Reviewed", "145", "0", "Negative Seq to Hide", "specified_text_box|||view_documents"), 
("ext_exam2_modules", "general_exam2", "Physical Examination", "150", "0", "Negative Seq to Hide", ""), 
("ext_exam2_modules", "proc", "Procedures", "-160", "0", "Negative Seq to Hide", ""), 
("ext_exam2_modules", "assess", "Assessment", "180", "0", "Negative Seq to Hide", "specified_text_box|||"), 
("ext_exam2_modules", "diag", "Diagnosis / Plan", "190", "0", "Negative Seq to Hide", "|"), 
("ext_exam2_modules", "instruct", "Patient Instructions", "170", "0", "Negative Seq to Hide", "specified_text_box|||print_instruct") 
ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`, `codes`) VALUES 
("lists", "wmt::procedures::ext_exam2", "Extended Exam Procedures", "0", "1", "Ext Exam Specific Procedures", ""), 
("wmt::procedures::ext_exam2", "cerumen_removal", "Microscopic Cerumen Removal", "10", "0", "Negative Seq to Hide", ""), 
("wmt::procedures::ext_exam2", "flex_laryngoscopy", "Flexible Laryngoscopy", "20", "0", "Negative Seq to Hide", "") 
ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `wmt_keyed_text` (`key_val`, `note`) VALUES 
("flex_laryngoscopy", "The bilateral nasal cavities were decongested and anesthetized with topical 4% lidocaine and 0.05% oxymetazoline. The flexible scope was then introduced through the right nasal cavity to examine the nasopharynx. The fossae of Rosenmuller were clear. The Eustachian orifices were unobstructed. Pharyngeal mucosa is unremarkable without lesion. The base of tongue is without lesion and the vallecula is clear. Epiglottis, AE folds, Arytenoids and false vocal cords are examined and without mass or mucosal lesion. The true vocal folds are fully mobile bilaterally and without mucosal lesion. Limited view of the subglottis is clear. The hypopharynx is visualized to the esophageal inlet and noted to be without lesion or pooling of secretions."),
("cerumen_removal", "Indications: Symptomatic excessive cerumen build-up resulting in uncomfortable sensation in the outer ear and decreased visualization of the ear canal and tymphic membrane. Right: Under otomicroscopic visualization, the ear speculum was introduced. Impacted cerumen was noted to be occluding ***% of the external auditory canal. Microsuction and microcurettes are used to remove the impacted cerumen in atraumatic fashion. Findings: See physical exam for details. Left: Under otomicroscopic visualization, the ear speculum was introduced. Impacted cerumen was noted to be occluding ***% of the external auditory canal. Microsuction and microcurettes are used to remove the impacted cerumen in atraumatic fashion. Findings: See physical exam for details.") 
ON DUPLICATE KEY UPDATE `key_val`= VALUES(`key_val`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`, `codes`) VALUES 
("lists", "Exam_Form_Visit_Types", "Exam Form Visit Types", "0", "1", "Types of exams that forms may be used for", ""), 
("Exam_Form_Visit_Types", "acute", "Acute", "10", "0", "ext_exam1::ext_exam2", ""), 
("Exam_Form_Visit_Types", "exam", "Exam", "20", "0", "ext_exam1::ext_exam2", "") 
ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);
