<?php
/**
 * interface/modules/zend_modules/module/Application/view/application/index.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Tyler Wrenn <tyler@tylerwrenn.com>
 * @copyright Copyright (c) 2020 Tyler Wrenn <tyler@tylerwrenn.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
?>
<h1>An error occurred</h1>
<h2><?php $this->message; ?></h2>

<?php if (isset($this->display_exceptions) && $this->display_exceptions) { ?>

    <?php if(isset($this->exception) && ($this->exception instanceof Exception || $this->exception instanceof Error)) { ?>
        <hr/>
        <h2>Additional information:</h2>
        <h3><?php get_class($this->exception); ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php $this->exception->getFile(); ?>:<?php $this->exception->getLine(); ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php $this->escapeHtml($this->exception->getMessage()); ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php $this->escapeHtml($this->exception->getTraceAsString()); ?></pre>
            </dd>
        </dl>
        <?php
        $e = $this->exception->getPrevious();
        $icount = 0;
        if ($e) {
            ?>
            <hr/>
            <h2>Previous exceptions:</h2>
            <ul class="unstyled">
                <?php while($e) { ?>
                    <li>
                        <h3><?php get_class($e); ?></h3>
                        <dl>
                            <dt>File:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php $e->getFile(); ?>:<?php $e->getLine(); ?></pre>
                            </dd>
                            <dt>Message:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php $this->escapeHtml($e->getMessage()); ?></pre>
                            </dd>
                            <dt>Stack trace:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php $this->escapeHtml($e->getTraceAsString()); ?></pre>
                            </dd>
                        </dl>
                    </li>
                    <?php
                    $e = $e->getPrevious();
                    $icount += 1;
                    if ($icount >= 50) {
                        echo "<li>There may be more exceptions, but we have no enough memory to proccess it.</li>";
                        break;
                    }
                }
                ?>
            </ul>
        <?php } ?>

    <?php else { ?>

        <h3>No Exception available</h3>

    <?php } ?>

<?php } ?>
