<?php

$eula = 'LabCorp EULA Text
Version: 2024-08-28
INTERFACE FACILITATION AGREEMENT
This Interface Facilitation Agreement (“Agreement”) is a legal agreement, between the lab or representative on behalf of the lab, executing these terms (“Client”) and Laboratory Corporation of America Holdings (“Labcorp”) (hereinafter each referred to as a “Party” or collectively as “Parties”). By signing or electronically assenting to this Agreement, Client accepts the terms herein and agree to follow and be bound by them. Once Client executes this Agreement electronically (including through a click-through agreement), these terms constitute a legal, binding agreement between Client and Labcorp.
WHEREAS, Client and Labcorp are engaged in a business relationship where Labcorp provides laboratory testing services to the Client under a laboratory services agreement; and
WHEREAS, as a convenience to Client, and not a requirement of such laboratory testing services, Labcorp is willing to assist Client in arranging for the installation of one or more interface connections between Labcorp and Client’s System (as defi ned below) for operational effi ciencies related to transmission and retrieval of laboratory orders and results (“Interface”).
The Parties hereby agree as follows:
A. Client Responsibilities
1. Client agrees to cooperate with Labcorp and the third party vendor(s) designated and agreed to by the Parties (each third party vendor collectively and individually “Vendor”), for the development and installation of the Interface as further described below, including testing of the Interface in connection with such installation and to sign any software licenses or similar agreements reasonably required by Vendor to facilitate development and/or installation of the Interface.
2. The Parties shall mutually agree to the Interface details below:
• Whether the Interface is an orders and results interface or results only interface;
• Which Vendor is responsible for development, installation and upkeep of the Interface;
• Costs associated with the Interface development, installation and upkeep, including but not limited to upfront maintenance fees; and
• Equipment furnished by Labcorp, as necessary for the Interface and as applicable to the Parties.
3. Labcorp may agree to pay, in its sole discretion, Vendor fees related to the Interface, including but not limited to, maintenance, support and service fees (“Vendor Fees”). In the event Labcorp chooses not to pay for such Vendor
Fees, Labcorp shall provide reasonable notice to Client, and Client shall be responsible for any Vendor Fees.
Notwithstanding the foregoing, Client shall continue to be responsible for all maintenance, support, upgrade costs and service and other fees which are related to Client’s System. For the purposes of this Agreement, “Client’s System” shall mean Client’s information technology infrastructure, including computers, software, hardware, databases, electronic systems and networks, whether (i)
operated directly by Client, (ii) on behalf of a customer of Client or any other third party whom Client manages or provides services to (iii) or through the use of third-party services.
4. Client is solely responsible for, and shall remain liable to, Labcorp for the actions and omissions of all employees, entities, subsidiaries and third parties who access or utilize the Interface, regardless of location, as if they were Client’s own actions or omissions.
B. Term and Termination
1. This Agreement shall remain in force and effect for successive annual periods unless terminated. Client and Labcorp shall have the right to terminate this Agreement, with or without cause, by giving the other party thirty (30) day prior written notice. In addition, if Client should at any time discontinue using laboratory services provided by Labcorp, the parties acknowledge that there shall be no further need for Client to have the Interface, Labcorp shall have the right to disable the Interface and this Agreement shall terminate immediately. In the event Client fails to cooperate with Labcorp or Vendor or to implement the Interface within six (6) months from the date the Vendor provides the Interface to Client, Labcorp in its sole discretion may immediately terminate this Agreement.
2. If this Agreement terminates as a result of Client’s failure to comply with the terms herein, including but not limited to Client cooperating and/or implementing the Interface, Client agrees to reimburse Labcorp the total cost of the fees Labcorp has paid related to the Interface, within thirty (30) days of termination of this Agreement by Labcorp.
C. Compliance/Warranties
1. It is the intent of the Parties hereto to comply with all applicable federal, state, and local statutes, regulations, and ordinances including, but not limited to the federal Physician Self-Referral Law [42 U.S.C. § 1395nn], the federal Anti-Kickback Statute [42 U.S.C. § 1320a-7b(b)], and accompanying regulations. The Parties acknowledge and agree that the Interface provided to Client pursuant to this Agreement shall be used solely to order or communicate the results of laboratory tests provided to Client by Labcorp, as well to exchange other patient and health care data directly related to the provision of such laboratory tests. The Parties further acknowledge and agree that the Interface does not confer independent value to Client separate and apart from the laboratory testing services provided by Labcorp and is not considered remuneration provided in exchange for, or to infl uence, the referral of services reimbursable by any commercial or government third-party payer, including Medicare, Medicaid, TRICARE, or any other state or federal health care program.
2. Should either party reasonably conclude that any portion of this Agreement is or may be in violation of such requirements or subsequent enactments by federal, state, or local authorities, this Agreement shall terminate immediately by written notice thereof to other party unless the Parties agree to such modifi cations of the Agreement as may be necessary to establish compliance with all federal, state, and local statutes, regulations, and ordinances.
D. Warranty/Liability
1. Client agrees that Labcorp does not own or control the functionality or performance of the Interface. Client and Labcorp each agree to be responsible for all claims, damages, or other expenses which arise, or are alleged to have arisen, in connection with the operation or function of their respective connection to the Interface and any other portions of the Interface which such party controls. For clarity purposes, Labcorp shall not indemnify Client for claims, damages, or other expenses that arise in respect to Client’s connection or control of the Interface and Client shall not indemnify Labcorp for claims, damages or other expenses that arise in respect to Labcorp’s
connection or control of the Interface. Notwithstanding the foregoing, Client agrees that any claims related to the establishment or functioning of the Interface shall be brought to the attention of Labcorp.
E. Miscellaneous
1. Assignment. Client may not assign this Agreement without the prior written consent of Labcorp.
2. Notices. All notices, requests, consents, claims, demands, waivers, and other communications under the Agreement have binding legal effect only if in writing and addressed to a party at the address set forth below. Notices sent in accordance with this section shall be deemed effectively given: (a) when received, if sent by a nationally recognized overnight courier, signature required; and (b) on the fi fth day after the date mailed by certifi ed or registered mail, return receipt requested, postage prepaid. Client shall submit all notices to their primary Labcorp business partner with a copy to 531 South Spring Street, Burlington NC, 27215, Attn: Law Department. Labcorp shall submit all notices to Client at the address listed in the signature block below.
3. Use of Name. Neither Party shall use the other’s name, trademark, logos, or otherwise refer to the other in any press release, marketing materials, advertisements or other broadcast or communication of any kind without fi rst obtaining that Party’s advance written consent. Any unauthorized use under this Section shall be considered a material breach of this Agreement.
4. Entire Agreement. This Agreement constitutes the entire understanding between the Parties hereto with respect to the subject matter herein and no amendment or modifi cation of its terms shall be valid or binding upon any party unless reduced to writing and signed by authorized representatives of the Parties hereto. Any applicable provisions required by federal, state, or local law are hereby incorporated by reference.
IN WITNESS WHEREOF, the Parties have caused this Agreement to be executed in their names as their offi cial acts by their respective representatives, each of whom is duly authorized to execute the same. ';

echo nl2br($eula);
