<?php

/**
 * The attribute types of the QDM data elements, entities and components of
 * cqm-models 4.3.2, generated from its mongoose schemas by
 * tests/Tests/Isolated/Cqm/Cql/qdm-schema.js. Do not edit by hand.
 *
 * Each attribute is a type name, a list of one ("[Code]"), a nested schema
 * ("@FacilityLocation", "[@Component]"), or a string default ("=encounter").
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Jerry Padgett <sjpadgett@gmail.com>
 * @copyright Copyright (c) 2026 Jerry Padgett <sjpadgett@gmail.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

declare(strict_types=1);

namespace OpenEMR\Cqm\Cql\Qdm;

final class QdmSchema
{
    /**
     * Data elements and entities, by type name without the QDM:: prefix.
     *
     * @var array<string, array<string, string>>
     */
    public const TYPES = [
        'AdverseEvent' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'severity' => 'Code', 'facilityLocation' => '@FacilityLocation', 'type' => 'Code', 'recorder' => '[AnyEntity]', 'qdmTitle' => '=Adverse Event', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.120', 'qdmCategory' => '=adverse_event', 'qdmVersion' => '=5.6', '_type' => '=QDM::AdverseEvent'],
        'AllergyIntolerance' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'prevalencePeriod' => 'Interval', 'type' => 'Code', 'severity' => 'Code', 'recorder' => '[AnyEntity]', 'qdmTitle' => '=Allergy/Intolerance', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.119', 'qdmCategory' => '=allergy', 'qdmStatus' => '=intolerance', 'qdmVersion' => '=5.6', '_type' => '=QDM::AllergyIntolerance'],
        'AssessmentOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'negationRationale' => 'Code', 'reason' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Assessment, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.131', 'qdmCategory' => '=assessment', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::AssessmentOrder'],
        'AssessmentPerformed' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'negationRationale' => 'Code', 'reason' => 'Code', 'method' => 'Code', 'result' => 'Any', 'interpretation' => 'Code', 'components' => '[@Component]', 'relatedTo' => '[String]', 'performer' => '[AnyEntity]', 'qdmTitle' => '=Assessment, Performed', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.117', 'qdmCategory' => '=assessment', 'qdmStatus' => '=performed', 'qdmVersion' => '=5.6', '_type' => '=QDM::AssessmentPerformed'],
        'AssessmentRecommended' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'negationRationale' => 'Code', 'reason' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Assessment, Recommended', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.118', 'qdmCategory' => '=assessment', 'qdmStatus' => '=recommended', 'qdmVersion' => '=5.6', '_type' => '=QDM::AssessmentRecommended'],
        'CareGoal' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'statusDate' => 'Date', 'relevantPeriod' => 'Interval', 'relatedTo' => '[String]', 'targetOutcome' => 'Any', 'performer' => '[AnyEntity]', 'qdmTitle' => '=Care Goal', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.7', 'qdmCategory' => '=care_goal', 'qdmVersion' => '=5.6', '_type' => '=QDM::CareGoal'],
        'CarePartner' => ['identifier' => '@Identifier', 'qdmVersion' => '=5.6', '_type' => '=QDM::CarePartner', 'id' => 'String', '_id' => 'ObjectId', 'relationship' => 'Code', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.134', 'qrdaOid' => '=2.16.840.1.113883.10.20.24.3.160'],
        'CommunicationPerformed' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'category' => 'Code', 'medium' => 'Code', 'sender' => '[AnyEntity]', 'recipient' => '[AnyEntity]', 'relatedTo' => '[String]', 'sentDatetime' => 'DateTime', 'receivedDatetime' => 'DateTime', 'negationRationale' => 'Code', 'qdmTitle' => '=Communication, Performed', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.132', 'qdmCategory' => '=communication', 'qdmStatus' => '=performed', 'qdmVersion' => '=5.6', '_type' => '=QDM::CommunicationPerformed'],
        'Component' => ['code' => 'Code', 'result' => 'Any', 'qdmVersion' => '=5.6', '_type' => '=QDM::Component', '_id' => 'ObjectId'],
        'DeviceOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'negationRationale' => 'Code', 'reason' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Device, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.15', 'qdmCategory' => '=device', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::DeviceOrder'],
        'DeviceRecommended' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'negationRationale' => 'Code', 'reason' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Device, Recommended', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.16', 'qdmCategory' => '=device', 'qdmStatus' => '=recommended', 'qdmVersion' => '=5.6', '_type' => '=QDM::DeviceRecommended'],
        'Diagnosis' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'prevalencePeriod' => 'Interval', 'anatomicalLocationSite' => 'Code', 'severity' => 'Code', 'recorder' => '[AnyEntity]', 'qdmTitle' => '=Diagnosis', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.110', 'qrdaOid' => '=2.16.840.1.113883.10.20.24.3.135', 'qdmCategory' => '=condition', 'qdmVersion' => '=5.6', '_type' => '=QDM::Diagnosis'],
        'DiagnosisComponent' => ['code' => 'Code', 'presentOnAdmissionIndicator' => 'Code', 'rank' => 'Number', 'qdmVersion' => '=5.6', '_type' => '=QDM::DiagnosisComponent', '_id' => 'ObjectId'],
        'DiagnosticStudyOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Diagnostic Study, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.22', 'qdmCategory' => '=diagnostic_study', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::DiagnosticStudyOrder'],
        'DiagnosticStudyPerformed' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'reason' => 'Code', 'result' => 'Any', 'resultDatetime' => 'DateTime', 'interpretation' => 'Code', 'status' => 'Code', 'method' => 'Code', 'facilityLocation' => '@FacilityLocation', 'negationRationale' => 'Code', 'components' => '[@Component]', 'performer' => '[AnyEntity]', 'relatedTo' => '[String]', 'qdmTitle' => '=Diagnostic Study, Performed', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.23', 'qdmCategory' => '=diagnostic_study', 'qdmStatus' => '=performed', 'qdmVersion' => '=5.6', '_type' => '=QDM::DiagnosticStudyPerformed'],
        'DiagnosticStudyRecommended' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Diagnostic Study, Recommended', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.24', 'qrdaOid' => '=2.16.840.1.113883.10.20.24.3.19', 'qdmCategory' => '=diagnostic_study', 'qdmStatus' => '=recommended', 'qdmVersion' => '=5.6', '_type' => '=QDM::DiagnosticStudyRecommended'],
        'EncounterOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'facilityLocation' => '@FacilityLocation', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'priority' => 'Code', 'qdmTitle' => '=Encounter, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.27', 'qdmCategory' => '=encounter', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::EncounterOrder'],
        'EncounterPerformed' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'admissionSource' => 'Code', 'class' => 'Code', 'relevantPeriod' => 'Interval', 'dischargeDisposition' => 'Code', 'facilityLocations' => '[@FacilityLocation]', 'diagnoses' => '[@DiagnosisComponent]', 'lengthOfStay' => 'Quantity', 'priority' => 'Code', 'participant' => '[AnyEntity]', 'relatedTo' => '[String]', 'qdmTitle' => '=Encounter, Performed', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.5', 'qdmCategory' => '=encounter', 'qdmStatus' => '=performed', 'qdmVersion' => '=5.6', '_type' => '=QDM::EncounterPerformed'],
        'EncounterRecommended' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'facilityLocation' => '@FacilityLocation', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Encounter, Recommended', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.28', 'qdmCategory' => '=encounter', 'qdmStatus' => '=recommended', 'qdmVersion' => '=5.6', '_type' => '=QDM::EncounterRecommended'],
        'Entity' => ['id' => 'String', 'identifier' => '@Identifier', 'qdmVersion' => '=5.6', '_type' => '=QDM::Entity', '_id' => 'ObjectId'],
        'FacilityLocation' => ['code' => 'Code', 'locationPeriod' => 'Interval', 'qdmVersion' => '=5.6', '_type' => '=QDM::FacilityLocation', '_id' => 'ObjectId'],
        'FamilyHistory' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relationship' => 'Code', 'recorder' => '[AnyEntity]', 'qdmTitle' => '=Family History', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.111', 'qrdaOid' => '=2.16.840.1.113883.10.20.24.3.12', 'qdmCategory' => '=family_history', 'qdmVersion' => '=5.6', '_type' => '=QDM::FamilyHistory'],
        'Identifier' => ['namingSystem' => 'String', 'value' => 'String', 'qdmVersion' => '=5.6', '_type' => '=QDM::Identifier'],
        'ImmunizationAdministered' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'reason' => 'Code', 'dosage' => 'Quantity', 'route' => 'Code', 'negationRationale' => 'Code', 'performer' => '[AnyEntity]', 'qdmTitle' => '=Immunization, Administered', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.112', 'qrdaOid' => '=2.16.840.1.113883.10.20.24.3.140', 'qdmCategory' => '=immunization', 'qdmStatus' => '=administered', 'qdmVersion' => '=5.6', '_type' => '=QDM::ImmunizationAdministered'],
        'ImmunizationOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'activeDatetime' => 'DateTime', 'authorDatetime' => 'DateTime', 'dosage' => 'Quantity', 'supply' => 'Quantity', 'reason' => 'Code', 'route' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Immunization, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.113', 'qdmCategory' => '=immunization', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::ImmunizationOrder'],
        'InterventionOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Intervention, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.35', 'qdmCategory' => '=intervention', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::InterventionOrder'],
        'InterventionPerformed' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'reason' => 'Code', 'result' => 'Any', 'status' => 'Code', 'negationRationale' => 'Code', 'performer' => '[AnyEntity]', 'relatedTo' => '[String]', 'qdmTitle' => '=Intervention, Performed', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.36', 'qdmCategory' => '=intervention', 'qdmStatus' => '=performed', 'qdmVersion' => '=5.6', '_type' => '=QDM::InterventionPerformed'],
        'InterventionRecommended' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Intervention, Recommended', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.37', 'qdmCategory' => '=intervention', 'qdmStatus' => '=recommended', 'qdmVersion' => '=5.6', '_type' => '=QDM::InterventionRecommended'],
        'LaboratoryTestOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Laboratory Test, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.41', 'qdmCategory' => '=laboratory_test', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::LaboratoryTestOrder'],
        'LaboratoryTestPerformed' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'status' => 'Code', 'method' => 'Code', 'result' => 'Any', 'resultDatetime' => 'DateTime', 'reason' => 'Code', 'referenceRange' => 'Interval', 'interpretation' => 'Code', 'negationRationale' => 'Code', 'components' => '[@Component]', 'performer' => '[AnyEntity]', 'relatedTo' => '[String]', 'qdmTitle' => '=Laboratory Test, Performed', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.42', 'qdmCategory' => '=laboratory_test', 'qdmStatus' => '=performed', 'qdmVersion' => '=5.6', '_type' => '=QDM::LaboratoryTestPerformed'],
        'LaboratoryTestRecommended' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Laboratory Test, Recommended', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.43', 'qdmCategory' => '=laboratory_test', 'qdmStatus' => '=recommended', 'qdmVersion' => '=5.6', '_type' => '=QDM::LaboratoryTestRecommended'],
        'Location' => ['identifier' => '@Identifier', 'qdmVersion' => '=5.6', '_type' => '=QDM::Location', 'id' => 'String', '_id' => 'ObjectId', 'locationType' => 'Code', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.142'],
        'MedicationActive' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'relevantDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'dosage' => 'Quantity', 'frequency' => 'Code', 'route' => 'Code', 'recorder' => '[AnyEntity]', 'qdmTitle' => '=Medication, Active', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.44', 'qdmCategory' => '=medication', 'qdmStatus' => '=active', 'qdmVersion' => '=5.6', '_type' => '=QDM::MedicationActive'],
        'MedicationAdministered' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'dosage' => 'Quantity', 'frequency' => 'Code', 'route' => 'Code', 'reason' => 'Code', 'negationRationale' => 'Code', 'performer' => '[AnyEntity]', 'qdmTitle' => '=Medication, Administered', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.45', 'qdmCategory' => '=medication', 'qdmStatus' => '=administered', 'qdmVersion' => '=5.6', '_type' => '=QDM::MedicationAdministered'],
        'MedicationDischarge' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'refills' => 'Number', 'dosage' => 'Quantity', 'supply' => 'Quantity', 'frequency' => 'Code', 'daysSupplied' => 'Number', 'route' => 'Code', 'negationRationale' => 'Code', 'prescriber' => '[AnyEntity]', 'recorder' => '[AnyEntity]', 'qdmTitle' => '=Medication, Discharge', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.48', 'qdmCategory' => '=medication', 'qdmStatus' => '=discharge', 'qdmVersion' => '=5.6', '_type' => '=QDM::MedicationDischarge'],
        'MedicationDispensed' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'refills' => 'Number', 'dosage' => 'Quantity', 'supply' => 'Quantity', 'frequency' => 'Code', 'daysSupplied' => 'Number', 'route' => 'Code', 'prescriber' => '[AnyEntity]', 'dispenser' => '[AnyEntity]', 'negationRationale' => 'Code', 'relatedTo' => '[String]', 'qdmTitle' => '=Medication, Dispensed', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.49', 'qdmCategory' => '=medication', 'qdmStatus' => '=dispensed', 'qdmVersion' => '=5.6', '_type' => '=QDM::MedicationDispensed'],
        'MedicationOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'refills' => 'Number', 'dosage' => 'Quantity', 'supply' => 'Quantity', 'frequency' => 'Code', 'daysSupplied' => 'Number', 'route' => 'Code', 'setting' => 'Code', 'reason' => 'Code', 'negationRationale' => 'Code', 'prescriber' => '[AnyEntity]', 'relatedTo' => '[String]', 'qdmTitle' => '=Medication, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.51', 'qdmCategory' => '=medication', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::MedicationOrder'],
        'Organization' => ['identifier' => '@Identifier', 'qdmVersion' => '=5.6', '_type' => '=QDM::Organization', 'id' => 'String', '_id' => 'ObjectId', 'organizationType' => 'Code', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.135', 'qrdaOid' => '=2.16.840.1.113883.10.20.24.3.163'],
        'Participation' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'participationPeriod' => 'Interval', 'qdmTitle' => '=Participation', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.130', 'qdmCategory' => '=participation', 'qdmVersion' => '=5.6', '_type' => '=QDM::Participation'],
        'PatientCareExperience' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'recorder' => '[AnyEntity]', 'qdmTitle' => '=Patient Care Experience', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.52', 'qdmCategory' => '=care_experience', 'qdmVersion' => '=5.6', '_type' => '=QDM::PatientCareExperience'],
        'PatientCharacteristic' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'qdmTitle' => '=Patient Characteristic', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.53', 'qdmCategory' => '=patient_characteristic', 'qdmVersion' => '=5.6', '_type' => '=QDM::PatientCharacteristic'],
        'PatientCharacteristicBirthdate' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'birthDatetime' => 'DateTime', 'qdmTitle' => '=Patient Characteristic Birthdate', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.54', 'qdmCategory' => '=patient_characteristic', 'qdmStatus' => '=birthdate', 'qdmVersion' => '=5.6', '_type' => '=QDM::PatientCharacteristicBirthdate'],
        'PatientCharacteristicClinicalTrialParticipant' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'reason' => 'Code', 'relevantPeriod' => 'Interval', 'qdmTitle' => '=Patient Characteristic Clinical Trial Participant', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.6', 'qrdaOid' => '=2.16.840.1.113883.10.20.24.3.51', 'qdmCategory' => '=patient_characteristic', 'qdmStatus' => '=clinical_trial_participant', 'qdmVersion' => '=5.6', '_type' => '=QDM::PatientCharacteristicClinicalTrialParticipant'],
        'PatientCharacteristicEthnicity' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'qdmTitle' => '=Patient Characteristic Ethnicity', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.56', 'qdmCategory' => '=patient_characteristic', 'qdmStatus' => '=ethnicity', 'qdmVersion' => '=5.6', '_type' => '=QDM::PatientCharacteristicEthnicity'],
        'PatientCharacteristicExpired' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'expiredDatetime' => 'DateTime', 'cause' => 'Code', 'qdmTitle' => '=Patient Characteristic Expired', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.57', 'qdmCategory' => '=patient_characteristic', 'qdmStatus' => '=expired', 'qdmVersion' => '=5.6', '_type' => '=QDM::PatientCharacteristicExpired'],
        'PatientCharacteristicPayer' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'relevantPeriod' => 'Interval', 'qdmTitle' => '=Patient Characteristic Payer', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.58', 'qdmCategory' => '=patient_characteristic', 'qdmStatus' => '=payer', 'qdmVersion' => '=5.6', '_type' => '=QDM::PatientCharacteristicPayer'],
        'PatientCharacteristicRace' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'qdmTitle' => '=Patient Characteristic Race', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.59', 'qdmCategory' => '=patient_characteristic', 'qdmStatus' => '=race', 'qdmVersion' => '=5.6', '_type' => '=QDM::PatientCharacteristicRace'],
        'PatientCharacteristicSex' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'qdmTitle' => '=Patient Characteristic Sex', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.55', 'qdmCategory' => '=patient_characteristic', 'qdmStatus' => '=gender', 'qdmVersion' => '=5.6', '_type' => '=QDM::PatientCharacteristicSex'],
        'PatientEntity' => ['identifier' => '@Identifier', 'qdmVersion' => '=5.6', '_type' => '=QDM::PatientEntity', 'id' => 'String', '_id' => 'ObjectId', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.136', 'qrdaOid' => '=2.16.840.1.113883.10.20.24.3.161'],
        'PhysicalExamOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'anatomicalLocationSite' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Physical Exam, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.61', 'qdmCategory' => '=physical_exam', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::PhysicalExamOrder'],
        'PhysicalExamPerformed' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'reason' => 'Code', 'method' => 'Code', 'result' => 'Any', 'anatomicalLocationSite' => 'Code', 'negationRationale' => 'Code', 'components' => '[@Component]', 'performer' => '[AnyEntity]', 'relatedTo' => '[String]', 'qdmTitle' => '=Physical Exam, Performed', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.62', 'qdmCategory' => '=physical_exam', 'qdmStatus' => '=performed', 'qdmVersion' => '=5.6', '_type' => '=QDM::PhysicalExamPerformed'],
        'PhysicalExamRecommended' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'anatomicalLocationSite' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Physical Exam, Recommended', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.63', 'qdmCategory' => '=physical_exam', 'qdmStatus' => '=recommended', 'qdmVersion' => '=5.6', '_type' => '=QDM::PhysicalExamRecommended'],
        'Practitioner' => ['identifier' => '@Identifier', 'qdmVersion' => '=5.6', '_type' => '=QDM::Practitioner', 'id' => 'String', '_id' => 'ObjectId', 'role' => 'Code', 'specialty' => 'Code', 'qualification' => 'Code', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.137', 'qrdaOid' => '=2.16.840.1.113883.10.20.24.3.162'],
        'ProcedureOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'anatomicalLocationSite' => 'Code', 'rank' => 'Number', 'priority' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Procedure, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.66', 'qdmCategory' => '=procedure', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::ProcedureOrder'],
        'ProcedurePerformed' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'reason' => 'Code', 'method' => 'Code', 'result' => 'Any', 'status' => 'Code', 'anatomicalLocationSite' => 'Code', 'rank' => 'Number', 'incisionDatetime' => 'DateTime', 'negationRationale' => 'Code', 'components' => '[@Component]', 'performer' => '[AnyEntity]', 'relatedTo' => '[String]', 'qdmTitle' => '=Procedure, Performed', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.67', 'qdmCategory' => '=procedure', 'qdmStatus' => '=performed', 'qdmVersion' => '=5.6', '_type' => '=QDM::ProcedurePerformed'],
        'ProcedureRecommended' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'anatomicalLocationSite' => 'Code', 'rank' => 'Number', 'requester' => '[AnyEntity]', 'negationRationale' => 'Code', 'qdmTitle' => '=Procedure, Recommended', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.68', 'qdmCategory' => '=procedure', 'qdmStatus' => '=recommended', 'qdmVersion' => '=5.6', '_type' => '=QDM::ProcedureRecommended'],
        'ProviderCareExperience' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'recorder' => '[AnyEntity]', 'qdmTitle' => '=Provider Care Experience', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.70', 'qdmCategory' => '=care_experience', 'qdmVersion' => '=5.6', '_type' => '=QDM::ProviderCareExperience'],
        'RelatedPerson' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'identifier' => '@Identifier', 'linkedPatientId' => 'String', 'qdmTitle' => '=Related Person', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.141', 'qdmCategory' => '=related_person', 'qdmVersion' => '=5.6', '_type' => '=QDM::RelatedPerson'],
        'ResultComponent' => ['code' => 'Code', 'result' => 'Any', 'qdmVersion' => '=5.6', '_type' => '=QDM::ResultComponent', '_id' => 'ObjectId', 'referenceRange' => 'Interval'],
        'SubstanceAdministered' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'dosage' => 'Quantity', 'frequency' => 'Code', 'route' => 'Code', 'negationRationale' => 'Code', 'performer' => '[AnyEntity]', 'qdmTitle' => '=Substance, Administered', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.73', 'qdmCategory' => '=substance', 'qdmStatus' => '=administered', 'qdmVersion' => '=5.6', '_type' => '=QDM::SubstanceAdministered'],
        'SubstanceOrder' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'relevantPeriod' => 'Interval', 'reason' => 'Code', 'dosage' => 'Quantity', 'supply' => 'Quantity', 'frequency' => 'Code', 'refills' => 'Number', 'route' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Substance, Order', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.77', 'qdmCategory' => '=substance', 'qdmStatus' => '=order', 'qdmVersion' => '=5.6', '_type' => '=QDM::SubstanceOrder'],
        'SubstanceRecommended' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'authorDatetime' => 'DateTime', 'reason' => 'Code', 'dosage' => 'Quantity', 'frequency' => 'Code', 'refills' => 'Number', 'route' => 'Code', 'negationRationale' => 'Code', 'requester' => '[AnyEntity]', 'qdmTitle' => '=Substance, Recommended', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.78', 'qdmCategory' => '=substance', 'qdmStatus' => '=recommended', 'qdmVersion' => '=5.6', '_type' => '=QDM::SubstanceRecommended'],
        'Symptom' => ['dataElementCodes' => '[Code]', 'description' => 'String', 'codeListId' => 'String', 'id' => 'String', '_id' => 'ObjectId', 'prevalencePeriod' => 'Interval', 'severity' => 'Code', 'recorder' => '[AnyEntity]', 'qdmTitle' => '=Symptom', 'hqmfOid' => '=2.16.840.1.113883.10.20.28.4.116', 'qrdaOid' => '=2.16.840.1.113883.10.20.24.3.136', 'qdmCategory' => '=symptom', 'qdmVersion' => '=5.6', '_type' => '=QDM::Symptom'],
    ];

    /**
     * Schemas nested in a data element: components, facility locations, identifiers.
     *
     * @var array<string, array<string, string>>
     */
    public const NESTED = [
        'Component' => ['code' => 'Code', 'result' => 'Any', 'qdmVersion' => '=5.6', '_type' => '=QDM::Component', '_id' => 'ObjectId'],
        'DiagnosisComponent' => ['code' => 'Code', 'presentOnAdmissionIndicator' => 'Code', 'rank' => 'Number', 'qdmVersion' => '=5.6', '_type' => '=QDM::DiagnosisComponent', '_id' => 'ObjectId'],
        'FacilityLocation' => ['code' => 'Code', 'locationPeriod' => 'Interval', 'qdmVersion' => '=5.6', '_type' => '=QDM::FacilityLocation', '_id' => 'ObjectId'],
        'Identifier' => ['namingSystem' => 'String', 'value' => 'String', 'qdmVersion' => '=5.6', '_type' => '=QDM::Identifier'],
    ];
}
