CREATE TABLE IF NOT EXISTS `form_soap2` (
  `id`                  bigint(20)   NOT NULL auto_increment,
  `date`                datetime     DEFAULT NULL,
  `pid`                 bigint(20)   NOT NULL DEFAULT 0,
  `user`                varchar(255) DEFAULT NULL,
  `groupname`           varchar(255) DEFAULT NULL,
  `authorized`          tinyint(4)   NOT NULL DEFAULT 0,
  `activity`            tinyint(4)   NOT NULL DEFAULT 0,
  `subjective`          text         NOT NULL DEFAULT '',
  `objective`           text         NOT NULL DEFAULT '',
  `assessment`          text         NOT NULL DEFAULT '',
  `plan`                text         NOT NULL DEFAULT '',
  `general`             varchar(255) NOT NULL DEFAULT '',
  `neurological`        varchar(255) NOT NULL DEFAULT '',
  `heent`               varchar(255) NOT NULL DEFAULT '',
  `respiratory`         varchar(255) NOT NULL DEFAULT '',
  `cardio`              varchar(255) NOT NULL DEFAULT '',
  `gastro`              varchar(255) NOT NULL DEFAULT '',
  `skin`                varchar(255) NOT NULL DEFAULT '',
  `extremities`         varchar(255) NOT NULL DEFAULT '',
  `neck`                varchar(255) NOT NULL DEFAULT '',
  `breasts`             varchar(255) NOT NULL DEFAULT '',
  `abdomen`             varchar(255) NOT NULL DEFAULT '',
  `mentalstatus`        varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
) TYPE=InnoDB;
