CREATE TABLE IF NOT EXISTS `form_chiro_history` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
general_condit TEXT,
muscle_joint TEXT,
pain_numb_locat TEXT,
gastrointest TEXT,
genitouro TEXT,
respiratory TEXT,
head_neck TEXT,
cardiovascular TEXT,
women_health TEXT,
alcoholism TEXT,
anemia TEXT,
arthritis TEXT,
cancer TEXT,
herpes TEXT,
hypoglycemia TEXT,
diabetes TEXT,
eczema TEXT,
goiter TEXT,
ulcers TEXT,
gout TEXT,
heart_disease TEXT,
rheumatic_fever TEXT,
miscarriage TEXT,
polio TEXT,
pneumonia TEXT,
atherosclerosis TEXT,
multiple_sclerosis TEXT,
stroke TEXT,
tuberculosis TEXT,
epilepsy TEXT,
measles TEXT,
chicken_pox TEXT,
venereal_disease TEXT,
organ_gland TEXT,
family_history TEXT,
regular_meals TEXT,

PRIMARY KEY (id)
) ENGINE=MyISAM;
