CREATE TABLE IF NOT EXISTS `form_immunization_record` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
vacc_tetanus longtext,
vacc_influenza longtext,
vacc_pneumococcal longtext,
vacc_mmr longtext,
vacc_hep_a longtext,
vacc_hep_b longtext,
vacc_varicella longtext,
last_vacc_tetanus longtext,
last_vacc_influenza longtext,
last_vacc_pneumococcal longtext,
last_vacc_mmr longtext,
last_vacc_hep_a longtext,
last_vacc_hep_b longtext,
last_vacc_varicella longtext,

PRIMARY KEY (id)
) ENGINE=MyISAM;
