x-includes:
  node-version: "24"
  selenium-template: compose-shared-selenium/docker-compose.yml
  webserver-template: compose-shared-apache.yml
  database-template: compose-shared-mariadb.yml
  mailpit-template: compose-shared-mailpit/compose.yml

services:
  mysql:
    image: mariadb:11.4.12@sha256:3b1303709dd92adb4a4b29966be30adf1ecb8aa8a78cab19cdc2bf0f9e4dee55
  openemr:
    image: openemr/openemr:flex-3.23-php-8.5@sha256:aee03b65198539f5425d712628b2f4d1c8da7436128f6b59d2702526ba4751bc
