CREATE TABLE IF NOT EXISTS `form_ros2` (
  `id`                  bigint(20)   NOT NULL auto_increment,
  `date`                datetime     DEFAULT NULL,
  `pid`                 bigint(20)   NOT NULL DEFAULT 0,
  `user`                TEXT,
  `groupname`           TEXT,
  `authorized`          tinyint(4)   NOT NULL DEFAULT 0,
  `activity`            tinyint(4)   NOT NULL DEFAULT 0,
`general_headache` varchar(3) NOT NULL default 'N/A',
`general_headache_text` TEXT,
`general_fever` varchar(3) NOT NULL default 'N/A',
`general_fever_text` TEXT,
`general_chills` varchar(3) NOT NULL default 'N/A',
`general_chills_text` TEXT,
`general_body_aches` varchar(3) NOT NULL default 'N/A',
`general_body_aches_text` TEXT,
`general_fatigue` varchar(3) NOT NULL default 'N/A',
`general_fatigue_text` TEXT,
`general_loss_of_appetite` varchar(3) NOT NULL default 'N/A',
`general_loss_of_appetite_text` TEXT,
`general_weight_loss` varchar(3) NOT NULL default 'N/A',
`general_weight_loss_text` TEXT,
`general_daytime_drowsiness` varchar(3) NOT NULL default 'N/A',
`general_daytime_drowsiness_text` TEXT,
`general_excessive_snoring` varchar(3) NOT NULL default 'N/A',
`general_excessive_snoring_text` TEXT,
`neuro_disorientation` varchar(3) NOT NULL default 'N/A',
`neuro_disorientation_text` TEXT,
`neuro_loss_of_consciousness` varchar(3) NOT NULL default 'N/A',
`neuro_loss_of_consciousness_text` TEXT,
`neuro_numbness` varchar(3) NOT NULL default 'N/A',
`neuro_numbness_text` TEXT,
`neuro_tingling` varchar(3) NOT NULL default 'N/A',
`neuro_tingling_text` TEXT,
`neuro_restlessness` varchar(3) NOT NULL default 'N/A',
`neuro_restlessness_text` TEXT,
`neuro_dizziness` varchar(3) NOT NULL default 'N/A',
`neuro_dizziness_text` TEXT,
`neuro_vertigo` varchar(3) NOT NULL default 'N/A',
`neuro_vertigo_text` TEXT,
`neuro_amaurosis_fugax` varchar(3) NOT NULL default 'N/A',
`neuro_amaurosis_fugax_text` TEXT,
`neuro_stroke` varchar(3) NOT NULL default 'N/A',
`neuro_stroke_text` TEXT,
`neuro_gait_abnormality` varchar(3) NOT NULL default 'N/A',
`neuro_gait_abnormality_text` TEXT,
`neuro_frequent_headaches` varchar(3) NOT NULL default 'N/A',
`neuro_frequent_headaches_text` TEXT,
`neuro_parathesias` varchar(3) NOT NULL default 'N/A',
`neuro_parathesias_text` TEXT,
`neuro_seizures` varchar(3) NOT NULL default 'N/A',
`neuro_seizures_text` TEXT,
`neuro_trans_ischemic_attacks` varchar(3) NOT NULL default 'N/A',
`neuro_trans_ischemic_attacks_text` TEXT,
`neuro_significant_tremors` varchar(3) NOT NULL default 'N/A',
`neuro_significant_tremors_text` TEXT,
`neck_neck_stiffness` varchar(3) NOT NULL default 'N/A',
`neck_neck_stiffness_text` TEXT,
`neck_neck_pain` varchar(3) NOT NULL default 'N/A',
`neck_neck_pain_text` TEXT,
`neck_neck_masses` varchar(3) NOT NULL default 'N/A',
`neck_neck_masses_text` TEXT,
`neck_neck_tenderness` varchar(3) NOT NULL default 'N/A',
`neck_neck_tenderness_text` TEXT,
`heent_oral_ulcers` varchar(3) NOT NULL default 'N/A',
`heent_oral_ulcers_text` TEXT,
`heent_excessive_cavities` varchar(3) NOT NULL default 'N/A',
`heent_excessive_cavities_text` TEXT,
`heent_gingival_disease` varchar(3) NOT NULL default 'N/A',
`heent_gingival_disease_text` TEXT,
`heent_persistent_hoarseness` varchar(3) NOT NULL default 'N/A',
`heent_persistent_hoarseness_text` TEXT,
`heent_mouth_lesions` varchar(3) NOT NULL default 'N/A',
`heent_mouth_lesions_text` TEXT,
`heent_dysphagia` varchar(3) NOT NULL default 'N/A',
`heent_dysphagia_text` TEXT,
`heent_odynophagia` varchar(3) NOT NULL default 'N/A',
`heent_odynophagia_text` TEXT,
`heent_dental_pain` varchar(3) NOT NULL default 'N/A',
`heent_dental_pain_text` TEXT,
`heent_sore_throat` varchar(3) NOT NULL default 'N/A',
`heent_sore_throat_text` TEXT,
`heent_ear_pain` varchar(3) NOT NULL default 'N/A',
`heent_ear_pain_text` TEXT,
`heent_ear_discharge` varchar(3) NOT NULL default 'N/A',
`heent_ear_discharge_text` TEXT,
`heent_tinnitus` varchar(3) NOT NULL default 'N/A',
`heent_tinnitus_text` TEXT,
`heent_hearing_loss` varchar(3) NOT NULL default 'N/A',
`heent_hearing_loss_text` TEXT,
`heent_allergic_rhinitis` varchar(3) NOT NULL default 'N/A',
`heent_allergic_rhinitis_text` TEXT,
`heent_nasal_congestion` varchar(3) NOT NULL default 'N/A',
`heent_nasal_congestion_text` TEXT,
`heent_nasal_discharge` varchar(3) NOT NULL default 'N/A',
`heent_nasal_discharge_text` TEXT,
`heent_nasal_injury` varchar(3) NOT NULL default 'N/A',
`heent_nasal_injury_text` TEXT,
`heent_nasal_surgery` varchar(3) NOT NULL default 'N/A',
`heent_nasal_surgery_text` TEXT,
`heent_nose_bleeds` varchar(3) NOT NULL default 'N/A',
`heent_nose_bleeds_text` TEXT,
`heent_post_nasal_drip` varchar(3) NOT NULL default 'N/A',
`heent_post_nasal_drip_text` TEXT,
`heent_sinus_pressure` varchar(3) NOT NULL default 'N/A',
`heent_sinus_pressure_text` TEXT,
`heent_sinus_pain` varchar(3) NOT NULL default 'N/A',
`heent_sinus_pain_text` TEXT,
`heent_headache` varchar(3) NOT NULL default 'N/A',
`heent_headache_text` TEXT,
`heent_eye_pain` varchar(3) NOT NULL default 'N/A',
`heent_eye_pain_text` TEXT,
`heent_eye_redness` varchar(3) NOT NULL default 'N/A',
`heent_eye_redness_text` TEXT,
`heent_visual_changes` varchar(3) NOT NULL default 'N/A',
`heent_visual_changes_text` TEXT,
`heent_blurry_vision` varchar(3) NOT NULL default 'N/A',
`heent_blurry_vision_text` TEXT,
`heent_eye_discharge` varchar(3) NOT NULL default 'N/A',
`heent_eye_discharge_text` TEXT,
`heent_eye_glasses_contacts` varchar(3) NOT NULL default 'N/A',
`heent_eye_glasses_contacts_text` TEXT,
`heent_excess_tearing` varchar(3) NOT NULL default 'N/A',
`heent_excess_tearing_text` TEXT,
`heent_photophobia` varchar(3) NOT NULL default 'N/A',
`heent_photophobia_text` TEXT,
`heent_scotomata` varchar(3) NOT NULL default 'N/A',
`heent_scotomata_text` TEXT,
`heent_tunnel_vision` varchar(3) NOT NULL default 'N/A',
`heent_tunnel_vision_text` TEXT,
`heent_glaucoma` varchar(3) NOT NULL default 'N/A',
`heent_glaucoma_text` TEXT,
`cardiovascular_sub_sternal_or_left_chest_pain` varchar(3) NOT NULL default 'N/A',
`cardiovascular_sub_sternal_or_left_chest_pain_text` TEXT,
`cardiovascular_other_chest_pain` varchar(3) NOT NULL default 'N/A',
`cardiovascular_other_chest_pain_text` TEXT,
`cardiovascular_palpitations` varchar(3) NOT NULL default 'N/A',
`cardiovascular_palpitations_text` TEXT,
`cardiovascular_irregular_rhythm` varchar(3) NOT NULL default 'N/A',
`cardiovascular_irregular_rhythm_text` TEXT,
`cardiovascular_jugular_vein_distention` varchar(3) NOT NULL default 'N/A',
`cardiovascular_jugular_vein_distention_text` TEXT,
`cardiovascular_claudication` varchar(3) NOT NULL default 'N/A',
`cardiovascular_claudication_text` TEXT,
`cardiovascular_dizziness` varchar(3) NOT NULL default 'N/A',
`cardiovascular_dizziness_text` TEXT,
`cardiovascular_dyspnea_on_exertion` varchar(3) NOT NULL default 'N/A',
`cardiovascular_dyspnea_on_exertion_text` TEXT,
`cardiovascular_orthopnea` varchar(3) NOT NULL default 'N/A',
`cardiovascular_orthopnea_text` TEXT,
`cardiovascular_noctural_dyspnea` varchar(3) NOT NULL default 'N/A',
`cardiovascular_noctural_dyspnea_text` TEXT,
`cardiovascular_edema` varchar(3) NOT NULL default 'N/A',
`cardiovascular_edema_text` TEXT,
`cardiovascular_presyncope` varchar(3) NOT NULL default 'N/A',
`cardiovascular_presyncope_text` TEXT,
`cardiovascular_syncope` varchar(3) NOT NULL default 'N/A',
`cardiovascular_syncope_text` TEXT,
`cardiovascular_heart_murmur` varchar(3) NOT NULL default 'N/A',
`cardiovascular_heart_murmur_text` TEXT,
`cardiovascular_raynauds` varchar(3) NOT NULL default 'N/A',
`cardiovascular_raynauds_text` TEXT,
`cardiovascular_severe_varicose_veins` varchar(3) NOT NULL default 'N/A',
`cardiovascular_severe_varicose_veins_text` TEXT,
`cardiovascular_deep_vein_thrombosis` varchar(3) NOT NULL default 'N/A',
`cardiovascular_deep_vein_thrombosis_text` TEXT,
`cardiovascular_thrombophlebitis` varchar(3) NOT NULL default 'N/A',
`cardiovascular_thrombophlebitis_text` TEXT,
`respirations_cough` varchar(3) NOT NULL default 'N/A',
`respirations_cough_text` TEXT,
`respirations_sputum` varchar(3) NOT NULL default 'N/A',
`respirations_sputum_text` TEXT,
`respirations_dyspnea` varchar(3) NOT NULL default 'N/A',
`respirations_dyspnea_text` TEXT,
`respirations_wheezes` varchar(3) NOT NULL default 'N/A',
`respirations_wheezes_text` TEXT,
`respirations_rales` varchar(3) NOT NULL default 'N/A',
`respirations_rales_text` TEXT,
`respirations_labored_breathing` varchar(3) NOT NULL default 'N/A',
`respirations_labored_breathing_text` TEXT,
`respirations_hemoptysis` varchar(3) NOT NULL default 'N/A',
`respirations_hemoptysis_text` TEXT,
`gu_frequent_urination` varchar(3) NOT NULL default 'N/A',
`gu_frequent_urination_text` TEXT,
`gu_dysuria` varchar(3) NOT NULL default 'N/A',
`gu_dysuria_text` TEXT,
`gu_dyspareunia` varchar(3) NOT NULL default 'N/A',
`gu_dyspareunia_text` TEXT,
`gu_discharge` varchar(3) NOT NULL default 'N/A',
`gu_discharge_text` TEXT,
`gu_odor` varchar(3) NOT NULL default 'N/A',
`gu_odor_text` TEXT,
`gu_fertility_problems` varchar(3) NOT NULL default 'N/A',
`gu_fertility_problems_text` TEXT,
`gu_flank_pain_kidney_stone` varchar(3) NOT NULL default 'N/A',
`gu_flank_pain_kidney_stone_text` TEXT,
`gu_polyuria` varchar(3) NOT NULL default 'N/A',
`gu_polyuria_text` TEXT,
`gu_hematuria` varchar(3) NOT NULL default 'N/A',
`gu_hematuria_text` TEXT,
`gu_pyuria` varchar(3) NOT NULL default 'N/A',
`gu_pyuria_text` TEXT,
`gu_umbilical_hernia` varchar(3) NOT NULL default 'N/A',
`gu_umbilical_hernia_text` TEXT,
`gu_incontinence` varchar(3) NOT NULL default 'N/A',
`gu_incontinence_text` TEXT,
`gu_nocturia` varchar(3) NOT NULL default 'N/A',
`gu_nocturia_text` TEXT,
`gu_urinary_urgency` varchar(3) NOT NULL default 'N/A',
`gu_urinary_urgency_text` TEXT,
`gu_recurrent_utis` varchar(3) NOT NULL default 'N/A',
`gu_recurrent_utis_text` TEXT,
`gu_venereal_disease` varchar(3) NOT NULL default 'N/A',
`gu_venereal_disease_text` TEXT,
`male_gu_erectile_dysfunction` varchar(3) NOT NULL default 'N/A',
`male_gu_erectile_dysfunction_text` TEXT,
`male_gu_inguinal_hernia` varchar(3) NOT NULL default 'N/A',
`male_gu_inguinal_hernia_text` TEXT,
`male_gu_penile_lesions` varchar(3) NOT NULL default 'N/A',
`male_gu_penile_lesions_text` TEXT,
`male_gu_scrotal_mass` varchar(3) NOT NULL default 'N/A',
`male_gu_scrotal_mass_text` TEXT,
`male_gu_testicular_pain` varchar(3) NOT NULL default 'N/A',
`male_gu_testicular_pain_text` TEXT,
`male_gu_urethral_discharge` varchar(3) NOT NULL default 'N/A',
`male_gu_urethral_discharge_text` TEXT,
`male_gu_weak_urinary_stream` varchar(3) NOT NULL default 'N/A',
`male_gu_weak_urinary_stream_text` TEXT,
`female_gu_abnormal_menses` varchar(3) NOT NULL default 'N/A',
`female_gu_abnormal_menses_text` TEXT,
`female_gu_abnormal_vaginal_bleeding` varchar(3) NOT NULL default 'N/A',
`female_gu_abnormal_vaginal_bleeding_text` TEXT,
`female_gu_vaginal_discharge` varchar(3) NOT NULL default 'N/A',
`female_gu_vaginal_discharge_text` TEXT,
`gi_abdominal_pain` varchar(3) NOT NULL default 'N/A',
`gi_abdominal_pain_text` TEXT,
`gi_cramps` varchar(3) NOT NULL default 'N/A',
`gi_cramps_text` TEXT,
`gi_tenderness` varchar(3) NOT NULL default 'N/A',
`gi_tenderness_text` TEXT,
`gi_vomiting` varchar(3) NOT NULL default 'N/A',
`gi_vomiting_text` TEXT,
`gi_frequent_diarrhea` varchar(3) NOT NULL default 'N/A',
`gi_frequent_diarrhea_text` TEXT,
`gi_significant_constipation` varchar(3) NOT NULL default 'N/A',
`gi_significant_constipation_text` TEXT,
`gi_excessive_belching` varchar(3) NOT NULL default 'N/A',
`gi_excessive_belching_text` TEXT,
`gi_changed_bowel_habits` varchar(3) NOT NULL default 'N/A',
`gi_changed_bowel_habits_text` TEXT,
`gi_excessive_flatulence` varchar(3) NOT NULL default 'N/A',
`gi_excessive_flatulence_text` TEXT,
`gi_hematemesis` varchar(3) NOT NULL default 'N/A',
`gi_hematemesis_text` TEXT,
`gi_hemorrhoids` varchar(3) NOT NULL default 'N/A',
`gi_hemorrhoids_text` TEXT,
`gi_hepatitis` varchar(3) NOT NULL default 'N/A',
`gi_hepatitis_text` TEXT,
`gi_jaundice` varchar(3) NOT NULL default 'N/A',
`gi_jaundice_text` TEXT,
`gi_lactose_intolerance` varchar(3) NOT NULL default 'N/A',
`gi_lactose_intolerance_text` TEXT,
`gi_chronic_laxative_use` varchar(3) NOT NULL default 'N/A',
`gi_chronic_laxative_use_text` TEXT,
`gi_melena` varchar(3) NOT NULL default 'N/A',
`gi_melena_text` TEXT,
`gi_frequent_nausea` varchar(3) NOT NULL default 'N/A',
`gi_frequent_nausea_text` TEXT,
`gi_rectal_bleeding` varchar(3) NOT NULL default 'N/A',
`gi_rectal_bleeding_text` TEXT,
`gi_rectal_pain` varchar(3) NOT NULL default 'N/A',
`gi_rectal_pain_text` TEXT,
`gi_stool_caliber_change` varchar(3) NOT NULL default 'N/A',
`gi_stool_caliber_change_text` TEXT,
`integument_pallor` varchar(3) NOT NULL default 'N/A',
`integument_pallor_text` TEXT,
`integument_diaphoresis` varchar(3) NOT NULL default 'N/A',
`integument_diaphoresis_text` TEXT,
`integument_rash` varchar(3) NOT NULL default 'N/A',
`integument_rash_text` TEXT,
`integument_itching` varchar(3) NOT NULL default 'N/A',
`integument_itching_text` TEXT,
`integument_ulcers` varchar(3) NOT NULL default 'N/A',
`integument_ulcers_text` TEXT,
`integument_abscess` varchar(3) NOT NULL default 'N/A',
`integument_abscess_text` TEXT,
`integument_nodules` varchar(3) NOT NULL default 'N/A',
`integument_nodules_text` TEXT,
`integument_acne` varchar(3) NOT NULL default 'N/A',
`integument_acne_text` TEXT,
`integument_recurrent_boils` varchar(3) NOT NULL default 'N/A',
`integument_recurrent_boils_text` TEXT,
`integument_chronic_eczema` varchar(3) NOT NULL default 'N/A',
`integument_chronic_eczema_text` TEXT,
`integument_changing_moles` varchar(3) NOT NULL default 'N/A',
`integument_changing_moles_text` TEXT,
`integument_nail_abnormalities` varchar(3) NOT NULL default 'N/A',
`integument_nail_abnormalities_text` TEXT,
`integument_psoriasis` varchar(3) NOT NULL default 'N/A',
`integument_psoriasis_text` TEXT,
`integument_recurrent_hives` varchar(3) NOT NULL default 'N/A',
`integument_recurrent_hives_text` TEXT,
`musculoskeletal_deformity` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_deformity_text` TEXT,
`musculoskeletal_edema` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_edema_text` TEXT,
`musculoskeletal_pain` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_pain_text` TEXT,
`musculoskeletal_limited_rom` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_limited_rom_text` TEXT,
`musculoskeletal_gait` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_gait_text` TEXT,
`musculoskeletal_arthritis` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_arthritis_text` TEXT,
`musculoskeletal_neck_pain` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_neck_pain_text` TEXT,
`musculoskeletal_mid_back_pain` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_mid_back_pain_text` TEXT,
`musculoskeletal_low_back_pain` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_low_back_pain_text` TEXT,
`musculoskeletal_bursitis` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_bursitis_text` TEXT,
`musculoskeletal_gout` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_gout_text` TEXT,
`musculoskeletal_joint_injury` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_joint_injury_text` TEXT,
`musculoskeletal_joint_pain` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_joint_pain_text` TEXT,
`musculoskeletal_joint_swelling` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_joint_swelling_text` TEXT,
`musculoskeletal_myalgias` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_myalgias_text` TEXT,
`musculoskeletal_sciatica` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_sciatica_text` TEXT,
`musculoskeletal_scoliosis` varchar(3) NOT NULL default 'N/A',
`musculoskeletal_scoliosis_text` TEXT,
`hematological_anemia` varchar(3) NOT NULL default 'N/A',
`hematological_anemia_text` TEXT,
`hematological_pallor` varchar(3) NOT NULL default 'N/A',
`hematological_pallor_text` TEXT,
`hematological_bleeding_tendencies` varchar(3) NOT NULL default 'N/A',
`hematological_bleeding_tendencies_text` TEXT,
`hematological_bruising` varchar(3) NOT NULL default 'N/A',
`hematological_bruising_text` TEXT,
`endocrine_thyroid_problems` varchar(3) NOT NULL default 'N/A',
`endocrine_thyroid_problems_text` TEXT,
`endocrine_enlarged_thyroid` varchar(3) NOT NULL default 'N/A',
`endocrine_enlarged_thyroid_text` TEXT,
`endocrine_hyperglycemia` varchar(3) NOT NULL default 'N/A',
`endocrine_hyperglycemia_text` TEXT,
`endocrine_hypoglycemia` varchar(3) NOT NULL default 'N/A',
`endocrine_hypoglycemia_text` TEXT,
`endocrine_cold_intolerance` varchar(3) NOT NULL default 'N/A',
`endocrine_cold_intolerance_text` TEXT,
`endocrine_heat_intolerance` varchar(3) NOT NULL default 'N/A',
`endocrine_heat_intolerance_text` TEXT,
`endocrine_early_awakening` varchar(3) NOT NULL default 'N/A',
`endocrine_early_awakening_text` TEXT,
`endocrine_fatigue_unexplained` varchar(3) NOT NULL default 'N/A',
`endocrine_fatigue_unexplained_text` TEXT,
`endocrine_weight_gain` varchar(3) NOT NULL default 'N/A',
`endocrine_weight_gain_text` TEXT,
`endocrine_weight_loss` varchar(3) NOT NULL default 'N/A',
`endocrine_weight_loss_text` TEXT,
`endocrine_premenstrual_symptoms` varchar(3) NOT NULL default 'N/A',
`endocrine_premenstrual_symptoms_text` TEXT,
`endocrine_hair_no_change_or_no_loss` varchar(3) NOT NULL default 'N/A',
`endocrine_hair_no_change_or_no_loss_text` TEXT,
`endocrine_hot_flashes` varchar(3) NOT NULL default 'N/A',
`endocrine_hot_flashes_text` TEXT,
`lymphatic_swollen_lymph_nodes` varchar(3) NOT NULL default 'N/A',
`lymphatic_swollen_lymph_nodes_text` TEXT,
`lymphatic_swollen_extremities` varchar(3) NOT NULL default 'N/A',
`lymphatic_swollen_extremities_text` TEXT,
`psychiatric_compulsions` varchar(3) NOT NULL default 'N/A',
`psychiatric_compulsions_text` TEXT,
`psychiatric_depression` varchar(3) NOT NULL default 'N/A',
`psychiatric_depression_text` TEXT,
`psychiatric_fear` varchar(3) NOT NULL default 'N/A',
`psychiatric_fear_text` TEXT,
`psychiatric_anxiety` varchar(3) NOT NULL default 'N/A',
`psychiatric_anxiety_text` TEXT,
`psychiatric_hallucinations` varchar(3) NOT NULL default 'N/A',
`psychiatric_hallucinations_text` TEXT,
`psychiatric_loss_of_interest` varchar(3) NOT NULL default 'N/A',
`psychiatric_loss_of_interest_text` TEXT,
`psychiatric_memory_loss` varchar(3) NOT NULL default 'N/A',
`psychiatric_memory_loss_text` TEXT,
`psychiatric_mood_swings` varchar(3) NOT NULL default 'N/A',
`psychiatric_mood_swings_text` TEXT,
`psychiatric_pananoia` varchar(3) NOT NULL default 'N/A',
`psychiatric_pananoia_text` TEXT,
`psychiatric_insomnia` varchar(3) NOT NULL default 'N/A',
`psychiatric_insomnia_text` TEXT,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
