CREATE TABLE IF NOT EXISTS `form_Forms2_Cardiology` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
_recommended_subacute_bacterial_endocarditis_prophylaxis TEXT,
_amoxicillin_regimen TEXT,
_other TEXT,
_full_active_participation_with_no_restrictions TEXT,
_full_active_participation_with_moderate_exercise TEXT,
_partial_active_participation_with_light_exercise TEXT,
_limited_active_participation_with_no_exercise TEXT,
_date_of_the_last_reaction1 TEXT,
_type_of_reaction1 TEXT,
_medication_trigger2 TEXT,
_date_of_the_last_reaction2 TEXT,
_type_of_reaction2 TEXT,
_medication_trigger3 TEXT,
_date_of_the_last_reaction3 TEXT,
_type_of_reaction3 TEXT,
_medication_strength__sig1 TEXT,
_special_instructions1 TEXT,
_medication_strength__sig2 TEXT,
_special_instructions2 TEXT,
_medication_strength__sig3 TEXT,
_special_instructions3 TEXT,
_medication_strength__sig4 TEXT,
_special_instructions4 TEXT,
_medication_strength__sig5 TEXT,
_special_instructions5 TEXT,
_non_prescription_medications TEXT,
_describe_any_recent_operations_or_serious_illness TEXT,
_describe_any_physical_disability_effecting_camp_activity TEXT,
_describe_any_pertinent_findings_on_examination TEXT,
_does_applicant_have_a_history_of_dysrhythmias TEXT,
_date_of_last_episode TEXT,
_please_describe TEXT,
_has_there_been_any_recent_cardiac_concerns_medical_events TEXT,
_does_applicant_have_a_pacemaker_or_icd TEXT,
_date_of_insertion TEXT,
_reason_for_implantable_device TEXT,
_pacemaker_brand TEXT,
_pacemaker_model TEXT,
_pacemakerdate_of_last_interrogation TEXT,
_pacemaker_programmed_to TEXT,
_pacemaker_mode TEXT,
_pacemaker_lower_rate TEXT,
_pacemaker_upper_rate TEXT,
_icd_brand TEXT,
_icd_model TEXT,
_icd_date_of_last_interrogation DATE,
_has_icd_discharged_recently_and_how_often TEXT,
_date_of_transplant TEXT,
_surgeon TEXT,
_name_of_center TEXT,
_phone TEXT,
_evidence_of_rejection TEXT,
_last_cardiac_biopsy_date DATE,
_if_evidence_of_rejection_then_type_and_grade TEXT,
_height TEXT,
_weight TEXT,
_heart_rate TEXT,
_o2_saturation TEXT,
_bp_ra TEXT,
_bp_la TEXT,
_bp_rl TEXT,
_bp_ll TEXT,
_pulses_rue TEXT,
_pulses_lue TEXT,
_pulses_rle TEXT,
_pulses_lle TEXT,
_cardiovascular TEXT,
_precordial_activity TEXT,
_murmurs TEXT,
_neurological TEXT,
_lungs TEXT,
_abdomen TEXT,
_gi_gu TEXT,

PRIMARY KEY (id)
) TYPE=MyISAM;
