x-includes:
  node-version: "24"
  selenium-template: "compose-shared-selenium/docker-compose.yml"
  webserver-template: "compose-shared-apache.yml"
  database-template: "compose-shared-mysql.yml"
  mailpit-template: "compose-shared-mailpit/compose.yml"

services:
  mysql:
    image: mysql:8.0.45@sha256:64756cc92f707eb504496d774353990bcb0f6999ddf598b6ad188f2da66bd000
  openemr:
    image: openemr/openemr:flex-3.23-php-8.5@sha256:e4562b0c7d3f222ec8f72122ce00d10ffa93f559c38c00ab12c1355394c35d1c
