INSERT INTO categories select (select MAX(id) from categories) + 1, 'Imaging', '', 3, rght, rght + 1 from categories where name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
INSERT INTO categories select (select MAX(id) from categories) + 1, 'Communication', '', 3, rght, rght + 1 from categories where name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
INSERT INTO categories select (select MAX(id) from categories) + 1, 'Encounters', '', 3, rght, rght + 1 from categories where name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';

INSERT INTO categories select (select MAX(id) from categories) + 1,'External Photos','EXT',(select id from categories where name='Imaging' and parent=3),rght, rght + 1 from categories where name = 'Imaging' and parent='3';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
UPDATE categories SET rght = rght + 2 WHERE name = 'Imaging';

INSERT INTO categories select (select MAX(id) from categories) + 1,'AntSeg Photos','ANTSEG',(select id from categories where name='Imaging' and parent=3),rght, rght + 1 from categories where name = 'Imaging' and parent='3';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
UPDATE categories SET rght = rght + 2 WHERE name = 'Imaging';

INSERT INTO categories select (select MAX(id) from categories) + 1,'US/Biometry','POSTSEG',(select id from categories where name='Imaging' and parent=3),rght, rght + 1 from categories where name = 'Imaging' and parent='3';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
UPDATE categories SET rght = rght + 2 WHERE name = 'Imaging';

INSERT INTO categories select (select MAX(id) from categories) + 1,'Drawings','DRAW',(select id from categories where name='Imaging' and parent=3),rght, rght + 1 from categories where name = 'Imaging' and parent='3';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
UPDATE categories SET rght = rght + 2 WHERE name = 'Imaging';

INSERT INTO categories select (select MAX(id) from categories) + 1,'VF','NEURO',(select id from categories where name='Imaging' and parent=3),rght, rght + 1 from categories where name = 'Imaging' and parent='3';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
UPDATE categories SET rght = rght + 2 WHERE name = 'Imaging';

INSERT INTO categories select (select MAX(id) from categories) + 1,'Radiology','NEURO',(select id from categories where name='Imaging' and parent=3),rght, rght + 1 from categories where name = 'Imaging' and parent='3';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
UPDATE categories SET rght = rght + 2 WHERE name = 'Imaging';

INSERT INTO categories select (select MAX(id) from categories) + 1,'FA/ICG','POSTSEG',(select id from categories where name='Imaging' and parent=3),rght, rght + 1 from categories where name = 'Imaging' and parent='3';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
UPDATE categories SET rght = rght + 2 WHERE name = 'Imaging';

INSERT INTO categories select (select MAX(id) from categories) + 1,'OCT','POSTSEG',(select id from categories where name='Imaging' and parent=3),rght, rght + 1 from categories where name = 'Imaging' and parent='3';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
UPDATE categories SET rght = rght + 2 WHERE name = 'Imaging';

INSERT INTO categories select (select MAX(id) from categories) + 1,'Optic Disk','POSTSEG',(select id from categories where name='Imaging' and parent=3),rght, rght + 1 from categories where name = 'Imaging' and parent='3';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
UPDATE categories SET rght = rght + 2 WHERE name = 'Imaging';

INSERT INTO categories select (select MAX(id) from categories) + 1,'Fundus','POSTSEG',(select id from categories where name='Imaging' and parent=3),rght, rght + 1 from categories where name = 'Imaging' and parent='3';
UPDATE categories SET rght = rght + 2 WHERE name = 'Categories';
UPDATE categories SET rght = rght + 2 WHERE name = 'Medical Record';
UPDATE categories SET rght = rght + 2 WHERE name = 'Imaging';
UPDATE categories_seq SET id = (select MAX(id) from categories);

ALTER TABLE `list_options`  ADD `subtype` VARCHAR(255) NOT NULL;
ALTER TABLE `lists`  ADD `subtype` VARCHAR(255) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS `form_eye_mag_dispense` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`pid` bigint(20) DEFAULT NULL,
`user` varchar(255) DEFAULT NULL,
`groupname` varchar(255) DEFAULT NULL,
`authorized` tinyint(4) DEFAULT NULL,
`activity` tinyint(4) DEFAULT NULL,
`REFDATE` char(10) DEFAULT NULL,
`REFTYPE` DATETIME NULL DEFAULT NULL,
`ODSPH` char(10) DEFAULT NULL,
`ODCYL` char(10) DEFAULT NULL,
`ODAXIS` char(10) DEFAULT NULL,
`OSSPH` char(10) DEFAULT NULL,
`OSCYL` char(10) DEFAULT NULL,
`OSAXIS` char(10) DEFAULT NULL,
`ODPRISM` varchar(50) DEFAULT NULL,
`ODBASE` varchar(50) DEFAULT NULL,
`OSPRISM` varchar(50) DEFAULT NULL,
`OSBASE` varchar(50) DEFAULT NULL,
`ODADD1` varchar(50) DEFAULT NULL,
`OSADD1` varchar(50) DEFAULT NULL,
`ODADD2` varchar(50) DEFAULT NULL,
`OSADD2` varchar(50) DEFAULT NULL,
`PD` varchar(50) DEFAULT NULL,
`RXCOMMENTS` mediumtext,
`ODBRAND` varchar(50) DEFAULT NULL,
`OSBRAND` varchar(50) DEFAULT NULL,
`ODDIAM` varchar(50) DEFAULT NULL,
`ODBC` varchar(50) DEFAULT NULL,
`OSDIAM` varchar(50) DEFAULT NULL,
`OSBC` varchar(50) DEFAULT NULL,
`COMMENTS` char(10) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS `form_eye_mag` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`date` datetime DEFAULT NULL,
`pid` bigint(20) DEFAULT NULL,
`user` varchar(255) DEFAULT NULL,
`groupname` varchar(255) DEFAULT NULL,
`authorized` tinyint(4) DEFAULT NULL,
`activity` tinyint(4) DEFAULT NULL,
`Narrative` mediumtext,
`VISITTYPE` varchar(50) DEFAULT NULL,
`CC1` longtext,
`HPI1` mediumtext,
`SNOMEDCC1` longtext,
`QUALITY1` mediumtext,
`TIMING1` mediumtext,
`DURATION1` mediumtext,
`CONTEXT1` mediumtext,
`SEVERITY1` mediumtext,
`MODIFY1` mediumtext,
`ASSOCIATED1` mediumtext,
`LOCATION1` mediumtext,
`CHRONIC1`  mediumtext,
`CHRONIC2`mediumtext,
`CHRONIC3`mediumtext,
`CC2` longtext,
`HPI2` mediumtext,
`SNOMEDCC2` longtext,
`QUALITY2` mediumtext,
`TIMING2` mediumtext,
`DURATION2` mediumtext,
`CONTEXT2` mediumtext,
`SEVERITY2` mediumtext,
`MODIFY2` mediumtext,
`ASSOCIATED2` mediumtext,
`LOCATION2` mediumtext,
`CC3` longtext,
`HPI3` mediumtext,
`SNOMEDCC3` longtext,
`QUALITY3` mediumtext,
`TIMING3` mediumtext,
`DURATION3` mediumtext,
`CONTEXT3` mediumtext,
`SEVERITY3` mediumtext,
`MODIFY3` mediumtext,
`ASSOCIATED3` mediumtext,
`LOCATION3` mediumtext,
`PMH` mediumtext,
`POH` mediumtext,
`PSURGHX` mediumtext,
`EYEMEDICATIONS` mediumtext,
`MEDICATIONS` mediumtext,
`ALLERGIES` mediumtext,
`SOCHX` mediumtext,
`FH` mediumtext,
`EYESURGHX` mediumtext,
`ROSGENERAL` longtext,
`ROSHEENT` longtext,
`ROSCV` longtext,
`ROSPULM` longtext,
`ROSGI` longtext,
`ROSGU` longtext,
`ROSDERM` longtext,
`ROSNEURO` longtext,
`ROSPSYCH` longtext,
`ROSMUSCULO` longtext,
`ROSIMMUNO` longtext,
`ROSENDOCRINE` longtext,
`alert` char(3) DEFAULT 'yes',
`oriented` char(3) DEFAULT 'TPP',
`confused` char(3) DEFAULT 'nml',
`SCODVA` varchar(100) DEFAULT NULL,
`SCOSVA` varchar(100) DEFAULT NULL,
`PHODVA` varchar(100) DEFAULT NULL,
`PHOSVA` varchar(100) DEFAULT NULL,
`WODVA` varchar(100) DEFAULT NULL,
`WOSVA` varchar(100) DEFAULT NULL,
`CTLODVA` varchar(100) DEFAULT NULL,
`CTLOSVA` varchar(100) DEFAULT NULL,
`MRODVA` varchar(100) DEFAULT NULL,
`MROSVA` varchar(100) DEFAULT NULL,
`SCNEARODVA` varchar(100) DEFAULT NULL,
`SCNEAROSVA` varchar(100) DEFAULT NULL,
`WNEARODVA` varchar(10) DEFAULT NULL,
`WNEAROSVA` varchar(10) DEFAULT NULL,
`MRNEARODVA` varchar(100) DEFAULT NULL,
`MRNEAROSVA` varchar(100) DEFAULT NULL,
`GLAREODVA` varchar(100) DEFAULT NULL,
`GLAREOSVA` varchar(100) DEFAULT NULL,
`GLARECOMMENTS` varchar(100) DEFAULT NULL,
`ARODVA` char(10) DEFAULT NULL,
`AROSVA` char(10) DEFAULT NULL,
`CRODVA` varchar(100) DEFAULT NULL,
`CROSVA` varchar(50) DEFAULT NULL,
`CTLODVA1` varchar(50) DEFAULT NULL,
`CTLOSVA1` varchar(50) DEFAULT NULL,
`PAMODVA` varchar(50) DEFAULT NULL,
`PAMOSVA` varchar(50) DEFAULT NULL,
`LIODVA` varchar(50) DEFAULT NULL,
`LIOSVA` varchar(50) DEFAULT NULL,
`WODVANEAR` varchar(50) DEFAULT NULL,
`OSVANEARCC` varchar(50) DEFAULT NULL,
`NVOCHECKED` varchar(50) DEFAULT NULL,
`ADDCHECKED` varchar(50) DEFAULT NULL,
`WODSPH` varchar(100) DEFAULT NULL,
`WODCYL` varchar(100) DEFAULT NULL,
`WODAXIS` varchar(100) DEFAULT NULL,
`WODADD1` varchar(100) DEFAULT NULL,
`WODADD2` varchar(100) DEFAULT NULL,
`WOSSPH` varchar(100) DEFAULT NULL,
`WOSCYL` varchar(100) DEFAULT NULL,
`WOSAXIS` varchar(100) DEFAULT NULL,
`WOSADD1` varchar(100) DEFAULT NULL,
`WOSADD2` varchar(100) DEFAULT NULL,
`WODPRISM` varchar(50) DEFAULT NULL,
`WODBASE` varchar(50) DEFAULT NULL,
`WOSPRISM` varchar(50) DEFAULT NULL,
`WOSBASE` varchar(50) DEFAULT NULL,
`WODCYLNEAR` varchar(50) DEFAULT NULL,
`WODAXISNEAR` varchar(50) DEFAULT NULL,
`WODPRISMNEAR` varchar(50) DEFAULT NULL,
`WODBASENEAR` varchar(50) DEFAULT NULL,
`WOSCYLNEAR` varchar(50) DEFAULT NULL,
`WOSAXISNEAR` varchar(50) DEFAULT NULL,
`WOSPRISMNEAR` varchar(50) DEFAULT NULL,
`WOSBASENEAR` varchar(50) DEFAULT NULL,
`WCOMMENTS` varchar(100) DEFAULT NULL,
`RX1` tinyint(1) DEFAULT '1',
`MRODSPH` varchar(100) DEFAULT NULL,
`MRODCYL` varchar(100) DEFAULT NULL,
`MRODAXIS` varchar(100) DEFAULT NULL,
`MRODPRISM` varchar(50) DEFAULT NULL,
`MRODBASE` varchar(50) DEFAULT NULL,
`MRODADD` varchar(100) DEFAULT NULL,
`MROSSPH` varchar(100) DEFAULT NULL,
`MROSCYL` varchar(100) DEFAULT NULL,
`MROSAXIS` varchar(100) DEFAULT NULL,
`MROSPRISM` varchar(50) DEFAULT NULL,
`MROSBASE` varchar(50) DEFAULT NULL,
`MROSADD` varchar(100) DEFAULT NULL,
`MRODNEARSPHERE` varchar(50) DEFAULT NULL,
`MRODNEARCYL` varchar(100) DEFAULT NULL,
`MRODNEARAXIS` varchar(100) DEFAULT NULL,
`MRODPRISMNEAR` varchar(50) DEFAULT NULL,
`MRODBASENEAR` varchar(50) DEFAULT NULL,
`MROSNEARSHPERE` varchar(50) DEFAULT NULL,
`MROSNEARCYL` varchar(100) DEFAULT NULL,
`MROSNEARAXIS` varchar(100) DEFAULT NULL,
`MROSPRISMNEAR` varchar(50) DEFAULT NULL,
`MROSBASENEAR` varchar(50) DEFAULT NULL,
`CRODSPH` varchar(100) DEFAULT NULL,
`CRODCYL` varchar(100) DEFAULT NULL,
`CRODAXIS` varchar(100) DEFAULT NULL,
`CROSSPH` varchar(100) DEFAULT NULL,
`CROSCYL` varchar(100) DEFAULT NULL,
`CROSAXIS` varchar(100) DEFAULT NULL,
`CRCOMMENTS` varchar(255) DEFAULT NULL,
`BALANCED` char(2) DEFAULT NULL,
`DIL_RISKS` char(2) DEFAULT 'on',
`WETTYPE` VARCHAR(10) DEFAULT NULL,
`ATROPINE` VARCHAR(25) DEFAULT NULL,
`CYCLOMYDRIL` VARCHAR(25) DEFAULT NULL,
`TROPICAMIDE` VARCHAR(25) DEFAULT NULL,
`CYCLOGYL` VARCHAR(25) DEFAULT NULL,
`NEO25` VARCHAR(25) DEFAULT NULL,
`ARODSPH` char(10) DEFAULT NULL,
`ARODCYL` char(10) DEFAULT NULL,
`ARODAXIS` char(10) DEFAULT NULL,
`AROSSPH` char(10) DEFAULT NULL,
`AROSCYL` char(10) DEFAULT NULL,
`AROSAXIS` char(10) DEFAULT NULL,
`ARODADD` varchar(10) DEFAULT NULL,
`AROSADD` varchar(10) DEFAULT NULL,
`ARNEARODVA` varchar(10) DEFAULT NULL,
`ARNEAROSVA` varchar(10) DEFAULT NULL,
`ARODPRISM` varchar(20) DEFAULT NULL,
`AROSPRISM` varchar(20) DEFAULT NULL,
`CTLODSPH` varchar(50) DEFAULT NULL,
`CTLODCYL` varchar(50) DEFAULT NULL,
`CTLODAXIS` varchar(50) DEFAULT NULL,
`CTLODBC` varchar(50) DEFAULT NULL,
`CTLODDIAM` varchar(50) DEFAULT NULL,
`CTLOSSPH` varchar(50) DEFAULT NULL,
`CTLOSCYL` varchar(50) DEFAULT NULL,
`CTLOSAXIS` varchar(50) DEFAULT NULL,
`CTLOSBC` varchar(50) DEFAULT NULL,
`CTLOSDIAM` varchar(50) DEFAULT NULL,
`CTL_COMMENTS` mediumtext,
`CTLMANUFACTUREROD` varchar(50) DEFAULT NULL,
`CTLSUPPLIEROD` varchar(50) DEFAULT NULL,
`CTLBRANDOD` varchar(50) DEFAULT NULL,
`CTLMANUFACTUREROS` varchar(50) DEFAULT NULL,
`CTLSUPPLIEROS` varchar(50) DEFAULT NULL,
`CTLBRANDOS` varchar(50) DEFAULT NULL,
`CTLODADD` varchar(50) DEFAULT NULL,
`CTLOSADD` varchar(50) DEFAULT NULL,
`ODIOPAP` varchar(50) DEFAULT NULL,
`OSIOPAP` varchar(50) DEFAULT NULL,
`ODIOPTPN` varchar(10) DEFAULT NULL,
`OSIOPTPN` varchar(10) DEFAULT NULL,
`ODIOPFTN` varchar(10) DEFAULT NULL,
`OSIOPFTN` varchar(10) DEFAULT NULL,
`ODIOPPOST`varchar(10) DEFAULT NULL,
`OSIOPPOST` varchar(10) DEFAULT NULL,
`IOPTIME` time DEFAULT NULL,
`IOPPOSTTIME` time DEFAULT NULL,
`AMSLEROD` smallint(1) DEFAULT NULL,
`AMSLEROS` smallint(1) DEFAULT NULL,
`ODK1` varchar(50) DEFAULT NULL,
`ODK2` varchar(50) DEFAULT NULL,
`ODK2AXIS` varchar(50) DEFAULT NULL,
`OSK1` varchar(50) DEFAULT NULL,
`OSK2` varchar(50) DEFAULT NULL,
`OSK2AXIS` varchar(50) DEFAULT NULL,
`ODAXIALLENGTH` varchar(50) DEFAULT NULL,
`OSAXIALLENGTH` varchar(50) DEFAULT NULL,
`ODACD` varchar(50) DEFAULT NULL,
`OSACD` varchar(50) DEFAULT NULL,
`ODW2W` varchar(10) DEFAULT NULL,
`OSW2W` varchar(10) DEFAULT NULL,
`ODLT` varchar(20) DEFAULT NULL,
`OSLT` varchar(20) DEFAULT NULL,
`ODPDMeasured` varchar(25) DEFAULT NULL,
`OSPDMeasured` varchar(25) DEFAULT NULL,
`ACT` char(3) DEFAULT 'on',
`ACT1CCDIST` varchar(50) DEFAULT NULL,
`ACT2CCDIST` varchar(50) DEFAULT NULL,
`ACT3CCDIST` varchar(50) DEFAULT NULL,
`ACT4CCDIST` varchar(50) DEFAULT NULL,
`ACT5CCDIST` varchar(50) DEFAULT NULL,
`ACT6CCDIST` varchar(50) DEFAULT NULL,
`ACT7CCDIST` varchar(50) DEFAULT NULL,
`ACT8CCDIST` varchar(50) DEFAULT NULL,
`ACT9CCDIST` varchar(50) DEFAULT NULL,
`ACT10CCDIST` varchar(50) DEFAULT NULL,
`ACT11CCDIST` varchar(50) DEFAULT NULL,
`ACT1SCDIST` varchar(50) DEFAULT NULL,
`ACT2SCDIST` varchar(50) DEFAULT NULL,
`ACT3SCDIST` varchar(50) DEFAULT NULL,
`ACT4SCDIST` varchar(50) DEFAULT NULL,
`ACT5SCDIST` varchar(50) DEFAULT NULL,
`ACT6SCDIST` varchar(50) DEFAULT NULL,
`ACT7SCDIST` varchar(50) DEFAULT NULL,
`ACT8SCDIST` varchar(50) DEFAULT NULL,
`ACT9SCDIST` varchar(50) DEFAULT NULL,
`ACT10SCDIST` varchar(50) DEFAULT NULL,
`ACT11SCDIST` varchar(50) DEFAULT NULL,
`ACT1SCNEAR` varchar(50) DEFAULT NULL,
`ACT2SCNEAR` varchar(50) DEFAULT NULL,
`ACT3SCNEAR` varchar(50) DEFAULT NULL,
`ACT4SCNEAR` varchar(50) DEFAULT NULL,
`ACT5SCNEAR` varchar(50) DEFAULT NULL,
`ACT6SCNEAR` varchar(50) DEFAULT NULL,
`ACT7SCNEAR` varchar(50) DEFAULT NULL,
`ACT8SCNEAR` varchar(50) DEFAULT NULL,
`ACT9SCNEAR` varchar(50) DEFAULT NULL,
`ACT10SCNEAR` varchar(50) DEFAULT NULL,
`ACT11SCNEAR` varchar(50) DEFAULT NULL,
`ACT1CCNEAR` varchar(50) DEFAULT NULL,
`ACT2CCNEAR` varchar(50) DEFAULT NULL,
`ACT3CCNEAR` varchar(50) DEFAULT NULL,
`ACT4CCNEAR` varchar(50) DEFAULT NULL,
`ACT5CCNEAR` varchar(50) DEFAULT NULL,
`ACT6CCNEAR` varchar(50) DEFAULT NULL,
`ACT7CCNEAR` varchar(50) DEFAULT NULL,
`ACT8CCNEAR` varchar(50) DEFAULT NULL,
`ACT9CCNEAR` varchar(50) DEFAULT NULL,
`ACT10CCNEAR` varchar(50) DEFAULT NULL,
`ACT11CCNEAR` varchar(50) DEFAULT NULL,
`ODVF1` tinyint(1) DEFAULT NULL,
`ODVF2` tinyint(1) DEFAULT NULL,
`ODVF3` tinyint(1) NOT NULL,
`ODVF4` tinyint(1) NOT NULL,
`OSVF1` tinyint(1) NOT NULL,
`OSVF2` tinyint(1) NOT NULL,
`OSVF3` tinyint(1) NOT NULL,
`OSVF4` tinyint(1) NOT NULL,
`MOTILITYNORMAL` char(3) DEFAULT 'on',
`MOTILITY_RS` int(1) DEFAULT NULL,
`MOTILITY_RI` int(1) DEFAULT NULL,
`MOTILITY_RR` int(1) DEFAULT NULL,
`MOTILITY_RL` int(1) DEFAULT NULL,
`MOTILITY_LS` int(1) DEFAULT NULL,
`MOTILITY_LI` int(1) DEFAULT NULL,
`MOTILITY_LR` int(1) DEFAULT NULL,
`MOTILITY_LL` int(1) DEFAULT NULL,
`STEREOPSIS` varchar(25) DEFAULT NULL,
`ODNPA` varchar(50) DEFAULT NULL,
`OSNPA` varchar(50) DEFAULT NULL,
`VERTFUSAMPS` varchar(50) DEFAULT NULL,
`DIVERGENCEAMPS` varchar(50) DEFAULT NULL,
`NPC` varchar(10) DEFAULT NULL,
`DACCDIST` varchar(10) DEFAULT NULL,
`DACCNEAR` varchar(10) DEFAULT NULL,
`CACCDIST` varchar(10) DEFAULT NULL,
`CACCNEAR` varchar(10) DEFAULT NULL,
`ODCOLOR` char(5) DEFAULT NULL,
`OSCOLOR` char(5) DEFAULT NULL,
`ODCOINS` char(5) DEFAULT NULL,
`OSCOINS` char(5) DEFAULT NULL,
`ODREDDESAT` varchar(10) DEFAULT NULL,
`OSREDDESAT` varchar(10) DEFAULT NULL,
`OD_NEURO_DRAWING` mediumblob,
`OS_NEURO_DRAWING` mediumblob,
`NEURO_COMMENTS` mediumtext,
`RUL` mediumtext,
`LUL` mediumtext,
`RLL` mediumtext,
`LLL` mediumtext,
`RBROW` text,
`LBROW` text,
`RMCT` mediumtext,
`LMCT` mediumtext,
`RADNEXA` varchar(255) DEFAULT NULL,
`LADNEXA` varchar(255) DEFAULT NULL,
`RMRD` varchar(25) DEFAULT NULL,
`LMRD` varchar(25) DEFAULT NULL,
`RLF` varchar(50) DEFAULT NULL,
`LLF` varchar(50) DEFAULT NULL,
`RVFISSURE` varchar(10) DEFAULT NULL,
`LVFISSURE` varchar(10) DEFAULT NULL,
`ODHERTEL` varchar(10) DEFAULT NULL,
`OSHERTEL` varchar(10) DEFAULT NULL,
`HERTELBASE` varchar(50) DEFAULT NULL,
`RCAROTID` varchar(255) DEFAULT NULL,
`LCAROTID` varchar(255) DEFAULT NULL,
`RTEMPART` varchar(255) DEFAULT NULL,
`LTEMPART` varchar(255) DEFAULT NULL,
`RCNV` varchar(255) DEFAULT NULL,
`LCNV` varchar(255) DEFAULT NULL,
`RCNVII` varchar(255) DEFAULT NULL,
`LCNVII` varchar(255) DEFAULT NULL,
`OD_EXT_DRAWING` mediumblob,
`OS_EXT_DRAWING` mediumblob,
`EXT_COMMENTS` mediumtext,
`ODSCHIRMER1` varchar(255) DEFAULT NULL,
`OSSCHRIMER1` varchar(255) DEFAULT NULL,
`ODSCHRIMER2` varchar(255) DEFAULT NULL,
`OSSCHRIMER2` varchar(255) DEFAULT NULL,
`OSCONJ` mediumtext,
`ODCONJ` mediumtext,
`ODCORNEA` mediumtext,
`OSCORNEA` mediumtext,
`ODAC` mediumtext,
`OSAC` mediumtext,
`ODLENS` mediumtext,
`OSLENS` mediumtext,
`ODIRIS` mediumtext,
`OSIRIS` mediumtext,
`ODKTHICKNESS` varchar(50) DEFAULT NULL,
`OSKTHICKNESS` varchar(50) DEFAULT NULL,
`ODGONIO` varchar(50) DEFAULT NULL,
`OSGONIO` varchar(50) DEFAULT NULL,
`OD_ANTSEG_DRAWING` mediumblob,
`OS_ANTSEG_DRAWING` mediumblob,
`ANTSEG_COMMENTS` mediumtext,
`PUPIL_NORMAL` VARCHAR(2) DEFAULT '1',
`ODPUPILSIZE1` varchar(50) DEFAULT NULL,
`ODPUPILSIZE2` varchar(50) DEFAULT NULL,
`ODPUPILREACTIVITY` char(10) DEFAULT NULL,
`ODAPD` varchar(50) DEFAULT NULL,
`OSPUPILSIZE1` varchar(50) DEFAULT NULL,
`OSPUPILSIZE2` varchar(50) DEFAULT NULL,
`OSPUPILREACTIVITY` char(10) DEFAULT NULL,
`OSAPD` varchar(50) DEFAULT NULL,
`DIMODPUPILSIZE1` varchar(50) DEFAULT NULL,
`DIMODPUPILSIZE2` varchar(50) DEFAULT NULL,
`DIMODPUPILREACTIVITY` varchar(50) DEFAULT NULL,
`DIMOSPUPILSIZE1` varchar(50) DEFAULT NULL,
`DIMOSPUPILSIZE2` varchar(50) DEFAULT NULL,
`DIMOSPUPILREACTIVITY` varchar(50) DEFAULT NULL,
`PUPIL_COMMENTS` varchar(255) DEFAULT NULL,
`ODVFCONFRONTATION1` int(11) DEFAULT NULL,
`ODVFCONFRONTATION2` int(11) DEFAULT NULL,
`ODVFCONFRONTATION3` int(11) DEFAULT NULL,
`ODVFCONFRONTATION4` int(11) DEFAULT NULL,
`ODVFCONFRONTATION5` int(11) DEFAULT NULL,
`OSVFCONFRONTATION1` int(11) DEFAULT NULL,
`OSVFCONFRONTATION2` int(11) DEFAULT NULL,
`OSVFCONFRONTATION3` int(11) DEFAULT NULL,
`OSVFCONFRONTATION4` int(11) DEFAULT NULL,
`OSVFCONFRONTATION5` int(11) DEFAULT NULL,
`ODDISC` varchar(100) DEFAULT NULL,
`OSDISC` varchar(100) DEFAULT NULL,
`ODCUP` varchar(100) DEFAULT NULL,
`OSCUP` varchar(100) DEFAULT NULL,
`ODMACULA` varchar(100) DEFAULT NULL,
`OSMACULA` varchar(100) DEFAULT NULL,
`ODVESSELS` varchar(100) DEFAULT NULL,
`OSVESSELS` varchar(100) DEFAULT NULL,
`ODPERIPH` varchar(100) DEFAULT NULL,
`OSPERIPH` varchar(100) DEFAULT NULL,
`OD_RETINA_DRAWING` mediumblob,
`OS_RETINA_DRAWING` mediumblob,
`ODCMT` varchar(255) DEFAULT NULL,
`OSCMT` varchar(255) DEFAULT NULL,
`RETINA_COMMENTS` mediumtext,
`IMP` mediumtext,
`PLAN` mediumtext,
`LetterID` varchar(30) DEFAULT NULL,
`LetterTo` char(50) DEFAULT NULL,
`LetterCc1` char(50) DEFAULT NULL,
`LetterCc2` char(50) DEFAULT NULL,
`LetterCc3` char(50) DEFAULT NULL,
`LetterCc4` char(50) DEFAULT NULL,
`LetterCc5` char(50) DEFAULT NULL,
`LocationOFFICE` varchar(50) DEFAULT NULL,
`Technician` varchar(50) DEFAULT NULL,
`Doctor` varchar(50) DEFAULT NULL,
`Resource` varchar(50) DEFAULT NULL,
`UNDO_ID` INT NULL,
`LOCKED` VARCHAR( 3 ) NULL DEFAULT NULL,
`LOCKEDDATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
`LOCKEDBY` varchar(50) DEFAULT NULL,
`FINISHED` char(25) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS `form_eye_mag_prefs` (
`PEZONE` char(25) NOT NULL,
`LOCATION` char(25) NOT NULL,
`LOCATION_text` varchar(25) NOT NULL,
`id` bigint(20) NOT NULL,
`selection` char(255) NOT NULL,
`ZONE_ORDER` int(11) DEFAULT NULL,
`VALUE` char(10) DEFAULT '0',
`ordering` tinyint(4) DEFAULT NULL,
`FILL_ACTION` char(10) NOT NULL DEFAULT 'ADD' COMMENT 'ADD, REPLACE, INSERT',
UNIQUE KEY `id` (`id`,`PEZONE`,`LOCATION`,`selection`)
) ENGINE=MyISAM;

INSERT INTO `form_eye_mag_prefs` (`PEZONE`, `LOCATION`, `LOCATION_text`, `id`, `selection`, `ZONE_ORDER`, `VALUE`, `ordering`,`FILL_ACTION`) VALUES
('ANTSEG', 'c', 'CONJ', 2048, 'quiet', 11, NULL, 1,'REPLACE'),
('ANTSEG', 'c', 'CONJ', 2048, 'injection', 11, NULL, 2,'ADD'),
('ANTSEG', 'c', 'CONJ', 2048, 'pinquecula', 11, NULL, 4,'ADD'),
('ANTSEG', 'c', 'CONJ', 2048, 'papillae', 11, NULL, 3,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'clear', 12, NULL, 1,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'abrasion', 12, NULL, 2,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'MDFP dystrophy', 12, NULL, 3,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'metallic FB', 12, NULL, 4,'ADD'),
('ANTSEG', 'l', 'LENS', 2048, 'PXE', 14, NULL, 5,'ADD'),
('ANTSEG', 'a/c', 'AC', 2048, 'clear', 13, NULL, 1,'ADD'),
('ANTSEG', 'a/c', 'AC', 2048, 'F/C', 13, NULL, 3,'ADD'),
('ANTSEG', 'l', 'LENS', 2048, 'PSC', 14, NULL, 4,'ADD'),
('ANTSEG', 'a/c', 'AC', 2048, 'narrow', 13, NULL, 5,'ADD'),
('ANTSEG', 'l', 'LENS', 2048, 'NS', 14, NULL, 3,'ADD'),
('EXT', 'BROW', 'BROW', 2048, 'ptosis', 1, NULL, 1,'ADD'),
('EXT', 'BROW', 'BROW', 2048, 'rhytids', 1, NULL, 2,'ADD'),
('EXT', 'BROW', 'BROW', 2048, 'scar', 1, NULL, 4,'ADD'),
('EXT', 'UL', 'UL', 2048, 'dermatochalasis', 2, NULL, 1,'ADD'),
('EXT', 'UL', 'UL', 2048, '2mm ptosis', 2, NULL, 2,'ADD'),
('EXT', 'UL', 'UL', 2048, '3mm ptosis', 2, NULL, 3,'ADD'),
('EXT', 'UL', 'UL', 2048, 'lesion', 2, NULL, 4,'ADD'),
('EXT', 'LL', 'LL', 2048, 'lesion', 2048, NULL, 4,'ADD'),
('EXT', 'LL', 'LL', 2048, 'ectropion', 2048, NULL, 1,'ADD'),
('EXT', 'LL', 'LL', 2048, 'entropion', 2048, NULL, 2,'ADD'),
('EXT', 'LL', 'LL', 2048, 'trichiasis', 2048, NULL, 3,'ADD'),
('EXT', 'MCT', 'MCT', 2048, 'lesion', 4, NULL, 1,'ADD'),
('EXT', 'MCT', 'MCT', 2048, 'NLDO, acute', 4, NULL, 2,'ADD'),
('EXT', 'MCT', 'MCT', 2048, 'NLDO, chronic', 4, NULL, 3,'ADD'),
('ANTSEG', 'i', 'IRIS', 2048, 'post synchia', 15, NULL, 1,'ADD'),
('ANTSEG', 'i', 'IRIS', 2048, 'TI', 15, NULL, 2,'ADD'),
('ANTSEG', 'i', 'IRIS', 2048, 'PXE', 15, NULL, 3,'ADD'),
('ANTSEG', 'i', 'IRIS', 2048, 'PI', 15, NULL, 4,'ADD'),
('ANTSEG', 'c', 'CONJ', 2048, 'follicles', 11, NULL, 5,'ADD'),
('RETINA', 'p', 'PERIPH', 2048, 'NVE', 35, NULL, 5,'ADD'),
('RETINA', 'cup', 'CUP', 2048, '0.1', 31, NULL, 1,'REPLACE'),
('RETINA', 'cup', 'CUP', 2048, '0.3', 31, NULL, 2,'REPLACE'),
('RETINA', 'cup', 'CUP', 2048, '0.5', 31, NULL, 3,'REPLACE'),
('RETINA', 'cup', 'CUP', 2048, '0.8', 31, NULL, 4,'REPLACE'),
('RETINA', 'cup', 'CUP', 2048, '0.95', 31, NULL, 5,'REPLACE'),
('RETINA', 'd', 'DISC', 2048, 'notch', 32, NULL, 1,'ADD'),
('RETINA', 'd', 'DISC', 2048, 'pallor', 32, NULL, 2,'ADD'),
('RETINA', 'd', 'DISC', 2048, 'NVD', 32, NULL, 3,'ADD'),
('RETINA', 'd', 'DISC', 2048, 'at risk', 32, NULL, 4,'ADD'),
('RETINA', 'm', 'MACULA', 2048, 'hard drusen', 33, NULL, 1,'ADD'),
('RETINA', 'm', 'MACULA', 2048, 'soft drusen', 33, NULL, 2,'ADD'),
('RETINA', 'm', 'MACULA', 2048, 'PED', 33, NULL, 3,'ADD'),
('RETINA', 'm', 'MACULA', 2048, 'CSR', 33, NULL, 4,'ADD'),
('RETINA', 'v', 'VESSELS', 2048, '1:2', 34, NULL, 1,'ADD'),
('RETINA', 'v', 'VESSELS', 2048, 'BDR', 34, NULL, 2,'ADD'),
('RETINA', 'v', 'VESSELS', 2048, 'PDR', 34, NULL, 3,'ADD'),
('RETINA', 'v', 'VESSELS', 2048, 'BRVO', 34, NULL, 4,'ADD'),
('RETINA', 'p', 'PERIPH', 2048, 'PVD', 35, NULL, 1,'ADD'),
('RETINA', 'p', 'PERIPH', 2048, 'VH', 35, NULL, 2,'ADD'),
('RETINA', 'p', 'PERIPH', 2048, 'tear', 35, NULL, 3,'ADD'),
('RETINA', 'p', 'PERIPH', 2048, 'schisis', 35, NULL, 4,'ADD'),
('ANTSEG', 'c', 'CONJ', 2048, 'mucopurulence', 11, NULL, 7,'ADD'),
('ANTSEG', 'c', 'CONJ', 2048, 'pterygium', 11, NULL, 8,'ADD'),
('ANTSEG', 'c', 'CONJ', 2048, 'moderate bleb', 10, '0', 9,'ADD'),
('ANTSEG', 'c', 'CONJ', 2048, 'flat bleb', 10, '0', 8,'ADD'),
('ANTSEG', 'c', 'CONJ', 2048, 'pyogenic granuloma', 10, '0', 5,'ADD'),
('ANTSEG', 'c', 'CONJ', 2048, 'siedel negative', 10, '0', 10,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'tight wound', 11, '0', 8,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'stromal scar', 12, '0', 8,'ADD'),
('ANTSEG', 'a/c', 'AC', 2048, 'hyphema', 13, '0', 7,'ADD'),
('ANTSEG', 'a/c', 'AC', 2048, 'hypopion', 13, '0', 8,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'edema', 12, NULL, 5,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'striae', 12, NULL, 6,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'mutton fat KP', 12, NULL, 7,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'stellate KP', 12, NULL, 8,'ADD'),
('ANTSEG', 'l', 'LENS', 2048, 'PCIOL', 14, NULL, 5,'ADD'),
('ANTSEG', 'k', 'CORNEA', 2048, 'dendrite 	', 12, '0', 7,'ADD'),
('ANTSEG', 'i', 'IRIS', 2048, 'nevus', 15, NULL, 7,'ADD'),
('EXT', 'BROW', 'BROW', 2048, 'seb ker', 1, '0', 5,'ADD'),
('EXT', 'BROW', 'BROW', 2048, 'actinic keratosis', 1, '0', 6,'ADD'),
('EXT', 'BROW', 'BROW', 2048, 'BCC', 1, '0', 7,'ADD'),
('EXT', 'BROW', 'BROW', 2048, 'SCC', 1, '0', 8,'ADD'),
('EXT', 'MRD', 'MRD', 2048, '0', 1, '0', 10,'REPLACE'),
('EXT', 'MRD', 'MRD', 2048, '1', 1, '0', 11,'REPLACE'),
('EXT', 'MRD', 'MRD', 2048, '2', 1, '0', 12,'REPLACE'),
('EXT', 'MRD', 'MRD', 2048, '3', 1, '0', 13,'REPLACE'),
('EXT', 'LF', 'LF', 2048, '17', 1, '0', 14,'REPLACE'),
('EXT', 'LF', 'LF', 2048, '15', 1, '0', 15,'REPLACE'),
('EXT', 'LF', 'LF', 2048, '13', 1, '0', 16,'REPLACE'),
('EXT', 'LL', 'LL', 2048, 'fat prolapse', 2048, '0', 5,'ADD'),
('EXT', 'LL', 'LL', 2048, 'erythema', 2048, '0', 6,'ADD'),
('EXT', 'LL', 'LL', 2048, 'tenderness', 2048, '0', 9,'ADD'),
('EXT', 'LL', 'LL', 2048, 'chalazion', 2048, '0', 10,'ADD'),
('EXT', 'LL', 'LL', 2048, 'stye', 2048, '0', 11,'ADD'),
('EXT', 'UL', 'UL', 2048, 'chalazion', 2, '0', 5,'ADD'),
('EXT', 'UL', 'UL', 2048, 'stye', 2, '0', 6,'ADD'),
('PREFS', 'EXAM', 'EXAM', 2048, 'EXAM', 57, 'QP', NULL,'ADD'),
('PREFS', 'VA', 'Vision', 2048, 'RS', 51, '1', 10,'ADD'),
('PREFS', 'CR', 'Cycloplegic Refracti', 2048, 'CR', 53, '0', 3,'ADD'),
('PREFS', 'MR', 'Manifest Refraction', 2048, 'MR', 54, '0', 2,'ADD'),
('NEURO', 'Color', 'COLOR', 2048, '11/11', 20, NULL, 1,'REPLACE'),
('NEURO', 'Color', 'COLOR', 2048, '15/15', 20, NULL, 2,'REPLACEC'),
('PREFS', 'CTL', 'Contact Lens', 2048, 'CTL', 55, '0', 4,'ADD'),
('PREFS', 'ADDITIONAL', 'Additional Data Points', 2048, 'ADDITIONAL', 56, '0', 5,'ADD'),
('PREFS', 'W', 'Current RX', 2048, 'W', 52, '0', 2,'ADD'),
('PREFS', 'CLINICAL', 'CLINICAL', 2048, 'CLINICAL', 58, '0', 8,'ADD'),
('PREFS', 'REFRACTION', 'REFRACTION', 2048, '59', 8, '+', 9,'ADD'),
('PREFS', 'CYLINDER', 'CYL', 2048, 'CYL', 8, '+', 9,'ADD'),
('PREFS', 'EXT_VIEW', 'Mid Face', 2048, 'EXT_VIEW', 59, '1', NULL,'ADD'),
('PREFS', 'ANTSEG_VIEW', 'ANTSEG View', 2048, 'ANTSEG_VIEW', 60, '1', NULL,'ADD'),
('PREFS', 'RETINA_VIEW', 'Retina View', 2048, 'RETINA_VIEW', 60, '1', NULL,'ADD'),
('PREFS', 'NEURO_VIEW', 'Neuro View', 2048, 'NEURO_VIEW', 61, 'undefined', NULL,'ADD'),
('PREFS', 'VA', 'Vision', 1, 'RS', 51, '1', 1,'ADD'),
('PREFS', 'W', 'Current Rx', 1, 'W', 52, '1', 2,'ADD'),
('PREFS', 'MR', 'Manifest Refraction', 1, 'MR', 53, '0', 3,'ADD'),
('PREFS', 'CR', 'Cycloplegic Refraction', 1, 'CR', 54, '1', 4,'ADD'),
('PREFS', 'CTL', 'Contact Lens', 1, 'CTL', 55, '0', 5,'ADD'),
('PREFS', 'IOP', 'Intraocular Pressure', 1, 'IOP',64, '0', 14,'ADD'),
('PREFS', 'ADDITIONAL', 'Additional Data Points', 1, 'ADDITIONAL', 56, '0', 6,'ADD'),
('PREFS', 'CLINICAL', 'CLINICAL', 1, 'CLINICAL', 57, '', 7,'ADD'),
('PREFS', 'EXAM', 'EXAM', 1, 'EXAM', 58, 'TEXT', 8,'ADD'),
('PREFS', 'CYLINDER', 'CYL', 1, 'CYL', 59, '', 9,'ADD'),
('PREFS', 'EXT_VIEW', 'External View', 1, 'EXT_VIEW', 60, '1', 10,'ADD'),
('PREFS', 'ANTSEG_VIEW', 'Anterior Segment View', 1, 'ANTSEG_VIEW', 61, '0', 11,'ADD'),
('PREFS', 'RETINA_VIEW', 'Retina View', 1, 'RETINA_VIEW', 62, '', 12,'ADD'),
('PREFS', 'NEURO_VIEW', 'Neuro View', 1, 'NEURO_VIEW', 63, '', 13,'ADD'),
('PREFS', 'PANEL_RIGHT', 'PMSFH Panel', 1, 'PANEL_RIGHT', 64, '', 14,''),
('PREFS', 'ACT_VIEW', 'ACT View', 1, 'ACT_VIEW', 64, '', 14,'ADD');

INSERT INTO `openemr`.`list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`, `mapping`, `notes`, `codes`) VALUES ('lists', 'eye_issues_list', 'Past Ocular Issues list', '0', '0', '0', '', '', '');