<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">

    <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headMeta();
    ?>

    <!-- css files -->
    <?php foreach($this->cssFiles as $file){

        $this->headLink()->appendStylesheet($this->basePath() . $this->cssBasePath . $file);
    }
    echo $this->headLink();
    ?>

    <!-- Scripts -->
    <?php
    foreach($this->jsFiles as $file){

        $this->headScript()->appendFile($this->basePath() . $this->jsBasePath . $file);
    }
    echo  $this->headScript() ;
    ?>

</head>

<body class="container-fluid body_top " dir="<?php echo $language_direction ?>" >
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <!--button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </--button-->
            <a class="navbar-brand" href="#"><?php echo $this->title;?></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

            </ul>
            <ul class="nav navbar-nav navbar-right">

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav><!----end of nav--->

    <div class='row'>
        <div class="col-md-12">
            <?php echo $this->content; ?>
        </div>
    </div>
    <footer>

    </footer>
</div>
