<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.9.5 setup script
 * Date: Tue, 12 May 2009 00:50:16 GMT
 */


/* OpenEMR Access Control */
require_once("../interface/globals.php");
require_once("../library/acl.inc");
if (! acl_check('admin', 'database')) {
  echo "You do not have access to this resource<br>";
  exit;
}

/* OpenEMR Database Settings */
require_once("../library/sqlconf.php");


/* Servers configuration */
$i = 0;

/* Server localhost (config:openemr) [1] */
$i++;
$cfg['Servers'][$i]['host'] = $sqlconf['host'];
$cfg['Servers'][$i]['port'] = $sqlconf['port'];
$cfg['Servers'][$i]['user'] = $sqlconf['login'];
$cfg['Servers'][$i]['password'] = $sqlconf['pass'];
$cfg['Servers'][$i]['only_db'] = $sqlconf['dbase'];
/* End of servers configuration */


/* Other mods - BM 05-2009 */
$cfg['ShowCreateDb'] = false;
?>
