-- ============================================================================
-- Vietnamese Physiotherapy Module - Menu Integration Migration
-- ============================================================================
-- File: 003_add_menu_items.sql
-- Purpose: Add Vietnamese PT module to OpenEMR main navigation menu
-- Author: AI-Generated (Claude Code)
-- Date: 2025-11-22
-- Version: 1.0.0
--
-- This migration adds menu entries for the Vietnamese Physiotherapy module
-- to appear in the standard OpenEMR navigation menu structure.
--
-- AI-GENERATED CODE: This entire file was generated by Claude Code
-- ============================================================================

-- Set proper character encoding for this session
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- ============================================================================
-- 1. Add PT Module Menu Entries to list_options
-- ============================================================================

-- Create main "Physiotherapy" menu list entry
INSERT INTO `list_options` (
    `list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`,
    `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`,
    `activity`, `subtype`, `edit_options`
) VALUES (
    'lists', 'vietnamese_pt_menu', 'Vietnamese Physiotherapy Menu', 1, 0, 0,
    '', 'Vietnamese PT module menu items', '', 0, 0, 1, '', 1
) ON DUPLICATE KEY UPDATE
    `title` = 'Vietnamese Physiotherapy Menu',
    `activity` = 1;

-- Create PT Dashboard menu item
INSERT INTO `list_options` (
    `list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`,
    `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`,
    `activity`, `subtype`, `edit_options`
) VALUES (
    'vietnamese_pt_menu', 'pt_dashboard', 'PT Dashboard', 10, 0, 0,
    '/interface/main/tabs/patient_dashboard.php?tab=vietnamese_pt',
    'Vietnamese PT Dashboard - View all PT activities', '', 0, 0, 1, '', 1
) ON DUPLICATE KEY UPDATE
    `title` = 'PT Dashboard',
    `activity` = 1;

-- Create Assessment Forms menu item
INSERT INTO `list_options` (
    `list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`,
    `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`,
    `activity`, `subtype`, `edit_options`
) VALUES (
    'vietnamese_pt_menu', 'pt_assessment_forms', 'Assessment Forms', 20, 0, 0,
    '/interface/patient_file/encounter/load_form.php?formname=vietnamese_pt_assessment',
    'PT Assessment Forms - Comprehensive patient assessments', '', 0, 0, 1, '', 1
) ON DUPLICATE KEY UPDATE
    `title` = 'Assessment Forms',
    `activity` = 1;

-- Create Exercise Library menu item
INSERT INTO `list_options` (
    `list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`,
    `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`,
    `activity`, `subtype`, `edit_options`
) VALUES (
    'vietnamese_pt_menu', 'pt_exercise_library', 'Exercise Library', 30, 0, 0,
    '/interface/patient_file/encounter/load_form.php?formname=vietnamese_pt_exercise',
    'Exercise Prescription Library - Manage exercise programs', '', 0, 0, 1, '', 1
) ON DUPLICATE KEY UPDATE
    `title` = 'Exercise Library',
    `activity` = 1;

-- Create Treatment Plans menu item
INSERT INTO `list_options` (
    `list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`,
    `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`,
    `activity`, `subtype`, `edit_options`
) VALUES (
    'vietnamese_pt_menu', 'pt_treatment_plans', 'Treatment Plans', 40, 0, 0,
    '/interface/patient_file/encounter/load_form.php?formname=vietnamese_pt_treatment_plan',
    'Active Treatment Plans - Plan and track treatment', '', 0, 0, 1, '', 1
) ON DUPLICATE KEY UPDATE
    `title` = 'Treatment Plans',
    `activity` = 1;

-- Create Outcome Reports menu item
INSERT INTO `list_options` (
    `list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`,
    `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`,
    `activity`, `subtype`, `edit_options`
) VALUES (
    'vietnamese_pt_menu', 'pt_outcome_reports', 'Outcome Reports', 50, 0, 0,
    '/interface/patient_file/encounter/load_form.php?formname=vietnamese_pt_outcome',
    'Outcome Measures & Reports - Track patient progress', '', 0, 0, 1, '', 1
) ON DUPLICATE KEY UPDATE
    `title` = 'Outcome Reports',
    `activity` = 1;

-- Create PT Settings menu item
INSERT INTO `list_options` (
    `list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`,
    `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`,
    `activity`, `subtype`, `edit_options`
) VALUES (
    'vietnamese_pt_menu', 'pt_settings', 'PT Settings', 60, 0, 0,
    '/interface/super/rules.php?action=detail&id=vietnamese_pt_config',
    'Vietnamese PT Module Settings - Configure module options', '', 0, 0, 1, '', 1
) ON DUPLICATE KEY UPDATE
    `title` = 'PT Settings',
    `activity` = 1;

-- ============================================================================
-- 2. Create ACL Entries for PT Module Menu Access
-- ============================================================================

-- Add Vietnamese PT section to ACL sections if not exists
INSERT INTO `gacl_aro_sections` (`value`, `order_value`, `name`, `hidden`)
SELECT 'vietnamese_pt', 100, 'Vietnamese Physiotherapy', 0
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM `gacl_aro_sections` WHERE `value` = 'vietnamese_pt'
);

-- Add Vietnamese PT ACL groups
INSERT INTO `gacl_aro_groups` (`parent_id`, `value`, `name`, `lft`, `rgt`)
SELECT NULL, 'vietnamese_pt_full', 'Vietnamese PT - Full Access', 100, 101
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM `gacl_aro_groups` WHERE `value` = 'vietnamese_pt_full'
);

INSERT INTO `gacl_aro_groups` (`parent_id`, `value`, `name`, `lft`, `rgt`)
SELECT NULL, 'vietnamese_pt_read', 'Vietnamese PT - Read Only', 102, 103
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM `gacl_aro_groups` WHERE `value` = 'vietnamese_pt_read'
);

-- Add ACO section for Vietnamese PT
INSERT INTO `gacl_aco_sections` (`value`, `order_value`, `name`, `hidden`)
SELECT 'vietnamese_pt', 100, 'Vietnamese Physiotherapy', 0
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM `gacl_aco_sections` WHERE `value` = 'vietnamese_pt'
);

-- Add ACO entries for Vietnamese PT module features
INSERT INTO `gacl_aco` (`section_value`, `value`, `order_value`, `name`, `hidden`)
SELECT 'vietnamese_pt', 'assessments', 10, 'PT Assessments', 0
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM `gacl_aco` WHERE `section_value` = 'vietnamese_pt' AND `value` = 'assessments'
);

INSERT INTO `gacl_aco` (`section_value`, `value`, `order_value`, `name`, `hidden`)
SELECT 'vietnamese_pt', 'exercises', 20, 'Exercise Prescriptions', 0
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM `gacl_aco` WHERE `section_value` = 'vietnamese_pt' AND `value` = 'exercises'
);

INSERT INTO `gacl_aco` (`section_value`, `value`, `order_value`, `name`, `hidden`)
SELECT 'vietnamese_pt', 'treatment_plans', 30, 'Treatment Plans', 0
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM `gacl_aco` WHERE `section_value` = 'vietnamese_pt' AND `value` = 'treatment_plans'
);

INSERT INTO `gacl_aco` (`section_value`, `value`, `order_value`, `name`, `hidden`)
SELECT 'vietnamese_pt', 'outcomes', 40, 'Outcome Measures', 0
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM `gacl_aco` WHERE `section_value` = 'vietnamese_pt' AND `value` = 'outcomes'
);

INSERT INTO `gacl_aco` (`section_value`, `value`, `order_value`, `name`, `hidden`)
SELECT 'vietnamese_pt', 'reports', 50, 'PT Reports', 0
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM `gacl_aco` WHERE `section_value` = 'vietnamese_pt' AND `value` = 'reports'
);

INSERT INTO `gacl_aco` (`section_value`, `value`, `order_value`, `name`, `hidden`)
SELECT 'vietnamese_pt', 'settings', 60, 'PT Module Settings', 0
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM `gacl_aco` WHERE `section_value` = 'vietnamese_pt' AND `value` = 'settings'
);

-- ============================================================================
-- 3. Create Default ACL Permissions
-- ============================================================================

-- Grant full access to administrators
-- Note: This requires manual ACL configuration through OpenEMR Admin interface
-- The following are template entries that may need adjustment based on your ACL setup

-- ============================================================================
-- 4. Add PT Module Version Tracking
-- ============================================================================

-- Create configuration table for PT module settings
CREATE TABLE IF NOT EXISTS `pt_configuration` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `config_key` varchar(255) NOT NULL,
    `config_value` text,
    `config_type` varchar(50) DEFAULT 'string',
    `description` varchar(500),
    `last_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_by` int(11) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_config_key` (`config_key`),
    KEY `idx_updated` (`last_updated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert module version and configuration
INSERT INTO `pt_configuration` (`config_key`, `config_value`, `config_type`, `description`) VALUES
    ('module_version', '1.0.0', 'string', 'Vietnamese PT module version'),
    ('schema_version', '003', 'string', 'Database schema version'),
    ('installation_date', NOW(), 'datetime', 'Module installation date'),
    ('last_migration', '003_add_menu_items.sql', 'string', 'Last applied migration'),
    ('default_language', 'vi', 'string', 'Default language preference (vi/en)'),
    ('pain_scale_type', '0-10', 'string', 'Default pain scale type'),
    ('enable_notifications', '1', 'boolean', 'Enable PT module notifications'),
    ('enable_reports', '1', 'boolean', 'Enable outcome reports'),
    ('menu_enabled', '1', 'boolean', 'Enable PT menu in navigation')
ON DUPLICATE KEY UPDATE
    `config_value` = VALUES(`config_value`),
    `last_updated` = CURRENT_TIMESTAMP;

-- ============================================================================
-- Migration Complete
-- ============================================================================

-- Log successful migration
SELECT 'Vietnamese PT Menu Integration Migration (003) completed successfully' AS status;
SELECT COUNT(*) AS menu_items_created FROM `list_options` WHERE `list_id` = 'vietnamese_pt_menu';
SELECT COUNT(*) AS aco_entries_created FROM `gacl_aco` WHERE `section_value` = 'vietnamese_pt';

-- AI-GENERATED CODE END
