#!/bin/bash

################################################################################
# Vietnamese Physiotherapy Module - Backup Script
################################################################################
# File: backup.sh
# Purpose: Create comprehensive backups of Vietnamese PT module data
# Author: AI-Generated (Claude Code)
# Date: 2025-11-22
# Version: 1.0.0
#
# AI-GENERATED CODE: This entire script was generated by Claude Code
#
# Usage:
#   ./backup.sh [options]
#
# Options:
#   --output-dir DIR    Specify backup output directory (default: ./backups)
#   --compress          Compress backup with gzip
#   --data-only         Backup data only (no schema)
#   --schema-only       Backup schema only (no data)
#   --help              Show this help message
#
# Exit Codes:
#   0 - Success
#   1 - Error
################################################################################

set -euo pipefail

# ============================================================================
# Configuration
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_OUTPUT_DIR="${SCRIPT_DIR}/backups"
OUTPUT_DIR="$DEFAULT_OUTPUT_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
COMPRESS=false
DATA_ONLY=false
SCHEMA_ONLY=false

# Database configuration
DB_HOST="localhost"
DB_USER="openemr"
DB_PASS="openemr123!"
DB_NAME="openemr"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --compress)
            COMPRESS=true
            shift
            ;;
        --data-only)
            DATA_ONLY=true
            shift
            ;;
        --schema-only)
            SCHEMA_ONLY=true
            shift
            ;;
        --help)
            head -n 30 "$0" | grep "^#" | sed 's/^# //'
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# ============================================================================
# Color Output
# ============================================================================

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# ============================================================================
# Backup Functions
# ============================================================================

create_backup_directory() {
    mkdir -p "$OUTPUT_DIR"

    if [ ! -w "$OUTPUT_DIR" ]; then
        log_error "Output directory not writable: $OUTPUT_DIR"
        exit 1
    fi

    log_info "Backup directory: $OUTPUT_DIR"
}

backup_pt_tables() {
    local backup_file="${OUTPUT_DIR}/vietnamese_pt_tables_${TIMESTAMP}.sql"

    log_info "Backing up Vietnamese PT tables..."

    local tables=(
        "vietnamese_test"
        "vietnamese_medical_terms"
        "pt_assessments_bilingual"
        "pt_exercise_prescriptions_bilingual"
        "pt_treatment_plans_bilingual"
        "pt_outcome_measures_bilingual"
        "pt_treatment_sessions_bilingual"
        "pt_assessment_templates_bilingual"
        "pt_configuration"
    )

    local mysqldump_opts=""

    if [ "$DATA_ONLY" = true ]; then
        mysqldump_opts="--no-create-info"
    elif [ "$SCHEMA_ONLY" = true ]; then
        mysqldump_opts="--no-data"
    fi

    mysqldump -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" \
        $mysqldump_opts \
        --single-transaction \
        --quick \
        "$DB_NAME" \
        "${tables[@]}" > "$backup_file" 2>/dev/null || {
        log_warning "Some tables may not exist yet"
    }

    if [ -f "$backup_file" ]; then
        local size=$(du -h "$backup_file" | cut -f1)
        log_success "PT tables backed up: $backup_file ($size)"
        echo "$backup_file"
    else
        log_error "Failed to create PT tables backup"
        return 1
    fi
}

backup_stored_procedures() {
    local backup_file="${OUTPUT_DIR}/vietnamese_pt_procedures_${TIMESTAMP}.sql"

    log_info "Backing up stored procedures..."

    mysqldump -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" \
        --routines \
        --no-create-info \
        --no-data \
        --no-create-db \
        --skip-opt \
        "$DB_NAME" > "$backup_file" 2>/dev/null || true

    # Filter to only Vietnamese PT procedures
    grep -A 50 "get_vietnamese_term\|get_english_term" "$backup_file" > "${backup_file}.tmp" || true
    mv "${backup_file}.tmp" "$backup_file" 2>/dev/null || true

    if [ -f "$backup_file" ] && [ -s "$backup_file" ]; then
        local size=$(du -h "$backup_file" | cut -f1)
        log_success "Stored procedures backed up: $backup_file ($size)"
        echo "$backup_file"
    else
        log_warning "No stored procedures found to backup"
        rm -f "$backup_file"
        echo ""
    fi
}

backup_form_registrations() {
    local backup_file="${OUTPUT_DIR}/vietnamese_pt_forms_${TIMESTAMP}.sql"

    log_info "Backing up form registrations..."

    mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" <<SQL > "$backup_file" 2>/dev/null
-- Form registrations backup
SELECT CONCAT(
    'INSERT INTO registry (directory, name, state, category, nickname, aco_spec) VALUES (',
    QUOTE(directory), ', ',
    QUOTE(name), ', ',
    state, ', ',
    QUOTE(category), ', ',
    QUOTE(IFNULL(nickname, '')), ', ',
    QUOTE(IFNULL(aco_spec, '')),
    ') ON DUPLICATE KEY UPDATE name=VALUES(name), state=VALUES(state);'
)
FROM registry
WHERE directory LIKE 'vietnamese_pt_%';
SQL

    if [ -f "$backup_file" ] && [ -s "$backup_file" ]; then
        local size=$(du -h "$backup_file" | cut -f1)
        log_success "Form registrations backed up: $backup_file ($size)"
        echo "$backup_file"
    else
        log_warning "No form registrations found to backup"
        rm -f "$backup_file"
        echo ""
    fi
}

backup_menu_items() {
    local backup_file="${OUTPUT_DIR}/vietnamese_pt_menu_${TIMESTAMP}.sql"

    log_info "Backing up menu items..."

    mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" <<SQL > "$backup_file" 2>/dev/null
-- Menu items backup
SELECT CONCAT(
    'INSERT INTO list_options (list_id, option_id, title, seq, is_default, option_value, mapping, notes, activity) VALUES (',
    QUOTE(list_id), ', ',
    QUOTE(option_id), ', ',
    QUOTE(title), ', ',
    seq, ', ',
    is_default, ', ',
    option_value, ', ',
    QUOTE(IFNULL(mapping, '')), ', ',
    QUOTE(IFNULL(notes, '')), ', ',
    activity,
    ') ON DUPLICATE KEY UPDATE title=VALUES(title), activity=VALUES(activity);'
)
FROM list_options
WHERE list_id = 'vietnamese_pt_menu' OR option_id = 'vietnamese_pt_menu';
SQL

    if [ -f "$backup_file" ] && [ -s "$backup_file" ]; then
        local size=$(du -h "$backup_file" | cut -f1)
        log_success "Menu items backed up: $backup_file ($size)"
        echo "$backup_file"
    else
        log_warning "No menu items found to backup"
        rm -f "$backup_file"
        echo ""
    fi
}

backup_acl_configuration() {
    local backup_file="${OUTPUT_DIR}/vietnamese_pt_acl_${TIMESTAMP}.sql"

    log_info "Backing up ACL configuration..."

    mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" <<SQL > "$backup_file" 2>/dev/null
-- ACL configuration backup
SELECT * FROM gacl_aco WHERE section_value = 'vietnamese_pt';
SELECT * FROM gacl_aro_sections WHERE value = 'vietnamese_pt';
SELECT * FROM gacl_aro_groups WHERE value LIKE 'vietnamese_pt%';
SQL

    if [ -f "$backup_file" ] && [ -s "$backup_file" ]; then
        local size=$(du -h "$backup_file" | cut -f1)
        log_success "ACL configuration backed up: $backup_file ($size)"
        echo "$backup_file"
    else
        log_warning "No ACL configuration found to backup"
        rm -f "$backup_file"
        echo ""
    fi
}

create_manifest() {
    local manifest_file="${OUTPUT_DIR}/backup_manifest_${TIMESTAMP}.txt"

    log_info "Creating backup manifest..."

    cat > "$manifest_file" <<EOF
Vietnamese PT Module Backup Manifest
=====================================
Date: $(date)
Timestamp: $TIMESTAMP

Backup Contents:
EOF

    for file in "${OUTPUT_DIR}"/*_${TIMESTAMP}.*; do
        if [ -f "$file" ]; then
            local filename=$(basename "$file")
            local size=$(du -h "$file" | cut -f1)
            echo "  - $filename ($size)" >> "$manifest_file"
        fi
    done

    cat >> "$manifest_file" <<EOF

Backup Options:
  - Data Only: $DATA_ONLY
  - Schema Only: $SCHEMA_ONLY
  - Compressed: $COMPRESS

Database Information:
  - Host: $DB_HOST
  - Database: $DB_NAME

Restore Command:
  ./restore.sh --backup-timestamp $TIMESTAMP

EOF

    log_success "Manifest created: $manifest_file"
    cat "$manifest_file"
}

compress_backups() {
    if [ "$COMPRESS" = true ]; then
        log_info "Compressing backup files..."

        for file in "${OUTPUT_DIR}"/*_${TIMESTAMP}.sql; do
            if [ -f "$file" ]; then
                gzip "$file"
                log_success "Compressed: $(basename "$file").gz"
            fi
        done
    fi
}

verify_backup() {
    log_info "Verifying backup integrity..."

    local file_count=0
    local total_size=0

    for file in "${OUTPUT_DIR}"/*_${TIMESTAMP}.*; do
        if [ -f "$file" ]; then
            ((file_count++))
            local size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null)
            ((total_size+=size))
        fi
    done

    if [ $file_count -eq 0 ]; then
        log_error "No backup files created"
        return 1
    fi

    local human_size=$(numfmt --to=iec-i --suffix=B $total_size 2>/dev/null || echo "${total_size} bytes")
    log_success "Backup verified: $file_count files, $human_size total"

    return 0
}

# ============================================================================
# Main Backup Flow
# ============================================================================

main() {
    echo "================================================================================"
    echo "  Vietnamese Physiotherapy Module - Backup"
    echo "================================================================================"
    echo "  Timestamp: $TIMESTAMP"
    echo "  Output: $OUTPUT_DIR"
    echo "================================================================================"
    echo ""

    # Create backup directory
    create_backup_directory

    # Perform backups
    local backup_files=()

    backup_files+=($(backup_pt_tables))
    backup_files+=($(backup_stored_procedures))
    backup_files+=($(backup_form_registrations))
    backup_files+=($(backup_menu_items))
    backup_files+=($(backup_acl_configuration))

    # Compress if requested
    compress_backups

    # Create manifest
    create_manifest

    # Verify backup
    echo ""
    if verify_backup; then
        log_success "Backup completed successfully!"
        echo ""
        echo "Backup location: $OUTPUT_DIR"
        echo "Restore with: ./restore.sh --backup-timestamp $TIMESTAMP"
        exit 0
    else
        log_error "Backup verification failed"
        exit 1
    fi
}

# Run main backup
main

# AI-GENERATED CODE END
