#!/bin/bash

################################################################################
# Vietnamese Physiotherapy Module - Deployment Script
################################################################################
# File: deploy.sh
# Purpose: Automated deployment for production environments
# Author: AI-Generated (Claude Code)
# Date: 2025-11-22
# Version: 1.0.0
#
# AI-GENERATED CODE: This entire script was generated by Claude Code
#
# This script automates deployment of the Vietnamese PT module to production,
# staging, or development environments with proper checks and rollback support.
#
# Usage:
#   ./deploy.sh [environment] [options]
#
# Environments:
#   dev         Development environment
#   staging     Staging environment
#   production  Production environment
#
# Options:
#   --skip-tests        Skip pre-deployment tests
#   --skip-backup       Skip backup creation
#   --notify-slack URL  Send notifications to Slack webhook
#   --notify-email ADDR Send notifications to email
#   --help              Show this help message
#
# Exit Codes:
#   0 - Success
#   1 - General error
#   2 - Pre-deployment checks failed
#   3 - Deployment failed
#   4 - Rollback successful after failure
################################################################################

set -euo pipefail

# ============================================================================
# Configuration
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OPENEMR_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
LOG_FILE="${SCRIPT_DIR}/deployment_$(date +%Y%m%d_%H%M%S).log"
DEPLOY_TIMESTAMP=$(date +%Y%m%d_%H%M%S)

ENVIRONMENT="${1:-}"
SKIP_TESTS=false
SKIP_BACKUP=false
SLACK_WEBHOOK=""
NOTIFY_EMAIL=""

# Parse arguments
shift || true
while [[ $# -gt 0 ]]; do
    case $1 in
        --skip-tests)
            SKIP_TESTS=true
            shift
            ;;
        --skip-backup)
            SKIP_BACKUP=true
            shift
            ;;
        --notify-slack)
            SLACK_WEBHOOK="$2"
            shift 2
            ;;
        --notify-email)
            NOTIFY_EMAIL="$2"
            shift 2
            ;;
        --help)
            head -n 40 "$0" | grep "^#" | sed 's/^# //'
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Validate environment
if [[ ! "$ENVIRONMENT" =~ ^(dev|staging|production)$ ]]; then
    echo "Error: Invalid or missing environment"
    echo "Usage: ./deploy.sh [dev|staging|production] [options]"
    exit 1
fi

# ============================================================================
# Color Output
# ============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1" | tee -a "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a "$LOG_FILE"
}

log_deploy() {
    echo -e "${MAGENTA}[DEPLOY]${NC} $1" | tee -a "$LOG_FILE"
}

# ============================================================================
# Notification Functions
# ============================================================================

send_slack_notification() {
    local message=$1
    local status=${2:-info}

    if [ -z "$SLACK_WEBHOOK" ]; then
        return 0
    fi

    local color="good"
    case $status in
        error) color="danger" ;;
        warning) color="warning" ;;
        success) color="good" ;;
    esac

    local payload=$(cat <<EOF
{
    "attachments": [{
        "color": "$color",
        "title": "Vietnamese PT Module Deployment",
        "text": "$message",
        "fields": [
            {"title": "Environment", "value": "$ENVIRONMENT", "short": true},
            {"title": "Timestamp", "value": "$DEPLOY_TIMESTAMP", "short": true}
        ]
    }]
}
EOF
)

    curl -X POST -H 'Content-type: application/json' \
        --data "$payload" "$SLACK_WEBHOOK" &>/dev/null || true
}

send_email_notification() {
    local subject=$1
    local message=$2

    if [ -z "$NOTIFY_EMAIL" ]; then
        return 0
    fi

    echo "$message" | mail -s "$subject" "$NOTIFY_EMAIL" 2>/dev/null || {
        log_warning "Failed to send email notification"
    }
}

notify() {
    local message=$1
    local status=${2:-info}

    send_slack_notification "$message" "$status"
    send_email_notification "Vietnamese PT Deployment - $ENVIRONMENT" "$message"
}

# ============================================================================
# Environment Detection
# ============================================================================

detect_environment_config() {
    log_info "Detecting environment configuration..."

    case $ENVIRONMENT in
        production)
            DB_HOST="${PROD_DB_HOST:-localhost}"
            DB_USER="${PROD_DB_USER:-openemr}"
            DB_PASS="${PROD_DB_PASS:-openemr123!}"
            DB_NAME="${PROD_DB_NAME:-openemr}"
            ;;
        staging)
            DB_HOST="${STAGING_DB_HOST:-localhost}"
            DB_USER="${STAGING_DB_USER:-openemr}"
            DB_PASS="${STAGING_DB_PASS:-openemr123!}"
            DB_NAME="${STAGING_DB_NAME:-openemr_staging}"
            ;;
        dev)
            DB_HOST="${DEV_DB_HOST:-localhost}"
            DB_USER="${DEV_DB_USER:-openemr}"
            DB_PASS="${DEV_DB_PASS:-openemr123!}"
            DB_NAME="${DEV_DB_NAME:-openemr}"
            ;;
    esac

    log_success "Environment: $ENVIRONMENT (Database: $DB_NAME)"
}

# ============================================================================
# Pre-Deployment Checks
# ============================================================================

check_database_connection() {
    log_info "Checking database connection..."

    if mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" -e "USE $DB_NAME" 2>/dev/null; then
        log_success "Database connection verified"
        return 0
    else
        log_error "Cannot connect to database"
        return 1
    fi
}

check_git_status() {
    log_info "Checking git status..."

    cd "$OPENEMR_ROOT"

    if [ -d ".git" ]; then
        local branch=$(git rev-parse --abbrev-ref HEAD)
        local dirty=$(git status --porcelain | wc -l)

        log_info "Git branch: $branch"

        if [ "$ENVIRONMENT" = "production" ] && [ "$dirty" -gt 0 ]; then
            log_warning "Working directory has uncommitted changes"
        fi

        # Store commit hash for deployment record
        DEPLOY_COMMIT=$(git rev-parse HEAD)
        log_info "Deploy commit: $DEPLOY_COMMIT"
    else
        log_warning "Not a git repository"
        DEPLOY_COMMIT="unknown"
    fi

    return 0
}

run_pre_deployment_tests() {
    if [ "$SKIP_TESTS" = true ]; then
        log_warning "Skipping pre-deployment tests"
        return 0
    fi

    log_info "Running pre-deployment tests..."

    # Check if PHPUnit is available
    if [ -f "$OPENEMR_ROOT/vendor/bin/phpunit" ]; then
        log_info "Running Vietnamese PT tests..."

        if "$OPENEMR_ROOT/vendor/bin/phpunit" \
            --testsuite vietnamese \
            --log-junit "${SCRIPT_DIR}/test-results-${DEPLOY_TIMESTAMP}.xml" \
            >> "$LOG_FILE" 2>&1; then
            log_success "Pre-deployment tests passed"
        else
            log_error "Pre-deployment tests failed"
            return 1
        fi
    else
        log_warning "PHPUnit not found, skipping tests"
    fi

    return 0
}

run_pre_deployment_checks() {
    log_deploy "Running pre-deployment checks..."

    local failed=0

    check_database_connection || ((failed++))
    check_git_status || ((failed++))
    run_pre_deployment_tests || ((failed++))

    if [ $failed -gt 0 ]; then
        log_error "Pre-deployment checks failed"
        notify "Deployment FAILED: Pre-deployment checks failed" "error"
        return 2
    fi

    log_success "All pre-deployment checks passed"
    return 0
}

# ============================================================================
# Deployment Steps
# ============================================================================

create_deployment_backup() {
    if [ "$SKIP_BACKUP" = true ]; then
        log_warning "Skipping deployment backup"
        return 0
    fi

    log_deploy "Creating deployment backup..."

    if "${SCRIPT_DIR}/backup.sh" --output-dir "${SCRIPT_DIR}/backups" --compress >> "$LOG_FILE" 2>&1; then
        log_success "Deployment backup created"
        return 0
    else
        log_error "Failed to create deployment backup"
        return 1
    fi
}

deploy_database_migrations() {
    log_deploy "Deploying database migrations..."

    if "${SCRIPT_DIR}/INSTALL_PRODUCTION.sh" --silent >> "$LOG_FILE" 2>&1; then
        log_success "Database migrations deployed"
        return 0
    else
        log_error "Database migration deployment failed"
        return 1
    fi
}

deploy_application_files() {
    log_deploy "Deploying application files..."

    # Update Composer autoload
    cd "$OPENEMR_ROOT"

    if command -v composer &> /dev/null; then
        composer dump-autoload -o >> "$LOG_FILE" 2>&1
        log_success "Composer autoload updated"
    else
        log_warning "Composer not found"
    fi

    # Clear cache
    log_info "Clearing application cache..."
    local cache_dirs=(
        "$OPENEMR_ROOT/sites/default/documents/smarty/main"
        "$OPENEMR_ROOT/sites/default/documents/smarty/gacl"
    )

    for cache_dir in "${cache_dirs[@]}"; do
        if [ -d "$cache_dir" ]; then
            rm -rf "${cache_dir:?}"/* 2>/dev/null || true
        fi
    done

    log_success "Application files deployed"
    return 0
}

run_post_deployment_health_check() {
    log_deploy "Running post-deployment health check..."

    # Test database tables
    log_info "Verifying database tables..."
    local table_count=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
        -N -e "SELECT COUNT(*) FROM information_schema.TABLES
               WHERE TABLE_SCHEMA = '$DB_NAME'
               AND TABLE_NAME LIKE 'pt_%bilingual'" 2>/dev/null)

    if [ "$table_count" -ge 5 ]; then
        log_success "Database tables verified ($table_count tables)"
    else
        log_warning "Expected 5+ PT tables, found $table_count"
    fi

    # Test health endpoint if available
    # This requires the health check controller to be registered in routes
    # Uncomment if REST API is accessible
    # if curl -s "http://localhost/apis/default/vietnamese-pt/health" | grep -q "healthy"; then
    #     log_success "Health endpoint responding"
    # else
    #     log_warning "Health endpoint not responding"
    # fi

    log_success "Post-deployment health check completed"
    return 0
}

record_deployment() {
    log_deploy "Recording deployment..."

    local deployment_record="${SCRIPT_DIR}/deployments.log"

    cat >> "$deployment_record" <<EOF
================================================================================
Deployment: $DEPLOY_TIMESTAMP
Environment: $ENVIRONMENT
Commit: $DEPLOY_COMMIT
Status: SUCCESS
Log: $LOG_FILE
================================================================================

EOF

    # Update configuration table
    mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" <<SQL 2>/dev/null
INSERT INTO pt_configuration (config_key, config_value, config_type, description)
VALUES ('last_deployment', '$DEPLOY_TIMESTAMP', 'string', 'Last deployment timestamp')
ON DUPLICATE KEY UPDATE config_value = '$DEPLOY_TIMESTAMP', last_updated = NOW();

INSERT INTO pt_configuration (config_key, config_value, config_type, description)
VALUES ('last_deployment_commit', '$DEPLOY_COMMIT', 'string', 'Last deployment git commit')
ON DUPLICATE KEY UPDATE config_value = '$DEPLOY_COMMIT', last_updated = NOW();

INSERT INTO pt_configuration (config_key, config_value, config_type, description)
VALUES ('deployment_environment', '$ENVIRONMENT', 'string', 'Current deployment environment')
ON DUPLICATE KEY UPDATE config_value = '$ENVIRONMENT', last_updated = NOW();
SQL

    log_success "Deployment recorded"
}

# ============================================================================
# Rollback Function
# ============================================================================

rollback_deployment() {
    log_warning "Initiating deployment rollback..."

    notify "Deployment FAILED: Rolling back..." "warning"

    # Find latest backup
    local latest_backup=$(find "${SCRIPT_DIR}/backups" -name "backup_manifest_*.txt" -type f | sort -r | head -n1)

    if [ -n "$latest_backup" ]; then
        local backup_ts=$(basename "$latest_backup" | sed 's/backup_manifest_\(.*\)\.txt/\1/')
        log_info "Restoring from backup: $backup_ts"

        if "${SCRIPT_DIR}/restore.sh" --backup-timestamp "$backup_ts" >> "$LOG_FILE" 2>&1; then
            log_success "Rollback completed successfully"
            notify "Deployment rolled back successfully" "warning"
            return 4
        else
            log_error "Rollback failed"
            notify "CRITICAL: Deployment AND rollback failed" "error"
            return 1
        fi
    else
        log_error "No backup found for rollback"
        notify "CRITICAL: No backup available for rollback" "error"
        return 1
    fi
}

# ============================================================================
# Main Deployment Flow
# ============================================================================

main() {
    echo "================================================================================"
    echo "  Vietnamese Physiotherapy Module - Deployment"
    echo "================================================================================"
    echo "  Environment: $ENVIRONMENT"
    echo "  Timestamp: $DEPLOY_TIMESTAMP"
    echo "  Log: $LOG_FILE"
    echo "================================================================================"
    echo ""

    notify "Deployment started to $ENVIRONMENT" "info"

    # Detect environment
    detect_environment_config

    # Pre-deployment checks
    if ! run_pre_deployment_checks; then
        exit 2
    fi

    # Create backup
    if ! create_deployment_backup; then
        log_error "Backup creation failed. Aborting deployment."
        notify "Deployment ABORTED: Backup failed" "error"
        exit 1
    fi

    # Deploy database migrations
    if ! deploy_database_migrations; then
        log_error "Database migration deployment failed"
        rollback_deployment
        exit 3
    fi

    # Deploy application files
    if ! deploy_application_files; then
        log_error "Application file deployment failed"
        rollback_deployment
        exit 3
    fi

    # Post-deployment health check
    run_post_deployment_health_check

    # Record deployment
    record_deployment

    # Success
    echo ""
    log_success "Deployment to $ENVIRONMENT completed successfully!"
    notify "Deployment to $ENVIRONMENT completed successfully" "success"

    echo ""
    echo "Deployment Details:"
    echo "  - Environment: $ENVIRONMENT"
    echo "  - Timestamp: $DEPLOY_TIMESTAMP"
    echo "  - Commit: $DEPLOY_COMMIT"
    echo "  - Log: $LOG_FILE"
    echo ""

    exit 0
}

# Run main deployment
main

# AI-GENERATED CODE END
