CREATE TABLE IF NOT EXISTS `form_Forms3_Cardiology` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
_date TEXT,
_name TEXT,
_chief_complaint TEXT,
_wt TEXT,
_bp TEXT,
_p TEXT,
_t TEXT,
_r TEXT,
_ht TEXT,
_location TEXT,
_quality TEXT,
_severity TEXT,
_duration TEXT,
_timing TEXT,
_context TEXT,
_modifying_factors TEXT,
_signs_symptoms TEXT,
_status_of_chronic_illness TEXT,
_systemic_positive TEXT,
_systemic_negative TEXT,
_ent_positive TEXT,
_ent_negative TEXT,
_eyes_positive TEXT,
_eyes_negative TEXT,
_lymph_positive TEXT,
_lymph_negative TEXT,
_resp_positive TEXT,
_resp_negative TEXT,
_cv_positive TEXT,
_cv_negative TEXT,
_gi_positive TEXT,
_gi_negative TEXT,
_gu_positive TEXT,
_gu_negative TEXT,
_skin_positive TEXT,
_skin_negative TEXT,
_ms_positive TEXT,
_ms_negative TEXT,
_psych_positive TEXT,
_psych_negative TEXT,
_all_other_ros_negative_ TEXT,
_past_famiy_social_history TEXT,
_ph_no_change_since TEXT,
_fh_no_change_since TEXT,
_sh_no_change_since TEXT,
examination TEXT,

PRIMARY KEY (id)
) TYPE=MyISAM;
