<?php
/**
 * interface/modules/zend_modules/module/Documents/view/layout/layout.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Basil PT <basil@zhservices.com>
 * @copyright Copyright (c) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
echo $this->doctype();
use OpenEMR\Core\Header;
?>
<html lang="en" ng-app="documentsApp">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate()->xl('Welcome to OpenEMR'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php Header::setupHeader(['angular', 'modernizr']); ?>
        <link rel="stylesheet" href="<?php $this->basePath() . '/css/' . $GLOBALS['zhemr']['default_theme']. '/documents.css' ?>" />
        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/file_uploader.css')
        ->prependStylesheet($this->basePath() . '/css/layout.css')
        ->prependStylesheet($this->basePath() . '/css/skeleton.css')
        ->prependStylesheet($this->basePath() . '/css/base.css'); ?>
    </head>
    <body class="body_top">
            <div class="container">
                <div class="row">
          <div class="fullwidth">
            <div class="container" ng-controller="documentsController">
            <?php echo $this->content; ?>
            </div>
          </div>
                </div>
            <?php echo $this->inlineScript()->prependFile($this->basePath() . '/js/scripts/file_uploader.js')
                                      ->prependFile($this->basePath() . '/js/controller/documentsController.js')
                                                                          ->prependFile($this->basePath() . '/js/scripts/documents.js'); ?>
          <?php echo $this->javascriptGlobals(); ?>
    </body>
</html>
