CREATE TABLE IF NOT EXISTS `form_ankleinjury` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
ankle_date_of_injuary datetime default NULL,
ankle_work_related varchar(255),
ankle_foot varchar(255),
ankle_severity_of_pain varchar(255),
ankle_significant_swelling varchar(255),
ankle_onset_of_swelling varchar(255),
ankle_how_did_injury_occur longtext,
ankle_ottawa_bone_tenderness varchar(255),
ankle_able_to_bear_weight_steps varchar(255),
ankle_x_ray_interpretation varchar(255),
ankle_additional_x_ray_notes longtext,
ankle_diagnosis1 varchar(255),
ankle_diagnosis2 varchar(255),
ankle_diagnosis3 varchar(255),
ankle_diagnosis4 varchar(255),
ankle_plan longtext,
ankle_additional_diagnisis longtext,
PRIMARY KEY (id)
) ENGINE=InnoDB;
