CREATE TABLE IF NOT EXISTS form_sketchpad (
	id			BIGINT(20) NOT NULL AUTO_INCREMENT,
	date		DATETIME DEFAULT NULL comment 'last modified date',
	pid			BIGINT(20) NOT NULL DEFAULT 0,
	user		VARCHAR(255) DEFAULT NULL,
	groupname 	VARCHAR(255) DEFAULT NULL,
	authorized	TINYINT(4) DEFAULT NULL,
	activity	TINYINT(4) DEFAULT NULL,
	background	VARCHAR(128) DEFAULT NULL,
	output		MEDIUMTEXT DEFAULT NULL,
	comments	MEDIUMTEXT DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1;
