CREATE TABLE IF NOT EXISTS `form_ext_ros` (
	`id` bigint(20) NOT NULL auto_increment,
	`date` datetime DEFAULT NULL,
	`pid` bigint(20),
	`user` VARCHAR(255) DEFAULT NULL,
	`groupname` VARCHAR(255) DEFAULT NULL,
	`authorized` TINYINT(4),
	`activity` TINYINT(4),

	`ee1_link_id` bigint(20),
	`ee1_link_name` VARCHAR(255) DEFAULT NULL,
	`ee1_rs_non_contrib` TINYINT(1),
	`ee1_rs_adopted` TINYINT(1),

	`ee1_rs_const_hpi` TINYINT(1),
	`ee1_rs_fev` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_fev_nt` TEXT DEFAULT NULL,
	`ee1_rs_loss` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_loss_nt` TEXT DEFAULT NULL,
	`ee1_rs_gain` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_gain_nt` TEXT DEFAULT NULL,

/* Eyes */
	`ee1_rs_eyes_hpi` TINYINT(1),
	`ee1_rs_blr` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_blr_nt` TEXT DEFAULT NULL,
	`ee1_rs_dbl` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_dbl_nt` TEXT DEFAULT NULL,
	`ee1_rs_vis` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_vis_nt` TEXT DEFAULT NULL,
	`ee1_rs_blind` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_blind_nt` TEXT DEFAULT NULL,
	`ee1_rs_mac` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_mac_nt` TEXT DEFAULT NULL,
	`ee1_rs_vpain` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_vpain_nt` TEXT DEFAULT NULL,
	`ee1_rs_vloss` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_vloss_nt` TEXT DEFAULT NULL,
	`ee1_rs_dry` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_dry_nt` TEXT DEFAULT NULL,

/* Immunologic */
	`ee1_rs_imm_hpi` TINYINT(1),
	`ee1_rs_hay` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hay_nt` TEXT DEFAULT NULL,
	`ee1_rs_med` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_med_nt` TEXT DEFAULT NULL,

/* Neurologic */
	`ee1_rs_neuro_hpi` TINYINT(1),
	`ee1_rs_diz` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_diz_nt` TEXT DEFAULT NULL,
	`ee1_rs_sz` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_sz_nt` TEXT DEFAULT NULL,
	`ee1_rs_numb` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_numb_nt` TEXT DEFAULT NULL,
	`ee1_rs_strength` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_strength_nt` TEXT DEFAULT NULL,
	`ee1_rs_tremor` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_tremor_nt` TEXT DEFAULT NULL,
	`ee1_rs_dysarthria` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_dysarthria_nt` TEXT DEFAULT NULL,
	`ee1_rs_head` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_head_nt` TEXT DEFAULT NULL,

/* Endocrine */
	`ee1_rs_endocrine_hpi` TINYINT(1),
	`ee1_rs_hair` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hair_nt` TEXT DEFAULT NULL,
	`ee1_rs_diabetes` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_diabetes_nt` TEXT DEFAULT NULL,
	`ee1_rs_thyroid` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_thyroid_nt` TEXT DEFAULT NULL,
	`ee1_rs_tired` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_tired_nt` TEXT DEFAULT NULL,
	`ee1_rs_dysphagia` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_dysphagia_nt` TEXT DEFAULT NULL,
	`ee1_rs_odyno` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_odyno_nt` TEXT DEFAULT NULL,
	`ee1_rs_voice` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_voice_nt` TEXT DEFAULT NULL,
	`ee1_rs_polyuria` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_polyuria_nt` TEXT DEFAULT NULL,
	`ee1_rs_polydipsia` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_polydipsia_nt` TEXT DEFAULT NULL,
	`ee1_rs_nightmare` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_nightmare_nt` TEXT DEFAULT NULL,
	`ee1_rs_nightswt` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_nightswt_nt` TEXT DEFAULT NULL,
	`ee1_rs_hairloss` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hairloss_nt` TEXT DEFAULT NULL,
	`ee1_rs_brittle` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_brittle_nt` TEXT DEFAULT NULL,
	`ee1_rs_hotcold` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hotcold_nt` TEXT DEFAULT NULL,
	`ee1_rs_sweat` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_sweat_nt` TEXT DEFAULT NULL,
	`ee1_rs_neck` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_neck_nt` TEXT DEFAULT NULL,
	`ee1_rs_acne` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_acne_nt` TEXT DEFAULT NULL,
	`ee1_rs_menses` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_menses_nt` TEXT DEFAULT NULL,
	`ee1_rs_hirs` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hirs_nt` TEXT DEFAULT NULL,
	`ee1_rs_thirst` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_thirst_nt` TEXT DEFAULT NULL,

/* Gastrointestinal */
	`ee1_rs_gastro_hpi` TINYINT(1),
	`ee1_rs_naus` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_naus_nt` TEXT DEFAULT NULL,
	`ee1_rs_vomit` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_vomit_nt` TEXT DEFAULT NULL,
	`ee1_rs_ref` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_ref_nt` TEXT DEFAULT NULL,
	`ee1_rs_anal_p` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_anal_p_nt` TEXT DEFAULT NULL,
	`ee1_rs_abd_p` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_abd_p_nt` TEXT DEFAULT NULL,
	`ee1_rs_jaun` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_jaun_nt` TEXT DEFAULT NULL,
	`ee1_rs_bow` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_bow_nt` TEXT DEFAULT NULL,
	`ee1_rs_dia` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_dia_nt` TEXT DEFAULT NULL,
	`ee1_rs_const` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_const_nt` TEXT DEFAULT NULL,
	`ee1_rs_melena` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_melena_nt` TEXT DEFAULT NULL,
	`ee1_rs_hematemesis` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hematemesis_nt` TEXT DEFAULT NULL,
	`ee1_rs_hematochezia` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hematochezia_nt` TEXT DEFAULT NULL,

/* Cardiovascular */
	`ee1_rs_cardio_hpi` TINYINT(1),
	`ee1_rs_cpain` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_cpain_nt` TEXT DEFAULT NULL,
	`ee1_rs_breathe` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_breathe_nt` TEXT DEFAULT NULL,
	`ee1_rs_swell` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_swell_nt` TEXT DEFAULT NULL,
	`ee1_rs_palp` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_palp_nt` TEXT DEFAULT NULL,
	`ee1_rs_jaw` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_jaw_nt` TEXT DEFAULT NULL,
	`ee1_rs_arm` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_arm_nt` TEXT DEFAULT NULL,
	`ee1_rs_back` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_back_nt` TEXT DEFAULT NULL,
	`ee1_rs_acute` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_acute_nt` TEXT DEFAULT NULL,

/* Respiratory */
	`ee1_rs_resp_hpi` TINYINT(1),
	`ee1_rs_whz` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_whz_nt` TEXT DEFAULT NULL,
	`ee1_rs_shrt` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_shrt_nt` TEXT DEFAULT NULL,
	`ee1_rs_cgh` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_cgh_nt` TEXT DEFAULT NULL,
	`ee1_rs_slp` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_slp_nt` TEXT DEFAULT NULL,
	`ee1_rs_spu` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_spu_nt` TEXT DEFAULT NULL,
	`ee1_rs_dys` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_dys_nt` TEXT DEFAULT NULL,
	`ee1_rs_snore` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_snore_nt` TEXT DEFAULT NULL,
	`ee1_rs_hemoptysis` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hemoptysis_nt` TEXT DEFAULT NULL,

/* Musculoskeletal */
	`ee1_rs_msk_hpi` TINYINT(1),
	`ee1_rs_jnt` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_jnt_nt` TEXT DEFAULT NULL,
	`ee1_rs_stiff` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_stiff_nt` TEXT DEFAULT NULL,
	`ee1_rs_wk` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_wk_nt` TEXT DEFAULT NULL,
	`ee1_rs_mpain` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_mpain_nt` TEXT DEFAULT NULL,
	`ee1_rs_ply_up` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_ply_up_nt` TEXT DEFAULT NULL,
	`ee1_rs_ply_dn` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_ply_dn_nt` TEXT DEFAULT NULL,

/* Ear/Nose/Throat/Mouth */
	`ee1_rs_ent_hpi` TINYINT(1),
	`ee1_rs_sore` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_sore_nt` TEXT DEFAULT NULL,
	`ee1_rs_sin` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_sin_nt` TEXT DEFAULT NULL,
	`ee1_rs_hear` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hear_nt` TEXT DEFAULT NULL,
	`ee1_rs_tin` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_tin_nt` TEXT DEFAULT NULL,
	`ee1_rs_hot` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hot_nt` TEXT DEFAULT NULL,
	`ee1_rs_lymph` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_lymph_nt` TEXT DEFAULT NULL,
	`ee1_rs_mass` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_mass_nt` TEXT DEFAULT NULL,
	`ee1_rs_epain` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_epain_nt` TEXT DEFAULT NULL,

/* Lymphatic */
	`ee1_rs_lymph_hpi` TINYINT(1),
	`ee1_rs_swl` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_swl_nt` TEXT DEFAULT NULL,
	`ee1_rs_brse` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_brse_nt` TEXT DEFAULT NULL,
	`ee1_rs_nose` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_nose_nt` TEXT DEFAULT NULL,
	`ee1_rs_trait` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_trait_nt` TEXT DEFAULT NULL,

/* Psychiatric */
	`ee1_rs_psych_hpi` TINYINT(1),
	`ee1_rs_dep` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_dep_nt` TEXT DEFAULT NULL,
	`ee1_rs_anx` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_anx_nt` TEXT DEFAULT NULL,
	`ee1_rs_sui` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_sui_nt` TEXT DEFAULT NULL,
	`ee1_rs_hom` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hom_nt` TEXT DEFAULT NULL,

/* Skin */
	`ee1_rs_skin_hpi` TINYINT(1),
	`ee1_rs_rash` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_rash_nt` TEXT DEFAULT NULL,
	`ee1_rs_ml` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_ml_nt` TEXT DEFAULT NULL,

/* Breasts */
	`ee1_rs_breast_hpi` TINYINT(1),
	`ee1_rs_nip` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_nip_nt` TEXT DEFAULT NULL,
	`ee1_rs_lmp` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_lmp_nt` TEXT DEFAULT NULL,
	`ee1_rs_skn` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_skn_nt` TEXT DEFAULT NULL,

/* Genitourinary */
	`ee1_rs_gen_hpi` TINYINT(1),
	`ee1_rs_leak` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_leak_nt` TEXT DEFAULT NULL,
	`ee1_rs_urine_burn` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_urine_burn_nt` TEXT DEFAULT NULL,
	`ee1_rs_urine_freq` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_urine_freq_nt` TEXT DEFAULT NULL,
	`ee1_rs_ret` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_ret_nt` TEXT DEFAULT NULL,
	`ee1_rs_vag` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_vag_nt` TEXT DEFAULT NULL,
	`ee1_rs_bleed` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_bleed_nt` TEXT DEFAULT NULL,
	`ee1_rs_pp` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_pp_nt` TEXT DEFAULT NULL,
	`ee1_rs_sex` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_sex_nt` TEXT DEFAULT NULL,
	`ee1_rs_fib` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_fib_nt` TEXT DEFAULT NULL,
	`ee1_rs_inf` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_inf_nt` TEXT DEFAULT NULL,
	`ee1_rs_urg` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_urg_nt` TEXT DEFAULT NULL,
	`ee1_rs_weaks` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_weaks_nt` TEXT DEFAULT NULL,
	`ee1_rs_drib` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_drib_nt` TEXT DEFAULT NULL,
	`ee1_rs_ed` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_ed_nt` TEXT DEFAULT NULL,
	`ee1_rs_low` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_low_nt` TEXT DEFAULT NULL,
	`ee1_rs_libido` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_libido_nt` TEXT DEFAULT NULL,
	`ee1_rs_hematuria` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_hematuria_nt` TEXT DEFAULT NULL,
	`ee1_rs_nocturia` VARCHAR(1) DEFAULT NULL,
	`ee1_rs_nocturia_nt` TEXT DEFAULT NULL,
	`ee1_rs_nt` TEXT,

PRIMARY KEY (`id`)
) ENGINE=MyISAM;

