CREATE TABLE IF NOT EXISTS `form_dashboard` (
	`id` BIGINT(20) NOT NULL auto_increment,
	`date` DATETIME DEFAULT NULL,
	`pid` BIGINT(20),
	`user` VARCHAR(255) DEFAULT NULL,
	`groupname` VARCHAR(255) DEFAULT NULL,
	`authorized` TINYINT(4),
	`activity` TINYINT(4),

/* Patient Info */
	`db_form_dt` DATE,
	`db_DOB` DATE,
	`db_race` VARCHAR(64) DEFAULT NULL,
	`db_status` VARCHAR(32) DEFAULT NULL,
	`db_occupation` VARCHAR(64) DEFAULT NULL,
	`db_wmt_education` VARCHAR(64) DEFAULT NULL,
	`db_language` VARCHAR(64) DEFAULT NULL,
	`db_ethnicity` VARCHAR(64) DEFAULT NULL,
	`db_wmt_partner_name` VARCHAR(128) DEFAULT NULL,
	`db_wmt_partner_ph` VARCHAR(32) DEFAULT NULL,
	`db_wmt_father_name` VARCHAR(128) DEFAULT NULL,
	`db_wmt_father_ph` VARCHAR(32) DEFAULT NULL,
	`db_street` VARCHAR(128) DEFAULT NULL,
	`db_city` VARCHAR(32) DEFAULT NULL,
	`db_state` VARCHAR(16) DEFAULT NULL,
	`db_postal_code` VARCHAR(16) DEFAULT NULL,
	`db_phone_home` VARCHAR(32) DEFAULT NULL,
	`db_phone_biz` VARCHAR(32) DEFAULT NULL,
	`db_phone_cell` VARCHAR(32) DEFAULT NULL,
	`db_email` VARCHAR(64) DEFAULT NULL,
	`db_carrier_id` VARCHAR(128) DEFAULT NULL,
	`db_policy` VARCHAR(64) DEFAULT NULL,
	`db_emergency_contact` VARCHAR(64) DEFAULT NULL,
	`db_phone_contact` VARCHAR(32) DEFAULT NULL,
	`db_hpi` TEXT DEFAULT NULL,
	`db_cc` TEXT DEFAULT NULL,

/* Vitals */
	`db_height` VARCHAR(16) DEFAULT NULL,
	`db_weight` VARCHAR(16) DEFAULT NULL,
	`db_BMI` float(4,1) DEFAULT NULL,
	`db_BMI_status` VARCHAR(64) DEFAULT NULL,
	`db_bps` VARCHAR(16) DEFAULT NULL,
	`db_bpd` VARCHAR(16) DEFAULT NULL,
	`db_pulse` VARCHAR(16) DEFAULT NULL,
	`db_HCG` VARCHAR(16) DEFAULT NULL,
	`db_hear_screen` VARCHAR(1) DEFAULT NULL,
	`db_hearl_result` VARCHAR(1) DEFAULT NULL,
	`db_hearr_result` VARCHAR(1) DEFAULT NULL,
	
/* Social History */
	`db_alcohol` VARCHAR(64) DEFAULT NULL,
	`db_alcohol_note` VARCHAR(255) DEFAULT NULL,
	`db_alcohol_dt` VARCHAR(16) DEFAULT NULL,
	`db_drug_use` VARCHAR(64) DEFAULT NULL,
	`db_drug_note` TEXT DEFAULT NULL,
	`db_drug_dt` VARCHAR(16) DEFAULT NULL,
	`db_smoking` TEXT DEFAULT NULL,
	`db_smoking_desc` VARCHAR(4) DEFAULT NULL,
	`db_smoking_dt` VARCHAR(16) DEFAULT NULL,
	`db_smoking_status` VARCHAR(32) DEFAULT NULL,
	`db_bc_chc` VARCHAR(4) DEFAULT NULL,
	`db_bc` TEXT DEFAULT NULL,
	`db_sex_active` VARCHAR(1) DEFAULT NULL,
	`db_sex_nt` TEXT DEFAULT NULL,
	`db_sex_act_nt` TEXT DEFAULT NULL,
	`db_pflow` VARCHAR(1) DEFAULT NULL,
	`db_pflow_dur` VARCHAR(32) DEFAULT NULL,
	`db_pfreq` VARCHAR(1) DEFAULT NULL,	
	`db_pfreq_days` VARCHAR(32) DEFAULT NULL,
	`db_ptext` TEXT DEFAULT NULL,
	`db_other_nt` TEXT DEFAULT NULL,
	`db_wellness_nt` TEXT DEFAULT NULL,
	`db_group_b_strep` VARCHAR(1) DEFAULT NULL,	
	`db_latex_allergy` VARCHAR(4) DEFAULT NULL,	
	`db_drug_allergy` TEXT DEFAULT NULL,	

/* Medical history */
	`db_last_colon` VARCHAR(32) DEFAULT NULL,
	`db_last_bone` VARCHAR(32) DEFAULT NULL,
	`db_last_chol` VARCHAR(32) DEFAULT NULL,
	`db_last_lipid` VARCHAR(32) DEFAULT NULL,
	`db_last_lipo` VARCHAR(32) DEFAULT NULL,
	`db_last_tri` VARCHAR(32) DEFAULT NULL,
	`db_last_hepc` VARCHAR(32) DEFAULT NULL,
	`db_last_pap` VARCHAR(32) DEFAULT NULL,
	`db_last_mamm` VARCHAR(32) DEFAULT NULL,
	`db_mam_law` VARCHAR(4) DEFAULT NULL,
	`db_last_ww` VARCHAR(32) DEFAULT NULL,
	`db_last_mp` VARCHAR(32) DEFAULT NULL,
	`db_last_rectal` VARCHAR(32) DEFAULT NULL,
	`db_last_psa` VARCHAR(32) DEFAULT NULL,
	`db_age_men` VARCHAR(32) DEFAULT NULL,
	`db_last_db_foot` VARCHAR(32) DEFAULT NULL,
	`db_last_db_eye` VARCHAR(32) DEFAULT NULL,
	`db_last_db_screen` VARCHAR(32) DEFAULT NULL,
	`db_last_db_dbsmt` VARCHAR(32) DEFAULT NULL,
	`db_last_hpv` VARCHAR(32) DEFAULT NULL,
	`db_hpv` VARCHAR(4) DEFAULT NULL,
	`db_last_urine_alb` VARCHAR(32) DEFAULT NULL,
	`db_last_sigmoid` VARCHAR(32) DEFAULT NULL,
	`db_last_fecal` VARCHAR(32) DEFAULT NULL,
	`db_last_col_scrn` VARCHAR(32) DEFAULT NULL,
	`db_last_barium` VARCHAR(32) DEFAULT NULL,
	`db_last_glaucoma` VARCHAR(32) DEFAULT NULL,
	`db_last_hgba1c` VARCHAR(32) DEFAULT NULL,
	`db_last_hgba1c_val` VARCHAR(32) DEFAULT NULL,
	`db_last_ekg` VARCHAR(32) DEFAULT NULL,
	`db_last_pft` VARCHAR(32) DEFAULT NULL,
	`db_last_dental` VARCHAR(32) DEFAULT NULL,
	`db_last_dental_nt` TEXT DEFAULT NULL,
	`db_last_hear` VARCHAR(32) DEFAULT NULL,
	`db_left_ear` VARCHAR(4) DEFAULT NULL,
	`db_right_ear` VARCHAR(4) DEFAULT NULL,
	`db_hear_nt` TEXT DEFAULT NULL,

/* Misc */
	`db_fh_nt` TEXT DEFAULT NULL,
	`db_fh_non_contrib` TINYINT(1) DEFAULT 0,
	`db_fh_adopted` TINYINT(1) DEFAULT 0,
	`db_fh_extra_yes` TEXT DEFAULT NULL,
	`db_fh_extra_no` TEXT DEFAULT NULL,
	`db_birth_nt` TEXT DEFAULT NULL,
	`db_pregnancies` TINYINT(2) DEFAULT 0,
	`db_deliveries` TINYINT(2) DEFAULT 0,
	`db_live_births` TINYINT(2) DEFAULT 0,
	`db_contact_email` VARCHAR(128) DEFAULT NULL,
	`db_contact_relationship` VARCHAR(64) DEFAULT NULL,
	`db_contact_cell` VARCHAR(32) DEFAULT NULL,
	`db_place_of_birth` VARCHAR(64) DEFAULT NULL,
	`db_adopted` VARCHAR(1) DEFAULT NULL,
	`db_brothers` VARCHAR(2) DEFAULT NULL,
	`db_sisters` VARCHAR(2) DEFAULT NULL,
	`db_birth_order` VARCHAR(2) DEFAULT NULL,
	`db_birth_of` VARCHAR(2) DEFAULT NULL,
	`db_sex_orient` VARCHAR(16) DEFAULT NULL,
	`db_sex_orient_nt` TEXT DEFAULT NULL,
	`db_sex_sti` VARCHAR(16) DEFAULT NULL,
	`db_sex_sti_nt` TEXT DEFAULT NULL,
	`db_num_marriages` VARCHAR(2) DEFAULT NULL,
	`db_num_divorces` VARCHAR(2) DEFAULT NULL,
	`db_num_children` VARCHAR(2) DEFAULT NULL,
	`db_pap_nt` TEXT DEFAULT NULL,
	`db_pap_hist_nt` TEXT DEFAULT NULL,

/* Pediatric Diet info */
	`db_ped_diet_f` TINYINT(1),
	`db_ped_diet_b` TINYINT(1),
	`db_ped_diet_o` TINYINT(1),
	`db_ped_diet_nt` TEXT DEFAULT NULL,
	`db_ped_diet_tube` VARCHAR(2) DEFAULT NULL,
	`db_ped_diet_ttype` VARCHAR(128) DEFAULT NULL,
	`db_ped_diet_tsize` VARCHAR(64) DEFAULT NULL,
	`db_ped_diet_chc` VARCHAR(64) DEFAULT NULL,
	`db_ped_diet_amt` VARCHAR(64) DEFAULT NULL,
	`db_ped_diet_rate` VARCHAR(64) DEFAULT NULL,
	`db_ped_diet_special` TEXT DEFAULT NULL,
	`db_ped_diet_other` TEXT DEFAULT NULL,

/* Hep C Questionnaire */
	`db_hepc_test` TINYINT(1),
	`db_hepc_risk_factors` TEXT DEFAULT NULL,
	`db_hepc_other` TEXT DEFAULT NULL,
	`db_hepc_nt` TEXT DEFAULT NULL,
	`db_hepc_method_ph` TINYINT(1),
	`db_hepc_phone`	VARCHAR(16) DEFAULT NULL,
	`db_hepc_callback` TINYINT(1),
	`db_hepc_method_ml` TINYINT(1),
	`db_hepc_addr` TEXT DEFAULT NULL,
	`db_hepc_dt` VARCHAR(32) DEFAULT NULL,
	`db_hepc_usr` bigint(20),
	`db_hepc_pt_dt` VARCHAR(16) DEFAULT NULL,
	`db_hepc_pt_ssn` VARCHAR(16) DEFAULT NULL,
	`db_hepc_tester_dt` VARCHAR(16) DEFAULT NULL,

PRIMARY KEY (id)
) ENGINE=MyISAM;

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "One_To_Four", "One To Four", "0", "1", "Multi-Use List"), ("One_To_Four", "1", "1", "10", "0", ""),("One_To_Four", "2", "2", "20", "0", ""),("One_To_Four", "3", "3", "30", "0", ""),("One_To_Four", "4", "4", "40", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Yes_No", "Yes/No", "0", "1", "Multi-Use List"), ("Yes_No", "y", "Yes", "10", "0", ""),("Yes_No", "n", "No", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Caffeine_Use", "Caffeine Use", "0", "1", "Multi-Use List"), ("Caffeine_Use", "not_applicablecoffee", "N/A", "10", "0", ""),("Caffeine_Use", "nevercoffee", "Never", "20", "0", ""),("Caffeine_Use", "currentcoffee", "Current", "30", "0", ""),("Caffeine_Use", "quitcoffee", "Quit", "40", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Blood_Types", "Blood Types", "0", "1", "Multi-Use List"), ("Blood_Types", "A", "A", "10", "0", ""),("Blood_Types", "B", "B", "20", "0", ""),("Blood_Types", "AB", "AB", "30", "0", ""),("Blood_Types", "O", "O", "40", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "RH_Factor", "RH Factor", "0", "1", "Multi-Use List"), ("RH_Factor", "+", "Positive", "10", "0", ""),("RH_Factor", "-", "Negative", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Family_History_Problems", "Family History Problems", "0", "1", "Multi-Use List"), ("Family_History_Problems", "DIA", "Diabetes", "10", "0", "Sample Entry"),("Family_History_Problems", "HD", "Heart Disease", "20", "0", "Sample Entry") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Family_Relationships", "Family Relationships", "0", "1", "Multi-Use List"), ("Family_Relationships", "f", "Father", "10", "0", ""),("Family_Relationships", "m", "Mother", "20", "0", ""),("Family_Relationships", "mf", "Maternal Grandfather", "30", "0", ""),("Family_Relationships", "mm", "Maternal Grandmother", "40", "0", ""),("Family_Relationships", "pf", "Paternal Grandfather", "50", "0", ""),("Family_Relationships", "pm", "Paternal Grandmother", "50", "0", ""),("Family_Relationships", "b", "Brother", "50", "0", ""),("Family_Relationships", "s", "Sister", "50", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Medical_History_Problems", "Medical History Problems", "0", "1", "Multi-Use List"), ("Medical_History_Problems", "DIA", "Diabetes", "10", "0", "Sample Entry"),("Medical_History_Problems", "HD", "Heart Disease", "20", "0", "Sample Entry") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Image_Types", "Image Types", "0", "1", "Multi-Use List"), ("Image_Types", "X", "X-Ray", "10", "0", "Sample Entry"),("Image_Types", "ct", "CT Scan", "20", "0", "Sample Entry"),("Image_Types", "mri", "MRI", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Vital_Arm", "Vital Arm", "0", "1", "Multi-Use List"), ("Vital_Arm", "left", "Left", "10", "0", "System Use - DO NOT DELETE"),("Vital_Arm", "right", "Right", "20", "0", "System Use - DO NOT DELETE") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Form_Priority", "Form Priority", "0", "1", "Multi-Use List"), ("Form_Priority", "l", "Low", "10", "0", ""),("Form_Priority", "n", "Normal", "20", "0", ""), ("Form_Priority", "u", "Urgent", "30", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "PassFail", "PassFail", "0", "1", "Multi-Use List"), ("PassFail", "Pass", "Pass", "10", "0", ""),("PassFail", "Fail", "Fail", "20", "0", "") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES ("lists", "Form_Status", "Form Status", "0", "1", "Multi-Use List"), ("Form_Status", "i", "Incomplete", "10", "0", "Required - Do Not Delete"),("Form_Status", "c", "Complete", "20", "0", "Required - Do Not Delete"), ("Form_Status", "a", "Approved", "30", "0", "Required - Do Not Delete") ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`, `codes`) VALUES
("lists", "Rules_To_DB", "Rules To DB", "0", "1", "Internal Link - DO NOT DELETE", ""), 
("Rules_To_DB", "db_last_mamm", "act_mammo", "10", "0", "USED - DO NOT DELETE", "YES"),
("Rules_To_DB", "db_last_pap", "act_pap", "20", "0", "USED - DO NOT DELETE", "YES"),
("Rules_To_DB", "db_last_db_eye", "act_eye", "40", "0", "USED - DO NOT DELETE", "YES"),
("Rules_To_DB", "db_last_hgba1c", "act_hemo_a1c", "50", "0", "USED - DO NOT DELETE", "YES"),
("Rules_To_DB", "db_last_urine_alb", "act_urine_alb", "60", "0", "USED - DO NOT DELETE", "YES"),
("Rules_To_DB", "db_last_pft", "act_pulmonary", "70", "0", "USED - DO NOT DELETE", "YES"),
("Rules_To_DB", "db_last_psa", "act_prostate_cancer_screen", "80", "0", "USED - DO NOT DELETE", "YES"),
("Rules_To_DB", "db_last_db_foot", "act_foot", "100", "0", "USED - DO NOT DELETE", "YES") 
ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES 
("lists", "Drug_Use_Status", "Drug Use Status", "0", "1", "Internal Link - DO NOT DELETE"), 
("Drug_Use_Status", "neverrecreational_drugs", "Never", "10", "0", "USED - DO NOT DELETE"), 
("Drug_Use_Status", "currentrecreational_drugs", "Current", "20", "0", "USED - DO NOT DELETE"), 
("Drug_Use_Status", "quitrecreational_drugs", "Quit", "30", "0", "USED - DO NOT DELETE"), 
("Drug_Use_Status", "not_applicablerecreational_drugs", "N/A", "40", "0", "USED - DO NOT DELETE") 
ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`) VALUES
("lists", "Alcohol_Use_Status", "Alcohol Use Status", "0", "1", "Internal Link - DO NOT DELETE"), 
("Alcohol_Use_Status", "neveralcohol", "Never", "10", "0", "USED - DO NOT DELETE"),
("Alcohol_Use_Status", "currentalcohol", "Current", "20", "0", "USED - DO NOT DELETE"),
("Alcohol_Use_Status", "quitalcohol", "Quit", "30", "0", "USED - DO NOT DELETE"),
("Alcohol_Use_Status", "not_applicablealcohol", "N/A", "40", "0", "USED - DO NOT DELETE") 
ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`, `codes`) VALUES
("lists", "Social_History_Questions", "Social History Questions", "0", "1", "Internal Link - DO NOT DELETE", ""), 
("Social_History_Questions", "occ_hazard", "Occupational Hazards/Environmental Toxins", "10", "0", "USED - DO NOT DELETE", "Yes_No"),
("Social_History_Questions", "living", "Living Situation", "20", "0", "USED - DO NOT DELETE", ""),
("Social_History_Questions", "nutrition", "Healthy Eating/Nutrition", "30", "0", "USED - DO NOT DELETE", "Yes_No"),
("Social_History_Questions", "diet_supp", "Dietary Supplements", "40", "0", "USED - DO NOT DELETE", "Yes_No"), 
("Social_History_Questions", "phys", "Physical Activity", "50", "0", "USED - DO NOT DELETE", "Yes_No"), 
("Social_History_Questions", "adl", "Activities of Daily Living", "60", "0", "USED - DO NOT DELETE", "Yes_No") 
ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`, `codes`) VALUES 
("lists", "dashboard_modules", "Dashboard Modules/Order", "10", "1", "Required for the Dashboard", ""), 
("dashboard_modules", "pat_info_fyi", "Patient Demographics", "20", "0", "Negative Seq to Hide", "|pat_"), 
("dashboard_modules", "sh_full", "Social History", "30", "0", "Negative Seq to Hide", "db_"), 
("dashboard_modules", "well_ob", "Wellness", "40", "0", "Negative Seq to Hide", "|db_"), 
("dashboard_modules", "med", "Current Medications", "50", "0", "Negative Seq to Hide", "medications_erx"), 
("dashboard_modules", "all", "Allergies", "60", "0", "Negative Seq to Hide", "allergies"), 
("dashboard_modules", "ob_hist", "Obstetrical History", "70", "0", "Negative Seq to Hide", "past_pregnancies||f"), 
("dashboard_modules", "ps", "Surgeries", "80", "0", "Negative Seq to Hide", "previous_surgeries"), 
("dashboard_modules", "pmh", "Medical History", "90", "0", "Negative Seq to Hide", "past_med_history"), 
("dashboard_modules", "fh", "Family History", "100", "0", "Negative Seq to Hide", "family_history"), 
("dashboard_modules", "ros2", "Review of Systems", "-110", "0", "Negative Seq to Hide", ""), 
("dashboard_modules", "pap", "Pap Tracking", "120", "0", "Negative Seq to Hide", "pap_track||f|pap_track|pap_track"), 
("dashboard_modules", "imm", "Immunizations", "130", "0", "Negative Seq to Hide", "immunizations"), 
("dashboard_modules", "img", "Images", "140", "0", "Negative Seq to Hide", "image_summary"), 
("dashboard_modules", "hosp", "Admissions", "150", "0", "Negative Seq to Hide", "hospitalizations"), 
("dashboard_modules", "us", "Ultrasounds", "160", "0", "Negative Seq to Hide", "us_track||f|us_track|us_track"), 
("dashboard_modules", "bd", "Bone Density", "170", "0", "Negative Seq to Hide", "bd_track||f|bd_track|bd_track"), 
("dashboard_modules", "diag", "Diagnosis / Plan", "180", "0", "Negative Seq to Hide", "diagnosis"), 
("lists", "portal_modules", "Patient Portal Modules/Order", "10", "1", "Required for the Portal", ""), 
("portal_modules", "pat_info_ins", "Patient Demographics", "20", "0", "Negative Seq to Hide", "|prt_"), 
("portal_modules", "sh", "Social History", "30", "0", "Negative Seq to Hide", "|prt_"), 
("portal_modules", "well_ob", "Wellness", "40", "0", "Negative Seq to Hide", "|prt_"), 
("portal_modules", "fertile", "Fertility History", "50", "0", "Negative Seq to Hide", "|prt_"), 
("portal_modules", "exam_fertility", "Fertility Questionnaire", "55", "0", "Negative Seq to Hide", "|prt_"), 
("portal_modules", "appt", "Appointments", "60", "0", "Negative Seq to Hide", "appt_portal"), 
("portal_modules", "med", "Current Medications", "70", "0", "Negative Seq to Hide", "medications_erx"), 
("portal_modules", "all", "Allergies", "80", "0", "Negative Seq to Hide", "allergies"), 
("portal_modules", "ob_hist", "Obstetrical History", "90", "0", "Negative Seq to Hide", "past_pregnancies||f"), 
("portal_modules", "ps", "Surgeries", "100", "0", "Negative Seq to Hide", "previous_surgeries"), 
("portal_modules", "pmh", "Medical History", "110", "0", "Negative Seq to Hide", "past_med_history"), 
("portal_modules", "fh", "Family History", "120", "0", "Negative Seq to Hide", "family_history"), 
("portal_modules", "ros2", "Review of Systems", "-130", "0", "Negative Seq to Hide", ""), 
("portal_modules", "pap", "Pap Tracking", "-140", "0", "Negative Seq to Hide", "pap_track||f|pap_track|pap_track"), 
("portal_modules", "imm", "Immunizations", "150", "0", "Negative Seq to Hide", "immunizations"), 
("portal_modules", "img", "Images", "160", "0", "Negative Seq to Hide", "image_summary"), 
("portal_modules", "hosp", "Admissions", "170", "0", "Negative Seq to Hide", "hospitalizations"), 
("portal_modules", "us", "Ultrasounds", "-180", "0", "Negative Seq to Hide", "us_track||f|us_track|us_track"), 
("portal_modules", "bd", "Bone Density", "-190", "0", "Negative Seq to Hide", "bd_track||f|bd_track|bd_track"), 
("portal_modules", "diag", "Diagnosis / Plan", "220", "0", "Negative Seq to Hide", "diagnosis_portal"), 
("portal_modules", "rto", "Actions / Orders", "230", "0", "Negative Seq to Hide", "rto_portal||rto|rto") 
ON DUPLICATE KEY UPDATE `notes`= VALUES(`notes`);

INSERT INTO `user_settings` (`setting_user`, `setting_label`, `setting_value`) VALUES 
("0", "wmt::float_menu_save_quit::dashboard", "1"),
("0", "wmt::float_menu_portal_link::dashboard", "1"),
("0", "wmt::float_menu_lab_link::dashboard", "1"),
("0", "wmt::float_menu_vital_trend::dashboard", "1"),
("0", "wmt::float_menu_cancel::dashboard", "1"),
("0", "wmt::tmp_pat_disp_mode::dashboard", "block"),
("0", "wmt::tmp_sh_disp_mode::dashboard", "block"),
("0", "wmt::tmp_well_full_disp_mode::dashboard", "block"),
("0", "wmt::tmp_med_disp_mode::dashboard", "block"),
("0", "wmt::tmp_all_disp_mode::dashboard", "block"),
("0", "wmt::tmp_ob_hist_disp_mode::dashboard", ""),
("0", "wmt::tmp_ps_disp_mode::dashboard", "none"),
("0", "wmt::tmp_mhist_disp_mode::dashboard", "none"),
("0", "wmt::tmp_fh_disp_mode::dashboard", "none"),
("0", "wmt::tmp_ros_disp_mode::dashboard", "none"),
("0", "wmt::tmp_pap_disp_mode::dashboard", "none"),
("0", "wmt::tmp_imm_disp_mode::dashboard", "none"),
("0", "wmt::tmp_img_disp_mode::dashboard", "none"),
("0", "wmt::tmp_hosp_disp_mode::dashboard", "none"),
("0", "wmt::tmp_us_diap_mode::dashboard", "none"),
("0", "wmt::tmp_bd_disp_mode::dashboard", "none"),
("0", "wmt::tmp_diag_disp_mode::dashboard", "block"),
("0", "wmt::tmp_rto_disp_mode::dashboard", "none"),
("0", "wmt::tmp_ped_diet_disp_mode::dashboard", "none"),
("0", "wmt::tmp_bh_disp_mode::dashboard", "none"),
("0", "wmt::tmp_hepc_disp_mode::dashboard", "none"),
("0", "wmt::tmp_lab_disp_mode::dashboard", "none"),
("0", "wmt::tmp_fertile_disp_mode::dashboard", "none"),
("0", "wmt::tmp_pat_disp_mode::portal", "block"),
("0", "wmt::tmp_pat_info_ins_disp_mode::portal", "block"),
("0", "wmt::tmp_sh_disp_mode::portal", "block"),
("0", "wmt::tmp_well_full_disp_mode::portal", "block"),
("0", "wmt::tmp_well_ob_disp_mode::portal", "block"),
("0", "wmt::tmp_med_disp_mode::portal", "block"),
("0", "wmt::tmp_all_disp_mode::portal", "block"),
("0", "wmt::tmp_ob_hist_disp_mode::portal", "block"),
("0", "wmt::tmp_ps_disp_mode::portal", "none"),
("0", "wmt::tmp_mhist_disp_mode::portal", "none"),
("0", "wmt::tmp_fh_disp_mode::portal", "none"),
("0", "wmt::tmp_ros_disp_mode::portal", "none"),
("0", "wmt::tmp_pap_disp_mode::portal", "none"),
("0", "wmt::tmp_imm_disp_mode::portal", "none"),
("0", "wmt::tmp_img_disp_mode::portal", "none"),
("0", "wmt::tmp_hosp_disp_mode::portal", "none"),
("0", "wmt::tmp_us_diap_mode::portal", "none"),
("0", "wmt::tmp_bd_disp_mode::portal", "none"),
("0", "wmt::tmp_diag_disp_mode::portal", "block"),
("0", "wmt::tmp_rto_disp_mode::portal", "none"),
("0", "wmt::tmp_ped_diet_disp_mode::portal", "none"),
("0", "wmt::tmp_bh_disp_mode::portal", "none"),
("0", "wmt::tmp_hepc_disp_mode::portal", "none"),
("0", "wmt::tmp_lab_disp_mode::portal", "none"),
("0", "wmt::tmp_fertile_disp_mode::portal", "block"),
("0", "wmt::tmp_exam_fertility_disp_mode::portal", "block"),
("0", "wmt::tmp_ccr_disp_mode::portal", "none"),
("0", "wmt::tmp_appt_disp_mode::portal", "block"),
("0", "wmt::wellness_hearing::dashboard", "0"),
("0", "wmt::wellness_hearing::portal", "0"),
("0", "wmt::wellness_blood::dashboard", "0"),
("0", "wmt::wellness_blood::portal", "0"),
("0", "wmt::wellness_cardio::dashboard", "0"),
("0", "wmt::wellness_cardio::portal", "0"),
("0", "wmt::wellness_colon::dashboard", "0"),
("0", "wmt::wellness_colon::portal", "0"),
("0", "wmt::wellness_diabetes::dashboard", "1"),
("0", "wmt::wellness_dental::dashboard", "1"),
("0", "wmt::wellness_dental::portal", "1"),
("0", "wmt::wellness_diabetes::portal", "1"),
("0", "wmt::wellness_gyn::dashboard", "1"),
("0", "wmt::wellness_gyn::portal", "1"),
("0", "wmt::fyi_surg_nt", "1"),
("0", "wmt::fyi_admissions_nt", "1"),
("0", "wmt::fyi_img_nt", "1"),
("0", "wmt::fyi_med_nt", "1"),
("0", "wmt::fyi_medhist_nt", "1"),
("0", "wmt::fyi_allergy_nt", "1"),
("0", "wmt::fyi_pmh_nt", "1"),
("0", "wmt::fyi_fh_nt", "1"),
("0", "wmt::fyi_imm_nt", "1"),
("0", "wmt::fyi_pp_nt", "1"),
("0", "wmt::fyi_sh_nt", "1"),
("0", "wmt::fyi_imm_nt", "1"),
("0", "wmt::fyi_ros", "block"),
("0", "wmt::fyi_ros_pp", "block"),
("0", "wmt::db_diagnosis", "block"),
("0", "wmt::db_social_history", "block"),
("0", "wmt::db_wellness", "block"),
("0", "wmt::db_allergies", "block"),
("0", "wmt::db_medications", "block"),
("0", "wmt::db_ob_history", ""),
("0", "wmt::db_medical_history", "block"),
("0", "wmt::db_family_history", "block"),
("0", "wmt::db_birth_history", "block"),
("0", "wmt::db_medications", "block"),
("0", "wmt::db_admissions", "block"),
("0", "wmt::db_bone_density", "block"),
("0", "wmt::db_ultrasounds", "block"),
("0", "wmt::db_images", "block"),
("0", "wmt::db_immunizations", "block"),
("0", "wmt::db_pap_track", "block"),
("0", "wmt::db_surgeries", "block"),
("0", "wmt::db_reproductive1", ""),
("0", "wmt::sh_expanded::dashboard", "1"),
("0", "wmt::db_link_rules", "0")
 ON DUPLICATE KEY UPDATE `setting_label`= VALUES(`setting_label`);

