db_bc text DEFAULT NULL,
db_sex_active varchar(1) DEFAULT NULL,
db_sex_nt text DEFAULT NULL,
db_pflow varchar(1) DEFAULT NULL,
db_pfreq varchar(1) DEFAULT NULL,
db_pregnancies tinyint(2) DEFAULT 0,
db_deliveries tinyint(2) DEFAULT 0,
db_live_births tinyint(2) DEFAULT 0,
db_ptext text DEFAULT NULL,
db_last_hpv varchar(32) DEFAULT NULL,
db_pfreq_days varchar(32) DEFAULT NULL,
db_pflow_dur varchar(32) DEFAULT NULL,
db_alcohol_dt varchar(16) DEFAULT NULL,
db_drug_dt varchar(16) DEFAULT NULL,
db_sex_act_nt text DEFAULT NULL,
db_last_urine_alb varchar(32) DEFAULT NULL,
db_contact_email varchar(128) DEFAULT NULL,
db_contact_relationship varchar(64) DEFAULT NULL,
db_contact_cell varchar(32) DEFAULT NULL,
db_place_of_birth varchar(64) DEFAULT NULL,
db_adopted varchar(1) DEFAULT NULL,
db_brothers varchar(2) DEFAULT NULL,
db_sisters varchar(2) DEFAULT NULL,
db_birth_order varchar(2),
db_birth_of varchar(2) DEFAULT NULL,
db_sex_orient varchar(16) DEFAULT NULL,
db_sex_orient_nt TEXT DEFAULT NULL,
db_sex_sti varchar(4) DEFAULT NULL,
db_sex_sti_nt TEXT DEFAULT NULL,
db_num_marriages varchar(2) DEFAULT NULL,
db_num_divorces varchar(2) DEFAULT NULL,
db_num_children varchar(2) DEFAULT NULL,
db_birth_nt text DEFAULT NULL,
db_ped_diet_f tinyint(1),
db_ped_diet_b tinyint(1),
db_ped_diet_o tinyint(1),
db_ped_diet_nt text DEFAULT NULL,
db_ped_diet_tube varchar(2) DEFAULT NULL,
db_ped_diet_ttype varchar(128) DEFAULT NULL,
db_ped_diet_tsize varchar(64) DEFAULT NULL,
db_ped_diet_chc varchar(64) DEFAULT NULL,
db_ped_diet_amt varchar(64) DEFAULT NULL,
db_ped_diet_rate varchar(64) DEFAULT NULL,
db_ped_diet_special text DEFAULT NULL,
db_ped_diet_other text DEFAULT NULL,
db_hepc_test tinyint(1),
db_hepc_risk_factors text DEFAULT NULL,
db_hepc_other text DEFAULT NULL,
db_hepc_nt text DEFAULT NULL,
db_hepc_method_ph tinyint(1),
db_hepc_phone varchar(16) DEFAULT NULL,
db_hepc_callback tinyint(1),
db_hepc_method_ml tinyint(1),
db_hepc_addr text DEFAULT NULL,
db_hepc_dt varchar(32) DEFAULT NULL,
db_hepc_usr bigint(20) DEFAULT NULL,
db_last_hepc varchar(32) DEFAULT NULL,
db_last_lipid varchar(32) DEFAULT NULL,
db_last_lipo varchar(32) DEFAULT NULL,
db_last_tri varchar(32) DEFAULT NULL,
db_last_sigmoid varchar(32) DEFAULT NULL,
db_last_fecal varchar(32) DEFAULT NULL,
db_last_barium varchar(32) DEFAULT NULL,
db_last_glaucoma varchar(32) DEFAULT NULL,
db_last_db_screen varchar(32) DEFAULT NULL,
db_last_db_dbsmt varchar(32) DEFAULT NULL,
db_last_col_scrn varchar(32) DEFAULT NULL,
db_hpv varchar(4) DEFAULT NULL,
db_last_hgba1c varchar(32) DEFAULT NULL,
db_last_hgba1c_val varchar(32) DEFAULT NULL,
db_last_ekg varchar(32) DEFAULT NULL,
db_last_pft varchar(32) DEFAULT NULL,
db_hepc_pt_dt varchar(16) DEFAULT NULL,
db_hepc_pt_ssn varchar(16) DEFAULT NULL,
db_hepc_tester_dt varchar(16) DEFAULT NULL,
db_hear_screen varchar(1) DEFAULT NULL,
db_hearl_result varchar(1) DEFAULT NULL,
db_hearr_result varchar(1) DEFAULT NULL,
db_fh_non_contrib tinyint(1),
db_fh_adopted tinyint(1),
db_pap_nt TEXT DEFAULT NULL,
db_pap_hist_nt TEXT DEFAULT NULL,
db_other_nt TEXT DEFAULT NULL,
db_wellness_nt TEXT DEFAULT NULL,
db_group_b_strep varchar(4) DEFAULT NULL,
db_latex_allergy varchar(4) DEFAULT NULL,
db_drug_allergy text DEFAULT NULL,
db_last_dental varchar(32) DEFAULT NULL,
db_last_dental_nt TEXT DEFAULT NULL,
db_last_hear VARCHAR(32) DEFAULT NULL,
db_left_ear VARCHAR(4) DEFAULT NULL,
db_right_ear VARCHAR(4) DEFAULT NULL,
db_hear_nt TEXT DEFAULT NULL,
db_fh_extra_yes TEXT DEFAULT NULL,
db_fh_extra_no TEXT DEFAULT NULL,
db_bc_chc VARCHAR(4) DEFAULT NULL,
db_mam_law VARCHAR(4) DEFAULT NULL,
