x-includes:
  node-version: "22"
  selenium-template: "compose-shared-selenium/docker-compose.yml"
  webserver-template: "compose-shared-apache.yml"
  database-template: "compose-shared-mariadb.yml"
  mailpit-template: "compose-shared-mailpit/compose.yml"

services:
  mysql:
    image: mariadb:11.8.6@sha256:78a5047d3ba33975f183f183c2464cc7f1eab13ec8667e57cc9a5821d6da7577
  openemr:
    image: openemr/openemr:flex-3.22-php-8.2@sha256:a9311e49f92e152c44e5ba13ff15446a4363234eada6aa56c40c8f5ce82d9fee
