x-includes:
  node-version: "22"
  selenium-template: "compose-shared-selenium/docker-compose.yml"
  webserver-template: "compose-shared-apache.yml"
  database-template: "compose-shared-mariadb.yml"
  mailpit-template: "compose-shared-mailpit/compose.yml"

services:
  mysql:
    image: mariadb:11.8.8@sha256:be1ef4fe5f14589325c08a41c76334097ce66c86264b75e1d28342c742782a61
  openemr:
    image: openemr/openemr:flex-3.22-php-8.2@sha256:228aa69703ffdb3b030c66deaef5ceb40f48994b43f05c122bb22a64562048a6
