x-includes:
  node-version: "22"
  selenium-template: "compose-shared-selenium/docker-compose.yml"
  webserver-template: "compose-shared-apache.yml"
  database-template: "compose-shared-mariadb.yml"
  mailpit-template: "compose-shared-mailpit/compose.yml"

services:
  mysql:
    image: mariadb:11.8.8@sha256:efb4959ef2c835cd735dbc388eb9ad6aab0c78dd64febcd51bc17481111890c4
  openemr:
    image: openemr/openemr:flex-3.22-php-8.2@sha256:acb17bfb8549259a6042b792e007c99d727bd7479532eda133bb0789cbeee8f4
