<?php
/**
 * interface/modules/zend_modules/module/Acl/view/layout/layout_tabs.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Jacob T.Paul <jacob@zhservices.com>
 * @author    Shalini Balakrishnan  <shalini@zhservices.com>
 * @author    Basil PT <basil@zhservices.com>
 * @copyright Copyright (c) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="<?php echo  $GLOBALS['css_header'];?>">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
				<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
			->prependStylesheet($this->basePath() . '/css/easyui.css')
                        ->prependStylesheet($this->basePath() . '/css/icon.css')
                        ->prependStylesheet($this->basePath() . '/css/demo.css')
			->prependStylesheet($this->basePath() . '/css/style.css')
			->prependStylesheet($this->basePath() . '/css/suggestion.css')
			->prependStylesheet($this->basePath() . '/css/bubbletip-IE.css')
			->prependStylesheet($this->basePath() . '/css/bubbletip.css')
			->prependStylesheet($this->basePath() . '/css/bubbles.css')
			->prependStylesheet($this->basePath() . '/css/emr.css')
			->prependStylesheet($GLOBALS['css_header'])
			->prependStylesheet($GLOBALS['assets_static_relative'] . '/bootstrap/dist/css/bootstrap.min.css')
	?>

        <!-- Scripts -->
        <?php echo $this->headScript()
			->prependFile($GLOBALS['assets_static_relative'] . '/bootstrap/dist/js/bootstrap.bundle.min.js')
			->prependFile($this->basePath() . '/js/lib/jquery.easyui.min.js')
			->prependFile($GLOBALS['assets_static_relative'] . '/jquery/dist/jquery.min.js')
	?>
<script>
    var i = 0;
    $(function () {
        $('#tab').tabs({
        onSelect: function(title,index){
            if(index == 0){
                if(i>0) document.getElementById('general_acl').contentWindow.location.reload();
                i++;
            }else if(index == 1){
                document.getElementById('advanced_acl').contentWindow.location.reload();
            }
        }
      });
    });
</script>
    </head>
    <body class="body_top" style="margin: 0px !important;padding: 0px !important;">
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
