<?php
/**
 * interface/modules/zend_modules/module/Acl/view/layout/layout.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Jacob T.Paul <jacob@zhservices.com>
 * @author    Basil PT <basil@zhservices.com>
 * @copyright Copyright (c) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
echo $this->doctype();
use OpenEMR\Core\Header;
?>

<html>
    <head>
        <?php Header::setupHeader(['jquery-easyui', 'jqtree', 'interactjs', 'laminas-style']); ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'));
        ?>

        <script src="<?php echo $this->basePath(); ?>/js/application/common.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/acl/acl.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
