<?php
/**
 * interface/modules/zend_modules/module/Carecoordination/view/layout/encountermanager.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Vinish K <vinish@zhservices.com>
 * @copyright Copyright (c) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
 echo $this->doctype();
 use OpenEMR\Core\Header;
?>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle($this->translate()->xl('Care Coordination'))->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php Header::setupHeader(['datetime-picker']); ?>
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/carecoordination_style.css" />
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/style.css" />
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/sendTo.css" />
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/autosuggest/autosuggest.css" />

        <script>
        var APP_URL = "<?php echo $this->basePath(); ?>";
        var WEB_ROOT = "<?php echo $GLOBALS['webroot']; ?>";
        </script>

        <script src="<?php echo $this->basePath(); ?>/js/autosuggest/autosuggest.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/application/sendTo.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/carecoordination/encounterManager.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/application/common.js"></script>
        <script>
        $(function() {
          $(".dateClass").datetimepicker({
            <?php $datetimepicker_timepicker = false; ?>
            <?php $datetimepicker_showseconds = false; ?>
            <?php $datetimepicker_formatInput = false; ?>
            <?php require($GLOBALS['srcdir'] . '/js/xl/jquery-datetimepicker-2-5-4.js.php'); ?>
          });
          $(".rangeClass").datetimepicker({
            <?php $datetimepicker_timepicker = false; ?>
            <?php $datetimepicker_showseconds = false; ?>
            <?php $datetimepicker_formatInput = false; ?>
            <?php require($GLOBALS['srcdir'] . '/js/xl/jquery-datetimepicker-2-5-4.js.php'); ?>
          });
        });
        </script>
    </head>
    <body class="body_top">
        <div class="container-fluid">
            <?php echo $this->javascriptGlobals(); ?>
            <?php echo $this->content; ?>
        </div>
    </body>
</html>
