<?php
/**
 * interface/modules/zend_modules/module/Carecoordination/view/layout/encountermanager.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Vinish K <vinish@zhservices.com>
 * @copyright Copyright (c) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
?>
<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate()->xl('Care Coordination'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/responsive-tables.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/css/carecoordination_style.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/sendTo.css')
		->prependStylesheet($this->basePath() . '/css/autosuggest/autosuggest.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <?php echo $this->headScript()
		->prependFile($this->basePath() . '/js/autosuggest/autosuggest.js')
        ->prependFile($this->basePath() . '/js/application/sendTo.js')
        ->prependFile($this->basePath() . '/js/carecoordination/encounterManager.js')
        ->prependFile($this->basePath() . '/js/lib/jquery-ui.custom.js')
        ->prependFile($this->basePath() . '/js/lib/jquery.ui.datepicker.js')
        ->prependFile($this->basePath() . '/js/lib/jquery.ui.core.js')
        ->prependFile($this->basePath() . '/js/carecoordination/responsive-tables.js')
        ->prependFile($this->basePath() . '/js/lib/bootstrap.min.js')
		->prependFile($this->basePath() . '/js/application/common.js')
        ->prependFile($this->basePath() . '/js/lib/jquery-1.8.3.js')
        ?>

    </head>
    <body  class="body_top">
        <div class="container" style="width:100%">
			<?php echo $this->javascriptGlobals(); ?>
            <?php echo $this->content; ?>
        </div>
    </body>
</html>
