<?php
/* +-----------------------------------------------------------------------------+
*    OpenEMR - Open Source Electronic Medical Record
*    Copyright (C) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
*
*    This program is free software: you can redistribute it and/or modify
*    it under the terms of the GNU Affero General Public License as
*    published by the Free Software Foundation, either version 3 of the
*    License, or (at your option) any later version.
*
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU Affero General Public License for more details.
*
*    You should have received a copy of the GNU Affero General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*    @author  Vinish K <vinish@zhservices.com>
* +------------------------------------------------------------------------------+
*/
?>
<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Care Coordination'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/responsive-tables.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/css/carecoordination_style.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/sendTo.css')
		->prependStylesheet($this->basePath() . '/css/autosuggest/autosuggest.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <?php echo $this->headScript()
		->prependFile($this->basePath() . '/js/autosuggest/autosuggest.js')
        ->prependFile($this->basePath() . '/js/application/sendTo.js')
        ->prependFile($this->basePath() . '/js/carecoordination/encounterManager.js')
        ->prependFile($this->basePath() . '/js/carecoordination/jquery-ui.custom.js')
        ->prependFile($this->basePath() . '/js/carecoordination/jquery.ui.datepicker.js')
        ->prependFile($this->basePath() . '/js/carecoordination/jquery.ui.core.js')
        ->prependFile($this->basePath() . '/js/carecoordination/responsive-tables.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
		->prependFile($this->basePath() . '/js/application/common.js')
        ->prependFile($this->basePath() . '/js/carecoordination/jquery-1.8.3.js')
        ?>

    </head>
    <body  class="body_top">
        <div class="container" style="width:100%">
			<?php echo $this->javascriptGlobals(); ?>
            <?php echo $this->content; ?>
        </div>
    </body>
</html>
