<?php
/**
 * interface/modules/zend_modules/module/Carecoordination/view/layout/layout.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Vinish K <vinish@zhservices.com>
 * @copyright Copyright (c) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
echo $this->doctype();
use OpenEMR\Core\Header;
?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate()->xl('CCDA'))->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php Header::setupHeader(['datetime-picker', 'modernizr', 'laminas-style']); ?>
        <script src="<?php echo $this->basePath(); ?>/js/application/sendTo.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/application/common.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/autosuggest/autosuggest.js"></script>

        <script>
        var APP_URL = "<?php echo $this->basePath(); ?>";
        var WEB_ROOT = "<?php echo $GLOBALS['webroot']; ?>";
        </script>
    </head>
    <body>
        <div class="container-fluid">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
