<?php
/**
 * interface/modules/zend_modules/module/Carecoordination/view/layout/mapper.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Vinish K <vinish@zhservices.com>
 * @copyright Copyright (c) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
 echo $this->doctype();
 use OpenEMR\Core\Header;
?>
<html lang="en">
<head>
  <meta charset="utf-8">
  <?php Header::setupHeader(['jqtree']); ?>
  <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/ccda.css')
    ->prependStylesheet($this->basePath() . '/css/demo.css');
    ?>

  <?php echo $this->headScript()->prependFile($this->basePath() . '/js/lib/virtualpaginate.js'); ?>
</head>
<body class="body_top">
  <div class="container-fluid">
        <?php echo $this->content; ?>
  </div>
</body>
</html>
