<?php
/**
 * interface/modules/zend_modules/module/Carecoordination/view/layout/setup.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Vinish K <vinish@zhservices.com>
 * @copyright Copyright (c) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
 echo $this->doctype();
 use OpenEMR\Core\Header;
?>
<html>
    <head>
        <?php Header::setupHeader(['jqtree', 'datetime-picker', 'laminas-style']); ?>
        <script src="<?php echo $this->basePath(); ?>/js/lib/virtualpaginate.js"></script>
    </head>
    <body class="body_top setup-carecoordination">
        <div class="container-fluid">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>
