import "themes/style_light.scss";
import "themes/style_manila.scss";

import "themes/style_cadmium_yellow.scss";
import "themes/style_coral.scss";
import "themes/style_emerald.scss";
import "themes/style_mustard_green.scss";
import "themes/style_powder_blue.scss";
import "themes/style_tangerine.scss";
import "themes/style_ash_blue.scss";
import "themes/style_chocolate.scss";
import "themes/style_deep_purple.scss";
import "themes/style_forest_green.scss";
import "themes/style_olive.scss";
import "themes/style_red.scss";
import "themes/style_burgundy.scss";
import "themes/style_cobalt_blue.scss";
import "themes/style_dune.scss";
import "themes/style_mauve.scss";
import "themes/style_pink.scss";
import "themes/style_sienna.scss
