#!/usr/bin/env bash
#
# Helpers for shell-script tests under .github/scripts/tests/.
#
# Each test creates a synthetic git repo in a temp dir, populates it with
# fixture files, runs the script under test, and asserts against the
# resulting working tree + script outputs. setup_test_repo and friends
# provide the boilerplate.
#
# Sourced by test files. Not invoked directly.

# Capture absolute paths AT SOURCE TIME, before any test does `cd` into
# its temp working dir. BASH_SOURCE[0] is the path used to source this
# file (possibly relative); we resolve it once here and stash the
# absolute path in a variable that survives the later cd.
__HELPERS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNC_BYTE_IDENTICAL_SCRIPT="${__HELPERS_DIR}/../sync-byte-identical.sh"

# Create a fresh temp git repo with master + the target rel branch, both
# rooted at an initial seed commit. Sets $REPO and $OUTPUT_DIR in the caller.
#
# Args:
#   $1  rel branch name (default: rel-810)
#
# Side effects:
#   Sets REPO=<tempdir>, OUTPUT_DIR=<tempdir/output>
#   cd's into REPO
#   Initializes master + the rel branch, both pointing at an empty seed commit
setup_test_repo() {
  local rel_branch="${1:-rel-810}"
  REPO=$(mktemp -d -t sync-byte-identical-test-XXXX)
  OUTPUT_DIR="${REPO}/output"
  mkdir -p "$OUTPUT_DIR"

  cd "$REPO"
  git init -q -b master
  git config user.email "test@example.com"
  git config user.name "Test"
  git commit -q --allow-empty -m "seed"

  # Create the rel branch from the same seed.
  git branch "$rel_branch"
}

# Add or update a file on a specific branch.
#
# Args:
#   $1  branch
#   $2  path
#   $3  content
write_on_branch() {
  local branch="$1" path="$2" content="$3"
  git checkout -q "$branch"
  mkdir -p "$(dirname "$path")"
  echo "$content" > "$path"
  git add "$path"
  git commit -q -m "write $path on $branch"
}

# Delete a file on a specific branch.
delete_on_branch() {
  local branch="$1" path="$2"
  git checkout -q "$branch"
  git rm -q "$path"
  git commit -q -m "delete $path on $branch"
}

# Write the FILES_ALL config on master with the given file list (one per
# line in $@). Skipping arguments yields an empty `files:` list.
write_files_all_config() {
  git checkout -q master
  mkdir -p .github
  {
    echo "# Auto-generated by helpers.sh for testing."
    echo "files:"
    for f in "$@"; do
      echo "  - $f"
    done
  } > .github/docker-byte-identical.yml
  git add .github/docker-byte-identical.yml
  git commit -q -m "FILES_ALL config: $*"
}

# Write the FILES_ALL config raw -- caller provides the entire YAML content.
# Useful for testing malformed lists, duplicates, etc.
write_files_all_raw() {
  local content="$1"
  git checkout -q master
  mkdir -p .github
  echo "$content" > .github/docker-byte-identical.yml
  git add .github/docker-byte-identical.yml
  git commit -q -m "FILES_ALL config (raw)"
}

# Run the script under test, capturing its exit code.
# Caller should already be on the target rel branch (the script reads HEAD:
# for the rel-branch side).
run_sync() {
  local target_branch="${1:-rel-810}"
  set +e
  OUTPUT_DIR="$OUTPUT_DIR" bash "$SYNC_BYTE_IDENTICAL_SCRIPT" "$target_branch" > "$OUTPUT_DIR/stdout.txt" 2> "$OUTPUT_DIR/stderr.txt"
  EXIT_CODE=$?
  set -e
}

# Assertion helpers. Each returns non-zero on failure (which propagates up
# through the test function's set -e). They also print a clear failure
# message before failing so the test runner output is interpretable.

assert_exit_code() {
  local expected="$1"
  if [ "$EXIT_CODE" -ne "$expected" ]; then
    echo "FAIL: expected exit code $expected, got $EXIT_CODE"
    echo "  stdout: $(cat "$OUTPUT_DIR/stdout.txt")"
    echo "  stderr: $(cat "$OUTPUT_DIR/stderr.txt")"
    return 1
  fi
}

assert_file_exists() {
  local path="$1"
  if [ ! -f "$path" ]; then
    echo "FAIL: expected file to exist: $path"
    return 1
  fi
}

assert_file_missing() {
  local path="$1"
  if [ -f "$path" ]; then
    echo "FAIL: expected file to be missing: $path"
    return 1
  fi
}

assert_file_content() {
  local path="$1" expected="$2"
  if [ ! -f "$path" ]; then
    echo "FAIL: expected file to exist: $path"
    return 1
  fi
  local actual
  actual=$(cat "$path")
  if [ "$actual" != "$expected" ]; then
    echo "FAIL: file content mismatch at $path"
    echo "  expected: $expected"
    echo "  actual:   $actual"
    return 1
  fi
}

assert_changes_contains() {
  local pattern="$1"
  if ! grep -qxF "$pattern" "$OUTPUT_DIR/changes.txt"; then
    echo "FAIL: changes.txt missing entry: $pattern"
    echo "  actual changes.txt:"
    sed 's/^/    /' "$OUTPUT_DIR/changes.txt"
    return 1
  fi
}

assert_no_changes() {
  if [ -s "$OUTPUT_DIR/changes.txt" ]; then
    echo "FAIL: expected no changes, but changes.txt is non-empty:"
    sed 's/^/  /' "$OUTPUT_DIR/changes.txt"
    return 1
  fi
}

assert_stderr_contains() {
  local pattern="$1"
  if ! grep -qF "$pattern" "$OUTPUT_DIR/stderr.txt"; then
    echo "FAIL: stderr missing pattern: $pattern"
    echo "  actual stderr:"
    sed 's/^/    /' "$OUTPUT_DIR/stderr.txt"
    return 1
  fi
}

teardown_test_repo() {
  cd /
  rm -rf "$REPO"
}
