CREATE TABLE IF NOT EXISTS `form_Obstetrics_Form` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
lmp DATE,
edc DATE,
weeks TEXT,
days TEXT,
supplements TEXT,
treatments TEXT,
height_of_fundus TEXT,
hemoglobin TEXT,
platelets TEXT,
urinalysis TEXT,
urine_culture TEXT,
abo_and_rh TEXT,
coombs_test TEXT,
syphillis_rpr TEXT,
hepatitis_b TEXT,
hiv TEXT,
group_b_streptococcus_culture TEXT,
glucose_challenge_test TEXT,
others TEXT,
fetal_heart TEXT,
ultrasound_notes TEXT,
problem_list TEXT,
other_notes TEXT,

PRIMARY KEY (id)
) ENGINE=InnoDB;
