CREATE TABLE IF NOT EXISTS `form_intakeverslag` (
  `id` bigint(20) unsigned NOT NULL auto_increment,
  `date` datetime default NULL,
  `pid` bigint(20) default NULL,
  `user` varchar(255) character set latin1 default NULL,
  `groupname` varchar(255) character set latin1 default NULL,
  `authorized` tinyint(4) default NULL,
  `activity` tinyint(4) default NULL,
  `intakedatum` datetime default NULL,
  `reden_van_aanmelding` longtext character set latin1,
  `klachten_probleemgebieden` longtext character set latin1,
  `hulpverlening_onderzoek` longtext character set latin1,
  `hulpvraag_en_doelen` longtext character set latin1,
  `bijzonderheden_systeem` longtext character set latin1,
  `werk_opleiding_vrije_tijdsbesteding` longtext character set latin1,
  `relatie_kinderen` longtext character set latin1,
  `somatische_context` longtext character set latin1,
  `alcohol` varchar(255) character set latin1 default NULL,
  `drugs` varchar(255) character set latin1 default NULL,
  `roken` varchar(255) character set latin1 default NULL,
  `medicatie` longtext character set latin1,
  `familieanamnese` longtext character set latin1,
  `indruk_observaties` longtext character set latin1,
  `beschrijvende_conclusie` longtext character set latin1,
  `behandelvoorstel` longtext character set latin1,
  `autosave_flag` tinyint(4) default 1,
  `autosave_datetime` datetime default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=2 ;
