CREATE TABLE IF NOT EXISTS `form_phq9` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
interest_score varchar(255),
interest_extra_info varchar(255),
hopeless_score varchar(255),
hopeless_extra_info varchar(255),
sleep_score varchar(255),
sleep_extra_info varchar(255),
fatigue_score varchar(255),
fatigue_extra_info varchar(255),
appetite_score varchar(255),
appetite_extra_info varchar(255),
failure_score varchar(255),
failure_extra_info varchar(255),
focus_score varchar(255),
focus_extra_info varchar(255),
psychomotor_score varchar(255),
psychomotor_extra_info varchar(255),
suicide_score varchar(255),
suicide_extra_info varchar(255),
difficulty varchar(255),
difficulty_extra_info varchar(255),
PRIMARY KEY (id)
) ENGINE=InnoDB;
