CREATE TABLE IF NOT EXISTS `form_habits` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
coffee ENUM ('YES','NO') default NULL,
tea ENUM ('YES','NO') default NULL,
soft_drinks ENUM ('YES','NO') default NULL,
other_caffeine ENUM ('YES','NO') default NULL,
caffeine_per_day VARCHAR (255) default NULL,
salt_usage ENUM ('Heavy','Moderate','Light','No salt') default NULL,
sugar_usage ENUM ('Heavy','Moderate','Light','No sugar') default NULL,
diet ENUM ('Healthy','Fair','Poor') default NULL,
diet_comments VARCHAR (255) default NULL,
alc_per_day TINYINT (3) default NULL,
alc_per_week TINYINT (3) default NULL,
recr_drugs VARCHAR (255) default NULL,
recr_drugs_often VARCHAR (255) default NULL,
alc_drug_problem ENUM ('YES','NO') default NULL,
alc_drug_problem_explain VARCHAR (255) default NULL,
current_smoke ENUM ('YES','NO') default NULL,
ever_smoked ENUM ('YES','NO') default NULL,
cig_per_day_now TINYINT (3) default NULL,
cig_per_day_past TINYINT (3) default NULL,
how_long_smoke TINYINT (3) default NULL,
smoke_quit DATE default NULL,
like_to_quit ENUM ('YES','NO') default NULL,
exercise_reg ENUM ('YES','NO') default NULL,
exercise_types VARCHAR (255) default NULL,
exercise_per_week VARCHAR (255) default NULL,
exercise_minutes VARCHAR (255) default NULL,
seat_belt ENUM ('Always','Usually','Seldom','Never') default NULL,
ever_been_molested ENUM ('YES','NO') default NULL,
ever_molested_other ENUM ('YES','NO') default NULL,
PRIMARY KEY (id)
) ENGINE=MyISAM;
