x-includes:
  node-version: "24"
  selenium-template: "compose-shared-selenium/docker-compose.yml"
  webserver-template: "compose-shared-apache.yml"
  database-template: "compose-shared-mysql.yml"
  mailpit-template: "compose-shared-mailpit/compose.yml"

services:
  mysql:
    image: mysql:8.4.10@sha256:563602a18ffd5be220968e8508d84c9dcd80fbffe69e28af51572db29e3285b2
  openemr:
    image: openemr/openemr:flex-3.23-php-8.5@sha256:c1eb26a24f4f3e2fa96c518df8a40444435a3373036a2b8fd3a7580fcca335fc
