CREATE TABLE IF NOT EXISTS `form_vet_genphys_exam` (
  `id`                  bigint(20)   NOT NULL auto_increment,
  `date`                datetime     DEFAULT NULL,
  `pid`                 bigint(20)   NOT NULL DEFAULT 0,
  `user`                TEXT,
  `groupname`           TEXT,
  `authorized`          tinyint(4)   NOT NULL DEFAULT 0,
  `activity`            tinyint(4)   NOT NULL DEFAULT 0,
`presenting_complaint`  TEXT,
`consciousness`         varchar(5),
`behaviour`             varchar(5),
`gait`                  TEXT,
`general_notes`         TEXT,
`anamnesis`             TEXT,
`general_condition`     varchar(5),
`bws_bodyscore`         varchar(5),
`body_posture`          TEXT,
`care_condition`        tinyint(4),
`vitals_weight`         float(5,2),  DEFAULT 0,
`vitals_temperature`    float(5,2),  DEFAULT 0,
`heart_frequency`       tinyint(4),
`heart_tones`           varchar(24),
`heart_murmur`          varchar(5),
`heart_murmur_phase`    varchar(24),
`pulse_frequency`       tinyint(4),
`pulse_intensity`       varchar(5)   NOT NULL DEFAULT 3,
`pulse_regularity`      varchar(24),
`pulse_equality`        varchar(24),
`mucosae_colour`        varchar(24),
`mucosae_status`        varchar(24), 
`mucosae_CRT`           varchar(5),
`respiration_frequency` tinyint(4),
`respiration_type`      varchar(24),
`respiration_character` varchar(24),
`lungf_ausc_1`          varchar(5),
`lungf_ausc_2`          varchar(5),
`lungf_ausc_3`          varchar(5),
`lungf_ausc_4`          varchar(5),
`lungf_ausc_5`          varchar(5),
`lungf_ausc_6`          varchar(5),
`lungf_ausc_7`          varchar(5),
`lungfield_percussion`  TEXT,
`up_airways_1`          varchar(5),
`up_airways_2`          varchar(5),
`up_airways_3`          varchar(5),
`up_airways_4`          varchar(5),
`up_airways_5`          varchar(5), 
`upper_airways_2descr`  TEXT,
`elasticity_abdomen`    varchar(24),
`sensibility_abdomen`   varchar(24),
`palp_abdomen_other`    TEXT,
`skin_turgor`           varchar(5),
`skin_colour`           varchar(55),
`skin_thickness`        varchar(24),
`skin_mobility`         varchar(55),
`integ_general`         varchar(55),
`integ_local`           varchar(55),
`lnn_mandibulares`      TEXT,
`lnn_parotidei`         TEXT,
`lnn_retropharyng`      TEXT,
`lnn_cervicales`        TEXT,
`lnn_axillares`         TEXT,
`lnn_axill_access`      TEXT,
`lnn_inguinales`        TEXT,
`lnn_poplitei`          TEXT,
`genphys_other_findings` TEXT,
`presumptive_diagnosis` TEXT,
`differential_diagnosis` TEXT,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
