services:
  openemr:
    restart: always
    image: openemr/openemr:flex-3.21
    ports:
    - 80:80
    - 443:443
    volumes:
    - ../../:/var/www/localhost/htdocs/openemr
    environment:
      FORCE_NO_BUILD_MODE: "yes"
      EMPTY: "yes"
    depends_on:
    - mysql