services:
  selenium:
    image: selenium/standalone-chrome:134.0-chromedriver-134.0-grid-4.31.0-20250414    # Pinned to Chrome 134 and grid 4.31
    ports:
    - 4444:4444    # Selenium WebDriver interface
    environment:
      SE_SCREEN_WIDTH: 1920
      SE_SCREEN_HEIGHT: 1080
      SE_SCREEN_DEPTH: 24
      SE_START_XVFB: true
    volumes:
    - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 3
  openemr:
    environment:
      SELENIUM_USE_GRID: "true"
      SELENIUM_HOST: selenium
      SELENIUM_FORCE_HEADLESS: "true"
