services:
  openemr:
    ports:
    - 80:80
    - 443:443
    volumes:
    - ../:/var/www/localhost/htdocs/openemr
    environment:
      FORCE_NO_BUILD_MODE: "yes"
      EMPTY: "yes"
    healthcheck:
      test:
      - CMD
      - /usr/bin/curl
      - --fail
      - --insecure
      - --location
      - --show-error
      - --silent
      - https://localhost/
      start_period: 10m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
