services:
  mailpit:
    image: axllent/mailpit:latest
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_MAX_MESSAGES: 5000
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025/api/v1/messages"]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 3
  openemr:
    depends_on:
      mailpit:
        condition: service_healthy
    environment:
      OPENEMR_SETTING_EMAIL_METHOD: SMTP
      OPENEMR_SETTING_SMTP_HOST: mailpit
      OPENEMR_SETTING_SMTP_PORT: 1025
      OPENEMR_SETTING_SMTP_USER: openemr
      OPENEMR_SETTING_SMTP_PASS: openemr
      OPENEMR_SETTING_SMTP_SECURE: ''
      OPENEMR_SETTING_SMTP_Auth: 'TRUE'
      OPENEMR_SETTING_practice_return_email_path: 'noreply@openemr.local'
      OPENEMR_SETTING_Patient_Reminder_Sender_Name: 'OpenEMR Reminders'
