<?php
/**
 * interface/modules/zend_modules/module/Installer/view/layout/layout.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Jacob T.Paul <jacob@zhservices.com>
 * @author    Vipin Kumar <vipink@zhservices.com>
 * @author    Remesh Babu S <remesh@zhservices.com>
 * @copyright Copyright (c) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

echo $this->doctype();
use OpenEMR\Core\Header;
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php Header::setupHeader(['jquery-easyui', 'fontawesome']); ?>
        <?php echo $this->headTitle(xl('Manage Modules'))->setSeparator(' - ')->setAutoEscape(false); ?>
                <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/icon.css')
                        ->prependStylesheet($this->basePath() . '/css/demo.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/suggestion.css')
                        ->prependStylesheet($this->basePath() . '/css/emr.css'); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/application/common.js')->prependFile($this->basePath() . '/js/lib/jquery.easyui.overrider.js');
        ?>

    </head>
    <body class="body_top">
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
