<?php
/**
 * interface/modules/zend_modules/module/Installer/view/layout/layout.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Jacob T.Paul <jacob@zhservices.com>
 * @author    Vipin Kumar <vipink@zhservices.com>
 * @author    Remesh Babu S <remesh@zhservices.com>
 * @copyright Copyright (c) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="<?php echo  $GLOBALS['css_header'];?>">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headTitle(xl('Manage Modules'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/easyui.css')
        ->prependStylesheet($this->basePath() . '/css/icon.css')
        ->prependStylesheet($this->basePath() . '/css/demo.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/suggestion.css')
        ->prependStylesheet($this->basePath() . '/css/bubbletip-IE.css')
        ->prependStylesheet($this->basePath() . '/css/bubbletip.css')
        ->prependStylesheet($this->basePath() . '/css/bubbles.css')
        ->prependStylesheet($this->basePath() . '/css/emr.css')
        ->prependStylesheet($GLOBALS['css_header']) ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/application/common.js')
        ->prependFile($this->basePath() . '/js/lib/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/lib/jquery.easyui.overrider.js')
        ->prependFile($this->basePath() . '/js/lib/jquery.easyui.min.js')
        ->prependFile($this->basePath() . '/js/lib/jquery-1.8.0.min.js')
		?>
    </head>
    <body class="body-top">
        <div class="row">
            <!-- iteration of content depending on type. e.g. wrapper for module config include. -->
            <div class="col-12"><?php echo $this->content; ?></div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
