x-includes:
  node-version: "24"
  selenium-template: "compose-shared-selenium/docker-compose.yml"
  webserver-template: "compose-shared-apache.yml"
  database-template: "compose-shared-mariadb.yml"
  mailpit-template: "compose-shared-mailpit/compose.yml"

services:
  mysql:
    image: mariadb:11.8.7@sha256:78185355dd49b54dd6909072531ce8d7e06aa0eccd7aa5b23c93ebb7e34c5aaa
  openemr:
    image: openemr/openemr:flex-3.23-php-8.4@sha256:38c0c7dd50cf883be812c0cfdcc7265b62f6abdc1db9c53ba272236bec7d6ed4
