x-includes:
  node-version: "24"
  selenium-template: "compose-shared-selenium/docker-compose.yml"
  webserver-template: "compose-shared-apache.yml"
  database-template: "compose-shared-mariadb.yml"
  mailpit-template: "compose-shared-mailpit/compose.yml"

services:
  mysql:
    image: mariadb:11.8.6@sha256:78a5047d3ba33975f183f183c2464cc7f1eab13ec8667e57cc9a5821d6da7577
  openemr:
    image: openemr/openemr:flex-3.23-php-8.4@sha256:b33ea5f2bf6e56045cce0def33a8baa19e7b0d1993bcb0fd9a09f07ee2e815db
