<?php

/* +-----------------------------------------------------------------------------+
* Copyright 2016 matrix israel
* LICENSE: This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 3
* of the License, or (at your option) any later version.
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
* You should have received a copy of the GNU General Public License
* along with this program. If not, see
* http://www.gnu.org/licenses/licenses.html#GPL
*    @author  Oshri Rozmarin <oshri.rozmarin@gmail.com>
* +------------------------------------------------------------------------------+
 *
 */

?>

<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">

    <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headMeta();
    ?>

    <!-- css files -->
    <?php foreach($this->cssFiles as $file){

        $this->headLink()->appendStylesheet( $GLOBALS['assets_static_relative']  . $file);
    }
    $this->headLink()->appendStylesheet( $this->basePath()  . '/css/multipledb/multipledb.css');
    echo $this->headLink();
    ?>

    <!-- Scripts -->
    <?php
    foreach($this->jsFiles as $file){

        $this->headScript()->appendFile($GLOBALS['assets_static_relative']   . $file);
    }
    echo  $this->headScript() ;
    ?>

</head>

<body class="container-fluid body_top " dir="<?php echo $language_direction?>" >
<?php if($title): ?>
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <div class="container-fluid">
                    <a class="navbar-brand" href="#"><?php echo $this->escapeHtml($title);?></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="navbar-nav">

                    </ul>
                    <ul class="navbar-nav ms-auto">

                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav><!----end of nav--->
<?php endif; ?>
    <div class='row'>
        <div class="col-md-12">
            <?php echo $this->content; ?>
        </div>
    </div>
    <footer>

    </footer>
</div>
