CREATE TABLE IF NOT EXISTS `wmt_plan_fav` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`date` DATETIME DEFAULT NULL,
	`user` VARCHAR(255) DEFAULT NULL,
	`code_type` VARCHAR(15) DEFAULT NULL,
	`code` VARCHAR(15) DEFAULT NULL,
	`type` VARCHAR(15) DEFAULT NULL,
	`plan` TEXT DEFAULT NULL,
	`seq` VARCHAR(8) DEFAULT NULL,
	`title` VARCHAR(255) DEFAULT NULL,
	`notes` TEXT DEFAULT NULL,
	`list_user` VARCHAR(255) DEFAULT NULL,
	`global_list` TINYINT(1),
PRIMARY KEY (`id`)

) ENGINE=InnoDB;
