CREATE TABLE IF NOT EXISTS `form_vitalsigns` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
standing_bp_1 longtext,
standing_bp_2 longtext,
sitting_bp_1 longtext,
sitting_bp_2 longtext,
supine_bp_1 longtext,
supine_bp_2 longtext,
systolic_bp_1 longtext,
systolic_bp_2 longtext,
diastolic_bp_1 longtext,
diastolic_bp_2 longtext,
heart_rate_beats_per_minute longtext,
temperature_c longtext,
temperature_f longtext,
temperature_method longtext,
respiration_beats_per_minute longtext,
height_feet longtext,
height_inches longtext,
height_centimeters longtext,
weight_lbs longtext,
weight_ozs longtext,
weight_kgs longtext,
body_mass_index longtext,
figure_shape longtext,
additional_notes longtext,
PRIMARY KEY (id)
) TYPE=MyISAM;
