<?php
/**
 * interface/modules/zend_modules/module/Syndromicsurveillance/view/layout/layout.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Vinish K <vinish@zhservices.com>
 * @copyright Copyright (c) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
?>
<?php
echo $this->doctype();
use OpenEMR\Core\Header;
?>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle($this->translate()->xl('Syndromic Surveillance - Non Reported Issues'))->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php Header::setupHeader(['datetime-picker', 'modernizr', 'laminas-style']); ?>
        <script src="<?php echo $this->basePath(); ?>/js/scripts/syndromicsurveillance.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/application/sendTo.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/application/common.js"></script>
        <script>
        $(function() {
            $(".dateClass_syndrome").datetimepicker({
              <?php $datetimepicker_timepicker = false; ?>
              <?php $datetimepicker_showseconds = false; ?>
              <?php $datetimepicker_formatInput = false; ?>
              <?php require($GLOBALS['srcdir'] . '/js/xl/jquery-datetimepicker-2-5-4.js.php'); ?>
            });
        });
        </script>
    </head>
    <body class="body_top">
        <div class="container-fluid">
            <?php echo $this->javascriptGlobals(); ?>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
