<?php
/**
 * interface/modules/zend_modules/module/Syndromicsurveillance/view/layout/layout.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Vinish K <vinish@zhservices.com>
 * @copyright Copyright (c) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
?>
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate()->xl('Syndromic Surveillance - Non Reported Issues'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/responsive-tables.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/css/carecoordination_style.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/sendTo.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/scripts/syndromicsurveillance.js')
        ->prependFile($this->basePath() . '/js/application/sendTo.js')
        ->prependFile($this->basePath() . '/js/application/common.js')
        ->prependFile($this->basePath() . '/js/lib/jquery-ui.custom.js')
        ->prependFile($this->basePath() . '/js/lib/jquery.ui.datepicker.js')
        ->prependFile($this->basePath() . '/js/lib/jquery.ui.core.js')
        ->prependFile($this->basePath() . '/js/lib/jquery-ui.js')
        ->prependFile($this->basePath() . '/js/lib/jquery-1.10.2.min.js')
        ->prependFile($this->basePath() . '/js/lib/modernizr-2.6.2.min.js')
        ?>

    </head>
    <body class="body_top">
        <div class="container" style="width:100%">
            <?php echo $this->javascriptGlobals(); ?>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
