<?php
/**
 * interface/modules/zend_modules/module/Application/view/layout/layout.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Tyler Wrenn <tyler@tylerwrenn.com>
 * @copyright Copyright (c) 2020 Tyler Wrenn <tyler@tylerwrenn.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
echo $this->doctype();
use OpenEMR\Core\Header;
?>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('ZF2 '. $this->translate()->xl('OpenEMR Application'))->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php Header::setupHeader(['laminas-style']); ?>
    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
            <hr />
            <footer>
                <p></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
