<?php
/**
 * interface/modules/zend_modules/module/Application/view/layout/sendto.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Tyler Wrenn <tyler@tylerwrenn.com>
 * @copyright Copyright (c) 2020 Tyler Wrenn <tyler@tylerwrenn.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
echo $this->doctype();
use OpenEMR\Core\Header;
?>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('ZF2 '. $this->translate()->xl('OpenEMR'))->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php Header::setupHeader(); ?>
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/style.css" />
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/sendTo.css" />
        <script src="<?php echo $this->basePath(); ?>/js/autosuggest/autosuggest.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/application/sendTo.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/application/addRule.js"></script>
        <script>
          var APP_URL = "<?php echo $this->basePath(); ?>";
          var WEB_ROOT = "<?php echo $GLOBALS['webroot']; ?>";
        </script>
    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
