<?php

require_once("../../globals.php");
require_once("$srcdir/api.inc");
require_once("$srcdir/forms.inc");

if ($encounter == "") {
    $encounter = date("Ymd");
}

if ($_GET["mode"] == "new") {
    $newid = formSubmit("form_assessment_intake", $_POST, $_GET["id"], $userauthorized);
    print 'formSubmitt';  /*debugging */
    addForm($encounter, "Assessment and Intake", $newid, "assessment_intake", $pid, $userauthorized);
} elseif ($_GET["mode"] == "update") {
    sqlInsert("update form_assessment_intake set pid = '" . add_escape_custom($_SESSION["pid"]) . "',groupname='" . add_escape_custom($_SESSION["authProvider"]) . "',user='" . add_escape_custom($_SESSION["authUser"]) . "',authorized='" . add_escape_custom($userauthorized) . "',activity=1, date = NOW(), 
dcn='".add_escape_custom($_POST["dcn"])."', 
location='".add_escape_custom($_POST["location"])."',
time_in='".add_escape_custom($_POST["time_in"])."',
time_out='".add_escape_custom($_POST["time_out"])."',
referral_source='".add_escape_custom($_POST["referral_source"])."',
new_client_eval='".add_escape_custom($_POST["new_client_eval"])."',
readmission='".add_escape_custom($_POST["readmission"])."',
consultation='".add_escape_custom($_POST["consultation"])."',
copy_sent_to='".add_escape_custom($_POST["copy_sent_to"])."',
reason_why='".add_escape_custom($_POST["reason_why"])."',
behavior_led_to='".add_escape_custom($_POST["behavior_led_to"])."',
school_work='".add_escape_custom($_POST["school_work"])."',
personal_relationships='".add_escape_custom($_POST["personal_relationships"])."',
fatherc='".add_escape_custom($_POST["fatherc"])."',
motherc='".add_escape_custom($_POST["motherc"])."',
father_involved='".add_escape_custom($_POST["father_involved"])."',
mother_involved='".add_escape_custom($_POST["mother_involved"])."',
number_children='".add_escape_custom($_POST["number_children"])."',
siblings='".add_escape_custom($_POST["siblings"])."',
other_relationships='".add_escape_custom($_POST["other_relationships"])."',
social_relationships='".add_escape_custom($_POST["social_relationships"])."',
current_symptoms='".add_escape_custom($_POST["current_symptoms"])."',
personal_strengths='".add_escape_custom($_POST["personal_strengths"])."',
spiritual='".add_escape_custom($_POST["spiritual"])."',
legal='".add_escape_custom($_POST["legal"])."',
prior_history='".add_escape_custom($_POST["prior_history"])."',
number_admitt='".add_escape_custom($_POST["number_admitt"])."',
type_admitt='".add_escape_custom($_POST["type_admitt"])."',
substance_use='".add_escape_custom($_POST["substance_use"])."',
substance_abuse='".add_escape_custom($_POST["substance_abuse"])."',
axis1='".add_escape_custom($_POST["axis1"])."',
axis2='".add_escape_custom($_POST["axis2"])."',
axis3='".add_escape_custom($_POST["axis3"])."',
allergies='".add_escape_custom($_POST["allergies"])."',
ax4_prob_support_group='".add_escape_custom($_POST["ax4_prob_support_group"])."',
ax4_prob_soc_env='".add_escape_custom($_POST["ax4_prob_soc_env"])."',
ax4_educational_prob='".add_escape_custom($_POST["ax4_educational_prob"])."',
ax4_occ_prob='".add_escape_custom($_POST["ax4_occ_prob"])."',
ax4_housing='".add_escape_custom($_POST["ax4_housing"])."',
ax4_economic='".add_escape_custom($_POST["ax4_economic"])."',
ax4_access_hc='".add_escape_custom($_POST["ax4_access_hc"])."',
ax4_legal='".add_escape_custom($_POST["ax4_legal"])."',
ax4_other_cb='".add_escape_custom($_POST["ax4_other_cb"])."',
ax4_other='".add_escape_custom($_POST["ax4_other"])."',
ax5_current='".add_escape_custom($_POST["ax5_current"])."',
ax5_past='".add_escape_custom($_POST["ax5_past"])."',
risk_suicide_na='".add_escape_custom($_POST["risk_suicide_na"])."',
risk_suicide_nk='".add_escape_custom($_POST["risk_suicide_nk"])."',
risk_suicide_io='".add_escape_custom($_POST["risk_suicide_io"])."',
risk_suicide_plan='".add_escape_custom($_POST["risk_suicide_plan"])."',
risk_suicide_iwom='".add_escape_custom($_POST["risk_suicide_iwom"])."',
risk_suicide_iwm='".add_escape_custom($_POST["risk_suicide_iwm"])."',
risk_homocide_na='".add_escape_custom($_POST["risk_homocide_na"])."',
risk_homocide_nk='".add_escape_custom($_POST["risk_homocide_nk"])."',
risk_homocide_io='".add_escape_custom($_POST["risk_homocide_io"])."',
risk_homocide_plan='".add_escape_custom($_POST["risk_homocide_plan"])."',
risk_homocide_iwom='".add_escape_custom($_POST["risk_homocide_iwom"])."',
risk_homocide_iwm='".add_escape_custom($_POST["risk_homocide_iwm"])."',
risk_compliance_na='".add_escape_custom($_POST["risk_compliance_na"])."',
risk_compliance_fc='".add_escape_custom($_POST["risk_compliance_fc"])."',
risk_compliance_mc='".add_escape_custom($_POST["risk_compliance_mc"])."',
risk_compliance_moc='".add_escape_custom($_POST["risk_compliance_moc"])."',
risk_compliance_var='".add_escape_custom($_POST["risk_compliance_var"])."',
risk_compliance_no='".add_escape_custom($_POST["risk_compliance_no"])."',
risk_substance_na ='".add_escape_custom($_POST["risk_substance_na"])."',
risk_substance_none='".add_escape_custom($_POST["risk_substance_none"])."',
risk_normal_use='".add_escape_custom($_POST["risk_normal_use"])."',
risk_substance_ou='".add_escape_custom($_POST["risk_substance_ou"])."',
risk_substance_dp='".add_escape_custom($_POST["risk_substance_dp"])."',
risk_substance_ur='".add_escape_custom($_POST["risk_substance_ur"])."',
risk_substance_ab='".add_escape_custom($_POST["risk_substance_ab"])."',
risk_sexual_na='".add_escape_custom($_POST["risk_sexual_na"])."',
risk_sexual_y='".add_escape_custom($_POST["risk_sexual_y"])."',
risk_sexual_n='".add_escape_custom($_POST["risk_sexual_n"])."',
risk_sexual_ry='".add_escape_custom($_POST["risk_sexual_ry"])."',
risk_sexual_rn='".add_escape_custom($_POST["risk_sexual_rn"])."',
risk_sexual_cv='".add_escape_custom($_POST["risk_sexual_cv"])."',
risk_sexual_cp='".add_escape_custom($_POST["risk_sexual_cp"])."',
risk_sexual_b='".add_escape_custom($_POST["risk_sexual_b"])."',
risk_sexual_nf='".add_escape_custom($_POST["risk_sexual_nf"])."',
risk_neglect_na='".add_escape_custom($_POST["risk_neglect_na"])."',
risk_neglect_y='".add_escape_custom($_POST["risk_neglect_y"])."',
risk_neglect_n='".add_escape_custom($_POST["risk_neglect_n"])."',
risk_neglect_ry='".add_escape_custom($_POST["risk_neglect_ry"])."',
risk_neglect_rn='".add_escape_custom($_POST["risk_neglect_rn"])."',
risk_neglect_cv='".add_escape_custom($_POST["risk_neglect_cv"])."',
risk_neglect_cp='".add_escape_custom($_POST["risk_neglect_cp"])."',
risk_neglect_cb='".add_escape_custom($_POST["risk_neglect_cb"])."',
risk_neglect_cn='".add_escape_custom($_POST["risk_neglect_cn"])."',
risk_exists_c='".add_escape_custom($_POST["risk_exists_c"])."',
risk_exists_cn='".add_escape_custom($_POST["risk_exists_cn"])."',
risk_exists_s='".add_escape_custom($_POST["risk_exists_s"])."',
risk_exists_o='".add_escape_custom($_POST["risk_exists_o"])."',
risk_exists_b='".add_escape_custom($_POST["risk_exists_b"])."',
risk_community='".add_escape_custom($_POST["risk_community"])."',
recommendations_psy_i='".add_escape_custom($_POST["recommendations_psy_i"])."',
recommendations_psy_f='".add_escape_custom($_POST["recommendations_psy_f"])."',
recommendations_psy_m='".add_escape_custom($_POST["recommendations_psy_m"])."',
recommendations_psy_o='".add_escape_custom($_POST["recommendations_psy_o"])."',
recommendations_psy_notes='".add_escape_custom($_POST["recommendations_psy_notes"])."',
refer_date='".add_escape_custom($_POST["refer_date"])."',
parent ='".add_escape_custom($_POST["parent"])."',
supervision_level='".add_escape_custom($_POST["supervision_level"])."',
supervision_type='".add_escape_custom($_POST["supervision_type"])."',
supervision_res='".add_escape_custom($_POST["supervision_res"])."',
supervision_services='".add_escape_custom($_POST["supervision_services"])."',
support_ps='".add_escape_custom($_POST["support_ps"])."',
support_cs='".add_escape_custom($_POST["support_cs"])."',
support_sm='".add_escape_custom($_POST["support_sm"])."',
support_a='".add_escape_custom($_POST["support_a"])."',
support_o='".add_escape_custom($_POST["support_o"])."',
support_ol='".add_escape_custom($_POST["support_ol"])."',
legal_op='".add_escape_custom($_POST["legal_op"])."',
legal_so='".add_escape_custom($_POST["legal_so"])."',
legal_sa='".add_escape_custom($_POST["legal_sa"])."',
legal_ve='".add_escape_custom($_POST["legal_ve"])."',
legal_ad='".add_escape_custom($_POST["legal_ad"])."',
legal_adl='".add_escape_custom($_POST["legal_adl"])."',
legal_o='".add_escape_custom($_POST["legal_o"])."',
legal_ol='".add_escape_custom($_POST["legal_ol"])."',
referrals_pepm='".add_escape_custom($_POST["referrals_pepm"])."',
referrals_mc='".add_escape_custom($_POST["referrals_mc"])."',
referrals_vt='".add_escape_custom($_POST["referrals_vt"])."',
referrals_o='".add_escape_custom($_POST["referrals_o"])."',
referrals_cu='".add_escape_custom($_POST["referrals_cu"])."',
referrals_docs='".add_escape_custom($_POST["referrals_docs"])."',
referrals_or='".add_escape_custom($_POST["referrals_or"])."' where id='".add_escape_custom($id)."'");
}

$_SESSION["encounter"] = $encounter;
formHeader("Redirecting....");
formJump();
formFooter();
