<?php
/**
 * interface/modules/zend_modules/module/Installer/view/installer/installer/configure.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Jacob T.Paul <jacob@zhservices.com>
 * @author    Vipin Kumar <vipink@zhservices.com>
 * @author    Remesh Babu S <remesh@zhservices.com>
 * @copyright Copyright (c) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

// Warning : PoC code
// TBD - Must handle modules in external namespaces
Use OpenEMR\Modules;

$listener = $this->listenerObject;
$hangers = $this->hangers;
$Hooks = $this->Hooks;
$hookObj = $this->hookObject;
$mod_id = $this->mod_id;
$title = $listener->z_xlt('Module Installer');
$this->headTitle($title);
$baseModuleDir = $GLOBALS['baseModDir'];
$customDir = $GLOBALS['customModDir'];
$zendModDir = $GLOBALS['zendModDir'];
$confirmationMSG = $listener->z_xlt("Do you really want to delete?");
// TODO: Change all of these magic numbers into constants, set them in the view and use them here so we can know what this all means.
if (count($TabSettings) > 0) {

    ?>
    <div class="easyui-tabs container" id="tab<?php echo $this->escapeHtml($mod_id); ?>" style="width:950px;height:auto;">
        <?php
        if (isset($TabSettings[1]) && $TabSettings[1] > 0) {
            ?>
            <div title="<?php echo $listener->z_xla('Access Control'); ?>" id="tab_acl<?php echo $this->escapeHtml($mod_id); ?>" iconCls="icon-acl">
                <div class="easyui-accordion" id="configaccord<?php echo $this->escapeHtml($mod_id); ?>" style="width:930px;height:auto;align:center;margin:5px">
                    <iframe src="<?php echo $GLOBALS['webroot']; ?>/interface/modules/zend_modules/public/acl/acltab?module_id=<?php echo $this->escapeHtml($this->mod_id); ?>" style="width:100%;height: 700px;overflow: hidden;" frameborder="0"></iframe>
                </div>
            </div>
            <?php
        } else {
            ?>
            <div class="easyui-accordion" id="configaccord<?php echo $this->escapeHtml($mod_id); ?>" style="width:930px;height:auto;align:center;margin:5px"></div>
            <?php
        }
        if (isset($TabSettings[2]) && $TabSettings[2] > 0) {
            ?>
            <div title="<?php echo $listener->z_xla('Preference'); ?>" id="tab_preference<?php echo $this->escapeHtml($mod_id); ?>" iconCls="icon-preference">
                <!-- For Future Development-->
            </div>
            <?php
        }
        if (isset($TabSettings[3]) && $TabSettings[3] > 0) {
            $modID = '';
            ?>
            <div title="<?php echo $listener->z_xla('Hooks'); ?>" id="tab_hooks<?php echo $this->escapeHtml($mod_id); ?>" iconCls="icon-plug">
                <table width="100%">
                    <tr>
                        <td colspan="2" align="center" style="font-size:14px;font-weight:bold">
                            <?php echo $listener->z_xlt("Manage Hooks"); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <form name="hooksform<?php echo $this->escapeHtml($mod_id); ?>" id="hooksform<?php echo $this->escapeHtml($mod_id); ?>">
                                <table width="100%">
                                    <tr>
                                        <td style="width: 150px"><span id="hook_response<?php echo $this->escapeHtml($mod_id); ?>">&nbsp;</span></td>
                                        <?php
                                        $hanger_count = 0;
                                        foreach ($hangers as $value => $title) {
                                            ?>
                                            <td align="center"><?php echo $listener->z_xlt($title); ?></td>
                                            <?php
                                            $hanger_count++;
                                        }
                                        ?>
                                    </tr>
                                    <?php
                                    if (count($Hooks) > 0) {
                                        foreach ($Hooks as $obj_hooks) {
                                            ?>
                                            <tr>
                                                <td><?php echo $listener->z_xlt($obj_hooks['title']); ?></td>
                                                <?php
                                                foreach ($hangers as $value => $title) {
                                                    $checked = "";
                                                    if ($hookObj->getHookStatus($mod_id, $obj_hooks['name'], $value) == "1") {
                                                        $checked = "checked=\"checked\"";
                                                    }
                                                    ?>
                                                    <td align="center">
                                                        <input type="checkbox" <?php echo $checked; ?>
                                                            name="hook_hanger[<?php echo $this->escapeHtml($obj_hooks['name']); ?>][<?php echo $this->escapeHtml($value); ?>]"
                                                            id="hook_hanger_<?php echo $this->escapeHtml($obj_hooks['name']); ?>_<?php echo $this->escapeHtml($value); ?>"
                                                            value="<?php echo $this->escapeHtml($obj_hooks['name']) . "," . $this->escapeHtml($value); ?>"
                                                            onclick="javascript:SaveMe('hooksform',<?php echo $this->escapeHtml($mod_id); ?>)">
                                                    </td>
                                                    <?php
                                                }
                                                ?>
                                            </tr>
                                            <?php
                                        }
                                    } else { ?>
                                        <tr>
                                            <td colspan="<?php echo $this->escapeHtml($hanger_count) + 1; ?>" align="center" style="font-size:14px">
                                                <?php echo $listener->z_xlt('No Hooks Available in this Module'); ?>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                    ?>
                                </table>
                                <input type="hidden" name="mod_id" value="<?php echo $this->escapeHtml($mod_id); ?>">
                            </form>
                        </td>
                    </tr>
                </table>
            </div>
            <!-- Start Configuration Tab -->
            <div title="<?php echo $listener->z_xla('Settings'); ?>" id="tab_config<?php echo $this->escapeHtml($mod_id); ?>" iconCls="icon-preference">
                <?php
                if (is_object($this->settings) && count($this->settings) > 0) {

                    $form = $this->settings;
                    if (method_exists($form, 'prepare')) {
                        $form->prepare();
                        ?>
                        <form name="configform" id="configform<?php echo $this->escapeHtml($mod_id); ?>">
                            <table style="width:100%; margin: 0px; height: 140px">
                                <?php

                                $i = 0;
                                foreach ($form as $element) :
                                    ?>
                                    <tr>
                                        <td width='15%'><?php echo $listener->z_xlt($element->getLabel()) ?></td>
                                        <td><?php echo $this->formElement($element->setValue($configuration[$element->getAttribute('id')]['field_value'] ?? null)); ?></td>
                                    </tr>
                                    <?php
                                    $i++;
                                endforeach;
                                ?>
                                <tr>
                                    <td></td>
                                    <td>
                                        <a href="#" class="easyui-linkbutton" iconCls="icon-save"
                                            plain="true" onclick="javascript:saveConfig('configform',<?php echo $this->escapeHtml($mod_id); ?>)">
                                            <?php echo $listener->z_xlt('Save'); ?>
                                        </a>
                                        <span id='target<?php echo $this->escapeHtml($mod_id); ?>' style="color: #996600"></span>
                                    </td>
                                </tr>
                            </table>
                            <input type="hidden" name="module_id" value="<?php echo $this->escapeHtml($mod_id); ?>">
                        </form>
                        <?php
                    } else {
                        echo $listener->z_xlt('No Settings avaliable in this module');
                    }
                } else {
                    echo $listener->z_xlt('No Settings avaliable in this module');
                }
                ?>
            </div>
            <!-- End Configuration Tab -->
            <?php
        }
        ?>
        <?php if (count($setup) > 0) { ?>
            <div title="<?php echo $listener->z_xla($setup['title']); ?>" style="height:auto;"
                id="tab_config<?php echo $this->escapeHtml($mod_id); ?>"
                iconCls="icon-setup">
                <iframe scrolling="yes" frameborder="0"
                    src="<?php echo $this->basePath() . '/' . $this->escapeHtml($setup['module_dir']); ?>/setup/index"
                    style="width:100%;height:400px;">
                </iframe>
            </div>
        <?php } ?>
    </div>
    <?php
} elseif (count($setup) > 0) { ?>
    <div class="easyui-tabs container" id="tab<?php echo $this->escapeHtml($mod_id); ?>" style="height:auto;">
        <div title="<?php echo $listener->z_xla($setup['title']); ?>"
            id="tab_config<?php echo $this->escapeHtml($mod_id); ?>"
            iconCls="icon-setup">
            <iframe scrolling="yes" frameborder="0"
                src="<?php echo $this->basePath() . '/' . $this->escapeHtml($setup['module_dir']); ?>/setup/index"
                style="width:100%;height:400px;">
            </iframe>
        </div>
    </div>
    <?php
} else {
    // Final check for config
    // TBD : clsOeModule
    $rs_mod = sqlQuery('select * from modules where mod_id=? and mod_active=1', [$mod_id]);
    $fConfig = dirname(realpath('.')) . '/custom_modules/' . $rs_mod['mod_directory'] . '/moduleConfig.php';
    if (($rs_mod['type'] == 0) && file_exists($fConfig)) {
        ?>
        <div class="container" id="tab<?php echo $this->escapeHtml($mod_id); ?>" style="height:100vh;">
            <iframe src="<?php echo dirname($this->basePath(), 2) . '/custom_modules/' . $rs_mod['mod_directory'] . '/moduleConfig.php'; ?>"
                style="width:100%;height:100%;border:0px">
            </iframe>
        </div>
        <?php
    } else {
        ?>
        <div class="easyui-tabs container" id="tab<?php echo $this->escapeHtml($mod_id); ?>" style="height:auto;">
            <?php echo $listener->z_xlt('No Configuration Defined for this Module'); ?>
        </div>
        <?php
    }
}
?>
