<?php
// +-----------------------------------------------------------------------------+
//OpenEMR - Open Source Electronic Medical Record
//    Copyright (C) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as
//    published by the Free Software Foundation, either version 3 of the
//    License, or (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
// 		Author:   Jacob T.Paul <jacob@zhservices.com>
//							Vipin Kumar <vipink@zhservices.com>
// +------------------------------------------------------------------------------+

$listener	= $this->listenerObject;
$hangers    = $this->hangers;
$Hooks = $this->Hooks;
$hookObj    =  $this->hookObject;
$mod_id = $this->mod_id;
$title = $listener->z_xlt('Module Installer');
$this->headTitle($title);
$baseModuleDir 	= $GLOBALS['baseModuleDir'];
$customDir 	= $GLOBALS['customDir'];
$zendModDir 	= $GLOBALS['zendModDir'];
$confirmationMSG = $listener->z_xlt("Do you really want to delete?");
if(count($TabSettings)>0){
    
?>
<div class="easyui-tabs" id="tab<?php echo $mod_id; ?>" style="width:800px;height:auto;">
<?php
  if($TabSettings[1]['cnt'] > 0){            
?>
    <div title="<?php echo $listener->z_xlt('Access Control');?>" id="tab_acl<?php echo $mod_id; ?>" iconCls="icon-acl">
      <div class="easyui-accordion" id="configaccord<?php echo $mod_id; ?>" style="width:787px;height:auto;align:center;margin:5px">
        <iframe src="<?php echo $GLOBALS['webroot']; ?>/interface/modules/zend_modules/public/acl/acltab?module_id=<?php echo $this->mod_id; ?>" style="width:100%;height: 700px;overflow: hidden;" frameborder="0"></iframe>
      </div>    
    </div>
  <?php       
  }else{
  ?>
    <div class="easyui-accordion" id="configaccord<?php echo $mod_id; ?>" style="width:787px;height:auto;align:center;margin:5px"></div>
  <?php
  }
  if($TabSettings[2]['cnt'] > 0){
?>
    <div title="<?php echo $listener->z_xlt('Preference');?>" id="tab_preference<?php echo $mod_id; ?>" iconCls="icon-preference">  
    <!-- For Future Development-->
    </div>
<?php
}
if($TabSettings[3]['cnt'] > 0){
  $modID = '';
?>
    <div title="<?php echo $listener->z_xlt('Hooks');?>" id="tab_hooks<?php echo $mod_id; ?>" iconCls="icon-plug" > 
      <table width="100%">
            <tr>
              <td colspan="2" align="center" style="font-size:14px;font-weight:bold">
                 <?php echo $listener->z_xlt("Manage Hooks");?>
              </td>
            </tr>
            <tr>
                <td>
                  <form name="hooksform<?php echo $mod_id; ?>" id="hooksform<?php echo $mod_id; ?>">                    
                    <table  width="100%">
                        <tr>
                            <td style="width: 150px"><span id="hook_response<?php echo $mod_id; ?>">&nbsp;</span></td>
                            <?php
                                $hanger_count = 0;
                                foreach($hangers as $value => $title){ 
                                ?>
                                    <td align="center"><?php echo $listener->z_xlt($title);?></td>
                            <?php
                                    $hanger_count++;
                                }
                                ?>                                
                        </tr>
                        <?php
                        if(count($Hooks)> 0){
                            foreach($Hooks as $obj_hooks){                               
                            ?>
                            <tr>
                                <td><?php echo $listener->z_xlt($obj_hooks['title']);?></td>
                                <?php
                                    foreach($hangers as $value => $title){
                                        $checked = "";
                                        if($hookObj->getHookStatus($mod_id,$obj_hooks['name'],$value) == "1"){
                                            $checked = "checked=\"checked\"";
                                        }
                                    ?>
                                        <td align="center">
                                            <input type="checkbox" <?php echo $checked; ?>
                                                name="hook_hanger[<?php echo $obj_hooks['name'];?>][<?php echo $value; ?>]"
                                                id="hook_hanger_<?php echo $obj_hooks['name'];?>_<?php echo $value; ?>"
                                                value="<?php echo $obj_hooks['name'].",".$value;?>"
                                                onclick="javascript:SaveMe('hooksform',<?php echo $mod_id;?>)" >
                                        </td>
                                <?php
                                    }
                                    ?>    
                            </tr>    
                        <?php
                            }
                        }  
                                else{ ?>
                            <tr>                            
                            <td  colspan="<?php echo $hanger_count+1; ?>" align="center" style="font-size:14px">
                                <?php echo $listener->z_xlt('No Hooks Available in this Module'); ?>
                            </td>
                        </tr>
                        <?php
                            }
                                    ?>                            
                    </table>
                    <input type="hidden" name="mod_id" value="<?php echo $mod_id;?>">
                  </form>
                </td>
            </tr>            
        </table>
    </div>
    <!-- Start Configuration Tab -->
     <div title="<?php echo $listener->z_xlt('Settings');?>" id="tab_config<?php echo $mod_id; ?>" iconCls="icon-preference"> 
        <?php
            //var_dump($this->settings);
            if(is_object($this->settings) && count($this->settings) > 0){
                
            $form = $this->settings;
                if(method_exists($form,'prepare')){
                    $form->prepare();                
        ?>
         <form name="configform" id="configform<?php echo $mod_id; ?>">
            <table style="width:100%; margin: 0px; height: 140px">
                    <?php
                            
                    $i = 0;
                    foreach ($form as $element) : 
                    ?>
                    <tr>
                            <td width='15%'><?php echo $listener->z_xlt($element->getLabel()) ?></td>
                            <td><?php echo $this->formElement($element->setValue($configuration[$i]['field_value'])); ?></td>
                    </tr>
                    <?php
                    $i++;
                     endforeach;        
                    ?>
                <tr>
                    <td></td>
                    <td>
                       <a href="#" class="easyui-linkbutton" iconCls="icon-save" 
                          plain="true" onclick="javascript:saveConfig('configform',<?php echo $mod_id;?>)">
                              <?php echo $listener->z_xlt('Save'); ?>
                       </a>
                        <span id='target<?php echo $mod_id; ?>' style="color: #996600" ></span>
                    </td>
                </tr>
            </table>
             <input type="hidden" name="module_id" value="<?php echo $mod_id;?>">
         </form>
         <?php
         }
                else {
                    echo $listener->z_xlt('No Settings avaliable in this module');
                }
            }
            else {
                echo $listener->z_xlt('No Settings avaliable in this module');
            }
         ?>
     </div>
    <!-- End Configuration Tab -->
    <?php    
    }
    ?>
</div>
<?php
}
else{
?>
    <div class="easyui-tabs" id="tab<?php echo $mod_id; ?>" style="width:800px;height:auto;">
    <?php echo $listener->z_xlt('No Configuration Defined for this Module');?>
    </div>
<?php
}
?>
<script>
  function saveConfig(frmId, mod_id) {
    $.ajax({
      type: 'POST',
      url: "./Installer/saveConfig",
      data: $('#' + frmId + mod_id).serialize(),   
      success: function(data){
        $('#target' + data.modeId).html('<?php echo $listener->z_xlt('Configuration saved successfully'); ?> ....').show().fadeOut(4000);
      }
    });
  }
</script>
    
    
