<?php

/**
 * PHPStan Type Aliases for OpenEMR Database Tables
 *
 * THIS FILE IS GENERATED - DO NOT EDIT MANUALLY
 *
 * Regenerate with: composer generate-phpstan-types
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

namespace OpenEMR\Common\Database;

/**
 * Type definitions for database row arrays
 *
 * Import this interface and reference types with @see annotations:
 *   @return TableTypes::PatientDataRow|false
 *
 * @phpstan-type PatientDataRow array{
 *   id: numeric-string,
 *   uuid: ?string,
 *   title: string,
 *   language: string,
 *   financial: string,
 *   fname: string,
 *   lname: string,
 *   mname: string,
 *   DOB: ?string,
 *   street: string,
 *   postal_code: string,
 *   city: string,
 *   state: string,
 *   country_code: string,
 *   drivers_license: string,
 *   ss: string,
 *   occupation: ?string,
 *   phone_home: string,
 *   phone_biz: string,
 *   phone_contact: string,
 *   phone_cell: string,
 *   pharmacy_id: numeric-string,
 *   status: string,
 *   contact_relationship: string,
 *   date: ?string,
 *   sex: string,
 *   referrer: string,
 *   referrerID: string,
 *   providerID: ?numeric-string,
 *   ref_providerID: ?numeric-string,
 *   email: string,
 *   email_direct: string,
 *   ethnoracial: string,
 *   race: string,
 *   ethnicity: string,
 *   religion: string,
 *   interpreter: string,
 *   interpreter_needed: ?string,
 *   migrantseasonal: string,
 *   family_size: string,
 *   monthly_income: string,
 *   billing_note: ?string,
 *   homeless: string,
 *   financial_review: ?string,
 *   pubpid: string,
 *   pid: numeric-string,
 *   genericname1: string,
 *   genericval1: string,
 *   genericname2: string,
 *   genericval2: string,
 *   hipaa_mail: string,
 *   hipaa_voice: string,
 *   hipaa_notice: string,
 *   hipaa_message: string,
 *   hipaa_allowsms: string,
 *   hipaa_allowemail: string,
 *   squad: string,
 *   fitness: numeric-string,
 *   referral_source: string,
 *   usertext1: string,
 *   usertext2: string,
 *   usertext3: string,
 *   usertext4: string,
 *   usertext5: string,
 *   usertext6: string,
 *   usertext7: string,
 *   usertext8: string,
 *   userlist1: string,
 *   userlist2: string,
 *   userlist3: string,
 *   userlist4: string,
 *   userlist5: string,
 *   userlist6: string,
 *   userlist7: string,
 *   pricelevel: string,
 *   regdate: ?string,
 *   contrastart: ?string,
 *   completed_ad: string,
 *   ad_reviewed: ?string,
 *   advance_directive_user_authenticator: ?numeric-string,
 *   vfc: string,
 *   mothersname: string,
 *   guardiansname: ?string,
 *   allow_imm_reg_use: string,
 *   allow_imm_info_share: string,
 *   allow_health_info_ex: string,
 *   allow_patient_portal: string,
 *   deceased_date: ?string,
 *   deceased_reason: string,
 *   soap_import_status: ?numeric-string,
 *   cmsportal_login: string,
 *   care_team_provider: ?string,
 *   care_team_facility: ?string,
 *   care_team_status: ?string,
 *   county: string,
 *   industry: ?string,
 *   imm_reg_status: ?string,
 *   imm_reg_stat_effdate: ?string,
 *   publicity_code: ?string,
 *   publ_code_eff_date: ?string,
 *   protect_indicator: ?string,
 *   prot_indi_effdate: ?string,
 *   guardianrelationship: ?string,
 *   guardiansex: ?string,
 *   guardianaddress: ?string,
 *   guardiancity: ?string,
 *   guardianstate: ?string,
 *   guardianpostalcode: ?string,
 *   guardiancountry: ?string,
 *   guardianphone: ?string,
 *   guardianworkphone: ?string,
 *   guardianemail: ?string,
 *   sexual_orientation: ?string,
 *   gender_identity: ?string,
 *   birth_fname: ?string,
 *   birth_lname: ?string,
 *   birth_mname: ?string,
 *   dupscore: numeric-string,
 *   name_history: ?string,
 *   suffix: ?string,
 *   street_line_2: ?string,
 *   patient_groups: ?string,
 *   prevent_portal_apps: ?string,
 *   provider_since_date: ?string,
 *   created_by: ?numeric-string,
 *   updated_by: ?numeric-string,
 *   preferred_name: ?string,
 *   nationality_country: ?string,
 *   last_updated: string,
 *   tribal_affiliations: ?string,
 *   sex_identified: ?string,
 *   pronoun: ?string
 * }
 *
 * @phpstan-type UsersRow array{
 *   id: numeric-string,
 *   uuid: ?string,
 *   username: ?string,
 *   password: ?string,
 *   authorized: ?numeric-string,
 *   info: ?string,
 *   source: ?numeric-string,
 *   fname: ?string,
 *   mname: ?string,
 *   lname: ?string,
 *   suffix: ?string,
 *   federaltaxid: ?string,
 *   federaldrugid: ?string,
 *   upin: ?string,
 *   facility: ?string,
 *   facility_id: numeric-string,
 *   see_auth: numeric-string,
 *   active: numeric-string,
 *   npi: ?string,
 *   title: ?string,
 *   specialty: ?string,
 *   billname: ?string,
 *   email: ?string,
 *   email_direct: string,
 *   google_signin_email: ?string,
 *   url: ?string,
 *   assistant: ?string,
 *   organization: ?string,
 *   valedictory: ?string,
 *   street: ?string,
 *   streetb: ?string,
 *   city: ?string,
 *   state: ?string,
 *   zip: ?string,
 *   country_code: ?string,
 *   street2: ?string,
 *   streetb2: ?string,
 *   city2: ?string,
 *   state2: ?string,
 *   zip2: ?string,
 *   country_code2: ?string,
 *   phone: ?string,
 *   fax: ?string,
 *   phonew1: ?string,
 *   phonew2: ?string,
 *   phonecell: ?string,
 *   notes: ?string,
 *   cal_ui: numeric-string,
 *   taxonomy: string,
 *   calendar: numeric-string,
 *   abook_type: string,
 *   default_warehouse: string,
 *   irnpool: string,
 *   state_license_number: ?string,
 *   weno_prov_id: ?string,
 *   newcrop_user_role: ?string,
 *   cpoe: ?numeric-string,
 *   physician_type: ?string,
 *   main_menu_role: string,
 *   patient_menu_role: string,
 *   portal_user: numeric-string,
 *   supervisor_id: numeric-string,
 *   billing_facility: ?string,
 *   billing_facility_id: numeric-string,
 *   date_created: string,
 *   last_updated: string
 * }
 *
 * @phpstan-type FormEncounterRow array{
 *   id: numeric-string,
 *   uuid: ?string,
 *   date: ?string,
 *   reason: ?string,
 *   facility: ?string,
 *   facility_id: numeric-string,
 *   pid: ?numeric-string,
 *   encounter: ?numeric-string,
 *   onset_date: ?string,
 *   sensitivity: ?string,
 *   billing_note: ?string,
 *   pc_catid: numeric-string,
 *   last_level_billed: numeric-string,
 *   last_level_closed: numeric-string,
 *   last_stmt_date: ?string,
 *   stmt_count: numeric-string,
 *   provider_id: ?numeric-string,
 *   supervisor_id: ?numeric-string,
 *   invoice_refno: string,
 *   referral_source: string,
 *   billing_facility: numeric-string,
 *   external_id: ?string,
 *   pos_code: ?numeric-string,
 *   parent_encounter_id: ?numeric-string,
 *   class_code: string,
 *   shift: string,
 *   voucher_number: string,
 *   discharge_disposition: ?string,
 *   encounter_type_code: ?string,
 *   encounter_type_description: ?string,
 *   referring_provider_id: ?numeric-string,
 *   date_end: ?string,
 *   in_collection: ?numeric-string,
 *   last_update: string,
 *   ordering_provider_id: ?numeric-string
 * }
 *
 * @phpstan-type InsuranceDataRow array{
 *   id: numeric-string,
 *   uuid: ?string,
 *   type: ?string,
 *   provider: ?string,
 *   plan_name: ?string,
 *   policy_number: ?string,
 *   group_number: ?string,
 *   subscriber_lname: ?string,
 *   subscriber_mname: ?string,
 *   subscriber_fname: ?string,
 *   subscriber_relationship: ?string,
 *   subscriber_ss: ?string,
 *   subscriber_DOB: ?string,
 *   subscriber_street: ?string,
 *   subscriber_postal_code: ?string,
 *   subscriber_city: ?string,
 *   subscriber_state: ?string,
 *   subscriber_country: ?string,
 *   subscriber_phone: ?string,
 *   subscriber_employer: ?string,
 *   subscriber_employer_street: ?string,
 *   subscriber_employer_postal_code: ?string,
 *   subscriber_employer_state: ?string,
 *   subscriber_employer_country: ?string,
 *   subscriber_employer_city: ?string,
 *   copay: ?string,
 *   date: ?string,
 *   pid: numeric-string,
 *   subscriber_sex: ?string,
 *   accept_assignment: string,
 *   policy_type: string,
 *   subscriber_street_line_2: ?string,
 *   subscriber_employer_street_line_2: ?string,
 *   date_end: ?string
 * }
 *
 * @phpstan-type BillingRow array{
 *   id: numeric-string,
 *   date: ?string,
 *   code_type: ?string,
 *   code: ?string,
 *   pid: ?numeric-string,
 *   provider_id: ?numeric-string,
 *   user: ?numeric-string,
 *   groupname: ?string,
 *   authorized: ?numeric-string,
 *   encounter: ?numeric-string,
 *   code_text: ?string,
 *   billed: ?numeric-string,
 *   activity: ?numeric-string,
 *   payer_id: ?numeric-string,
 *   bill_process: numeric-string,
 *   bill_date: ?string,
 *   process_date: ?string,
 *   process_file: ?string,
 *   modifier: ?string,
 *   units: ?numeric-string,
 *   fee: ?numeric-string,
 *   justify: ?string,
 *   target: ?string,
 *   x12_partner_id: ?numeric-string,
 *   ndc_info: ?string,
 *   notecodes: string,
 *   external_id: ?string,
 *   pricelevel: ?string,
 *   revenue_code: string,
 *   chargecat: ?string
 * }
 *
 * @phpstan-type BackgroundServicesRow array{
 *   name: string,
 *   title: string,
 *   active: numeric-string,
 *   running: numeric-string,
 *   next_run: string,
 *   execute_interval: numeric-string,
 *   function: string,
 *   require_once: ?string,
 *   sort_order: numeric-string,
 *   lock_expires_at: ?string
 * }
 *
 * @phpstan-type FormsRow array{
 *   id: numeric-string,
 *   date: ?string,
 *   encounter: ?numeric-string,
 *   form_name: ?string,
 *   form_id: ?numeric-string,
 *   pid: ?numeric-string,
 *   user: ?string,
 *   groupname: ?string,
 *   authorized: ?numeric-string,
 *   deleted: ?numeric-string,
 *   formdir: ?string,
 *   therapy_group_id: ?numeric-string,
 *   issue_id: numeric-string,
 *   provider_id: numeric-string
 * }
 *
 * @phpstan-type FormVitalsRow array{
 *   id: numeric-string,
 *   uuid: ?string,
 *   date: ?string,
 *   pid: ?numeric-string,
 *   user: ?string,
 *   groupname: ?string,
 *   authorized: ?numeric-string,
 *   activity: ?numeric-string,
 *   bps: ?string,
 *   bpd: ?string,
 *   weight: ?numeric-string,
 *   height: ?numeric-string,
 *   temperature: ?numeric-string,
 *   temp_method: ?string,
 *   pulse: ?numeric-string,
 *   respiration: ?numeric-string,
 *   note: ?string,
 *   BMI: ?numeric-string,
 *   BMI_status: ?string,
 *   waist_circ: ?numeric-string,
 *   head_circ: ?numeric-string,
 *   oxygen_saturation: ?numeric-string,
 *   oxygen_flow_rate: ?numeric-string,
 *   external_id: ?string,
 *   ped_weight_height: ?numeric-string,
 *   ped_bmi: ?numeric-string,
 *   ped_head_circ: ?numeric-string,
 *   inhaled_oxygen_concentration: ?numeric-string,
 *   last_updated: string
 * }
 *
 * @phpstan-type LayoutOptionsRow array{
 *   form_id: string,
 *   field_id: string,
 *   group_id: string,
 *   title: ?string,
 *   seq: numeric-string,
 *   data_type: numeric-string,
 *   uor: numeric-string,
 *   fld_length: numeric-string,
 *   max_length: numeric-string,
 *   list_id: string,
 *   titlecols: numeric-string,
 *   datacols: numeric-string,
 *   default_value: string,
 *   edit_options: string,
 *   description: ?string,
 *   fld_rows: numeric-string,
 *   list_backup_id: string,
 *   source: string,
 *   conditions: ?string,
 *   validation: ?string,
 *   codes: string
 * }
 *
 * @phpstan-type FormCAMOSRow array{
 *   id: numeric-string,
 *   date: ?string,
 *   pid: ?numeric-string,
 *   user: ?string,
 *   groupname: ?string,
 *   authorized: ?numeric-string,
 *   activity: ?numeric-string,
 *   category: ?string,
 *   subcategory: ?string,
 *   item: ?string,
 *   content: ?string
 * }
 *
 * @phpstan-type FormCAMOSCategoryRow array{
 *   id: numeric-string,
 *   date: ?string,
 *   pid: ?numeric-string,
 *   user: ?string,
 *   groupname: ?string,
 *   authorized: ?numeric-string,
 *   activity: ?numeric-string,
 *   category: ?string
 * }
 *
 * @phpstan-type FormCAMOSSubcategoryRow array{
 *   id: numeric-string,
 *   date: ?string,
 *   pid: ?numeric-string,
 *   user: ?string,
 *   groupname: ?string,
 *   authorized: ?numeric-string,
 *   activity: ?numeric-string,
 *   subcategory: ?string,
 *   category_id: numeric-string
 * }
 *
 * @phpstan-type FormCAMOSItemRow array{
 *   id: numeric-string,
 *   date: ?string,
 *   pid: ?numeric-string,
 *   user: ?string,
 *   groupname: ?string,
 *   authorized: ?numeric-string,
 *   activity: ?numeric-string,
 *   item: ?string,
 *   content: ?string,
 *   subcategory_id: numeric-string
 * }
 */
interface TableTypes
{
    // This interface exists only to hold PHPStan type definitions.
}
