<?php

header("Content-Type:text/xml");
$ignoreAuth = true;
require_once 'classes.php';
$xml_string = "";
$xml_string = "<reviewofsystems>";

$token = $_POST['token'];
$rosId = $_POST['id'];

$patientId = $_POST['pid'];
$weight_change = $_POST['weight_change'];
$weakness = $_POST['weakness'];
$fatigue = $_POST['fatigue'];
$anorexia = $_POST['anorexia'];
$fever = $_POST['fever'];
$chills = $_POST['chills'];
$night_sweats = $_POST['night_sweats'];
$insomnia = $_POST['insomnia'];
$irritability = $_POST['irritability'];
$heat_or_cold = $_POST['heat_or_cold'];
$intolerance = $_POST['intolerance'];
$change_in_vision = $_POST['change_in_vision'];
$glaucoma_history = $_POST['glaucoma_history'];
$eye_pain = $_POST['eye_pain'];
$irritation = $_POST['irritation'];
$redness = $_POST['redness'];
$excessive_tearing = $_POST['excessive_tearing'];
$double_vision = $_POST['double_vision'];
$blind_spots = $_POST['blind_spots'];
$photophobia = $_POST['photophobia'];
$hearing_loss = $_POST['hearing_loss'];
$discharge = $_POST['discharge'];
$pain = $_POST['pain'];
$vertigo = $_POST['vertigo'];
$tinnitus = $_POST['tinnitus'];
$frequent_colds = $_POST['frequent_colds'];
$sore_throat = $_POST['sore_throat'];
$sinus_problems = $_POST['sinus_problems'];
$post_nasal_drip = $_POST['post_nasal_drip'];
$nosebleed = $_POST['nosebleed'];
$snoring = $_POST['snoring'];
$apnea = $_POST['apnea'];
$breast_mass = $_POST['breast_mass'];
$breast_discharge = $_POST['breast_discharge'];
$biopsy = $_POST['biopsy'];
$abnormal_mammogram = $_POST['abnormal_mammogram'];
$cough = $_POST['cough'];
$sputum = $_POST['sputum'];
$shortness_of_breath = $_POST['shortness_of_breath'];
$wheezing = $_POST['wheezing'];
$hemoptsyis = $_POST['hemoptsyis'];
$asthma = $_POST['asthma'];
$copd = $_POST['copd'];
$chest_pain = $_POST['chest_pain'];
$palpitation = $_POST['palpitation'];
$syncope = $_POST['syncope'];
$pnd = $_POST['pnd'];
$doe = $_POST['doe'];
$orthopnea = $_POST['orthopnea'];
$peripheal = $_POST['peripheal'];
$edema = $_POST['edema'];
$legpain_cramping = $_POST['legpain_cramping'];
$history_murmur = $_POST['history_murmur'];
$arrythmia = $_POST['arrythmia'];
$heart_problem = $_POST['heart_problem'];
$dysphagia = $_POST['dysphagia'];
$heartburn = $_POST['heartburn'];
$bloating = $_POST['bloating'];
$belching = $_POST['belching'];
$flatulence = $_POST['flatulence'];
$nausea = $_POST['nausea'];
$vomiting = $_POST['vomiting'];
$hematemesis = $_POST['hematemesis'];
$gastro_pain = $_POST['gastro_pain'];
$food_intolerance = $_POST['food_intolerance'];
$hepatitis = $_POST['hepatitis'];
$jaundice = $_POST['jaundice'];
$hematochezia = $_POST['hematochezia'];
$changed_bowel = $_POST['changed_bowel'];
$diarrhea = $_POST['diarrhea'];
$constipation = $_POST['constipation'];
$polyuria = $_POST['polyuria'];
$polydypsia = $_POST['polydypsia'];
$dysuria = $_POST['dysuria'];
$hematuria = $_POST['hematuria'];
$frequency = $_POST['frequency'];
$urgency = $_POST['urgency'];
$incontinence = $_POST['incontinence'];
$renal_stones = $_POST['renal_stones'];
$utis = $_POST['utis'];
$hesitancy = $_POST['hesitancy'];
$dribbling = $_POST['dribbling'];
$stream = $_POST['stream'];
$nocturia = $_POST['nocturia'];
$erections = $_POST['erections'];
$ejaculations = $_POST['ejaculations'];
$g = $_POST['g'];
$p = $_POST['p'];
$ap = $_POST['ap'];
$lc = $_POST['lc'];
$mearche = $_POST['mearche'];
$menopause = $_POST['menopause'];
$lmp = $_POST['lmp'];
$f_frequency = $_POST['f_frequency'];
$f_flow = $_POST['f_flow'];
$f_symptoms = $_POST['f_symptoms'];
$abnormal_hair_growth = $_POST['abnormal_hair_growth'];
$f_hirsutism = $_POST['f_hirsutism'];
$joint_pain = $_POST['joint_pain'];
$swelling = $_POST['swelling'];
$m_redness = $_POST['m_redness'];
$m_warm = $_POST['m_warm'];
$m_stiffness = $_POST['m_stiffness'];
$muscle = $_POST['muscle'];
$m_aches = $_POST['m_aches'];
$fms = $_POST['fms'];
$arthritis = $_POST['arthritis'];
$loc = $_POST['loc'];
$seizures = $_POST['seizures'];
$stroke = $_POST['stroke'];
$tia = $_POST['tia'];
$n_numbness = $_POST['n_numbness'];
$n_weakness = $_POST['n_weakness'];
$paralysis = $_POST['paralysis'];
$intellectual_decline = $_POST['intellectual_decline'];
$memory_problems = $_POST['memory_problems'];
$dementia = $_POST['dementia'];
$n_headache = $_POST['n_headache'];
$s_cancer = $_POST['s_cancer'];
$psoriasis = $_POST['psoriasis'];
$s_acne = $_POST['s_acne'];
$s_other = $_POST['s_other'];
$s_disease = $_POST['s_disease'];
$p_diagnosis = $_POST['p_diagnosis'];
$p_medication = $_POST['p_medication'];
$depression = $_POST['depression'];
$anxiety = $_POST['anxiety'];
$social_difficulties = $_POST['social_difficulties'];
$thyroid_problems = $_POST['thyroid_problems'];
$diabetes = $_POST['diabetes'];
$abnormal_blood = $_POST['abnormal_blood'];
$anemia = $_POST['anemia'];
$fh_blood_problems = $_POST['fh_blood_problems'];
$bleeding_problems = $_POST['bleeding_problems'];
$allergies = $_POST['allergies'];
$frequent_illness = $_POST['frequent_illness'];
$hiv = $_POST['hiv'];
$hai_status = $_POST['hai_status'];

if ($userId = validateToken($token)) {
    $user = getUsername($userId);
    $acl_allow = acl_check('encounters', 'auth_a', $user);
    $_SESSION['authUser'] = $user;
    $_SESSION['authGroup'] = $site;
    $_SESSION['pid'] = $patientId;
    if ($acl_allow) {
        $strQuery = 'UPDATE form_ros SET ';
        $strQuery .=' weight_change = "' . $weight_change . '",';
        $strQuery .=' weakness = "' . $weakness . '",';
        $strQuery .=' fatigue = "' . $fatigue . '",';
        $strQuery .=' anorexia = "' . $anorexia . '",';
        $strQuery .=' fever = "' . $fever . '",';
        $strQuery .=' chills = "' . $chills . '",';
        $strQuery .=' night_sweats = "' . $night_sweats . '",';
        $strQuery .=' insomnia = "' . $insomnia . '",';
        $strQuery .=' irritability = "' . $irritability . '",';
        $strQuery .=' heat_or_cold = "' . $heat_or_cold . '",';
        $strQuery .=' intolerance = "' . $intolerance . '",';
        $strQuery .=' change_in_vision = "' . $change_in_vision . '",';
        $strQuery .=' glaucoma_history = "' . $glaucoma_history . '",';
        $strQuery .=' eye_pain = "' . $eye_pain . '",';
        $strQuery .=' irritation = "' . $irritation . '",';
        $strQuery .=' redness = "' . $redness . '",';
        $strQuery .=' excessive_tearing = "' . $excessive_tearing . '",';
        $strQuery .=' double_vision = "' . $double_vision . '",';
        $strQuery .=' blind_spots = "' . $blind_spots . '",';
        $strQuery .=' photophobia = "' . $photophobia . '",';
        $strQuery .=' hearing_loss = "' . $hearing_loss . '",';
        $strQuery .=' discharge = "' . $discharge . '",';
        $strQuery .=' pain = "' . $pain . '",';
        $strQuery .=' vertigo = "' . $vertigo . '",';
        $strQuery .=' tinnitus = "' . $tinnitus . '",';
        $strQuery .=' frequent_colds = "' . $frequent_colds . '",';
        $strQuery .=' sore_throat = "' . $sore_throat . '",';
        $strQuery .=' sinus_problems = "' . $sinus_problems . '",';
        $strQuery .=' post_nasal_drip = "' . $post_nasal_drip . '",';
        $strQuery .=' nosebleed = "' . $nosebleed . '",';
        $strQuery .=' snoring = "' . $snoring . '",';
        $strQuery .=' apnea = "' . $apnea . '",';
        $strQuery .=' breast_mass = "' . $breast_mass . '",';
        $strQuery .=' breast_discharge = "' . $breast_discharge . '",';
        $strQuery .=' biopsy = "' . $biopsy . '",';
        $strQuery .=' abnormal_mammogram = "' . $abnormal_mammogram . '",';
        $strQuery .=' cough = "' . $cough . '",';
        $strQuery .=' sputum = "' . $sputum . '",';
        $strQuery .=' shortness_of_breath = "' . $shortness_of_breath . '",';
        $strQuery .=' wheezing = "' . $wheezing . '",';
        $strQuery .=' hemoptsyis = "' . $hemoptsyis . '",';
        $strQuery .=' asthma = "' . $asthma . '",';
        $strQuery .=' copd = "' . $copd . '",';
        $strQuery .=' chest_pain = "' . $chest_pain . '",';
        $strQuery .=' palpitation = "' . $palpitation . '",';
        $strQuery .=' syncope = "' . $syncope . '",';
        $strQuery .=' pnd = "' . $pnd . '",';
        $strQuery .=' doe = "' . $doe . '",';
        $strQuery .=' orthopnea = "' . $orthopnea . '",';
        $strQuery .=' peripheal = "' . $peripheal . '",';
        $strQuery .=' edema = "' . $edema . '",';
        $strQuery .=' legpain_cramping = "' . $legpain_cramping . '",';
        $strQuery .=' history_murmur = "' . $history_murmur . '",';
        $strQuery .=' arrythmia = "' . $arrythmia . '",';
        $strQuery .=' heart_problem = "' . $heart_problem . '",';
        $strQuery .=' dysphagia = "' . $dysphagia . '",';
        $strQuery .=' heartburn = "' . $heartburn . '",';
        $strQuery .=' bloating = "' . $bloating . '",';
        $strQuery .=' belching = "' . $belching . '",';
        $strQuery .=' flatulence = "' . $flatulence . '",';
        $strQuery .=' nausea = "' . $nausea . '",';
        $strQuery .=' vomiting = "' . $vomiting . '",';
        $strQuery .=' hematemesis = "' . $hematemesis . '",';
        $strQuery .=' gastro_pain = "' . $gastro_pain . '",';
        $strQuery .=' food_intolerance = "' . $food_intolerance . '",';
        $strQuery .=' hepatitis = "' . $hepatitis . '",';
        $strQuery .=' jaundice = "' . $jaundice . '",';
        $strQuery .=' hematochezia = "' . $hematochezia . '",';
        $strQuery .=' changed_bowel = "' . $changed_bowel . '",';
        $strQuery .=' diarrhea = "' . $diarrhea . '",';
        $strQuery .=' constipation = "' . $constipation . '",';
        $strQuery .=' polyuria = "' . $polyuria . '",';
        $strQuery .=' polydypsia = "' . $polydypsia . '",';
        $strQuery .=' dysuria = "' . $dysuria . '",';
        $strQuery .=' hematuria = "' . $hematuria . '",';
        $strQuery .=' frequency = "' . $frequency . '",';
        $strQuery .=' urgency = "' . $urgency . '",';
        $strQuery .=' incontinence = "' . $incontinence . '",';
        $strQuery .=' renal_stones = "' . $renal_stones . '",';
        $strQuery .=' utis = "' . $utis . '",';
        $strQuery .=' hesitancy = "' . $hesitancy . '",';
        $strQuery .=' dribbling = "' . $dribbling . '",';
        $strQuery .=' stream = "' . $stream . '",';
        $strQuery .=' nocturia = "' . $nocturia . '",';
        $strQuery .=' erections = "' . $erections . '",';
        $strQuery .=' ejaculations = "' . $ejaculations . '",';
        $strQuery .=' g = "' . $g . '",';
        $strQuery .=' p = "' . $p . '",';
        $strQuery .=' ap = "' . $ap . '",';
        $strQuery .=' lc = "' . $lc . '",';
        $strQuery .=' mearche = "' . $mearche . '",';
        $strQuery .=' menopause = "' . $menopause . '",';
        $strQuery .=' lmp = "' . $lmp . '",';
        $strQuery .=' f_frequency = "' . $f_frequency . '",';
        $strQuery .=' f_flow = "' . $f_flow . '",';
        $strQuery .=' f_symptoms = "' . $f_symptoms . '",';
        $strQuery .=' abnormal_hair_growth = "' . $abnormal_hair_growth . '",';
        $strQuery .=' f_hirsutism = "' . $f_hirsutism . '",';
        $strQuery .=' joint_pain = "' . $joint_pain . '",';
        $strQuery .=' swelling = "' . $swelling . '",';
        $strQuery .=' m_redness = "' . $m_redness . '",';
        $strQuery .=' m_warm = "' . $m_warm . '",';
        $strQuery .=' m_stiffness = "' . $m_stiffness . '",';
        $strQuery .=' muscle = "' . $muscle . '",';
        $strQuery .=' m_aches = "' . $m_aches . '",';
        $strQuery .=' fms = "' . $fms . '",';
        $strQuery .=' arthritis = "' . $arthritis . '",';
        $strQuery .=' loc = "' . $loc . '",';
        $strQuery .=' seizures = "' . $seizures . '",';
        $strQuery .=' stroke = "' . $stroke . '",';
        $strQuery .=' tia = "' . $tia . '",';
        $strQuery .=' n_numbness = "' . $n_numbness . '",';
        $strQuery .=' n_weakness = "' . $n_weakness . '",';
        $strQuery .=' paralysis = "' . $paralysis . '",';
        $strQuery .=' intellectual_decline = "' . $intellectual_decline . '",';
        $strQuery .=' memory_problems = "' . $memory_problems . '",';
        $strQuery .=' dementia = "' . $dementia . '",';
        $strQuery .=' n_headache = "' . $n_headache . '",';
        $strQuery .=' s_cancer = "' . $s_cancer . '",';
        $strQuery .=' psoriasis = "' . $psoriasis . '",';
        $strQuery .=' s_acne = "' . $s_acne . '",';
        $strQuery .=' s_other = "' . $s_other . '",';
        $strQuery .=' s_disease = "' . $s_disease . '",';
        $strQuery .=' p_diagnosis = "' . $p_diagnosis . '",';
        $strQuery .=' p_medication = "' . $p_medication . '",';
        $strQuery .=' depression = "' . $depression . '",';
        $strQuery .=' anxiety = "' . $anxiety . '",';
        $strQuery .=' social_difficulties = "' . $social_difficulties . '",';
        $strQuery .=' thyroid_problems = "' . $thyroid_problems . '",';
        $strQuery .=' diabetes = "' . $diabetes . '",';
        $strQuery .=' abnormal_blood = "' . $abnormal_blood . '",';
        $strQuery .=' anemia = "' . $anemia . '",';
        $strQuery .=' fh_blood_problems = "' . $fh_blood_problems . '",';
        $strQuery .=' bleeding_problems = "' . $bleeding_problems . '",';
        $strQuery .=' allergies = "' . $allergies . '",';
        $strQuery .=' frequent_illness = "' . $frequent_illness . '",';
        $strQuery .=' hiv = "' . $hiv . '",';
        $strQuery .=' hai_status = "' . $hai_status . '"';
        $strQuery .= ' WHERE id = ' . $rosId;

        $result = sqlStatement($strQuery);

        if ($result) {

            $xml_string .= "<status>0</status>";
            $xml_string .= "<reason>The Review of Systems has been updated</reason>";
        } else {
            $xml_string .= "<status>-1</status>";
            $xml_string .= "<reason>ERROR: Sorry, there was an error processing your data. Please re-submit the information again.</reason>";
        }
    } else {
        $xml_string .= "<status>-2</status>\n";
        $xml_string .= "<reason>You are not Authorized to perform this action</reason>\n";
    }
} else {
    $xml_string .= "<status>-2</status>";
    $xml_string .= "<reason>Invalid Token</reason>";
}

$xml_string .= "</reviewofsystems>";
echo $xml_string;
?>