name: API Docs Freshness Checks

on:
  pull_request:
    branches:
    - master
    - rel-*

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version: ['8.2']
    name: API Docs Freshness Check
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: "Setup PHP"
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - name: "Get composer cache directory"
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: "Composer Cache"
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-${{ matrix.php-version }}-
          ${{ runner.os }}-composer-

    - name: "Composer Install"
      run: composer install --prefer-dist --no-progress

    - name: "Refresh API Documentation"
      run: php bin/console openemr:create-api-documentation

    - name: "WIP"
      run: echo $(git diff --name-only)

    # If after docs regeneration there are any diff - that means docs are not in sync with new API code changes
    - name: "Check Docs Freshness"
      run: |
        if [[ -n $(git diff --name-only) ]]; then
          echo "Looks like openemr-api.yaml is not in sync with your changes."
          echo "Please, run:"
          echo "php bin/console openemr:create-api-documentation"
          echo "and push updated openemr-api.yaml file into your PR"
          exit 1
        else
          echo "openemr-api.yaml is in sync with your changes"
        fi
