name: Flex Edge Dockers Nightly Build

# This workflow builds the OpenEMR Flex Docker images with Alpine Edge and PHP versions 8.3, 8.4, and 8.5.
# And in this configuration will create following dockers (and tags):
#    PHP 8.3: openemr/openemr:flex-edge-php-8.3
#    PHP 8.4: openemr/openemr:flex-edge-php-8.4
#    PHP 8.5: openemr/openemr:flex-edge-php-8.5, openemr/openemr:flex-edge
#
# php_versions is a JSON array of PHP versions to build.
#
# The php_default will determine the default PHP version (ie. above tag without a php version).
#
# The is_default_flex environment variable is used to determine if this is the default flex image.
#  (This is NOT the default flex image, so is_default_flex is false)
on:
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * *'   # run at 2 AM UTC

jobs:
  build:
    uses: ./.github/workflows/docker-build-flex-core.yml
    with:
      is_default_flex: false
      alpine_version: "edge"
      php_versions: '["8.3", "8.4", "8.5"]'
      php_default: "8.5"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
