# This will run the OpenEMR flex dockers with Alpine 3.23 version. It will test the flex docker images in both
#  development (ie. dev) mode (codebase used from a shared volume) and production (ie. prod) mode (codebase collected via git).
#  - is_production_docker is required and needs to be false.
#  - alpine_versions is set to 3.23
#  - php_versions are set to 8.3, 8.4 and 8.5
#  - note not using the coverage settings (is_flex_coverage_docker, flex_coverage_php_version) in this workflow. see
#    test-flex-edge.yml for use of these settings.

name: OpenEMR Flex 3.23 Docker Test

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/docker-test-flex-323.yml'
    - 'docker/flex/**'
    - '.github/actions/test-actions-core/action.yml'
    - '.github/workflows/docker-test-core.yml'
  pull_request:
    branches:
    - master
    paths:
    - '.github/workflows/docker-test-flex-323.yml'
    - 'docker/flex/**'
    - '.github/actions/test-actions-core/action.yml'
    - '.github/workflows/docker-test-core.yml'

jobs:
  build:
    uses: ./.github/workflows/docker-test-core.yml
    with:
      is_production_docker: false
      alpine_version: "3.23"
      php_versions: '["8.3", "8.4", "8.5"]'
