name: Integration tests

on:
  pull_request:
    # All PRs
  push:
    branches:
      - master
      - rel-*

env:
  ENVIRONMENT: ci

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.suite }} - ${{ matrix.php }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php:
          - '8.5'
        suite:
          - 'common'


    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: ci
          MYSQL_PASSWORD: topsecret
          MYSQL_DATABASE: openemr_test
        ports:
          - 3306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP and Composer
        uses: ./.github/actions/setup-php-composer
        with:
          php-version: ${{ matrix.php }}

      - name: Run CLI installer
        run: ./cli install
            --db-host=127.0.0.1
            --db-port=3306
            --db-root-user=root
            --db-root-password=root
            --db-user=ci
            --db-password=topsecret
            --db-name=openemr_test
            --oe-admin-username=admin
            --oe-admin-password=pass
            --no-interaction
            -vvv

      - name: Verify installation
        run: |
          mysql -h 127.0.0.1 -u ci -ptopsecret openemr_test \
            -e "SELECT COUNT(*) as user_count FROM users WHERE username='admin';" \
            | grep -q "1"

      # TODO: actually run the test suite. For now, just verifying installer.
