name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  collect:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Collect Docker Dirs
      id: docker-dirs
      ##
      # Parse out the test parameters from the ci subdirectories that contain
      # docker-compose.yml files. We'll use that output as a test matrix
      # in github actions.
      run: |
        shopt -s nullglob
        dirs=( ci/*/docker-compose.yml )
        if (( "${#dirs[@]}" == 0 )); then
          echo 'No docker-compose.yml files found in ci subdirectories.' >&2
          exit 1
        fi
        dirs=( "${dirs[@]%/docker-compose.yml}" )
        dirs=( "${dirs[@]#ci/}" )
        # Everything inside this for loop that goes to stdout ends up
        # in the github output, so it must be valid json.
        for docker_dir in "${dirs[@]}"; do
            IFS=: read -r database db < <(yq '.services.mysql.image' "ci/${docker_dir}/docker-compose.yml")
            IFS=_ read -r webserver php _ <<< "${docker_dir}"
            printf -v php '%d.%d' "${php::1}" "${php:1}"
            case "$webserver" in
                apache)
                    openemr_dir=/var/www/localhost/htdocs/openemr
                    chromium_install='apk update; apk add --no-cache chromium chromium-chromedriver; export PANTHER_CHROME_DRIVER_BINARY=/usr/lib/chromium/chromedriver'
                    ;;
                nginx)
                    openemr_dir=/usr/share/nginx/html/openemr
                    chromium_install='apt-get update; apt-get install -y chromium-driver; export PANTHER_CHROME_DRIVER_BINARY=/usr/bin/chromedriver'
                    ;;
                *)
                    echo "Unknown webserver: $webserver" >&2;
                    exit 1
                    ;;
            esac
            printf '{
                "chromium_install": "%s",
                "docker_dir": "%s",
                "database": "%s",
                "db": "%s",
                "openemr_dir": "%s",
                "php": "%s",
                "webserver": "%s"
            }\n' "$chromium_install" "$docker_dir" "$database" "$db" "$openemr_dir" "$php" "$webserver"
        done | {
            printf 'configurations='
            jq -cs .
        } >> "$GITHUB_OUTPUT"
    outputs:
        configurations: ${{ steps.docker-dirs.outputs.configurations }}
  build:
    name: PHP ${{ matrix.configurations.php }} - ${{ matrix.configurations.webserver }} - ${{ matrix.configurations.database }} ${{ matrix.configurations.db }}
    runs-on: ubuntu-22.04
    needs: collect
    strategy:
      fail-fast: false
      matrix:
        configurations: ${{ fromJson(needs.collect.outputs.configurations) }}
    env:
      CHROMIUM_INSTALL: ${{ matrix.configurations.chromium_install }}
      DOCKER_DIR: ${{ matrix.configurations.docker_dir }}
      OPENEMR_DIR: ${{ matrix.configurations.openemr_dir }}
    steps:
    - uses: actions/checkout@v4
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.configurations.php }}
    - name: Report PHP Version
      run: php -v
    - name: Install npm package
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Main build
      run: |
        . ci/ciLibrary.source
        composer_github_auth
        main_build
    - name: CCDA build
      run: |
        . ci/ciLibrary.source
        ccda_build
    - name: Dockers environment start
      run: |
        . ci/ciLibrary.source
        dockers_env_start
    - name: Wait for MySQL to initialize
      if: ${{ matrix.configurations.database == 'mysql' }}
      run: |
        echo "Waiting 60 seconds for MySQL to initialize..."
        sleep 60
    - name: Install and configure
      run: |
        . ci/ciLibrary.source
        install_configure
    - name: Unit testing
      if: ${{ success() || failure() }}
      run: |
        . ci/ciLibrary.source
        build_test_unit
    - name: E2e testing
      if: ${{ success() || failure() }}
      run: |
        . ci/ciLibrary.source
        build_test_e2e
    - name: Api testing
      if: ${{ success() || failure() }}
      run: |
        . ci/ciLibrary.source
        build_test_api
    - name: Fixtures testing
      if: ${{ success() || failure() }}
      run: |
        . ci/ciLibrary.source
        build_test_fixtures
    - name: Services testing
      if: ${{ success() || failure() }}
      run: |
        . ci/ciLibrary.source
        build_test_services
    - name: Validators testing
      if: ${{ success() || failure() }}
      run: |
        . ci/ciLibrary.source
        build_test_validators
    - name: Controllers testing
      if: ${{ success() || failure() }}
      run: |
        . ci/ciLibrary.source
        build_test_controllers
    - name: Common testing
      if: ${{ success() || failure() }}
      run: |
        . ci/ciLibrary.source
        build_test_common
