<?php
/**
 * interface/modules/zend_modules/module/Acl/view/acl/acl/acltab.phtml
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    Jacob T.Paul <jacob@zhservices.com>
 * @author    Basil PT <basil@zhservices.com>
 * @author    Tyler Wrenn <tyler@tylerwrenn.com>
 * @copyright Copyright (c) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 * @copyright Copyright (c) 2020 Tyler Wrenn <tyler@tylerwrenn.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */
?>
<div id="tabs-acl-tabs">
<div class="easyui-tabs h-auto" id="tab">
    <div title="General" id="tab_acl" iconCls="icon-acl">
          <iframe id="general_acl" src="<?php echo $GLOBALS['webroot']; ?>/interface/modules/zend_modules/public/acl/acl?module_id=<?php echo $this->escapeHtml($this->mod_id); ?>" class="w-100 overflow-hidden" style="height: 700px;" frameborder="0"></iframe>
    </div>
    <div title="Advanced ACL" id="tab_acl2" iconCls="icon-acladvanced">
          <iframe id="advanced_acl" src="<?php echo $GLOBALS['webroot']; ?>/interface/modules/zend_modules/public/acl/index?module_id=<?php echo $this->escapeHtml($this->mod_id); ?>" class="w-100 overflow-hidden" style="height: 700px;" frameborder="0"></iframe>
    </div>
</div>
</div>
